/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Criterion
import Oka.CategoryTheory.Sites.CoversTop.Over
import Oka.Geometry.RingedSpace.LocallyRingedSpace
import Oka.Geometry.RingedSpace.LocallyRingedSpace.Modules

/-!
# Coherence of the structure sheaf of a locally ringed space, from local relations

Coherence of a sheaf of modules is defined by a condition on every object of the site and on
every one of its slice sites, which makes it awkward to transport between a space and its open
subspaces. This file provides a concrete replacement:
`AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations` says that, near every point, the
relations between finitely many sections of `𝒪_Y` are generated by finitely many of them. It
mentions only open subsets, sections and restriction maps, so it is manifestly local, and
`AlgebraicGeometry.LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations` shows it
implies coherence.

**There is nothing complex-analytic here, and there are now two consumers that prove it.** The
theorem is quoted for `ℂ^ι` in `Oka/AnalyticSpace/Relations.lean`, where Oka's coherence lemma
supplies the hypothesis, and for a locally noetherian scheme in
`Oka/AlgebraicGeometry/Modules/Coherent.lean`, where noetherianity does. See `README.md` on the
mirror tree.

## Where this would go upstream

A new file `Mathlib/Geometry/RingedSpace/LocallyRingedSpace/Coherent.lean`. Being new it costs no
existing Mathlib file anything; the Mathlib part of its transitive closure is **1861** modules,
which is 9 more than `Oka/Geometry/RingedSpace/LocallyRingedSpace/Modules.lean`'s 1852 — the
coherence machinery it adds on top of that file is almost entirely this repository's own.

**And that is the honest obstruction: `SheafOfModules.IsCoherent` is not in Mathlib.** It is
`Oka/Algebra/Category/ModuleCat/Sheaf/Coherent/Basic.lean`, itself a mirror file for a Mathlib
file that does not exist, and this file's `Oka` imports are that subtree plus
`Oka/CategoryTheory/Sites/CoversTop/Over.lean` and
`Oka/Geometry/RingedSpace/LocallyRingedSpace/Modules.lean`. So the mirror path is a claim about
where this belongs and not a claim that it could be upstreamed tomorrow: the coherence API has to
go first.

## What is *not* here, and where it went instead

The section and germ API this argument runs on — `AlgebraicGeometry.LocallyRingedSpace.res` and
its lemmas, the `imOpen`/`preOpen` pair for open subspaces, and the local-lifting lemmas
`exists_localCombination`, `exists_localLift` and `exists_localLift_family` — is in
`Oka/Geometry/RingedSpace/LocallyRingedSpace.lean`, whose target is an **existing** Mathlib file
that all of it costs **nothing**. It was measured to compile against that file's own two imports
and no others, which is why it is there rather than here: a proposed file is a weaker claim than
an existing one, and none of that API mentions coherence.

## Main definitions

- `AlgebraicGeometry.LocallyRingedSpace.IsCoherentStructureSheaf`: `𝒪_Y` is coherent as a sheaf
  of modules over itself.
- `AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations`: the concrete relations condition, and
  `AlgebraicGeometry.LocallyRingedSpace.HasLocalRelationsOn` its relativisation to an open set,
  which is what an open cover argument quantifies over.

## Main results

- `AlgebraicGeometry.LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations`: **local
  relations imply coherence.**
- `AlgebraicGeometry.LocallyRingedSpace.hasLocalRelations_of_openCover`: the condition may be
  checked on an open cover, and `AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations.restrict`
  is the converse direction, that it passes to an open subspace.

## Provenance

Split out of `Oka/AnalyticSpace/Relations.lean` for taxis #905, unchanged: no statement, proof or
name here differs from what that file held, and the split is by destination — the module theory
went to `Oka/Geometry/RingedSpace/LocallyRingedSpace/Modules.lean`, the section and germ API to
`Oka/Geometry/RingedSpace/LocallyRingedSpace.lean`, and what stayed behind is the three lines
about `ℂ^ι`.
-/

open CategoryTheory Limits TopologicalSpace Opposite SheafOfModules AlgebraicGeometry

universe u

namespace AlgebraicGeometry.LocallyRingedSpace

variable (Y : LocallyRingedSpace.{u})

/-- A locally ringed space has **coherent structure sheaf** if `𝒪_Y` is coherent as a sheaf of
modules over itself. -/
def IsCoherentStructureSheaf : Prop :=
  (SheafOfModules.unit Y.ringSheaf).IsCoherent

/-- The structure sheaf of `Y` has **locally finitely generated relations**: every finite
family `f₁, …, f_m` of sections of `𝒪_Y` over `V` admits, near every point of `V`, finitely
many relations `g₁, …, g_k` which generate all relations locally.

"Locally" is essential: a relation between the `fᵢ` over an open set `W'` is required only to
be a combination of the `gₗ` on a neighbourhood of each point of `W'`, not on all of `W'`. The
sectionwise variant would amount to a vanishing statement for `H¹` on arbitrary open sets and
is not available.

Unlike coherence stated via `SheafOfModules.IsCoherent`, this refers only to open subsets,
sections and restriction maps, so it is manifestly local and needs no transport of sites. -/
def HasLocalRelations : Prop :=
  ∀ (V : Opens Y) (m : ℕ) (f : Fin m → Y.presheaf.obj (op V)) (x : Y), x ∈ V →
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → (Fin m → Y.presheaf.obj (op W))),
      x ∈ W ∧ (∀ l, ∑ i, g l i * Y.res hWV (f i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin m → Y.presheaf.obj (op W')),
        (∑ i, a i * Y.res (hW'.trans hWV) (f i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i)

/-- The structure sheaf of `Y` has locally finitely generated relations **over the open set
`U`**: the condition of `HasLocalRelations` for families of sections defined on open subsets
of `U`. -/
def HasLocalRelationsOn (U : Opens Y) : Prop :=
  ∀ (V : Opens Y), V ≤ U → ∀ (m : ℕ) (f : Fin m → Y.presheaf.obj (op V)) (x : Y), x ∈ V →
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → (Fin m → Y.presheaf.obj (op W))),
      x ∈ W ∧ (∀ l, ∑ i, g l i * Y.res hWV (f i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin m → Y.presheaf.obj (op W')),
        (∑ i, a i * Y.res (hW'.trans hWV) (f i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i)

variable {Y}

/-- `HasLocalRelations` is `HasLocalRelationsOn` for the whole space. -/
lemma HasLocalRelationsOn.hasLocalRelations (h : Y.HasLocalRelationsOn ⊤) :
    Y.HasLocalRelations :=
  fun V m f x hx ↦ h V le_top m f x hx

/-- Having locally finitely generated relations may be checked on an open cover. -/
theorem hasLocalRelations_of_openCover {A : Type*} (U : A → Opens Y)
    (hU : ∀ x : Y, ∃ a, x ∈ U a) (h : ∀ a, Y.HasLocalRelationsOn (U a)) :
    Y.HasLocalRelations := by
  intro V m f x hx
  obtain ⟨a, ha⟩ := hU x
  obtain ⟨W, hWV, k, g, hxW, hrel, hgen⟩ :=
    h a (V ⊓ U a) inf_le_right m (fun i ↦ Y.res inf_le_left (f i)) x ⟨hx, ha⟩
  refine ⟨W, hWV.trans inf_le_left, k, g, hxW, ?_, ?_⟩
  · simpa only [res_res] using hrel
  · intro W' hW' aa haa y hy
    exact hgen W' hW' aa (by simpa only [res_res] using haa) y hy

variable (Y)

variable {Y}

set_option maxHeartbeats 1000000 in
-- the proof repeatedly identifies sections of the (iterated) restrictions of the sheaves of
-- modules involved with sections of the structure sheaf, which is definitionally expensive
/-- A locally ringed space whose structure sheaf has locally finitely generated relations has
coherent structure sheaf. -/
theorem isCoherentStructureSheaf_of_hasLocalRelations (h : Y.HasLocalRelations) :
    Y.IsCoherentStructureSheaf := by
  classical
  haveI : (unit Y.ringSheaf).IsFiniteType := by apply SheafOfModules.isFiniteType_unit
  refine isCoherent_of_forall_kernel_of_locally (M := unit Y.ringSheaf) ?_
  intro X I hI φ
  haveI := hI
  haveI : Fintype I := Fintype.ofFinite I
  obtain ⟨m, ⟨e⟩⟩ := Finite.exists_equiv_fin I
  set f : Fin m → Y.presheaf.obj (op X) := fun i ↦
    PresheafOfModules.sections.eval (freeHomEquiv _ φ (e.symm i)) (op (Over.mk (𝟙 X))) with hf
  choose V hVX k g hxV hrel hgen using fun (x : X) ↦ h X m f x.1 x.2
  refine ⟨↥X, fun a ↦ Over.mk (homOfLE (hVX a)),
    coversTop_over X V hVX (fun x hx ↦ ⟨⟨x, hx⟩, hxV ⟨x, hx⟩⟩), fun a ↦ ?_⟩
  set Ya : Over X := Over.mk (homOfLE (hVX a))
  set L := ULift.{u} (Fin (k a))
  have hWV : ∀ W : (Over Ya)ᵒᵖ, W.unop.left.left ≤ V a := fun W ↦ leOfHom W.unop.hom.left
  have hWX : ∀ W : (Over Ya)ᵒᵖ, W.unop.left.left ≤ X := fun W ↦ (hWV W).trans (hVX a)
  set ψ : free L ⟶ (free I).over Ya :=
    (freeHomEquiv _).symm (fun l ↦ sectionOfTerminal Over.mkIdTerminal ((free I).over Ya)
      (freeEvalSymm (R := Y.ringSheaf.over X) (I := I) (op (Over.mk (𝟙 Ya)).left)
        (fun i ↦ g a l.down (e i)))) with hψ
  have key_φ : ∀ (W : (Over Ya)ᵒᵖ) (b : ((free I).over Ya).val.obj W)
      (bc : I → Y.presheaf.obj (op W.unop.left.left))
      (_ : ∀ i, bc i = freeEval (op W.unop.left) b i)
      (v : Y.presheaf.obj (op W.unop.left.left)) (_ : v = (φ.over Ya).val.app W b),
      v = ∑ i : I, bc i * Y.res (hWX W) (f (e i)) := by
    intro W b bc hbc v hv
    have hsec : ∀ i : I, (PresheafOfModules.sections.eval (freeHomEquiv _ φ i)
        (op W.unop.left) : Y.presheaf.obj (op W.unop.left.left)) =
        Y.res (hWX W) (f (e i)) := by
      intro i
      simp only [hf, Equiv.symm_apply_apply]
      exact (PresheafOfModules.sections_property (freeHomEquiv _ φ i)
        (Over.mkIdTerminal.from W.unop.left).op).symm
    rw [hv, show (φ.over Ya).val.app W b = φ.val.app (op W.unop.left) b from rfl,
      val_app_eq_sum]
    refine Finset.sum_congr rfl (fun i _ ↦ ?_)
    rw [hbc i, ← hsec i]
    rfl
  have key_ψ : ∀ (W : (Over Ya)ᵒᵖ) (c : (free L).val.obj W)
      (cc : L → Y.presheaf.obj (op W.unop.left.left)) (_ : ∀ l, cc l = freeEval W c l) (i : I)
      (v : Y.presheaf.obj (op W.unop.left.left))
      (_ : v = freeEval (op W.unop.left) (ψ.val.app W c) i),
      v = ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i)) := by
    intro W c cc hcc i v hv
    obtain ⟨cc', hcc'⟩ : ∃ cc' : L → (Y.ringSheaf.over X).obj.obj (op W.unop.left),
        ∀ l, cc' l = cc l := ⟨fun l ↦ cc l, fun _ ↦ rfl⟩
    obtain ⟨vv, hvv⟩ : ∃ vv : L → I → (Y.ringSheaf.over X).obj.obj (op W.unop.left),
        ∀ l i, vv l i = Y.res (hWV W) (g a l.down (e i)) :=
      ⟨fun l i ↦ Y.res (hWV W) (g a l.down (e i)), fun _ _ ↦ rfl⟩
    have hsec : ∀ l : L, PresheafOfModules.sections.eval (freeHomEquiv _ ψ l) W =
        freeEvalSymm (op W.unop.left) (vv l) := by
      intro l
      rw [hψ, Equiv.apply_symm_apply, sectionOfTerminal_val,
        show vv l = fun i ↦ Y.res (hWV W) (g a l.down (e i)) from funext (hvv l)]
      exact map_freeEvalSymm (R := Y.ringSheaf.over X) (I := I)
        ((Over.mkIdTerminal.from W.unop).left).op (fun i ↦ g a l.down (e i))
    have h1 : ψ.val.app W c = freeEvalSymm (op W.unop.left)
        (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) := by
      have hrhs : freeEvalSymm (R := Y.ringSheaf.over X) (I := I) (op W.unop.left)
          (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) =
          ∑ l : L, cc' l • freeEvalSymm (op W.unop.left) (vv l) := by
        have hpi : (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) =
            ∑ l : L, cc' l • vv l := by
          funext i
          rw [Finset.sum_apply]
          refine Finset.sum_congr rfl (fun l _ ↦ ?_)
          rw [Pi.smul_apply, hcc', hvv]
          rfl
        refine (congrArg (freeEvalSymm (R := Y.ringSheaf.over X) (I := I)
          (op W.unop.left)) hpi).trans ((map_sum _ _ _).trans ?_)
        exact Finset.sum_congr rfl (fun l _ ↦ map_smul _ _ _)
      rw [val_app_eq_sum, hrhs]
      simp only [hsec, hcc', hcc]
      rfl
    rw [hv, h1]
    exact congrFun (freeEval_freeEvalSymm _ _) i
  have hgker : ∀ (W' : Opens Y) (hh : W' ≤ V a) (l : Fin (k a)),
      ∑ j : Fin m, Y.res hh (g a l j) * Y.res (hh.trans (hVX a)) (f j) = 0 := by
    intro W' hh l
    have h0 := congrArg (Y.res hh) (hrel a l)
    simp only [res_sum, res_mul, res_res, res_zero] at h0
    exact h0
  refine ⟨L, inferInstance, ψ, ?_, ?_⟩
  · ext W c
    obtain ⟨cc, hcc⟩ : ∃ cc : L → Y.presheaf.obj (op W.unop.left.left),
        ∀ l, cc l = freeEval W c l := ⟨fun l ↦ freeEval W c l, fun _ ↦ rfl⟩
    obtain ⟨v, hv⟩ : ∃ v : Y.presheaf.obj (op W.unop.left.left),
        v = (φ.over Ya).val.app W (ψ.val.app W c) := ⟨_, rfl⟩
    have h0 : v = 0 := by
      rw [key_φ W (ψ.val.app W c)
        (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i)))
        (fun i ↦ (key_ψ W c cc hcc i _ rfl).symm) v hv]
      have hterm : ∀ i : I, (∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) *
            Y.res (hWX W) (f (e i)) =
          ∑ l : L, cc l * (Y.res (hWV W) (g a l.down (e i)) * Y.res (hWX W) (f (e i))) := by
        intro i
        rw [Finset.sum_mul]
        exact Finset.sum_congr rfl (fun l _ ↦ mul_assoc _ _ _)
      simp only [hterm]
      rw [Finset.sum_comm]
      refine Finset.sum_eq_zero (fun l _ ↦ ?_)
      rw [← Finset.mul_sum, Equiv.sum_comp e (fun j : Fin m ↦
        Y.res (hWV W) (g a l.down j) * Y.res (hWX W) (f j)),
        hgker _ (hWV W) l.down, mul_zero]
    exact hv.symm.trans h0
  · intro Z b hb
    obtain ⟨bc, hbc⟩ : ∃ bc : I → Y.presheaf.obj (op Z.left.left),
        ∀ i, bc i = freeEval (op Z.left) b i :=
      ⟨fun i ↦ freeEval (op Z.left) b i, fun _ ↦ rfl⟩
    have hrelb : ∑ j : Fin m, bc (e.symm j) * Y.res (hWX (op Z)) (f j) = 0 := by
      rw [← Equiv.sum_comp e (fun j : Fin m ↦ bc (e.symm j) * Y.res (hWX (op Z)) (f j))]
      obtain ⟨v, hv⟩ : ∃ v : Y.presheaf.obj (op Z.left.left),
          v = (φ.over Ya).val.app (op Z) b := ⟨_, rfl⟩
      have h0 : v = 0 := hv.trans hb
      rw [key_φ (op Z) b bc hbc v hv] at h0
      simpa only [Equiv.symm_apply_apply] using h0
    choose Wy hWyle hyWy cy hcy using fun (y : Z.left.left) ↦
      hgen a Z.left.left (hWV (op Z)) (fun j ↦ bc (e.symm j)) hrelb y.1 y.2
    set S₀ : Sieve (Z.left.left : Opens Y) :=
      ⟨fun Wo _ ↦ ∃ y : Z.left.left, Wo ≤ Wy y, by
        rintro W₁ W₂ f₁ ⟨y, hy⟩ gg; exact ⟨y, (leOfHom gg).trans hy⟩⟩ with hS₀def
    have hS₀mem : S₀ ∈ Opens.grothendieckTopology Y Z.left.left := by
      intro x hx
      exact ⟨Wy ⟨x, hx⟩, homOfLE (hWyle ⟨x, hx⟩), ⟨⟨x, hx⟩, le_rfl⟩, hyWy ⟨x, hx⟩⟩
    refine ⟨(Sieve.overEquiv Z).symm ((Sieve.overEquiv Z.left).symm S₀), ?_, ?_⟩
    · rw [GrothendieckTopology.mem_over_iff, OrderIso.apply_symm_apply,
        GrothendieckTopology.mem_over_iff, OrderIso.apply_symm_apply]
      exact hS₀mem
    · intro Z' ff hff
      rw [Sieve.overEquiv_symm_iff, Sieve.overEquiv_symm_iff] at hff
      obtain ⟨y, hy⟩ := hff
      have hle : Z'.left.left ≤ Wy y := hy
      refine ⟨freeEvalSymm (op Z') (fun l : L ↦ Y.res hle (cy y l.down)), ?_⟩
      refine freeEval_injective (op Z'.left) (funext fun i ↦ ?_)
      have h1 := key_ψ (op Z')
        (freeEvalSymm (op Z') (fun l : L ↦ Y.res hle (cy y l.down)))
        (fun l ↦ Y.res hle (cy y l.down))
        (fun l ↦ (congrFun (freeEval_freeEvalSymm (R := (Y.ringSheaf.over X).over Ya) (I := L)
          (op Z') (fun l : L ↦ Y.res hle (cy y l.down))) l).symm) i _ rfl
      have hsum : (∑ l : L, Y.res hle (cy y l.down) *
          Y.res (hWV (op Z')) (g a l.down (e i))) =
          ∑ l : Fin (k a), Y.res hle (cy y l) * Y.res (hWV (op Z')) (g a l (e i)) :=
        Fintype.sum_equiv Equiv.ulift _ _ (fun _ ↦ rfl)
      have h3 : freeEval (op Z'.left) (((free I).over Ya).val.map ff.op b) i =
          Y.res (leOfHom ff.left.left) (bc i) := by
        rw [show (((free I).over Ya).val.map ff.op) b =
          (free I).val.map (ff.left).op b from rfl, freeEval_naturality, hbc i]
        rfl
      have h4 : (∑ l : Fin (k a), Y.res hle (cy y l) *
          Y.res (hWV (op Z')) (g a l (e i))) = Y.res (leOfHom ff.left.left) (bc i) := by
        have h5 := hcy y (e i)
        simp only [Equiv.symm_apply_apply] at h5
        have h6 := congrArg (Y.res hle) h5
        simp only [res_sum, res_mul, res_res] at h6
        exact h6.symm
      rw [h3, h1, hsum, h4]

section Restrict

variable {X : LocallyRingedSpace.{u}} (U : Opens X)
/-- Having locally finitely generated relations transfers from an open subspace of `X` to `X`
itself, over that open set. -/
theorem HasLocalRelations.hasLocalRelationsOn
    (h : (X.restrict U.isOpenEmbedding).HasLocalRelations) :
    X.HasLocalRelationsOn U := by
  intro V hVU m f x hx
  have hV : imOpen U (preOpen U V) = V := imOpen_preOpen U hVU
  obtain ⟨W', hW'V', k, g, hxW', hrel, hgen⟩ :=
    h (preOpen U V) m (fun i ↦ X.res hV.le (f i)) ⟨x, hVU hx⟩ hx
  refine ⟨imOpen U W', (Set.image_mono hW'V').trans hV.le, k, g,
    ⟨⟨x, hVU hx⟩, hxW', rfl⟩, fun l ↦ ?_, fun W2 hW2le a ha y hy ↦ ?_⟩
  · have h1 := hrel l
    simp only [restrict_res, res_res] at h1
    exact h1
  · have hW2 : imOpen U (preOpen U W2) = W2 :=
      imOpen_preOpen U (hW2le.trans (imOpen_le U W'))
    have hpre : preOpen U W2 ≤ W' := preOpen_le_of_le_imOpen U hW2le
    have hyU : y ∈ U := (hW2le.trans (imOpen_le U W')) hy
    have hrel2 : ∑ i, X.res hW2.le (a i) *
        X.res (Set.image_mono (hpre.trans hW'V')) (X.res hV.le (f i)) = 0 := by
      have h2 := congrArg (X.res hW2.le) ha
      simp only [res_sum, res_mul, res_res, res_zero] at h2
      simpa only [res_res] using h2
    obtain ⟨W3, hW3, hyW3, c, hc⟩ :=
      hgen (preOpen U W2) hpre (fun i ↦ X.res hW2.le (a i)) hrel2 ⟨y, hyU⟩ hy
    refine ⟨imOpen U W3, (Set.image_mono hW3).trans hW2.le, ⟨⟨y, hyU⟩, hyW3, rfl⟩,
      c, fun i ↦ ?_⟩
    have h3 := hc i
    simp only [restrict_res, res_res] at h3
    exact h3
/-- Having locally finitely generated relations passes to open subspaces. -/
theorem HasLocalRelations.restrict (h : X.HasLocalRelations) :
    (X.restrict U.isOpenEmbedding).HasLocalRelations := by
  intro V m f x hx
  obtain ⟨W, hWV, k, g, hxW, hrel, hgen⟩ := h (imOpen U V) m f x.1 ⟨x, hx, rfl⟩
  have hWU : W ≤ U := hWV.trans (imOpen_le U V)
  have hW : imOpen U (preOpen U W) = W := imOpen_preOpen U hWU
  refine ⟨preOpen U W, preOpen_le_of_le_imOpen U hWV, k, fun l i ↦ X.res hW.le (g l i),
    hxW, fun l ↦ ?_, fun W2 hW2 a ha y hy ↦ ?_⟩
  · have h1 := congrArg (X.res hW.le) (hrel l)
    simp only [res_sum, res_mul, res_res, res_zero] at h1
    simp only [restrict_res]
    exact h1
  · have him : imOpen U W2 ≤ W := (Set.image_mono hW2).trans hW.le
    obtain ⟨a', ha'⟩ : ∃ a' : Fin m → X.presheaf.obj (op (imOpen U W2)), ∀ i, a' i = a i :=
      ⟨fun i ↦ a i, fun _ ↦ rfl⟩
    have ha2 : ∑ i, a' i * X.res (him.trans hWV) (f i) = 0 := by
      simp only [ha']
      simp only [restrict_res] at ha
      exact ha
    obtain ⟨W3, hW3, hyW3, c, hc⟩ := hgen (imOpen U W2) him a' ha2 y.1 ⟨y, hy, rfl⟩
    have hW3U : W3 ≤ U := hW3.trans (imOpen_le U W2)
    have hW3e : imOpen U (preOpen U W3) = W3 := imOpen_preOpen U hW3U
    refine ⟨preOpen U W3, preOpen_le_of_le_imOpen U hW3, hyW3,
      fun l ↦ X.res hW3e.le (c l), fun i ↦ ?_⟩
    have h3 := congrArg (X.res hW3e.le) (hc i)
    simp only [res_sum, res_mul, res_res, ha'] at h3
    simp only [restrict_res, res_res]
    exact h3

end Restrict

end AlgebraicGeometry.LocallyRingedSpace
