/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
module

public import Mathlib.Algebra.Module.FinitePresentation

/-!
# Finite presentation of a module whose scalar ring is replaced by an isomorphic one

Material for `Mathlib/Algebra/Module/FinitePresentation.lean`; see `README.md` on the mirror tree.

`Module.FinitePresentation.of_ringEquiv` is the finite-presentation analogue of
`Module.Finite.of_ringEquiv`, at the same binders: one additive monoid `N` carries a module
structure over each of `A` and `B`, a ring isomorphism `e : A ≃+* B` identifies the two actions,
and finite presentation transfers. It is stated because the change-of-site arguments on
`AlgebraicGeometry.Scheme.Modules` need it wherever they already need the `Module.Finite` one:
the sections of a sheaf of modules over an open of a scheme are a module over the sections of the
structure sheaf, and restricting along an open immersion changes which ring acts on a *fixed*
carrier rather than the carrier.

## Its proof is not the proof of the `Module.Finite` version, and that is why it is here

`Module.Finite.of_ringEquiv` is `Module.Finite.of_restrictScalars_finite` applied to the algebra
structure `e` defines. **`Module.FinitePresentation` has no `of_restrictScalars` lemma and no
`RingEquiv` transport**, so that reduction is unavailable; the only `RingEquiv`-flavoured
finiteness lemma nearby, `RingEquiv.finite`, is about ring maps rather than modules. What is proved
here is proved from the definition instead, and the definition makes it short because both halves
of it are insensitive to which of the two rings acts:

* the **span** half is `Submodule.coe_span_eq_span_of_surjective`: the `A`-submodule and the
  `B`-submodule of `N` generated by a set have the same carrier, because `e` is surjective;
* the **kernel** half is a bijection between the two coefficient modules,
  `Finsupp.mapRange.linearMap` along `RingHom.toSemilinearMap`, under which the two
  `Finsupp.linearCombination` maps agree; the kernel over `B` is then the image of the kernel over
  `A`, and `Submodule.FG.map` is already stated at a *semilinear* map.

A shorter route exists and was rejected for its binders: `FinitePresentation.of_isBaseChange`
applied to `LinearMap.id`, whose `IsBaseChange` hypothesis follows from
`IsBaseChange.of_lift_unique` in about ten lines. **That version compiles**, and it needs
`CommRing A`, `CommRing B` and `AddCommGroup N`, because `FinitePresentation.of_isBaseChange` is
stated over a `CommRing`. The version below is the one that sits at `Module.Finite.of_ringEquiv`'s
binders, which is the reason to prefer it.

## Main results

- `Module.FinitePresentation.of_ringEquiv`
-/

@[expose] public section

namespace Module.FinitePresentation

/-- **Finite presentation transfers along a ring isomorphism identifying two actions on one
carrier.**

`N` is a module over both `A` and `B`, `e : A ≃+* B` is a ring isomorphism, and `he` says the two
actions agree along it. Then `N` is a finitely presented `B`-module if it is a finitely presented
`A`-module.

The finite generating set is the same `Finset` in both cases, and the two things
`Module.FinitePresentation` asks of it are transported separately; see the module docstring for
why this is not `Module.Finite.of_ringEquiv`'s proof with a different name. -/
theorem of_ringEquiv {A B N : Type*} [CommSemiring A] [CommSemiring B] [AddCommMonoid N]
    [Module A N] [Module B N] (e : A ≃+* B) (he : ∀ (a : A) (n : N), a • n = e a • n)
    [h : Module.FinitePresentation A N] : Module.FinitePresentation B N := by
  letI : Algebra A B := e.toRingHom.toAlgebra
  haveI : IsScalarTower A B N := ⟨fun a b n ↦ by
    simp only [Algebra.smul_def, RingHom.algebraMap_toAlgebra, RingEquiv.toRingHom_eq_coe,
      RingHom.coe_coe]
    rw [he a (b • n), mul_smul]⟩
  haveI : RingHomSurjective (e : A →+* B) := ⟨e.surjective⟩
  obtain ⟨s, hspan, hker⟩ := h
  set φ : (↥s →₀ A) →ₛₗ[(e : A →+* B)] (↥s →₀ B) :=
    Finsupp.mapRange.linearMap (e : A →+* B).toSemilinearMap with hφ
  have hcomp : ∀ c, Finsupp.linearCombination B ((↑) : ↥s → N) (φ c) =
      Finsupp.linearCombination A ((↑) : ↥s → N) c := fun c ↦ by
    rw [Finsupp.linearCombination_apply, Finsupp.linearCombination_apply, hφ]
    simp only [Finsupp.mapRange.linearMap_apply]
    rw [Finsupp.sum_mapRange_index (by simp)]
    exact Finsupp.sum_congr fun i _ ↦ (he _ _).symm
  refine ⟨s, ?_, ?_⟩
  · apply SetLike.ext'
    rw [Submodule.coe_span_eq_span_of_surjective A B e.surjective _, hspan]
    simp
  · have hkeq : LinearMap.ker (Finsupp.linearCombination B ((↑) : ↥s → N)) =
        Submodule.map φ (LinearMap.ker (Finsupp.linearCombination A ((↑) : ↥s → N))) := by
      apply le_antisymm
      · intro d hd
        have hd' : φ (Finsupp.mapRange e.symm (map_zero _) d) = d := by
          ext i; simp [hφ]
        refine ⟨Finsupp.mapRange e.symm (map_zero _) d, ?_, hd'⟩
        change Finsupp.linearCombination A _ _ = 0
        rw [← hcomp, hd']; exact hd
      · rintro _ ⟨c, hc, rfl⟩
        change Finsupp.linearCombination B _ (φ c) = 0
        rw [hcomp]; exact hc
    rw [hkeq]
    exact hker.map φ

end Module.FinitePresentation
