/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Oka.LocalOkaRing

/-!
# The maximal ideal of the germ ring, and the truncations

The germ ring `LocalOkaRing ι` is a local ring whose maximal ideal is the set of germs vanishing
at the origin. This file identifies that ideal concretely — it is generated by the coordinate
functions — describes its powers, and deduces that the germ ring and the ring of *formal* power
series have the same truncations.

The one substantial step is that the maximal ideal is generated by the coordinates. The formal
statement, that a power series with vanishing constant term is `∑ i, Xᵢ · Qᵢ`, is immediate; the
content is that the `Qᵢ` may be taken *convergent*. `MvPowerSeries.exists_eq_sum_X_mul` proves
this by assigning to every nonzero exponent one coordinate occurring in it — no ordering of the
variables is needed, any choice function will do — and letting `Qᵢ` collect the coefficients of
the exponents assigned to `i`, shifted down by one in the `i`-th place. Convergence is inherited
termwise, the shift costing exactly one factor of the polyradius.

Everything else follows. The `k`-th power of the maximal ideal is the ideal of germs vanishing
to order `k`, by induction, and the same statement holds formally; comparing the two gives the
isomorphism `𝒪 ⧸ 𝔪 ^ k ≃ 𝒪̂ ⧸ 𝔪̂ ^ k`, since a truncated power series is a polynomial and hence
convergent. In particular the germs and the formal power series are indistinguishable to any
finite order, which is the last entry in the germs ↔ formal power series dictionary that
`Oka/StalkEquiv.lean` began.

## Main results

- `MvPowerSeries.exists_eq_sum_X_mul`: a power series with vanishing constant term is a
  combination of the coordinates, with cofactors converging wherever it does and vanishing to one
  order less.
- `LocalOkaRing.maximalIdeal_eq_span_coord`: the maximal ideal is generated by the coordinates.
- `LocalOkaRing.mem_maximalIdeal_pow_iff` and `MvPowerSeries.mem_maximalIdeal_pow_iff`: the
  `k`-th power of the maximal ideal consists of the germs, respectively the formal power series,
  whose coefficients in total degree less than `k` vanish.
- `LocalOkaRing.truncQuotientEquiv`: `𝒪 ⧸ 𝔪 ^ k ≃ₐ[ℂ] ℂ⟦Xᵢ⟧ ⧸ 𝔪̂ ^ k`.
- `LocalOkaRing.iInf_maximalIdeal_pow_eq_bot`: a germ vanishing to every order is zero.

## Main definitions

- `LocalOkaRing.coord i`: the `i`-th coordinate function, as a germ.
- `LocalOkaRing.trunc k F`: the truncation of a formal power series to total degree less
  than `k`, which has finite support and is therefore a germ.

## References

- [Hans Grauert and Reinhold Remmert, *Analytische Stellenalgebren*][grauert-remmert1971], §I
- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984], §A
-/

universe u

open MvPowerSeries

namespace MvPowerSeries

variable {ι : Type u}

@[simp]
lemma evalMonomial_single_one (i : ι) (x : ι → ℂ) :
    evalMonomial (Finsupp.single i 1) x = x i :=
  (Finsupp.prod_single_index (by simp)).trans (pow_one _)

/-- The coefficients of `X i * P`: the `d`-th one is the `(d - single i 1)`-th coefficient of
`P` when `d` involves the variable `i`, and vanishes otherwise. -/
lemma coeff_X_mul' (i : ι) (P : MvPowerSeries ι ℂ) (d : ι →₀ ℕ) :
    coeff d (X i * P) = if d i = 0 then 0 else coeff (d - Finsupp.single i 1) P := by
  classical
  rw [X, coeff_monomial_mul, one_mul]
  by_cases h : d i = 0
  · rw [if_pos h, if_neg]
    exact fun hle ↦ by simpa [h] using hle i
  · rw [if_neg h, if_pos]
    exact Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr h)

/-- A power series with vanishing constant term is a combination `∑ i, X i * Q i` of the
coordinates, and the `Q i` may be taken to converge wherever the series itself does.

The `Q i` are built by splitting the exponents: a nonzero exponent `d` is assigned to a single
coordinate `idx d` occurring in it, and `Q i` collects the coefficients of the exponents assigned
to `i`, shifted down by one in the `i`-th place. Convergence is then inherited termwise, the shift
costing exactly one factor of the polyradius. -/
theorem exists_eq_sum_X_mul [Fintype ι] [Nonempty ι]
    {P : MvPowerSeries ι ℂ} (hP : constantCoeff P = 0) :
    ∃ Q : ι → MvPowerSeries ι ℂ, P = ∑ i, X i * Q i ∧
      (∀ ρ : ℝ, 0 < ρ → P.SummableAt (fun _ ↦ (ρ : ℂ)) →
        ∀ i, (Q i).SummableAt (fun _ ↦ (ρ : ℂ))) ∧
      ∀ k : ℕ, (∀ d : ι →₀ ℕ, ∑ j, d j < k + 1 → coeff d P = 0) →
        ∀ (i : ι) (e : ι →₀ ℕ), ∑ j, e j < k → coeff e (Q i) = 0 := by
  classical
  -- for each nonzero exponent, choose a coordinate occurring in it
  have hex : ∀ d : ι →₀ ℕ, ∃ i : ι, d ≠ 0 → d i ≠ 0 := by
    intro d
    rcases eq_or_ne d 0 with rfl | hd
    · exact ⟨Classical.arbitrary ι, fun h ↦ absurd rfl h⟩
    · obtain ⟨i, hi⟩ := Finsupp.support_nonempty_iff.mpr hd
      exact ⟨i, fun _ ↦ Finsupp.mem_support_iff.mp hi⟩
  choose idx hidx using hex
  set Q : ι → MvPowerSeries ι ℂ := fun i e ↦
    if idx (e + Finsupp.single i 1) = i then coeff (e + Finsupp.single i 1) P else 0 with hQdef
  have hQcoeff : ∀ (i : ι) (e : ι →₀ ℕ), coeff e (Q i) =
      if idx (e + Finsupp.single i 1) = i then coeff (e + Finsupp.single i 1) P else 0 :=
    fun _ _ ↦ rfl
  have hsingle : ∀ (i : ι) (e : ι →₀ ℕ),
      ∑ j, (e + Finsupp.single i 1 : ι →₀ ℕ) j = (∑ j, e j) + 1 := by
    intro i e
    simp [Finsupp.single_apply, Finset.sum_add_distrib]
  refine ⟨Q, ?_, ?_, ?_⟩
  · -- the coefficientwise identity
    ext d
    rw [map_sum]
    have hterm : ∀ i : ι, coeff d (X i * Q i) =
        if d i = 0 then 0 else if idx d = i then coeff d P else 0 := by
      intro i
      rw [coeff_X_mul']
      rcases eq_or_ne (d i) 0 with h | h
      · rw [if_pos h, if_pos h]
      · rw [if_neg h, if_neg h, hQcoeff,
          tsub_add_cancel_of_le (Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr h))]
    simp only [hterm]
    rcases eq_or_ne d 0 with rfl | hd
    · rw [Finset.sum_eq_zero fun i _ ↦ if_pos (by simp), coeff_zero_eq_constantCoeff_apply, hP]
    · rw [Finset.sum_eq_single (idx d)]
      · rw [if_neg (hidx d hd), if_pos rfl]
      · intro i _ hi
        rcases eq_or_ne (d i) 0 with h | h
        · rw [if_pos h]
        · rw [if_neg h, if_neg (Ne.symm hi)]
      · intro h
        exact absurd (Finset.mem_univ _) h
  · -- the convergence estimate
    intro ρ hρ hs i
    have hinj : Function.Injective fun e : ι →₀ ℕ ↦ e + Finsupp.single i 1 :=
      add_left_injective _
    refine Summable.of_nonneg_of_le (fun _ ↦ norm_nonneg _) (fun e ↦ ?_)
      ((hs.comp_injective hinj).mul_left ρ⁻¹)
    have hev : evalMonomial (e + Finsupp.single i 1) (fun _ ↦ (ρ : ℂ)) =
        evalMonomial e (fun _ ↦ (ρ : ℂ)) * (ρ : ℂ) := by
      rw [evalMonomial_add, evalMonomial_single_one]
    have hnorm : ‖P.term (fun _ ↦ (ρ : ℂ)) (e + Finsupp.single i 1)‖ =
        ‖coeff (e + Finsupp.single i 1) P‖ * ‖evalMonomial e (fun _ ↦ (ρ : ℂ))‖ * ρ := by
      rw [term, hev, norm_mul, norm_mul, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos hρ, mul_assoc]
    rw [Function.comp_apply, hnorm, term, hQcoeff, norm_mul,
      show ρ⁻¹ * (‖coeff (e + Finsupp.single i 1) P‖ *
        ‖evalMonomial e (fun _ ↦ (ρ : ℂ))‖ * ρ) =
        ‖coeff (e + Finsupp.single i 1) P‖ * ‖evalMonomial e (fun _ ↦ (ρ : ℂ))‖ from by
          field_simp]
    refine mul_le_mul_of_nonneg_right ?_ (norm_nonneg _)
    split_ifs with h
    · exact le_rfl
    · simp
  · -- the order of vanishing
    intro k hk i e he
    rw [hQcoeff]
    split_ifs with h
    · exact hk _ (by rw [hsingle]; omega)
    · rfl

/-! ### The formal picture -/

lemma mem_maximalIdeal_iff {P : MvPowerSeries ι ℂ} :
    P ∈ IsLocalRing.maximalIdeal (MvPowerSeries ι ℂ) ↔ constantCoeff P = 0 := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_iff_constantCoeff,
    isUnit_iff_ne_zero, not_not]

/-- The `k`-th power of the maximal ideal of `MvPowerSeries ι ℂ` consists of the series whose
coefficients in total degree less than `k` vanish. This is the formal counterpart of
`LocalOkaRing.mem_maximalIdeal_pow_iff`. -/
theorem mem_maximalIdeal_pow_iff [Fintype ι] {k : ℕ} {P : MvPowerSeries ι ℂ} :
    P ∈ IsLocalRing.maximalIdeal (MvPowerSeries ι ℂ) ^ k ↔
      ∀ d : ι →₀ ℕ, ∑ i, d i < k → coeff d P = 0 := by
  classical
  induction k generalizing P with
  | zero => simp
  | succ k ih =>
    constructor
    · intro hP
      rw [pow_succ] at hP
      refine Submodule.mul_induction_on hP ?_ ?_
      · intro a ha b hb d hd
        rw [coeff_mul]
        refine Finset.sum_eq_zero fun p hp ↦ ?_
        rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
        have hsum : (∑ i, p.1 i) + (∑ i, p.2 i) = ∑ i, d i := by
          rw [← Finset.sum_add_distrib]
          exact Finset.sum_congr rfl fun i _ ↦ by rw [← Finsupp.add_apply, hp]
        rcases Nat.eq_zero_or_pos (∑ i, p.2 i) with h2 | h2
        · have hp2 : p.2 = 0 := by
            ext i
            exact Nat.eq_zero_of_le_zero (h2 ▸ Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _)
              (Finset.mem_univ i))
          rw [hp2, coeff_zero_eq_constantCoeff_apply, mem_maximalIdeal_iff.mp hb, mul_zero]
        · rw [ih.mp ha p.1 (by omega), zero_mul]
      · intro x y hx hy d hd
        rw [map_add, hx d hd, hy d hd, add_zero]
    · intro hP
      rcases isEmpty_or_nonempty ι with hι | hι
      · have hP0 : P = 0 := by
          refine MvPowerSeries.ext fun d ↦ ?_
          have hd : d = 0 := by ext i; exact (IsEmpty.false i).elim
          subst hd
          rw [map_zero]
          exact hP 0 (by simp)
        rw [hP0]
        exact Submodule.zero_mem _
      · have hP0 : constantCoeff P = 0 := by
          rw [← coeff_zero_eq_constantCoeff_apply]
          exact hP 0 (by simp)
        obtain ⟨Q, hQ, -, hQvan⟩ := exists_eq_sum_X_mul hP0
        rw [hQ, pow_succ']
        refine Submodule.sum_mem _ fun i _ ↦ Ideal.mul_mem_mul ?_ ?_
        · exact mem_maximalIdeal_iff.mpr (by simp)
        · exact ih.mpr fun e he ↦ hQvan k hP i e he

/-- A power series with only finitely many nonzero coefficients converges everywhere. -/
lemma locallyConvergent_of_coeff_eq_zero {P : MvPowerSeries ι ℂ} {s : Finset (ι →₀ ℕ)}
    (h : ∀ d ∉ s, coeff d P = 0) : P.LocallyConvergent :=
  .of_forall fun x ↦ summable_of_ne_finset_zero (s := s) fun d hd ↦ by
    rw [term, h d hd, zero_mul, norm_zero]

/-- Absolute convergence at a constant polyradius implies local convergence. -/
lemma locallyConvergent_of_summableAt_const [Finite ι] {P : MvPowerSeries ι ℂ} {ρ : ℝ}
    (hρ : 0 < ρ) (h : P.SummableAt (fun _ ↦ (ρ : ℂ))) : P.LocallyConvergent := by
  have := Fintype.ofFinite ι
  filter_upwards [Metric.ball_mem_nhds (0 : ι → ℂ) hρ] with x hx
  refine h.mono fun i ↦ ?_
  rw [Complex.norm_real, Real.norm_eq_abs, abs_of_pos hρ]
  exact (norm_le_pi_norm x i).trans (mem_ball_zero_iff.mp hx).le

end MvPowerSeries

namespace LocalOkaRing

variable {ι : Type u}

/-- The `i`-th coordinate function, as a germ at the origin. -/
noncomputable def coord (i : ι) : LocalOkaRing ι :=
  ⟨MvPowerSeries.X i, .of_forall fun x ↦ by
    classical
    refine summable_of_ne_finset_zero (s := {Finsupp.single i 1}) fun d hd ↦ ?_
    rw [Finset.mem_singleton] at hd
    rw [MvPowerSeries.term, MvPowerSeries.coeff_X, if_neg hd, zero_mul, norm_zero]⟩

@[simp]
lemma coe_coord (i : ι) : (coord i : MvPowerSeries ι ℂ) = MvPowerSeries.X i := rfl

@[simp]
lemma constantCoeff_coord (i : ι) : constantCoeff (coord i) = 0 := by
  rw [constantCoeff_apply, coe_coord, ← MvPowerSeries.coeff_zero_eq_constantCoeff_apply]
  classical
  rw [MvPowerSeries.coeff_X, if_neg]
  exact fun h ↦ by simpa using congrArg (fun e ↦ e i) h

section Finite

variable [Finite ι]

/-! ### The maximal ideal as the germs vanishing at the origin -/

lemma mem_maximalIdeal_iff {P : LocalOkaRing ι} :
    P ∈ IsLocalRing.maximalIdeal (LocalOkaRing ι) ↔ constantCoeff P = 0 := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_iff, not_not]

lemma maximalIdeal_eq_ker_constantCoeff :
    IsLocalRing.maximalIdeal (LocalOkaRing ι) = RingHom.ker (constantCoeff (ι := ι)) :=
  Ideal.ext fun _ ↦ mem_maximalIdeal_iff.trans RingHom.mem_ker.symm

/-! ### The maximal ideal is generated by the coordinates -/

/-- **The maximal ideal of the germ ring is generated by the coordinates.**

The inclusion `⊇` is the observation that a coordinate vanishes at the origin. The inclusion
`⊆` is the substance: a germ vanishing at the origin can be written `∑ i, Xᵢ · Qᵢ` with the `Qᵢ`
again *convergent*, which is `MvPowerSeries.exists_eq_sum_X_mul`. -/
theorem maximalIdeal_eq_span_coord :
    IsLocalRing.maximalIdeal (LocalOkaRing ι) = Ideal.span (Set.range (coord (ι := ι))) := by
  classical
  have := Fintype.ofFinite ι
  refine le_antisymm (fun P hP ↦ ?_) ?_
  · rw [mem_maximalIdeal_iff] at hP
    rcases isEmpty_or_nonempty ι with hι | hι
    · -- with no variables a germ is its own constant term, hence zero
      have hP0 : P = 0 := by
        refine LocalOkaRing.ext (MvPowerSeries.ext fun d ↦ ?_)
        have hd : d = 0 := by ext i; exact (IsEmpty.false i).elim
        subst hd
        rw [MvPowerSeries.coeff_zero_eq_constantCoeff_apply,
          MvPowerSeries.coeff_zero_eq_constantCoeff_apply, ← constantCoeff_apply,
          ← constantCoeff_apply, hP, map_zero]
      rw [hP0]
      exact Submodule.zero_mem _
    · obtain ⟨ρ, hρ, hsum⟩ := P.2.exists_summableAt_const
      obtain ⟨Q, hQ, hQconv, -⟩ := MvPowerSeries.exists_eq_sum_X_mul
        (P := (P : MvPowerSeries ι ℂ)) (by rw [← constantCoeff_apply]; exact hP)
      set R : ι → LocalOkaRing ι := fun i ↦
        ⟨Q i, MvPowerSeries.locallyConvergent_of_summableAt_const hρ (hQconv ρ hρ hsum i)⟩
        with hR
      have hPeq : P = ∑ i, coord i * R i := by
        refine Subtype.ext ?_
        rw [show ((∑ i, coord i * R i : LocalOkaRing ι) : MvPowerSeries ι ℂ) =
          (localOkaSubring ι).val (∑ i, coord i * R i) from rfl, map_sum]
        simpa using hQ
      rw [hPeq]
      exact Submodule.sum_mem _ fun i _ ↦
        Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact mem_maximalIdeal_iff.mpr (constantCoeff_coord i)

end Finite

section Fintype

variable [Fintype ι]

/-! ### Powers of the maximal ideal are the germs vanishing to a given order -/

/-- **The `k`-th power of the maximal ideal is the ideal of germs vanishing to order `k`**: it
consists exactly of the germs all of whose coefficients in total degree less than `k` vanish. -/
theorem mem_maximalIdeal_pow_iff {k : ℕ} {P : LocalOkaRing ι} :
    P ∈ IsLocalRing.maximalIdeal (LocalOkaRing ι) ^ k ↔
      ∀ d : ι →₀ ℕ, ∑ i, d i < k → MvPowerSeries.coeff d (P : MvPowerSeries ι ℂ) = 0 := by
  classical
  induction k generalizing P with
  | zero => simp
  | succ k ih =>
    constructor
    · -- a product of `k + 1` germs vanishing at the origin vanishes to order `k + 1`
      intro hP
      rw [pow_succ] at hP
      refine Submodule.mul_induction_on hP ?_ ?_
      · intro a ha b hb d hd
        rw [MulMemClass.coe_mul, MvPowerSeries.coeff_mul]
        refine Finset.sum_eq_zero fun p hp ↦ ?_
        rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
        have hsum : (∑ i, p.1 i) + (∑ i, p.2 i) = ∑ i, d i := by
          rw [← Finset.sum_add_distrib]
          exact Finset.sum_congr rfl fun i _ ↦ by rw [← Finsupp.add_apply, hp]
        rcases Nat.eq_zero_or_pos (∑ i, p.2 i) with h2 | h2
        · -- the second factor contributes its constant term, which vanishes
          have hp2 : p.2 = 0 := by
            ext i
            exact Nat.eq_zero_of_le_zero (h2 ▸ Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _)
              (Finset.mem_univ i))
          rw [hp2, MvPowerSeries.coeff_zero_eq_constantCoeff_apply, ← constantCoeff_apply,
            mem_maximalIdeal_iff.mp hb, mul_zero]
        · rw [ih.mp ha p.1 (by omega), zero_mul]
      · intro x y hx hy d hd
        rw [AddMemClass.coe_add, map_add, hx d hd, hy d hd, add_zero]
    · -- conversely, split off one coordinate and induct
      intro hP
      rcases isEmpty_or_nonempty ι with hι | hι
      · have hP0 : P = 0 := by
          refine LocalOkaRing.ext (MvPowerSeries.ext fun d ↦ ?_)
          have hd : d = 0 := by ext i; exact (IsEmpty.false i).elim
          subst hd
          rw [show ((0 : LocalOkaRing ι) : MvPowerSeries ι ℂ) = 0 from rfl, map_zero]
          exact hP 0 (by simp)
        rw [hP0]
        exact Submodule.zero_mem _
      · obtain ⟨ρ, hρ, hsum⟩ := P.2.exists_summableAt_const
        have hP0 : MvPowerSeries.constantCoeff (P : MvPowerSeries ι ℂ) = 0 := by
          rw [← MvPowerSeries.coeff_zero_eq_constantCoeff_apply]
          exact hP 0 (by simp)
        obtain ⟨Q, hQ, hQconv, hQvan⟩ := MvPowerSeries.exists_eq_sum_X_mul
          (P := (P : MvPowerSeries ι ℂ)) hP0
        set R : ι → LocalOkaRing ι := fun i ↦
          ⟨Q i, MvPowerSeries.locallyConvergent_of_summableAt_const hρ (hQconv ρ hρ hsum i)⟩
        have hPeq : P = ∑ i, coord i * R i := by
          refine Subtype.ext ?_
          rw [show ((∑ i, coord i * R i : LocalOkaRing ι) : MvPowerSeries ι ℂ) =
            (localOkaSubring ι).val (∑ i, coord i * R i) from rfl, map_sum]
          simpa using hQ
        rw [hPeq, pow_succ']
        refine Submodule.sum_mem _ fun i _ ↦ Ideal.mul_mem_mul ?_ ?_
        · exact mem_maximalIdeal_iff.mpr (constantCoeff_coord i)
        · exact ih.mpr fun e he ↦ hQvan k hP i e he

/-! ### The truncations agree with those of the formal power series -/

/-- The truncation of a formal power series to total degree less than `k`. It has finite
support, so it is a germ.

This is not Mathlib's `MvPowerSeries.trunc`, which truncates below a fixed *multidegree*
`n : σ →₀ ℕ` and lands in `MvPolynomial`; the bound here is on the *total* degree, which is what
the filtration by powers of the maximal ideal uses. -/
noncomputable def trunc (k : ℕ) (F : MvPowerSeries ι ℂ) : LocalOkaRing ι :=
  ⟨fun d ↦ if ∑ i, d i < k then MvPowerSeries.coeff d F else 0, by
    classical
    refine MvPowerSeries.locallyConvergent_of_coeff_eq_zero
      (s := (Finset.range k).biUnion (MvPowerSeries.degFinset ι)) fun d hd ↦ ?_
    rw [MvPowerSeries.coeff_apply, if_neg]
    intro hlt
    exact hd (Finset.mem_biUnion.mpr ⟨_, Finset.mem_range.mpr hlt,
      MvPowerSeries.self_mem_degFinset d⟩)⟩

@[simp]
lemma coeff_trunc (k : ℕ) (F : MvPowerSeries ι ℂ) (d : ι →₀ ℕ) :
    MvPowerSeries.coeff d (trunc k F : MvPowerSeries ι ℂ) =
      if ∑ i, d i < k then MvPowerSeries.coeff d F else 0 :=
  rfl

/-- The germ ring and the formal power series have the same `k`-th truncation: the inclusion
induces an isomorphism `𝒪 ⧸ 𝔪 ^ k ≃ ℂ⟦X⟧ ⧸ 𝔪' ^ k`.

Surjectivity is because the truncation of a formal power series is a polynomial, hence
convergent; injectivity is `mem_maximalIdeal_pow_iff` together with its formal counterpart. -/
noncomputable def truncQuotientEquiv (k : ℕ) :
    (LocalOkaRing ι ⧸ IsLocalRing.maximalIdeal (LocalOkaRing ι) ^ k) ≃ₐ[ℂ]
      (MvPowerSeries ι ℂ ⧸ IsLocalRing.maximalIdeal (MvPowerSeries ι ℂ) ^ k) := by
  classical
  set f : LocalOkaRing ι →ₐ[ℂ] (MvPowerSeries ι ℂ ⧸
      IsLocalRing.maximalIdeal (MvPowerSeries ι ℂ) ^ k) :=
    (Ideal.Quotient.mkₐ ℂ _).comp (localOkaSubring ι).val with hf
  have hsurj : Function.Surjective f := by
    intro y
    obtain ⟨F, rfl⟩ := Ideal.Quotient.mk_surjective y
    refine ⟨trunc k F, ?_⟩
    rw [hf, AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk, Subalgebra.val_apply,
      Ideal.Quotient.eq]
    refine MvPowerSeries.mem_maximalIdeal_pow_iff.mpr fun d hd ↦ ?_
    rw [map_sub, coeff_trunc, if_pos hd, sub_self]
  have hker : RingHom.ker f.toRingHom =
      IsLocalRing.maximalIdeal (LocalOkaRing ι) ^ k := by
    ext P
    rw [RingHom.mem_ker]
    change (Ideal.Quotient.mk _ (P : MvPowerSeries ι ℂ) = 0) ↔ _
    rw [Ideal.Quotient.eq_zero_iff_mem, MvPowerSeries.mem_maximalIdeal_pow_iff,
      mem_maximalIdeal_pow_iff]
  exact (Ideal.quotientEquivAlgOfEq ℂ hker.symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective hsurj)

end Fintype

section Consequences

variable [Finite ι]

/-! ### Consequences -/

/-- **Krull intersection for the germ ring**, in the concrete form: a germ vanishing to every
order is zero. This is the identity theorem for convergent power series, read off from
`mem_maximalIdeal_pow_iff`; no appeal to the general Krull intersection theorem is needed. -/
theorem iInf_maximalIdeal_pow_eq_bot :
    ⨅ k : ℕ, IsLocalRing.maximalIdeal (LocalOkaRing ι) ^ k = ⊥ := by
  refine le_antisymm (fun P hP ↦ ?_) bot_le
  rw [Submodule.mem_iInf] at hP
  rw [Ideal.mem_bot]
  refine LocalOkaRing.ext (MvPowerSeries.ext fun d ↦ ?_)
  rw [show ((0 : LocalOkaRing ι) : MvPowerSeries ι ℂ) = 0 from rfl, map_zero]
  have := Fintype.ofFinite ι
  exact mem_maximalIdeal_pow_iff.mp (hP ((∑ i, d i) + 1)) d (by omega)

end Consequences

end LocalOkaRing
