/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.LocalOkaRing
import Oka.Weierstrass

/-!
# Oka's bounded degree lemma

Let `F₁, …, F_p` be monic polynomials of degree less than `d` over the germ ring
`LocalOkaRing (Fin n)`, viewed through `LocalOkaRing.fromPolynomial` as germs in `n + 1`
variables. Oka's bounded degree lemma states that the module of relations between the `F_j`
over `LocalOkaRing (Fin (n + 1))` is generated by those relations whose entries are again
polynomials of bounded degree. This is the algebraic engine of the inductive step in Oka's
coherence lemma: since the relations of bounded degree form a module over the germs in `n`
variables, it replaces relations between germs in `n + 1` variables by relations between
finitely many germs in `n` variables.

Two forms are proved. In `oka_lemma_weierstrass` the first entry is assumed to be a
Weierstrass polynomial and the degree bound is any `m ≥ 2 * d`; the general form `oka_lemma`
is reduced to it by factoring the first entry as a Weierstrass polynomial times a unit
(`exists_weierstrass_factor`), and there the bound is `d` itself.

The file first completes the Weierstrass division theorem of `Oka.Weierstrass` by its
uniqueness statement, which is what allows a quotient by a Weierstrass polynomial to be
recognized as a polynomial.

## Main definitions

- `polyIncl` and `polyInclPi`: a polynomial (resp. a row of polynomials) of bounded degree
  over the germs in `n` variables, viewed as a germ (resp. a row of germs) in `n + 1`
  variables.
- `K_deg d F`: the relations of bounded degree `d`, as a module over the germs in `n`
  variables.
- `KK_deg d F`: the submodule of all relations generated by `K_deg d F`.

## Main results

- `MvPowerSeries.eq_zero_of_fromPolynomial'_mul_eq`: a multiple of a Weierstrass polynomial
  which is a polynomial of smaller degree vanishes. This is purely formal, and is proved by
  induction on the total degree of the exponents in the first `n` variables.
- `localweierstrass_division_unique`: uniqueness of the quotient and the remainder in the
  Weierstrass division theorem `localweierstrass_division`.
- `fromPolynomial_eq_divByMonic`: the Weierstrass division of a polynomial is its polynomial
  division.
- `exists_weierstrass_factor`: a monic polynomial over the germ ring factors as a Weierstrass
  polynomial times a polynomial whose germ is a unit.
- `oka_lemma` and `oka_lemma_weierstrass`: Oka's bounded degree lemma, in the form for a row
  of monic polynomials and in the form for a row whose first entry is a Weierstrass
  polynomial.
-/

open Polynomial

variable {n : ℕ}

noncomputable instance : Algebra (LocalOkaRing (Fin n))
    (LocalOkaRing (Fin (n + 1))) :=
  ((LocalOkaRing.fromPolynomial (n := n)).toRingHom.comp
    (Polynomial.C : LocalOkaRing (Fin n) →+*
      (LocalOkaRing (Fin n))[X])).toAlgebra

noncomputable def LocalOkaRing.fromPolynomialAlg :
    (LocalOkaRing (Fin n))[X] →ₐ[LocalOkaRing (Fin n)] LocalOkaRing (Fin (n + 1)) where
  toRingHom := LocalOkaRing.fromPolynomial.toRingHom
  commutes' _ := rfl

noncomputable def polyIncl {d : ℕ} :
    (LocalOkaRing (Fin n))[X]_d →ₗ[LocalOkaRing (Fin n)]
        (LocalOkaRing (Fin (n + 1))) :=
  LocalOkaRing.fromPolynomialAlg (n := n) ∘ₗ (Submodule.subtype _)

noncomputable def polyInclPi {p : ℕ} {d : ℕ} :
    ((Fin p) → (LocalOkaRing (Fin n))[X]_d) →ₗ[LocalOkaRing (Fin n)]
        ((Fin p) → (LocalOkaRing (Fin (n + 1)))) :=
  LinearMap.piMap (fun _ : Fin p ↦ polyIncl)

noncomputable def K_deg {p : ℕ} (d : ℕ) (F : Fin p → LocalOkaRing (Fin (n + 1))) :
    Submodule (LocalOkaRing (Fin n)) (Fin p → (LocalOkaRing (Fin n))[X]_d) :=
  LinearMap.ker ((linOfFun F).restrictScalars _ ∘ₗ
    polyInclPi)

noncomputable def KK_deg {p : ℕ} (d : ℕ) (F : Fin p → LocalOkaRing (Fin (n + 1))) :
    Submodule (LocalOkaRing (Fin (n + 1))) (Fin p → LocalOkaRing (Fin (n + 1))) :=
  Submodule.span (LocalOkaRing (Fin (n + 1)))
    (Submodule.map polyInclPi (K_deg d F)).carrier

@[simp]
lemma polyIncl_apply {d : ℕ} (x : (LocalOkaRing (Fin n))[X]_d) :
    polyIncl x = LocalOkaRing.fromPolynomial (x : (LocalOkaRing (Fin n))[X]) :=
  rfl

/-! ### Uniqueness in the Weierstrass division theorem

The Weierstrass division theorem `localweierstrass_division` provides existence of the
division; here we prove the uniqueness part, which is needed to recognize quotients by
Weierstrass polynomials as polynomials. The key computation
`MvPowerSeries.eq_zero_of_fromPolynomial'_mul_eq` is purely formal: if a multiple of a
Weierstrass polynomial is a polynomial of degree less than the degree of the Weierstrass
polynomial, then it vanishes. It is proven by induction on the total degree of the exponents
in the first `n` variables.
-/

namespace MvPowerSeries

/-- The restriction of an exponent on `Fin (n + 1)` to the first `n` variables. -/
noncomputable def finInit (u : Fin (n + 1) →₀ ℕ) : Fin n →₀ ℕ :=
  Finsupp.equivFunOnFinite.symm fun i ↦ u i.castSucc

@[simp]
lemma finInit_apply (u : Fin (n + 1) →₀ ℕ) (i : Fin n) : finInit u i = u i.castSucc :=
  rfl

@[simp]
lemma finInit_add (u v : Fin (n + 1) →₀ ℕ) : finInit (u + v) = finInit u + finInit v := by
  ext i
  simp

@[simp]
lemma finInit_single_last (k : ℕ) :
    finInit (Finsupp.single (Fin.last n) k) = 0 := by
  ext i
  simp [(Fin.castSucc_lt_last i).ne]

/-- Every exponent on `Fin (n + 1)` is the sum of its initial part and its part in the last
variable. -/
lemma mapDomain_finInit_add_single_last (u : Fin (n + 1) →₀ ℕ) :
    Finsupp.mapDomain Fin.castSucc (finInit u) +
      Finsupp.single (Fin.last n) (u (Fin.last n)) = u := by
  ext j
  induction j using Fin.lastCases with
  | last =>
    rw [Finsupp.add_apply, Finsupp.mapDomain_notin_range _ _ (by simp),
      Finsupp.single_eq_same, zero_add]
  | cast i =>
    rw [Finsupp.add_apply, Finsupp.mapDomain_apply (Fin.castSucc_injective n), finInit_apply]
    simp [(Fin.castSucc_lt_last i).ne]

/-- The coefficients of `MvPowerSeries.fromPolynomial' Q` at an arbitrary exponent. -/
lemma coeff_fromPolynomial'_eq {R : Type*} [CommRing R] (Q : (MvPowerSeries (Fin n) R)[X])
    (u : Fin (n + 1) →₀ ℕ) :
    MvPowerSeries.coeff u (fromPolynomial' Q) =
      MvPowerSeries.coeff (finInit u) (Q.coeff (u (Fin.last n))) := by
  conv_lhs => rw [← mapDomain_finInit_add_single_last u]
  rw [coeff_fromPolynomial']

/-- Uniqueness part of the Weierstrass division theorem, key step: if a multiple of (the
power series attached to) a Weierstrass polynomial `W` is (the power series attached to) a
polynomial of degree less than the degree of `W`, then both the cofactor and the polynomial
vanish. -/
theorem eq_zero_of_fromPolynomial'_mul_eq {W : (MvPowerSeries (Fin n) ℂ)[X]}
    (hW : IsLocalWeierstrassPolynomial W) {c : MvPowerSeries (Fin (n + 1)) ℂ}
    {r : (MvPowerSeries (Fin n) ℂ)[X]} (hr : r.degree < W.degree)
    (heq : fromPolynomial' W * c = fromPolynomial' r) :
    c = 0 ∧ r = 0 := by
  classical
  have hWdeg : W.degree = (W.natDegree : WithBot ℕ) :=
    Polynomial.degree_eq_natDegree hW.monic.ne_zero
  have key : ∀ a : ℕ, ∀ u : Fin (n + 1) →₀ ℕ, Finsupp.degree (finInit u) < a →
      MvPowerSeries.coeff u c = 0 := by
    intro a
    induction a with
    | zero => exact fun u hu ↦ absurd hu (Nat.not_lt_zero _)
    | succ a ih =>
      intro u hu
      set D : Fin (n + 1) →₀ ℕ := u + Finsupp.single (Fin.last n) W.natDegree with hDdef
      have hDlast : D (Fin.last n) = u (Fin.last n) + W.natDegree := by
        rw [hDdef, Finsupp.add_apply, Finsupp.single_eq_same]
      -- the coefficient of `r` at the exponent `D` vanishes for degree reasons
      have hrz : r.coeff (D (Fin.last n)) = 0 := by
        apply Polynomial.coeff_eq_zero_of_degree_lt
        rw [hDlast]
        refine lt_of_lt_of_le (hr.trans_eq hWdeg) ?_
        exact_mod_cast Nat.le_add_left _ _
      -- in the product, only the pair `(single (last n) e, u)` contributes
      have hsum : ∑ p ∈ Finset.antidiagonal D,
          MvPowerSeries.coeff p.1 (fromPolynomial' W) * MvPowerSeries.coeff p.2 c =
          MvPowerSeries.coeff (Finsupp.single (Fin.last n) W.natDegree)
            (fromPolynomial' W) * MvPowerSeries.coeff u c := by
        refine Finset.sum_eq_single_of_mem
          ((Finsupp.single (Fin.last n) W.natDegree, u) :
            (Fin (n + 1) →₀ ℕ) × (Fin (n + 1) →₀ ℕ)) ?_ ?_
        · rw [Finset.mem_antidiagonal, hDdef]
          exact add_comm _ _
        · rintro ⟨x, y⟩ hxy hne
          rw [Finset.mem_antidiagonal] at hxy
          rw [coeff_fromPolynomial'_eq]
          rcases lt_trichotomy (x (Fin.last n)) W.natDegree with hj | hj | hj
          · by_cases hβ : finInit x = 0
            · rw [hβ, MvPowerSeries.coeff_zero_eq_constantCoeff_apply,
                hW.apply_zero _ (by rw [hWdeg]; exact_mod_cast hj), zero_mul]
            · -- the initial part of `y` has strictly smaller degree
              have hxy' : finInit x + finInit y = finInit u := by
                have h1 := congrArg finInit hxy
                rwa [finInit_add, hDdef, finInit_add, finInit_single_last, add_zero] at h1
              have h1 : 1 ≤ Finsupp.degree (finInit x) := by
                rcases Nat.eq_zero_or_pos (Finsupp.degree (finInit x)) with h | h
                · exact absurd ((Finsupp.degree_eq_zero_iff (finInit x)).mp h) hβ
                · exact h
              have hdy : Finsupp.degree (finInit y) < a := by
                have h2 := congrArg Finsupp.degree hxy'
                rw [map_add] at h2
                omega
              rw [ih y hdy, mul_zero]
          · by_cases hβ : finInit x = 0
            · -- then `(x, y)` is the distinguished pair
              exfalso
              apply hne
              have hx : x = Finsupp.single (Fin.last n) W.natDegree := by
                conv_lhs => rw [← mapDomain_finInit_add_single_last x]
                rw [hβ, Finsupp.mapDomain_zero, zero_add, hj]
              have hy : y = u := by
                rw [hx, hDdef, add_comm u] at hxy
                exact add_left_cancel hxy
              rw [hx, hy]
            · rw [hj, hW.monic.coeff_natDegree, MvPowerSeries.coeff_one, if_neg hβ,
                zero_mul]
          · rw [Polynomial.coeff_eq_zero_of_natDegree_lt hj, map_zero, zero_mul]
      -- the coefficient of the leading term is `1`
      have hlead : MvPowerSeries.coeff (Finsupp.single (Fin.last n) W.natDegree)
          (fromPolynomial' W) = 1 := by
        rw [coeff_fromPolynomial'_eq, finInit_single_last, Finsupp.single_eq_same,
          hW.monic.coeff_natDegree]
        simp
      have hco := congrArg (MvPowerSeries.coeff D) heq
      rw [MvPowerSeries.coeff_mul, coeff_fromPolynomial'_eq, hrz, map_zero, hsum, hlead,
        one_mul] at hco
      exact hco
  have hc : c = 0 := by
    refine MvPowerSeries.ext fun u ↦ ?_
    rw [map_zero]
    exact key (Finsupp.degree (finInit u) + 1) u (Nat.lt_succ_self _)
  refine ⟨hc, ?_⟩
  rw [hc, mul_zero, ← map_zero (fromPolynomial' (R := ℂ) (n := n))] at heq
  exact fromPolynomial'_injective heq.symm

end MvPowerSeries

/-- Uniqueness in the Weierstrass division theorem for germs. -/
theorem localweierstrass_division_unique
    {q : (LocalOkaRing (Fin n))[X]}
    (hq : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring _).toSubring) q))
    {a a' : LocalOkaRing (Fin (n + 1))} {b b' : (LocalOkaRing (Fin n))[X]}
    (hb : b.degree < q.degree) (hb' : b'.degree < q.degree)
    (h : a * LocalOkaRing.fromPolynomial q + LocalOkaRing.fromPolynomial b =
      a' * LocalOkaRing.fromPolynomial q + LocalOkaRing.fromPolynomial b') :
    a = a' ∧ b = b' := by
  have hφinj : Function.Injective (Subring.subtype (localOkaSubring (Fin n)).toSubring) :=
    Subtype.val_injective
  -- rearrange into a divisibility relation and pass to the underlying power series
  have h2 : (a - a') * LocalOkaRing.fromPolynomial q =
      LocalOkaRing.fromPolynomial (b' - b) := by
    rw [map_sub]
    linear_combination h
  have h3 := congrArg
    (Subtype.val : LocalOkaRing (Fin (n + 1)) → MvPowerSeries (Fin (n + 1)) ℂ) h2
  rw [MulMemClass.coe_mul, LocalOkaRing.coe_fromPolynomial,
    LocalOkaRing.coe_fromPolynomial] at h3
  have hkey := MvPowerSeries.eq_zero_of_fromPolynomial'_mul_eq hq
    (r := (b' - b).map (Subring.subtype (localOkaSubring (Fin n)).toSubring)) ?_
    (by rw [mul_comm] at h3; exact h3)
  · obtain ⟨h4, h5⟩ := hkey
    refine ⟨sub_eq_zero.mp (Subtype.ext h4), ?_⟩
    have h6 : b' - b = 0 := (Polynomial.map_eq_zero_iff hφinj).mp h5
    rw [sub_eq_zero] at h6
    exact h6.symm
  · refine lt_of_le_of_lt (Polynomial.degree_map_le) ?_
    rw [Polynomial.degree_map_eq_of_injective hφinj]
    exact lt_of_le_of_lt (Polynomial.degree_sub_le _ _) (max_lt hb' hb)

/-- If the germ attached to a polynomial `P` is divided by a Weierstrass polynomial `q`, the
quotient and remainder are the polynomial quotient and remainder of `P` by `q`. -/
theorem fromPolynomial_eq_divByMonic
    {q : (LocalOkaRing (Fin n))[X]}
    (hq : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring _).toSubring) q))
    (P : (LocalOkaRing (Fin n))[X]) {a : LocalOkaRing (Fin (n + 1))}
    {b : (LocalOkaRing (Fin n))[X]} (hb : b.degree < q.degree)
    (h : LocalOkaRing.fromPolynomial P =
      a * LocalOkaRing.fromPolynomial q + LocalOkaRing.fromPolynomial b) :
    a = LocalOkaRing.fromPolynomial (P /ₘ q) ∧ b = P %ₘ q := by
  have hqm : q.Monic := Polynomial.monic_of_injective Subtype.val_injective hq.monic
  have h2 : LocalOkaRing.fromPolynomial P =
      LocalOkaRing.fromPolynomial (P /ₘ q) * LocalOkaRing.fromPolynomial q +
        LocalOkaRing.fromPolynomial (P %ₘ q) := by
    conv_lhs => rw [← Polynomial.modByMonic_add_div P q]
    rw [map_add, map_mul]
    ring
  exact localweierstrass_division_unique hq hb
    (Polynomial.degree_modByMonic_lt P hqm) (h.symm.trans h2)

/-- Weierstrass preparation for monic polynomials over the germ ring: a monic polynomial
factors as a Weierstrass polynomial times a polynomial cofactor whose germ is a unit. -/
theorem exists_weierstrass_factor {f : (LocalOkaRing (Fin n))[X]} (hf : f.Monic) :
    ∃ g u : (LocalOkaRing (Fin n))[X],
      IsLocalWeierstrassPolynomial
        (g.map (Subring.subtype (localOkaSubring _).toSubring)) ∧
      f = g * u ∧ IsUnit (LocalOkaRing.fromPolynomial u) := by
  -- the germ of a monic polynomial is general in the last variable
  have hgen : ((LocalOkaRing.fromPolynomial f : LocalOkaRing (Fin (n + 1))) :
      MvPowerSeries (Fin (n + 1)) ℂ).IsGeneralIn (Fin.last n) := by
    rw [MvPowerSeries.IsGeneralIn, partialEval_coe_fromPolynomial, ne_eq,
      Polynomial.coe_eq_zero_iff]
    exact (hf.map _).ne_zero
  obtain ⟨u₀, hu₀, g, hg, hfact⟩ :=
    localweierstrass_preparation (LocalOkaRing.fromPolynomial f) hgen
  have hgm : g.Monic := Polynomial.monic_of_injective Subtype.val_injective hg.monic
  -- the unit is the germ of the polynomial quotient `f /ₘ g`
  have h2 : LocalOkaRing.fromPolynomial f =
      u₀ * LocalOkaRing.fromPolynomial g + LocalOkaRing.fromPolynomial 0 := by
    rw [map_zero, add_zero, hfact, mul_comm]
  have hb0 : (0 : (LocalOkaRing (Fin n))[X]).degree < g.degree := by
    rw [Polynomial.degree_zero]
    exact bot_lt_iff_ne_bot.mpr fun hc ↦ hgm.ne_zero (Polynomial.degree_eq_bot.mp hc)
  obtain ⟨h3, h4⟩ := fromPolynomial_eq_divByMonic hg f hb0 h2
  refine ⟨g, f /ₘ g, hg, ?_, ?_⟩
  · have h5 := Polynomial.modByMonic_add_div f g
    rw [← h4, zero_add] at h5
    exact h5.symm
  · rw [← h3]
    exact hu₀

theorem oka_lemma_weierstrass_rhs_containedIn_lhs (p : ℕ) (d : ℕ)
    (F : Fin p → (LocalOkaRing (Fin n))[X]) :
    letI F' (j : Fin p) : LocalOkaRing (Fin (n + 1)) :=
      LocalOkaRing.fromPolynomial (F j)
    Submodule.span _ (Submodule.map polyInclPi (K_deg d F')).carrier ≤
      LinearMap.ker (linOfFun F') := by
  rw [Submodule.span_le]
  intro G hG
  rcases hG with ⟨g, hg, rfl⟩
  simp only [SetLike.mem_coe, LinearMap.mem_ker, Module.Basis.constr_apply_fintype,
    Pi.basisFun_equivFun, LinearEquiv.refl_apply, smul_eq_mul]
  simp only [K_deg, SetLike.mem_coe, LinearMap.mem_ker, LinearMap.coe_comp,
    LinearMap.coe_restrictScalars, Function.comp_apply, Module.Basis.constr_apply_fintype,
    Pi.basisFun_equivFun, LinearEquiv.refl_apply, smul_eq_mul] at hg
  exact hg

theorem oka_lemma (p : ℕ) (d : ℕ)
    (F : Fin p → (LocalOkaRing (Fin n))[X]_d)
    (hF' : ∀ j, (F j).val.Monic) :
    letI F' (j : Fin p) : LocalOkaRing (Fin (n + 1)) :=
      polyIncl (F j)
    LinearMap.ker (linOfFun F') =
      Submodule.span (LocalOkaRing (Fin (n + 1)))
        (Submodule.map polyInclPi (K_deg d F')).carrier := by
  classical
  apply le_antisymm
  · rcases Nat.eq_zero_or_pos p with rfl | hp
    · -- for `p = 0` there is nothing to prove
      intro G _
      rw [Subsingleton.elim G 0]
      exact Submodule.zero_mem _
    intro G hG
    rw [LinearMap.mem_ker] at hG
    simp only [Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun, LinearEquiv.refl_apply,
      smul_eq_mul, polyIncl_apply] at hG
    set zero : Fin p := ⟨0, hp⟩ with hzerodef
    have hd1 : 0 < d := by
      have h0 : (0 : WithBot ℕ) ≤ ((F zero) : (LocalOkaRing (Fin n))[X]).degree :=
        Polynomial.zero_le_degree_iff.mpr (hF' zero).ne_zero
      have h1 : (0 : WithBot ℕ) < d :=
        lt_of_le_of_lt h0 (Polynomial.mem_degreeLT.mp (F zero).2)
      exact_mod_cast h1
    have hFnd : ∀ i, ((F i) : (LocalOkaRing (Fin n))[X]).natDegree < d := fun i ↦
      Polynomial.natDegree_lt_of_mem_degreeLT hd1 (F i).2
    -- Weierstrass factorization `F zero = W * U` with polynomial unit `U`
    obtain ⟨W, U, hW, hfact, hUunit⟩ := exists_weierstrass_factor (hF' zero)
    have hWm : W.Monic := Polynomial.monic_of_injective Subtype.val_injective hW.monic
    have hUm : U.Monic := hWm.of_mul_monic_left (hfact ▸ hF' zero)
    have hWUnd : ((F zero) : (LocalOkaRing (Fin n))[X]).natDegree =
        W.natDegree + U.natDegree := by
      rw [hfact]
      exact hWm.natDegree_mul hUm
    set u₀ : (LocalOkaRing (Fin (n + 1)))ˣ := hUunit.unit with hu₀def
    have hu₀val : (u₀ : LocalOkaRing (Fin (n + 1))) = LocalOkaRing.fromPolynomial U :=
      hUunit.unit_spec
    have hF0 : LocalOkaRing.fromPolynomial ((F zero) : (LocalOkaRing (Fin n))[X]) =
        LocalOkaRing.fromPolynomial W * ↑u₀ := by
      rw [hfact, map_mul, hu₀val]
    -- divide the components of `G` by `W` and twist by the unit
    choose A R hAR hAR' using fun j ↦ localweierstrass_division W hW (G j)
    set Ab : Fin p → LocalOkaRing (Fin (n + 1)) := fun j ↦ A j * ↑u₀⁻¹ with hAbdef
    have hAR'' : ∀ j, G j = Ab j * LocalOkaRing.fromPolynomial
        ((F zero) : (LocalOkaRing (Fin n))[X]) + LocalOkaRing.fromPolynomial (R j) := by
      intro j
      rw [hAR' j, hF0]
      simp only [hAbdef]
      have hcancel : (↑u₀⁻¹ : LocalOkaRing (Fin (n + 1))) * ↑u₀ = 1 := Units.inv_mul u₀
      linear_combination (-(A j * LocalOkaRing.fromPolynomial W)) * hcancel
    -- the elementary relations and the remainder relation
    let E : Fin p → (Fin p → (LocalOkaRing (Fin n))[X]_d) :=
      fun j ↦ -Pi.single zero (F j) + Pi.single j (F zero)
    let S : LocalOkaRing (Fin (n + 1)) :=
      ∑ i, Ab i * LocalOkaRing.fromPolynomial ((F i) : (LocalOkaRing (Fin n))[X])
    let R' : Fin p → LocalOkaRing (Fin (n + 1)) := fun j ↦ LocalOkaRing.fromPolynomial (R j)
    let E' : Fin p → Fin p → LocalOkaRing (Fin (n + 1)) := fun j i ↦
      LocalOkaRing.fromPolynomial ((E j i) : (LocalOkaRing (Fin n))[X])
    let H : Fin p → LocalOkaRing (Fin (n + 1)) := R' + Pi.single zero S
    have hsingle_comm : ∀ (j i : Fin p) (v : (LocalOkaRing (Fin n))[X]_d),
        LocalOkaRing.fromPolynomial
          ((Pi.single (M := fun _ ↦ ↥((LocalOkaRing (Fin n))[X]_d)) j v i :
              (LocalOkaRing (Fin n))[X]_d) :
            (LocalOkaRing (Fin n))[X]) =
          Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) j
            (LocalOkaRing.fromPolynomial ((v : (LocalOkaRing (Fin n))[X]))) i := by
      intro j i v
      by_cases h : i = j
      · subst h
        rw [Pi.single_eq_same, Pi.single_eq_same]
      · rw [Pi.single_eq_of_ne h, Pi.single_eq_of_ne h, ZeroMemClass.coe_zero, map_zero]
    have hE'apply : ∀ j i, E' j i =
        -Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) zero
            (LocalOkaRing.fromPolynomial ((F j) : (LocalOkaRing (Fin n))[X])) i +
          Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) j
            (LocalOkaRing.fromPolynomial ((F zero) : (LocalOkaRing (Fin n))[X])) i := by
      intro j i
      simp only [E', E, Pi.add_apply, Pi.neg_apply, Submodule.coe_add, NegMemClass.coe_neg,
        map_add, map_neg]
      rw [hsingle_comm, hsingle_comm]
    -- decomposition of `G`
    have hG' : G = H + ∑ j, Ab j • E' j := by
      funext i
      simp only [Pi.add_apply, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, H, R']
      have hterm : ∀ j, Ab j * E' j i =
          -(Ab j * Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) zero
              (LocalOkaRing.fromPolynomial ((F j) : (LocalOkaRing (Fin n))[X])) i) +
            Ab j * Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) j
              (LocalOkaRing.fromPolynomial ((F zero) : (LocalOkaRing (Fin n))[X])) i := by
        intro j
        rw [hE'apply j i]
        ring
      have hEsum : ∑ j, Ab j * E' j i =
          -Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) zero S i +
            Ab i * LocalOkaRing.fromPolynomial ((F zero) : (LocalOkaRing (Fin n))[X]) := by
        rw [Finset.sum_congr rfl fun j _ ↦ hterm j, Finset.sum_add_distrib]
        congr 1
        · rw [Finset.sum_neg_distrib]
          congr 1
          by_cases h : i = zero
          · subst h
            simp only [Pi.single_eq_same, S]
          · rw [Pi.single_eq_of_ne h]
            refine Finset.sum_eq_zero fun j _ ↦ ?_
            rw [Pi.single_eq_of_ne h, mul_zero]
        · rw [Fintype.sum_eq_single i]
          · rw [Pi.single_eq_same]
          · intro x hx
            rw [Pi.single_eq_of_ne (Ne.symm hx), mul_zero]
      rw [hEsum, hAR'' i]
      ring
    -- the germ `↑u₀ * S` is the germ of the polynomial `P /ₘ W`
    have hsum0 : S * LocalOkaRing.fromPolynomial ((F zero) : (LocalOkaRing (Fin n))[X]) +
        ∑ i, LocalOkaRing.fromPolynomial (R i) *
          LocalOkaRing.fromPolynomial ((F i) : (LocalOkaRing (Fin n))[X]) = 0 := by
      rw [← hG]
      simp only [S, Finset.sum_mul]
      rw [← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl fun x _ ↦ ?_
      rw [hAR'' x]
      ring
    set P : (LocalOkaRing (Fin n))[X] :=
      -∑ i, R i * ((F i) : (LocalOkaRing (Fin n))[X]) with hPdef
    have hrel : LocalOkaRing.fromPolynomial P =
        ((u₀ : LocalOkaRing (Fin (n + 1))) * S) * LocalOkaRing.fromPolynomial W +
          LocalOkaRing.fromPolynomial 0 := by
      rw [map_zero, add_zero, hPdef, map_neg, map_sum]
      simp only [map_mul]
      linear_combination -hsum0 + S * hF0
    obtain ⟨hSeq, -⟩ := fromPolynomial_eq_divByMonic hW P (b := 0) (by
      rw [Polynomial.degree_zero]
      exact bot_lt_iff_ne_bot.mpr fun hc ↦ hWm.ne_zero (Polynomial.degree_eq_bot.mp hc)) hrel
    set qS : (LocalOkaRing (Fin n))[X] := P /ₘ W with hqSdef
    -- degree bounds
    have hRnd : ∀ i, R i ≠ 0 → (R i).natDegree < W.natDegree := fun i h0 ↦ by
      rw [Polynomial.natDegree_lt_iff_degree_lt h0]
      exact lt_of_lt_of_le (hAR i) Polynomial.degree_le_natDegree
    have hPnd : P.natDegree ≤ W.natDegree + d - 1 := by
      rw [hPdef, Polynomial.natDegree_neg]
      refine Polynomial.natDegree_sum_le_of_forall_le _ _ fun i _ ↦ ?_
      refine le_trans Polynomial.natDegree_mul_le ?_
      rcases eq_or_ne (R i) 0 with h0 | h0
      · rw [h0, Polynomial.natDegree_zero]
        have := hFnd i
        omega
      · have h1 := hRnd i h0
        have := hFnd i
        omega
    have hqSnd : qS.natDegree ≤ d - 1 := by
      rw [hqSdef, Polynomial.natDegree_divByMonic P hWm]
      omega
    have hURnd : ∀ i, (U * R i).natDegree ≤ d - 1 := fun i ↦ by
      rcases eq_or_ne (R i) 0 with h0 | h0
      · rw [h0, mul_zero, Polynomial.natDegree_zero]
        omega
      · refine le_trans Polynomial.natDegree_mul_le ?_
        have h1 := hRnd i h0
        have h2 := hFnd zero
        omega
    have hURmem : ∀ i, U * R i ∈ Polynomial.degreeLT (LocalOkaRing (Fin n)) d := fun i ↦ by
      rw [Polynomial.mem_degreeLT]
      refine lt_of_le_of_lt Polynomial.degree_le_natDegree ?_
      exact_mod_cast lt_of_le_of_lt (hURnd i) (by omega : d - 1 < d)
    have hqSmem : qS ∈ Polynomial.degreeLT (LocalOkaRing (Fin n)) d := by
      rw [Polynomial.mem_degreeLT]
      refine lt_of_le_of_lt Polynomial.degree_le_natDegree ?_
      exact_mod_cast lt_of_le_of_lt hqSnd (by omega : d - 1 < d)
    -- the polynomial vector realizing `↑u₀ • H`
    let Hp : Fin p → (LocalOkaRing (Fin n))[X]_d :=
      (fun i ↦ (⟨U * R i, hURmem i⟩ : (LocalOkaRing (Fin n))[X]_d)) +
        Pi.single zero ⟨qS, hqSmem⟩
    have hHpH : polyInclPi Hp = (↑u₀ : LocalOkaRing (Fin (n + 1))) • H := by
      funext i
      simp only [polyInclPi, LinearMap.coe_piMap, Pi.map_apply, Hp, Pi.add_apply,
        polyIncl_apply, map_add, H, R', Pi.smul_apply, smul_eq_mul]
      by_cases hi : i = zero
      · simp only [hi, Pi.single_eq_same]
        rw [map_mul, ← hu₀val, mul_add]
        congr 1
        exact hSeq.symm
      · rw [Pi.single_eq_of_ne hi, Pi.single_eq_of_ne hi]
        simp only [ZeroMemClass.coe_zero, map_zero, add_zero]
        rw [map_mul, ← hu₀val]
    -- `H` is a relation
    have hHrel : ∑ i, H i *
        LocalOkaRing.fromPolynomial ((F i) : (LocalOkaRing (Fin n))[X]) = 0 := by
      simp only [H, R', Pi.add_apply, add_mul]
      rw [Finset.sum_add_distrib]
      have hsingle : ∑ i, Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) zero S i *
          LocalOkaRing.fromPolynomial ((F i) : (LocalOkaRing (Fin n))[X]) =
          S * LocalOkaRing.fromPolynomial ((F zero) : (LocalOkaRing (Fin n))[X]) := by
        rw [Fintype.sum_eq_single zero]
        · rw [Pi.single_eq_same]
        · intro x hx
          rw [Pi.single_eq_of_ne hx, zero_mul]
      rw [hsingle]
      linear_combination hsum0
    have hHmem : H ∈ Submodule.span (LocalOkaRing (Fin (n + 1)))
        (Submodule.map polyInclPi (K_deg d fun j ↦ polyIncl (F j))).carrier := by
      have hu : H = (↑u₀⁻¹ : LocalOkaRing (Fin (n + 1))) •
          ((↑u₀ : LocalOkaRing (Fin (n + 1))) • H) := by
        rw [smul_smul, Units.inv_mul, one_smul]
      rw [hu]
      refine Submodule.smul_mem _ _ ?_
      refine Submodule.subset_span ?_
      simp only [Submodule.carrier_eq_coe, Submodule.map_coe, Set.mem_image, SetLike.mem_coe]
      refine ⟨Hp, ?_, hHpH⟩
      simp only [K_deg, LinearMap.mem_ker, LinearMap.coe_comp, LinearMap.coe_restrictScalars,
        Function.comp_apply, Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun,
        LinearEquiv.refl_apply, smul_eq_mul, polyIncl_apply]
      simp only [hHpH, Pi.smul_apply, smul_eq_mul]
      have hassoc : ∑ i, (u₀ : LocalOkaRing (Fin (n + 1))) * H i * LocalOkaRing.fromPolynomial
          ((F i) : (LocalOkaRing (Fin n))[X]) =
          (u₀ : LocalOkaRing (Fin (n + 1))) * ∑ i, H i *
            LocalOkaRing.fromPolynomial ((F i) : (LocalOkaRing (Fin n))[X]) := by
        rw [Finset.mul_sum]
        exact Finset.sum_congr rfl fun i _ ↦ mul_assoc _ _ _
      rw [hassoc, hHrel, mul_zero]
    -- the elementary relations lie in the span
    have hE' : ∀ j, E' j ∈ Submodule.span (LocalOkaRing (Fin (n + 1)))
        (Submodule.map polyInclPi (K_deg d fun j ↦ polyIncl (F j))).carrier := by
      intro j
      refine Submodule.subset_span ?_
      simp only [Submodule.carrier_eq_coe, Submodule.map_coe, Set.mem_image, SetLike.mem_coe]
      refine ⟨E j, ?_, ?_⟩
      · simp only [K_deg, LinearMap.mem_ker, LinearMap.coe_comp,
          LinearMap.coe_restrictScalars, Function.comp_apply,
          Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun, LinearEquiv.refl_apply,
          smul_eq_mul, polyIncl_apply, polyInclPi, LinearMap.coe_piMap, Pi.map_apply]
        have hpoly : ∑ x, ((E j x) : (LocalOkaRing (Fin n))[X]) *
            ((F x) : (LocalOkaRing (Fin n))[X]) = 0 := by
          have hres : ∑ x, ((E j x) : (LocalOkaRing (Fin n))[X]) *
              ((F x) : (LocalOkaRing (Fin n))[X]) =
              ∑ x ∈ ({zero, j} : Finset (Fin p)), ((E j x) : (LocalOkaRing (Fin n))[X]) *
                ((F x) : (LocalOkaRing (Fin n))[X]) := by
            symm
            apply Fintype.sum_subset
            intro i hi
            by_contra hc
            simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hc
            simp only [Pi.add_apply, Pi.neg_apply, Submodule.coe_add, NegMemClass.coe_neg,
              ne_eq, mul_eq_zero, not_or, E] at hi
            rw [Pi.single_eq_of_ne hc.2, Pi.single_eq_of_ne hc.1] at hi
            simp only [ZeroMemClass.coe_zero, neg_zero, add_zero, not_true_eq_false,
              false_and] at hi
          rw [hres]
          by_cases hj : j = zero
          · simp only [hj]
            have hE : E zero = (fun _ ↦ 0) := by
              simp only [neg_add_cancel, E]
              trivial
            rw [hE]
            simp only [Finset.mem_singleton, Finset.insert_eq_of_mem, ZeroMemClass.coe_zero,
              zero_mul, Finset.sum_const_zero]
          · rw [Finset.sum_pair (Ne.symm hj)]
            simp only [Pi.add_apply, Pi.neg_apply, Pi.single_eq_same, Submodule.coe_add,
              NegMemClass.coe_neg, E]
            rw [Pi.single_eq_of_ne hj]
            rw [Pi.single_eq_of_ne (Ne.symm hj)]
            simp only [ZeroMemClass.coe_zero, add_zero, neg_mul, neg_zero, zero_add,
              mul_comm, neg_add_cancel]
        have hpoly' := congrArg LocalOkaRing.fromPolynomial hpoly
        simp only [map_sum, map_mul, map_zero] at hpoly'
        exact hpoly'
      · funext i
        simp only [polyInclPi, LinearMap.coe_piMap, Pi.map_apply, polyIncl_apply, E']
    rw [hG']
    refine Submodule.add_mem _ hHmem ?_
    refine Submodule.sum_mem _ fun j _ ↦ ?_
    exact Submodule.smul_mem _ _ (hE' j)
  · exact oka_lemma_weierstrass_rhs_containedIn_lhs p d
      fun j ↦ ((F j) : (LocalOkaRing (Fin n))[X])

theorem oka_lemma_weierstrass_lhs_containedIn_rhs (p : ℕ) (d : ℕ) (m : ℕ)
    (hp : 0 < p)
    (hm : m ≥ 2 * d)
    (F : Fin p → (LocalOkaRing (Fin n))[X])
    (hF : ∀ j, (F j).degree < d)
    (hF' : ∀ j, (F j).Monic)
    (hF₁ : IsLocalWeierstrassPolynomial (Polynomial.map
      (Subring.subtype (localOkaSubring _).toSubring) (F ⟨0, hp⟩))) :
    letI F' (j : Fin p) : LocalOkaRing (Fin (n + 1)) :=
      LocalOkaRing.fromPolynomial (F j)
    LinearMap.ker (linOfFun F') ≤ KK_deg m F' := by
  let F' (j : Fin p) : LocalOkaRing (Fin (n + 1)) :=
      LocalOkaRing.fromPolynomial (F j)
  let zero : Fin p := ⟨0, hp⟩
  let Fd (i : Fin p) : (LocalOkaRing (Fin n))[X]_d := ⟨F i, by
    simpa [Polynomial.mem_degreeLT] using hF i⟩
  let E : Fin p → (Fin p → (LocalOkaRing (Fin n))[X]_d) :=
    fun j ↦ - Pi.single zero (Fd j) + Pi.single j (Fd zero)
  intro G hG
  rw [LinearMap.mem_ker] at hG
  simp only [Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun, LinearEquiv.refl_apply,
    smul_eq_mul] at hG
  choose A R hAR hAR' using fun (j : Fin p) ↦ localweierstrass_division (F zero) hF₁ (G j)
  let S := ∑ (i : Fin p), (A i) * (F' i)
  let R' := fun (j : Fin p) ↦ LocalOkaRing.fromPolynomial (R j)
  let E' := fun (j : Fin p) (i : Fin p) ↦
    LocalOkaRing.fromPolynomial (E j i).val
  let H := R' + Pi.single zero S
  have hG' : G = H + ∑ (j : Fin p), (A j) • (E' j) := by
    funext i
    simp only [Pi.add_apply, Finset.sum_apply,
      Pi.smul_apply, smul_eq_mul, H, hAR', R', Pi.add_apply]
    rw [add_comm (A i * (F' zero)) (R' i)]
    simp only [R', add_assoc]
    congr
    by_cases h : i = zero
    · simp only [h, Pi.single_eq_same, Pi.add_apply, Pi.neg_apply,
      Submodule.coe_add, NegMemClass.coe_neg, map_add, map_neg, S, E', E, Fd, F']
      simp_rw [mul_add]
      rw [Finset.sum_add_distrib]
      simp only [mul_neg, Finset.sum_neg_distrib, add_neg_cancel_left]
      rw [Fintype.sum_eq_single zero]
      · simp only [Pi.single_eq_same]
      · intro x hx
        rw [Pi.single_eq_of_ne (Ne.symm hx)]
        simp only [ZeroMemClass.coe_zero, map_zero, mul_zero]
    · simp only [ne_eq, h, not_false_eq_true, Pi.single_eq_of_ne, Pi.add_apply, Pi.neg_apply,
      Submodule.coe_add, NegMemClass.coe_neg, map_add, map_neg, ZeroMemClass.coe_zero, map_zero,
      neg_zero, zero_add, E', E]
      let ff' (x : Fin p) :=
        (A ↑x) * LocalOkaRing.fromPolynomial
          ↑(Pi.single (M := fun _ ↦ (LocalOkaRing (Fin n))[X]_d) x (Fd zero) i)
      have hh (x : Fin p) (hx : x ≠ i) : (ff' x) = 0 := by
        simp only [mul_eq_zero, ff']
        right
        rw [Pi.single_eq_of_ne _ _]
        · simp only [ZeroMemClass.coe_zero, map_zero]
        · exact hx.symm
      rw [Fintype.sum_eq_single i]
      · simp only [Pi.single_eq_same, F', Fd]
      · intro x hx
        rw [Pi.single_eq_of_ne (Ne.symm hx)]
        simp only [ZeroMemClass.coe_zero, map_zero, mul_zero]
  have hH : (H ∈ KK_deg m F') := by
    classical
    have hd1 : 0 < d := by
      have h0 : (0 : WithBot ℕ) ≤ (F zero).degree :=
        Polynomial.zero_le_degree_iff.mpr (hF' zero).ne_zero
      have h1 : (0 : WithBot ℕ) < d := lt_of_le_of_lt h0 (hF zero)
      exact_mod_cast h1
    -- the sum of the relations, in terms of the germs of the polynomials
    have hsum0 : S * LocalOkaRing.fromPolynomial (F zero) +
        ∑ i, LocalOkaRing.fromPolynomial (R i) * LocalOkaRing.fromPolynomial (F i) = 0 := by
      rw [← hG]
      simp only [S, F', Finset.sum_mul]
      rw [← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl fun x _ ↦ ?_
      rw [hAR' x]
      ring
    -- hence `S * F' zero` is the germ of the polynomial `P`
    set P : (LocalOkaRing (Fin n))[X] := -∑ i, R i * F i with hPdef
    have hrel : LocalOkaRing.fromPolynomial P =
        S * LocalOkaRing.fromPolynomial (F zero) + LocalOkaRing.fromPolynomial 0 := by
      rw [map_zero, add_zero, hPdef, map_neg, map_sum]
      simp only [map_mul]
      linear_combination -hsum0
    -- by uniqueness of division, `S` is the germ of the polynomial `P /ₘ F zero`
    obtain ⟨hSeq, -⟩ := fromPolynomial_eq_divByMonic hF₁ P (b := 0) (by
      rw [Polynomial.degree_zero]
      exact bot_lt_iff_ne_bot.mpr fun hc ↦ (hF' zero).ne_zero
        (Polynomial.degree_eq_bot.mp hc)) hrel
    set qS : (LocalOkaRing (Fin n))[X] := P /ₘ F zero with hqSdef
    -- degree bounds
    have hFzero_nd : (F zero).natDegree < d :=
      Polynomial.natDegree_lt_of_mem_degreeLT hd1 (Polynomial.mem_degreeLT.mpr (hF zero))
    have hPnd : P.natDegree ≤ 2 * d - 2 := by
      rw [hPdef, Polynomial.natDegree_neg]
      refine Polynomial.natDegree_sum_le_of_forall_le _ _ fun i _ ↦ ?_
      refine le_trans Polynomial.natDegree_mul_le ?_
      have hFi : (F i).natDegree < d :=
        Polynomial.natDegree_lt_of_mem_degreeLT hd1 (Polynomial.mem_degreeLT.mpr (hF i))
      rcases eq_or_ne (R i) 0 with h0 | h0
      · rw [h0, Polynomial.natDegree_zero]
        omega
      · have hRi : (R i).natDegree < (F zero).natDegree := by
          rw [Polynomial.natDegree_lt_iff_degree_lt h0]
          exact lt_of_lt_of_le (hAR i) Polynomial.degree_le_natDegree
        omega
    have hqSdeg : qS.degree < (m : WithBot ℕ) := by
      have h2 : qS.natDegree < m := by
        rw [hqSdef, Polynomial.natDegree_divByMonic P (hF' zero)]
        omega
      exact lt_of_le_of_lt Polynomial.degree_le_natDegree (by exact_mod_cast h2)
    -- assemble the polynomial vector realizing `H`
    have hRmem : ∀ i, R i ∈ Polynomial.degreeLT (LocalOkaRing (Fin n)) m := fun i ↦ by
      rw [Polynomial.mem_degreeLT]
      refine lt_of_lt_of_le (lt_of_lt_of_le (hAR i) (le_of_lt (hF zero))) ?_
      exact_mod_cast (by omega : d ≤ m)
    have hqSmem : qS ∈ Polynomial.degreeLT (LocalOkaRing (Fin n)) m :=
      Polynomial.mem_degreeLT.mpr hqSdeg
    let Hp : Fin p → (LocalOkaRing (Fin n))[X]_m :=
      (fun i ↦ (⟨R i, hRmem i⟩ : (LocalOkaRing (Fin n))[X]_m)) +
        Pi.single zero ⟨qS, hqSmem⟩
    have hHpH : polyInclPi Hp = H := by
      funext i
      simp only [polyInclPi, LinearMap.coe_piMap, Pi.map_apply, Hp, Pi.add_apply,
        polyIncl_apply, map_add, H, R']
      by_cases hi : i = zero
      · simp only [hi, Pi.single_eq_same]
        rw [hSeq]
      · rw [Pi.single_eq_of_ne hi, Pi.single_eq_of_ne hi]
        simp
    -- the vector is a relation
    have hHrel : ∑ i, H i * F' i = 0 := by
      simp only [H, R', Pi.add_apply, add_mul]
      rw [Finset.sum_add_distrib]
      have hsingle : ∑ i, Pi.single (M := fun _ ↦ LocalOkaRing (Fin (n + 1))) zero S i * F' i =
          S * F' zero := by
        rw [Fintype.sum_eq_single zero]
        · rw [Pi.single_eq_same]
        · intro x hx
          rw [Pi.single_eq_of_ne hx, zero_mul]
      rw [hsingle]
      simp only [F']
      linear_combination hsum0
    simp only [KK_deg]
    refine Submodule.subset_span (R := LocalOkaRing (Fin (n + 1))) ?_
    simp only [Submodule.carrier_eq_coe, Submodule.map_coe, Set.mem_image, SetLike.mem_coe]
    refine ⟨Hp, ?_, hHpH⟩
    simp only [K_deg, LinearMap.mem_ker, LinearMap.coe_comp, LinearMap.coe_restrictScalars,
      Function.comp_apply, Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun,
      LinearEquiv.refl_apply, smul_eq_mul]
    simp only [hHpH]
    exact hHrel
  have hE' : ∀ (j : Fin p), (E' j ∈ KK_deg m F') := by
    intro j
    simp only [KK_deg, E']
    refine Submodule.subset_span (R := LocalOkaRing (Fin (n + 1))) ?_
    simp only [Submodule.carrier_eq_coe, Submodule.map_coe, Set.mem_image, SetLike.mem_coe]
    let Ej : Fin p → (LocalOkaRing (Fin n))[X]_m :=
      fun i ↦
        ⟨(E j i: (LocalOkaRing (Fin n))[X]),
        Polynomial.degreeLT_mono (R := LocalOkaRing (Fin n)) (by omega) (E j i).property⟩
    use Ej
    constructor
    · simp only [K_deg, LinearMap.mem_ker, LinearMap.coe_comp, LinearMap.coe_restrictScalars,
      Function.comp_apply, Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun,
      LinearEquiv.refl_apply, smul_eq_mul, polyInclPi, Ej]
      simp only [LinearMap.coe_piMap, Pi.map_apply]
      simp only [polyIncl, LocalOkaRing.fromPolynomialAlg, AlgHom.toRingHom_eq_coe,
        LinearMap.coe_comp, LinearMap.coe_coe, AlgHom.coe_mk, RingHom.coe_coe,
        Submodule.coe_subtype, Function.comp_apply, F']
      have hpoly : ∑ x, ↑(E j x) * (F x) = 0 := by
        simp only [E]
        have hres : ∑ x, ↑(E j x) * (F x) =
            ∑ x ∈ {zero, j}, ↑(E j x) * (F x) := by
          symm
          apply Fintype.sum_subset
          intro i hi
          by_contra hc
          simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hc
          simp only [Pi.add_apply, Pi.neg_apply, Submodule.coe_add, NegMemClass.coe_neg, ne_eq,
            mul_eq_zero, not_or, E] at hi
          rw [Pi.single_eq_of_ne hc.2, Pi.single_eq_of_ne hc.1] at hi
          simp only [ZeroMemClass.coe_zero, neg_zero, add_zero, not_true_eq_false, false_and] at hi
        rw [hres]
        by_cases hj : j = zero
        · simp only [hj]
          have hE : E zero = (fun _ ↦ 0) := by
            simp only [neg_add_cancel, E]
            trivial
          rw [hE]
          simp only [Finset.mem_singleton, Finset.insert_eq_of_mem, ZeroMemClass.coe_zero, zero_mul,
            Finset.sum_const_zero]
        · rw [Finset.sum_pair (Ne.symm hj)]
          simp only [Pi.add_apply, Pi.neg_apply, Pi.single_eq_same, Submodule.coe_add,
            NegMemClass.coe_neg, E, Fd]
          rw [Pi.single_eq_of_ne hj]
          rw [Pi.single_eq_of_ne (Ne.symm hj)]
          simp only [ZeroMemClass.coe_zero, add_zero, neg_mul, neg_zero, zero_add, mul_comm,
            neg_add_cancel]
      have hpoly' := congrArg LocalOkaRing.fromPolynomial hpoly
      simp only [map_sum, map_mul, map_zero] at hpoly'
      exact hpoly'
    · simp only [polyInclPi, LinearMap.coe_piMap]
      funext i
      simp only [polyIncl, LinearMap.coe_comp, LinearMap.coe_coe, Submodule.coe_subtype,
        Pi.map_apply, Function.comp_apply]
      rfl
  rw [hG']
  refine Submodule.add_mem (KK_deg m F') hH ?_
  apply Submodule.sum_mem (KK_deg m F')
  intro i hi
  exact Submodule.smul_mem _ _ (hE' i)



theorem oka_lemma_weierstrass (p : ℕ) (d : ℕ) (m : ℕ)
    (hp : 0 < p)
    (hm : m ≥ 2 * d)
    (F : Fin p → (LocalOkaRing (Fin n))[X])
    (hF : ∀ j, (F j).degree < d)
    (hF' : ∀ j, (F j).Monic)
    (hF₁ : IsLocalWeierstrassPolynomial (Polynomial.map
      (Subring.subtype (localOkaSubring _).toSubring) (F ⟨0, hp⟩))) :
    letI F' (j : Fin p) : LocalOkaRing (Fin (n + 1)) :=
      LocalOkaRing.fromPolynomial (F j)
    LinearMap.ker (linOfFun F') = KK_deg m F' := by
  apply le_antisymm
  · exact oka_lemma_weierstrass_lhs_containedIn_rhs p d m hp hm F hF hF' hF₁
  · exact oka_lemma_weierstrass_rhs_containedIn_lhs _ _ _
