/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.RingTheory.KrullDimension.Regular
import Mathlib.RingTheory.RegularLocalRing.Defs
import Oka.MaximalIdeal
import Oka.Noetherian
import Oka.UFD

/-!
# The germ ring is a regular local ring of dimension `n`

The ring `LocalOkaRing (Fin n)` of germs at the origin of holomorphic functions in `n` variables
has Krull dimension `n` and is a regular local ring: its maximal ideal is generated by the `n`
coordinates, and `n` is exactly the dimension, so no smaller generating set exists.

## How the dimension is computed

Not by exhibiting a chain of primes. Mathlib computes the dimension of a Noetherian local ring by
cutting with one nonzerodivisor at a time
(`ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`, an
*equality*), so all that is needed is an induction step: quotienting the germ ring in `n + 1`
variables by the last coordinate returns the germ ring in `n` variables,

  `LocalOkaRing (Fin n) ≃+* LocalOkaRing (Fin (n + 1)) ⧸ (X_n)`.

That isomorphism is `LocalOkaRing.quotientLastVarEquiv`, and it is **Weierstrass division in
disguise**. The coordinate `X_n` is a local Weierstrass polynomial of degree one
(`LocalOkaRing.isLocalWeierstrassPolynomial_X`), so `Oka/Weierstrass.lean`'s division theorem
says every germ `f` in `n + 1` variables is `a · X_n + c` with `c` a germ in the first `n`
variables (`LocalOkaRing.exists_eq_mul_lastVar_add_incl`) — surjectivity — and the uniqueness
half of the division theorem, `localweierstrass_division_unique`, says that a `c` lying in
`(X_n)` is zero (`LocalOkaRing.incl_eq_zero_of_mem_span_lastVar`) — injectivity. The convergence
bookkeeping that "setting the last variable to zero" would otherwise require is entirely absorbed
by the division theorem, which already produces convergent quotient and remainder. (Mathlib does
have the purely algebraic projection, `MvPowerSeries.killCompl`, and it would give the
isomorphism just as well — but only after one proves that it preserves local convergence, which
is exactly the work the division theorem has already done.)

The base case is `LocalOkaRing (Fin 0)`, whose maximal ideal is generated by the empty family and
so is a field.

## Main results

- `LocalOkaRing.quotientLastVarEquiv`: `LocalOkaRing (Fin (n + 1)) ⧸ (X_n) ≃+* LocalOkaRing
  (Fin n)`, by Weierstrass division by the last coordinate.
- `LocalOkaRing.quotientDegreeOneEquiv`: **the same for an arbitrary local Weierstrass polynomial
  of degree one**, and not only for the coordinate `X_n`. Its two halves are
  `LocalOkaRing.exists_eq_mul_fromPolynomial_add_incl` and
  `LocalOkaRing.incl_eq_zero_of_mem_span_fromPolynomial`.
- `LocalOkaRing.quotientGraphEquiv`: **the germ ring on the graph of an analytic function is the
  germ ring of its domain**, which is the previous statement at `X_n - c`;
  `LocalOkaRing.isLocalWeierstrassPolynomial_X_sub_C` is the hypothesis it discharges.
- `LocalOkaRing.span_fromPolynomial_X_sub_C_ne_span_lastVar`: **`(X_n - c)` and `(X_n)` are
  different ideals for `c ≠ 0`**, which is what says the previous statement is not the coordinate
  case in disguise. The two equivalences have the same source, so the ideals are the only place
  the difference can live.
- `LocalOkaRing.exists_span_eq_span_X_sub_C`: **a germ whose restriction to the last axis has a
  simple zero generates the same ideal as some `X_n - c`**, so it is a graph up to the ideal even
  when it is not one on the nose. `LocalOkaRing.order_partialEval_eq_natDegree` and
  `LocalOkaRing.eq_X_sub_C_of_natDegree_eq_one` are its two halves.
- `LocalOkaRing.quotientSimpleZeroEquiv`: **the germ ring of a hypersurface with a simple zero
  along the last axis is the germ ring one dimension down** — the previous two together, with no
  graph left in the statement.
- `LocalOkaRing.ringKrullDim_eq`: **`ringKrullDim (LocalOkaRing (Fin n)) = n`**, and
  `LocalOkaRing.ringKrullDim_eq_natCard` for an arbitrary finite set of variables.
- `LocalOkaRing.instIsRegularLocalRing`: **the germ ring is a regular local ring.**
- `LocalOkaRing.spanFinrank_maximalIdeal_le` and `LocalOkaRing.spanFinrank_maximalIdeal_eq`: the
  maximal ideal is generated by `n` elements and by no fewer.

## References

- [Hans Grauert and Reinhold Remmert, *Analytische Stellenalgebren*][grauert-remmert1971], §I
-/

open IsLocalRing Polynomial

namespace LocalOkaRing

variable {n : ℕ}

/-! ### Quotienting by the last coordinate -/

/-- The last coordinate, as an element of the polynomial ring in which Weierstrass division takes
place, is a local Weierstrass polynomial: it is monic of degree one, and there is no coefficient
below the leading one to vanish at the origin. -/
theorem isLocalWeierstrassPolynomial_X :
    IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring)
        (X : (LocalOkaRing (Fin n))[X])) where
  monic := by rw [Polynomial.map_X]; exact monic_X
  apply_zero i hi := by
    rw [Polynomial.map_X] at hi ⊢
    rw [degree_X, Nat.cast_lt_one] at hi
    rw [hi, coeff_X_zero, map_zero]

/-- The last coordinate is the coordinate at `Fin.last n`. -/
theorem lastVar_eq_coord :
    (lastVar : LocalOkaRing (Fin (n + 1))) = coord (Fin.last n) :=
  Subtype.ext rfl

/-- **Weierstrass division by the last coordinate.** Every germ in `n + 1` variables is a
multiple of the last coordinate plus a germ in the first `n` variables.

This is `localweierstrass_division` for the Weierstrass polynomial `X`, whose remainder has
degree `< 1` and is therefore a constant. -/
theorem exists_eq_mul_lastVar_add_incl (f : LocalOkaRing (Fin (n + 1))) :
    ∃ (a : LocalOkaRing (Fin (n + 1))) (c : LocalOkaRing (Fin n)),
      f = a * lastVar + incl c := by
  obtain ⟨a, b, hb, hf⟩ := localweierstrass_division X isLocalWeierstrassPolynomial_X f
  refine ⟨a, b.coeff 0, ?_⟩
  rw [degree_X] at hb
  have hb0 : b = C (b.coeff 0) :=
    eq_C_of_degree_le_zero (Nat.WithBot.lt_one_iff_le_zero.mp hb)
  rw [hf, fromPolynomial_X]
  conv_lhs => rw [hb0]
  rw [fromPolynomial_C]

/-- A germ in the first `n` variables which is divisible by the last coordinate is zero.

This is the *uniqueness* half of Weierstrass division: `c` and `a · X_n` are two divisions of the
same germ by `X`, one with quotient `0` and remainder `C c`, the other with quotient `a` and
remainder `0`. -/
theorem incl_eq_zero_of_mem_span_lastVar {c : LocalOkaRing (Fin n)}
    (h : incl c ∈ Ideal.span {(lastVar : LocalOkaRing (Fin (n + 1)))}) : c = 0 := by
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp h
  have key := localweierstrass_division_unique (q := (X : (LocalOkaRing (Fin n))[X]))
    isLocalWeierstrassPolynomial_X (a := a) (a' := 0)
    (b := (0 : (LocalOkaRing (Fin n))[X])) (b' := C c)
    (by simp [degree_X]) (by rw [degree_X]; exact degree_C_le.trans_lt (by norm_num))
    (by
      rw [fromPolynomial_X, fromPolynomial_C, map_zero]
      simpa using ha)
  simpa using key.2.symm

/-- **Quotienting the germ ring in `n + 1` variables by the last coordinate returns the germ ring
in `n` variables.** Surjectivity is Weierstrass division by `X`, injectivity is its uniqueness
half. -/
noncomputable def quotientLastVarEquiv : LocalOkaRing (Fin n) ≃+*
    (LocalOkaRing (Fin (n + 1)) ⧸ Ideal.span {(lastVar : LocalOkaRing (Fin (n + 1)))}) :=
  RingEquiv.ofBijective
    ((Ideal.Quotient.mk _).comp (incl : LocalOkaRing (Fin n) →ₐ[ℂ] _).toRingHom)
    ⟨(injective_iff_map_eq_zero _).2 fun _ hc ↦
        incl_eq_zero_of_mem_span_lastVar (Ideal.Quotient.eq_zero_iff_mem.mp hc),
      by
        intro x
        obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective x
        obtain ⟨a, c, rfl⟩ := exists_eq_mul_lastVar_add_incl f
        refine ⟨c, ?_⟩
        simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
        rw [eq_comm, Ideal.Quotient.mk_eq_mk_iff_sub_mem]
        simpa using Ideal.mul_mem_left _ a (Ideal.mem_span_singleton_self _)⟩

/-! ### Quotienting by a degree-one Weierstrass polynomial

`LocalOkaRing.quotientLastVarEquiv` above is stated for the coordinate `X_n`, which is what the
Krull-dimension induction needs. **The same argument works for any local Weierstrass polynomial of
degree one**, and nothing in the proof used `X` beyond its degree: `localweierstrass_division` is
already stated for a general Weierstrass polynomial `q`, and at `q.degree = 1` its remainder has
degree `< 1` and is therefore a constant — which is the whole of what makes the quotient the germ
ring one variable down.

**Why the generality is worth having.** A degree-one local Weierstrass polynomial in `X_n` is
`X_n - c` for a germ `c` in the first `n` variables, so the statement says that the germ ring on
the *graph* of an analytic function is the germ ring of its domain. That is the algebraic content
of *a map with non-vanishing derivative in the last variable is a local isomorphism on stalks*,
which is the shape a standard étale algebra `A[X] ⧸ (f)` presents when `f'` is invertible; see
`Mathlib/RingTheory/Etale/StandardEtale.lean` for that notion.

**Producing the `c` from a general `f` is the section below**, and two things about it are worth
saying here because the obvious statement of them is wrong. The hypothesis one expects — that the
last partial derivative is a unit — **is not expressible on `LocalOkaRing`, which carries no
partial-derivative operator**; the workable form is that the restriction to the last axis has a
simple zero, which is what `localweierstrass_preparation` computes on its own second line. And
the route is **three steps and not two**: preparation gives `f = fromPolynomial g * u` with `u` a
unit but **does not report `g.degree`**, so the degree has to be recovered from the conclusion
before a unit factor not changing the ideal can finish it.

**What is deliberately not claimed.** Nothing is said about analytic *spaces*: the bridge from a
stalk of the structure sheaf of `ℂ^ι` to `LocalOkaRing` is `okaStalkEquiv`
(`Oka/StalkEquiv.lean`, root namespace), and the bridge
from a cut-out subspace's stalk to a quotient of the ambient one is
`ComplexAnalytic.IsCutOutBy`'s `surjective_stalkMap` and `ker_stalkMap` fields. Both exist;
neither is used here. -/

/-- **Division by a degree-one local Weierstrass polynomial**: every germ in `n + 1` variables is
a multiple of `q` plus a germ in the first `n`.

`localweierstrass_division` at `q`, whose remainder has degree `< q.degree = 1` and is therefore a
constant. `LocalOkaRing.exists_eq_mul_lastVar_add_incl` is this at `q = X`, where
`LocalOkaRing.fromPolynomial_X` identifies `fromPolynomial X` with `LocalOkaRing.lastVar`. -/
theorem exists_eq_mul_fromPolynomial_add_incl {q : (LocalOkaRing (Fin n))[X]}
    (hq : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring) q))
    (hdeg : q.degree = 1) (f : LocalOkaRing (Fin (n + 1))) :
    ∃ (a : LocalOkaRing (Fin (n + 1))) (c : LocalOkaRing (Fin n)),
      f = a * fromPolynomial q + incl c := by
  obtain ⟨a, b, hb, hf⟩ := localweierstrass_division q hq f
  refine ⟨a, b.coeff 0, ?_⟩
  rw [hdeg] at hb
  have hb0 : b = C (b.coeff 0) :=
    eq_C_of_degree_le_zero (Nat.WithBot.lt_one_iff_le_zero.mp hb)
  rw [hf]
  conv_lhs => rw [hb0]
  rw [fromPolynomial_C]

/-- **A germ in the first `n` variables which is divisible by a degree-one local Weierstrass
polynomial is zero.**

The uniqueness half of Weierstrass division, exactly as in
`LocalOkaRing.incl_eq_zero_of_mem_span_lastVar`: `incl c` has two divisions by `q`, one with
quotient `a` and remainder `0`, one with quotient `0` and remainder `C c`, and both remainders
have degree `< 1`. -/
theorem incl_eq_zero_of_mem_span_fromPolynomial {q : (LocalOkaRing (Fin n))[X]}
    (hq : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring) q))
    (hdeg : q.degree = 1) {c : LocalOkaRing (Fin n)}
    (h : incl c ∈ Ideal.span {fromPolynomial q}) : c = 0 := by
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp h
  have key := localweierstrass_division_unique (q := q) hq (a := a) (a' := 0)
    (b := (0 : (LocalOkaRing (Fin n))[X])) (b' := C c)
    (by simp [hdeg])
    (by rw [hdeg]; exact degree_C_le.trans_lt (by norm_num))
    (by
      rw [fromPolynomial_C, map_zero]
      simpa using ha)
  simpa using key.2.symm

/-- **Quotienting the germ ring in `n + 1` variables by a degree-one local Weierstrass polynomial
returns the germ ring in `n` variables.**

`LocalOkaRing.quotientLastVarEquiv` is this at `q = X`. Surjectivity is
`LocalOkaRing.exists_eq_mul_fromPolynomial_add_incl` and injectivity is
`LocalOkaRing.incl_eq_zero_of_mem_span_fromPolynomial`; the map itself is `LocalOkaRing.incl`
followed by the quotient, so it is the inclusion of the germs that do not involve the last
variable, and the statement is that *every* class has exactly one such representative. -/
noncomputable def quotientDegreeOneEquiv {q : (LocalOkaRing (Fin n))[X]}
    (hq : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring) q))
    (hdeg : q.degree = 1) :
    LocalOkaRing (Fin n) ≃+*
      (LocalOkaRing (Fin (n + 1)) ⧸ Ideal.span {fromPolynomial q}) :=
  RingEquiv.ofBijective
    ((Ideal.Quotient.mk _).comp (incl : LocalOkaRing (Fin n) →ₐ[ℂ] _).toRingHom)
    ⟨(injective_iff_map_eq_zero _).2 fun _ hc ↦
        incl_eq_zero_of_mem_span_fromPolynomial hq hdeg (Ideal.Quotient.eq_zero_iff_mem.mp hc),
      by
        intro x
        obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective x
        obtain ⟨a, c, rfl⟩ := exists_eq_mul_fromPolynomial_add_incl hq hdeg f
        refine ⟨c, ?_⟩
        simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
        rw [eq_comm, Ideal.Quotient.mk_eq_mk_iff_sub_mem]
        simpa using Ideal.mul_mem_left _ a (Ideal.mem_span_singleton_self _)⟩

/-- **`X_n - c` is a local Weierstrass polynomial of degree one**, for any germ `c` in the first
`n` variables vanishing at the origin.

Monicity is `Polynomial.monic_X_sub_C`; the one coefficient below the leading one is `-c`, and it
vanishes at the origin exactly when `c` does — `LocalOkaRing.mem_maximalIdeal_iff`, which is where
the hypothesis is used and the only place it is.

This is what makes `LocalOkaRing.quotientDegreeOneEquiv` say something the coordinate case does
not: `X_n - c` cuts out the **graph** of `c`, and `X_n` is its special case at `c = 0`. -/
theorem isLocalWeierstrassPolynomial_X_sub_C {c : LocalOkaRing (Fin n)}
    (hc : c ∈ IsLocalRing.maximalIdeal (LocalOkaRing (Fin n))) :
    IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring)
        (X - C c : (LocalOkaRing (Fin n))[X])) where
  monic := by
    rw [Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C]
    exact monic_X_sub_C _
  apply_zero i hi := by
    rw [Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C] at hi ⊢
    rw [degree_X_sub_C, Nat.cast_lt_one] at hi
    subst hi
    rw [coeff_sub, coeff_X_zero, coeff_C_zero, zero_sub, map_neg, neg_eq_zero]
    exact LocalOkaRing.mem_maximalIdeal_iff.mp hc

/-- **The germ ring on the graph of an analytic function is the germ ring of its domain.**

`LocalOkaRing.quotientDegreeOneEquiv` at `X_n - c`, which
`LocalOkaRing.isLocalWeierstrassPolynomial_X_sub_C` supplies. At `c = 0` it is
`LocalOkaRing.quotientLastVarEquiv` up to the identification of `fromPolynomial X` with
`LocalOkaRing.lastVar`.

**This is the algebraic half of *a hypersurface with non-vanishing derivative in the last variable
is locally a graph, and its germ ring is one dimension down*.** What it does not do is produce the
`c`; `LocalOkaRing.exists_span_eq_span_X_sub_C` below does, from a germ whose restriction to the
last axis has a simple zero, and `LocalOkaRing.quotientSimpleZeroEquiv` is the two composed. -/
noncomputable def quotientGraphEquiv {c : LocalOkaRing (Fin n)}
    (hc : c ∈ IsLocalRing.maximalIdeal (LocalOkaRing (Fin n))) :
    LocalOkaRing (Fin n) ≃+*
      (LocalOkaRing (Fin (n + 1)) ⧸ Ideal.span {fromPolynomial (X - C c)}) :=
  quotientDegreeOneEquiv (isLocalWeierstrassPolynomial_X_sub_C hc) (degree_X_sub_C c)

/-- **The graph of a nonzero germ is not the last coordinate**, as an ideal: for `c ≠ 0` the
principal ideals `(X_n - c)` and `(X_n)` are different.

This is what makes `LocalOkaRing.quotientGraphEquiv` a generalisation of
`LocalOkaRing.quotientLastVarEquiv` rather than a respelling of it. The two equivalences have the
*same source*, so nothing about them separates the two statements; what separates them is that
their targets are quotients by different ideals, and that is this.

**A statement about `c` alone does not get there.** `c ≠ 0` says the two *polynomials* differ, and
`LocalOkaRing.fromPolynomial_injective` upgrades that to the two germs differing, but two distinct
elements can perfectly well generate the same principal ideal — they need only differ by a unit.
The step that is actually needed is the uniqueness half of Weierstrass division, in the form
already stated as `LocalOkaRing.incl_eq_zero_of_mem_span_lastVar`: if the ideals agreed then
`incl c = X_n - (X_n - incl c)` would lie in `(X_n)`, and a germ in the first `n` variables lying
in `(X_n)` is zero. -/
theorem span_fromPolynomial_X_sub_C_ne_span_lastVar {c : LocalOkaRing (Fin n)} (hc : c ≠ 0) :
    Ideal.span {fromPolynomial (X - C c)} ≠
      Ideal.span {(lastVar : LocalOkaRing (Fin (n + 1)))} := by
  intro h
  have hmem : fromPolynomial (X - C c) ∈
      Ideal.span {(lastVar : LocalOkaRing (Fin (n + 1)))} := by
    rw [← h]
    exact Ideal.mem_span_singleton_self _
  rw [map_sub, fromPolynomial_X, fromPolynomial_C] at hmem
  exact hc (incl_eq_zero_of_mem_span_lastVar
    (by simpa using Ideal.sub_mem _ (Ideal.mem_span_singleton_self _) hmem))

/-! ### From a simple zero along the last axis to a degree-one polynomial

The section above quotients by `X_n - c`; this one produces the `c`. A germ `f` in `n + 1`
variables whose restriction to the last axis has a **simple zero** generates the same ideal as
some `X_n - c`, so `LocalOkaRing.quotientGraphEquiv` applies to it and
`LocalOkaRing.quotientSimpleZeroEquiv` is the composite: **the germ ring of a hypersurface with a
simple zero along the last axis is the germ ring one dimension down**, with no graph left in the
statement.

**Why the hypothesis is stated with `PowerSeries.order` and not with a derivative.** The
condition one expects is that `∂f/∂X_n` is a unit at the origin. That is not expressible here:
this repository has no partial-derivative operator on `LocalOkaRing`, and the one declaration
under `Oka/` that computes a partial derivative,
`MvPowerSeries.LocallyConvergent.fderiv_eval_zero`, is about the derivative of the *sum* of a
convergent series. `PowerSeries.order (MvPowerSeries.partialEval (Fin.last n) f) = 1` is the same
condition for a germ vanishing at the origin, and it costs nothing because it is what
`localweierstrass_preparation` already computes internally as its order of generality. Bridging
the two is a separate piece of work and nothing here attempts it.

**Preparation does not report the degree, and that is the only real content below.**
`localweierstrass_preparation` concludes `f = fromPolynomial g * u` with `u` a unit and `g` a
local Weierstrass polynomial, and says nothing about `g.degree`. So the degree has to be recovered
from the conclusion rather than read off it, which is
`LocalOkaRing.order_partialEval_eq_natDegree`: `MvPowerSeries.partialEval` is an `AlgHom`, so it
splits the product; the unit contributes order `0` because a unit has nonzero constant
coefficient; and the polynomial factor contributes `X ^ g.natDegree` by
`LocalOkaRing.map_constantCoeff_eq_X_pow`. Only then does *a unit factor does not change the
ideal* finish it. -/

/-- **A local Weierstrass polynomial of degree one is `X - C c`**, for a germ `c` in the first `n`
variables vanishing at the origin.

The converse of `LocalOkaRing.isLocalWeierstrassPolynomial_X_sub_C`. Monicity pins every
coefficient above the constant one, and the Weierstrass condition puts the constant one in the
maximal ideal. -/
theorem eq_X_sub_C_of_natDegree_eq_one {g : (LocalOkaRing (Fin n))[X]}
    (hg : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring) g))
    (hdeg : g.natDegree = 1) :
    ∃ c : LocalOkaRing (Fin n), c ∈ IsLocalRing.maximalIdeal (LocalOkaRing (Fin n)) ∧
      g = X - C c := by
  have hmonic : g.Monic := monic_of_isLocalWeierstrass hg
  refine ⟨-g.coeff 0, ?_, ?_⟩
  · rw [mem_maximalIdeal_iff]
    have hi : (0 : WithBot ℕ) <
        (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring) g).degree := by
      rw [Polynomial.degree_map_eq_of_injective Subtype.val_injective,
        Polynomial.degree_eq_natDegree hmonic.ne_zero, hdeg]
      exact_mod_cast Nat.zero_lt_one
    have h0 := hg.apply_zero 0 hi
    rw [Polynomial.coeff_map] at h0
    rw [map_neg, constantCoeff_apply]
    exact neg_eq_zero.mpr h0
  · rw [sub_eq_add_neg, map_neg, neg_neg]
    conv_lhs => rw [hmonic.as_sum]
    rw [hdeg]
    simp

/-- **The order of the restriction to the last axis is the degree of the Weierstrass polynomial.**

This is what recovers the degree that `localweierstrass_preparation` does not report.
`MvPowerSeries.partialEval` is an `AlgHom`, so `PowerSeries.order_mul` splits `f = fromPolynomial
g * u`; `partialEval_coe_fromPolynomial` (`Oka/Weierstrass.lean`, root namespace) and
`LocalOkaRing.map_constantCoeff_eq_X_pow` (`Oka/UFD.lean`) turn the first factor into
`X ^ g.natDegree`; and the unit contributes order `0` because `LocalOkaRing.isUnit_iff` says its
constant coefficient is nonzero. -/
theorem order_partialEval_eq_natDegree {f u : LocalOkaRing (Fin (n + 1))}
    {g : (LocalOkaRing (Fin n))[X]} (hu : IsUnit u)
    (hg : IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring) g))
    (hf : f = fromPolynomial g * u) :
    PowerSeries.order (MvPowerSeries.partialEval (Fin.last n)
      (f : MvPowerSeries (Fin (n + 1)) ℂ)) = g.natDegree := by
  have hcoe : (f : MvPowerSeries (Fin (n + 1)) ℂ)
      = ((fromPolynomial g : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ) *
        ((u : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ) := by
    rw [hf]; rfl
  rw [hcoe, map_mul, PowerSeries.order_mul, partialEval_coe_fromPolynomial,
    map_constantCoeff_eq_X_pow hg]
  have h1 : ((X ^ g.natDegree : ℂ[X]) : PowerSeries ℂ)
      = (PowerSeries.X : PowerSeries ℂ) ^ g.natDegree := by
    push_cast
    rfl
  rw [h1, PowerSeries.order_X_pow]
  have h2 : PowerSeries.order (MvPowerSeries.partialEval (Fin.last n)
      ((u : LocalOkaRing (Fin (n + 1))) : MvPowerSeries (Fin (n + 1)) ℂ)) = 0 := by
    by_contra hne
    have hcc := isUnit_iff.mp hu
    rw [constantCoeff_apply] at hcc
    exact hcc (by simpa using PowerSeries.order_ne_zero_iff_constCoeff_eq_zero.mp hne)
  rw [h2, add_zero]

/-- **A germ whose restriction to the last axis has a simple zero generates the same ideal as
`X_n - c`**, for a germ `c` in the first `n` variables vanishing at the origin.

Weierstrass preparation, the degree recovered by
`LocalOkaRing.order_partialEval_eq_natDegree`, the shape supplied by
`LocalOkaRing.eq_X_sub_C_of_natDegree_eq_one`, and `Ideal.span_singleton_mul_right_unit` for the
unit factor. The hypothesis also supplies `MvPowerSeries.IsGeneralIn`, which unfolds to the
restriction being nonzero and so cannot hold at order `⊤`. -/
theorem exists_span_eq_span_X_sub_C {f : LocalOkaRing (Fin (n + 1))}
    (hf : PowerSeries.order
      (MvPowerSeries.partialEval (Fin.last n) (f : MvPowerSeries (Fin (n + 1)) ℂ)) = 1) :
    ∃ c : LocalOkaRing (Fin n), c ∈ IsLocalRing.maximalIdeal (LocalOkaRing (Fin n)) ∧
      Ideal.span {f} = Ideal.span {fromPolynomial (X - C c)} := by
  have hgen : (f : MvPowerSeries (Fin (n + 1)) ℂ).IsGeneralIn (Fin.last n) := by
    intro h
    rw [h, PowerSeries.order_zero] at hf
    simp at hf
  obtain ⟨u, hu, g, hg, hfeq⟩ := localweierstrass_preparation f hgen
  have hdeg : g.natDegree = 1 := by
    have hd := order_partialEval_eq_natDegree hu hg hfeq
    rw [hf] at hd
    exact_mod_cast hd.symm
  obtain ⟨c, hc, rfl⟩ := eq_X_sub_C_of_natDegree_eq_one hg hdeg
  exact ⟨c, hc, by rw [hfeq]; exact Ideal.span_singleton_mul_right_unit hu _⟩

/-- **The germ ring of a hypersurface with a simple zero along the last axis is the germ ring one
dimension down.**

`LocalOkaRing.quotientGraphEquiv` at the `c` that `LocalOkaRing.exists_span_eq_span_X_sub_C`
produces, transported along the equality of ideals by `Ideal.quotEquivOfEq`. **No graph appears in
the statement**: `f` is an arbitrary germ and the hypothesis is a condition on its restriction to
one axis.

The `c` is chosen and is not part of the data, which is why this is stated as an equivalence with
the quotient by `(f)` rather than as an equality of ideals with a named `c` — that is
`LocalOkaRing.exists_span_eq_span_X_sub_C`, one line above. -/
noncomputable def quotientSimpleZeroEquiv {f : LocalOkaRing (Fin (n + 1))}
    (hf : PowerSeries.order
      (MvPowerSeries.partialEval (Fin.last n) (f : MvPowerSeries (Fin (n + 1)) ℂ)) = 1) :
    LocalOkaRing (Fin n) ≃+* (LocalOkaRing (Fin (n + 1)) ⧸ Ideal.span {f}) :=
  (quotientGraphEquiv (exists_span_eq_span_X_sub_C hf).choose_spec.1).trans
    (Ideal.quotEquivOfEq (exists_span_eq_span_X_sub_C hf).choose_spec.2.symm)

/-! ### The Krull dimension -/

/-- **The germ ring in `n` variables has Krull dimension `n`.**

By induction: `ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`
drops the dimension by exactly one when one cuts by the last coordinate — which is a
nonzerodivisor because the germ ring is a domain, and lies in the maximal ideal because it
vanishes at the origin — and `quotientLastVarEquiv` identifies the quotient. -/
theorem ringKrullDim_eq (n : ℕ) : ringKrullDim (LocalOkaRing (Fin n)) = n := by
  induction n with
  | zero =>
    refine ringKrullDim_eq_zero_of_isField ?_
    rw [isField_iff_maximalIdeal_eq, maximalIdeal_eq_span_coord]
    simp
  | succ n ih =>
    have key := ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors
      (R := LocalOkaRing (Fin (n + 1))) (x := lastVar)
      (mem_nonZeroDivisors_of_ne_zero (by rw [lastVar_eq_coord]; exact coord_ne_zero _))
      (mem_maximalIdeal_iff.2 (by rw [lastVar_eq_coord]; exact constantCoeff_coord _))
    rw [← ringKrullDim_eq_of_ringEquiv (quotientLastVarEquiv (n := n)), ih] at key
    rw [← key]
    push_cast
    ring

/-- The Krull dimension of the germ ring is the number of variables. -/
theorem ringKrullDim_eq_natCard (ι : Type*) [Finite ι] :
    ringKrullDim (LocalOkaRing ι) = Nat.card ι := by
  have := Fintype.ofFinite ι
  rw [ringKrullDim_eq_of_ringEquiv (congrEquiv (Finite.equivFin ι)).toRingEquiv, ringKrullDim_eq]

/-! ### Regularity -/

/-- **The maximal ideal of `LocalOkaRing (Fin n)` is generated by at most `n` elements**, namely
the `n` coordinate functions. -/
theorem spanFinrank_maximalIdeal_le (n : ℕ) :
    (Submodule.spanFinrank (maximalIdeal (LocalOkaRing (Fin n))) : ℕ∞) ≤ n := by
  rw [maximalIdeal_eq_span_coord]
  refine le_trans (Submodule.spanFinrank_span_le_encard _) ?_
  rw [← Set.image_univ]
  refine le_trans (Set.encard_image_le _ _) ?_
  rw [Set.encard_univ]
  simp

/-- **The germ ring in `n` variables is a regular local ring.** Its maximal ideal is generated by
the `n` coordinates, and by `ringKrullDim_eq` that is exactly the Krull dimension. -/
theorem isRegularLocalRing_fin (n : ℕ) : IsRegularLocalRing (LocalOkaRing (Fin n)) := by
  refine IsRegularLocalRing.of_spanFinrank_maximalIdeal_le _ ?_
  rw [ringKrullDim_eq]
  exact_mod_cast WithBot.coe_le_coe.2 (spanFinrank_maximalIdeal_le n)

/-- **The germ ring is a regular local ring**, for an arbitrary finite set of variables. -/
instance instIsRegularLocalRing {ι : Type*} [Finite ι] : IsRegularLocalRing (LocalOkaRing ι) := by
  have := Fintype.ofFinite ι
  have := isRegularLocalRing_fin (Nat.card ι)
  exact IsRegularLocalRing.of_ringEquiv (congrEquiv (Finite.equivFin ι)).symm.toRingEquiv

/-- **The maximal ideal of `LocalOkaRing (Fin n)` needs exactly `n` generators**: `n` coordinates
suffice, and regularity says no smaller generating set exists. -/
theorem spanFinrank_maximalIdeal_eq (n : ℕ) :
    Submodule.spanFinrank (maximalIdeal (LocalOkaRing (Fin n))) = n := by
  have h := IsRegularLocalRing.spanFinrank_maximalIdeal (R := LocalOkaRing (Fin n))
  rw [ringKrullDim_eq] at h
  exact_mod_cast h

end LocalOkaRing
