/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.RingTheory.KrullDimension.Regular
import Mathlib.RingTheory.RegularLocalRing.Defs
import Oka.MaximalIdeal
import Oka.Noetherian

/-!
# The germ ring is a regular local ring of dimension `n`

The ring `LocalOkaRing (Fin n)` of germs at the origin of holomorphic functions in `n` variables
has Krull dimension `n` and is a regular local ring: its maximal ideal is generated by the `n`
coordinates, and `n` is exactly the dimension, so no smaller generating set exists.

## How the dimension is computed

Not by exhibiting a chain of primes. Mathlib computes the dimension of a Noetherian local ring by
cutting with one nonzerodivisor at a time
(`ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`, an
*equality*), so all that is needed is an induction step: quotienting the germ ring in `n + 1`
variables by the last coordinate returns the germ ring in `n` variables,

  `LocalOkaRing (Fin n) ≃+* LocalOkaRing (Fin (n + 1)) ⧸ (X_n)`.

That isomorphism is `LocalOkaRing.quotientLastVarEquiv`, and it is **Weierstrass division in
disguise**. The coordinate `X_n` is a local Weierstrass polynomial of degree one
(`LocalOkaRing.isLocalWeierstrassPolynomial_X`), so `Oka/Weierstrass.lean`'s division theorem
says every germ `f` in `n + 1` variables is `a · X_n + c` with `c` a germ in the first `n`
variables (`LocalOkaRing.exists_eq_mul_lastVar_add_incl`) — surjectivity — and the uniqueness
half of the division theorem, `localweierstrass_division_unique`, says that a `c` lying in
`(X_n)` is zero (`LocalOkaRing.incl_eq_zero_of_mem_span_lastVar`) — injectivity. The convergence
bookkeeping that "setting the last variable to zero" would otherwise require is entirely absorbed
by the division theorem, which already produces convergent quotient and remainder. (Mathlib does
have the purely algebraic projection, `MvPowerSeries.killCompl`, and it would give the
isomorphism just as well — but only after one proves that it preserves local convergence, which
is exactly the work the division theorem has already done.)

The base case is `LocalOkaRing (Fin 0)`, whose maximal ideal is generated by the empty family and
so is a field.

## Main results

- `LocalOkaRing.quotientLastVarEquiv`: `LocalOkaRing (Fin (n + 1)) ⧸ (X_n) ≃+* LocalOkaRing
  (Fin n)`, by Weierstrass division by the last coordinate.
- `LocalOkaRing.ringKrullDim_eq`: **`ringKrullDim (LocalOkaRing (Fin n)) = n`**, and
  `LocalOkaRing.ringKrullDim_eq_natCard` for an arbitrary finite set of variables.
- `LocalOkaRing.instIsRegularLocalRing`: **the germ ring is a regular local ring.**
- `LocalOkaRing.spanFinrank_maximalIdeal_le` and `LocalOkaRing.spanFinrank_maximalIdeal_eq`: the
  maximal ideal is generated by `n` elements and by no fewer.

## References

- [Hans Grauert and Reinhold Remmert, *Analytische Stellenalgebren*][grauert-remmert1971], §I
-/

open IsLocalRing Polynomial

namespace LocalOkaRing

variable {n : ℕ}

/-! ### Quotienting by the last coordinate -/

/-- The last coordinate, as an element of the polynomial ring in which Weierstrass division takes
place, is a local Weierstrass polynomial: it is monic of degree one, and there is no coefficient
below the leading one to vanish at the origin. -/
theorem isLocalWeierstrassPolynomial_X :
    IsLocalWeierstrassPolynomial
      (Polynomial.map (Subring.subtype (localOkaSubring (Fin n)).toSubring)
        (X : (LocalOkaRing (Fin n))[X])) where
  monic := by rw [Polynomial.map_X]; exact monic_X
  apply_zero i hi := by
    rw [Polynomial.map_X] at hi ⊢
    rw [degree_X, Nat.cast_lt_one] at hi
    rw [hi, coeff_X_zero, map_zero]

/-- The last coordinate is the coordinate at `Fin.last n`. -/
theorem lastVar_eq_coord :
    (lastVar : LocalOkaRing (Fin (n + 1))) = coord (Fin.last n) :=
  Subtype.ext rfl

/-- **Weierstrass division by the last coordinate.** Every germ in `n + 1` variables is a
multiple of the last coordinate plus a germ in the first `n` variables.

This is `localweierstrass_division` for the Weierstrass polynomial `X`, whose remainder has
degree `< 1` and is therefore a constant. -/
theorem exists_eq_mul_lastVar_add_incl (f : LocalOkaRing (Fin (n + 1))) :
    ∃ (a : LocalOkaRing (Fin (n + 1))) (c : LocalOkaRing (Fin n)),
      f = a * lastVar + incl c := by
  obtain ⟨a, b, hb, hf⟩ := localweierstrass_division X isLocalWeierstrassPolynomial_X f
  refine ⟨a, b.coeff 0, ?_⟩
  rw [degree_X] at hb
  have hb0 : b = C (b.coeff 0) :=
    eq_C_of_degree_le_zero (Nat.WithBot.lt_one_iff_le_zero.mp hb)
  rw [hf, fromPolynomial_X]
  conv_lhs => rw [hb0]
  rw [fromPolynomial_C]

/-- A germ in the first `n` variables which is divisible by the last coordinate is zero.

This is the *uniqueness* half of Weierstrass division: `c` and `a · X_n` are two divisions of the
same germ by `X`, one with quotient `0` and remainder `C c`, the other with quotient `a` and
remainder `0`. -/
theorem incl_eq_zero_of_mem_span_lastVar {c : LocalOkaRing (Fin n)}
    (h : incl c ∈ Ideal.span {(lastVar : LocalOkaRing (Fin (n + 1)))}) : c = 0 := by
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp h
  have key := localweierstrass_division_unique (q := (X : (LocalOkaRing (Fin n))[X]))
    isLocalWeierstrassPolynomial_X (a := a) (a' := 0)
    (b := (0 : (LocalOkaRing (Fin n))[X])) (b' := C c)
    (by simp [degree_X]) (by rw [degree_X]; exact degree_C_le.trans_lt (by norm_num))
    (by
      rw [fromPolynomial_X, fromPolynomial_C, map_zero]
      simpa using ha)
  simpa using key.2.symm

/-- **Quotienting the germ ring in `n + 1` variables by the last coordinate returns the germ ring
in `n` variables.** Surjectivity is Weierstrass division by `X`, injectivity is its uniqueness
half. -/
noncomputable def quotientLastVarEquiv : LocalOkaRing (Fin n) ≃+*
    (LocalOkaRing (Fin (n + 1)) ⧸ Ideal.span {(lastVar : LocalOkaRing (Fin (n + 1)))}) :=
  RingEquiv.ofBijective
    ((Ideal.Quotient.mk _).comp (incl : LocalOkaRing (Fin n) →ₐ[ℂ] _).toRingHom)
    ⟨(injective_iff_map_eq_zero _).2 fun _ hc ↦
        incl_eq_zero_of_mem_span_lastVar (Ideal.Quotient.eq_zero_iff_mem.mp hc),
      by
        intro x
        obtain ⟨f, rfl⟩ := Ideal.Quotient.mk_surjective x
        obtain ⟨a, c, rfl⟩ := exists_eq_mul_lastVar_add_incl f
        refine ⟨c, ?_⟩
        simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
        rw [eq_comm, Ideal.Quotient.mk_eq_mk_iff_sub_mem]
        simpa using Ideal.mul_mem_left _ a (Ideal.mem_span_singleton_self _)⟩

/-! ### The Krull dimension -/

/-- **The germ ring in `n` variables has Krull dimension `n`.**

By induction: `ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`
drops the dimension by exactly one when one cuts by the last coordinate — which is a
nonzerodivisor because the germ ring is a domain, and lies in the maximal ideal because it
vanishes at the origin — and `quotientLastVarEquiv` identifies the quotient. -/
theorem ringKrullDim_eq (n : ℕ) : ringKrullDim (LocalOkaRing (Fin n)) = n := by
  induction n with
  | zero =>
    refine ringKrullDim_eq_zero_of_isField ?_
    rw [isField_iff_maximalIdeal_eq, maximalIdeal_eq_span_coord]
    simp
  | succ n ih =>
    have key := ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors
      (R := LocalOkaRing (Fin (n + 1))) (x := lastVar)
      (mem_nonZeroDivisors_of_ne_zero (by rw [lastVar_eq_coord]; exact coord_ne_zero _))
      (mem_maximalIdeal_iff.2 (by rw [lastVar_eq_coord]; exact constantCoeff_coord _))
    rw [← ringKrullDim_eq_of_ringEquiv (quotientLastVarEquiv (n := n)), ih] at key
    rw [← key]
    push_cast
    ring

/-- The Krull dimension of the germ ring is the number of variables. -/
theorem ringKrullDim_eq_natCard (ι : Type*) [Finite ι] :
    ringKrullDim (LocalOkaRing ι) = Nat.card ι := by
  have := Fintype.ofFinite ι
  rw [ringKrullDim_eq_of_ringEquiv (congrEquiv (Finite.equivFin ι)).toRingEquiv, ringKrullDim_eq]

/-! ### Regularity -/

/-- **The maximal ideal of `LocalOkaRing (Fin n)` is generated by at most `n` elements**, namely
the `n` coordinate functions. -/
theorem spanFinrank_maximalIdeal_le (n : ℕ) :
    (Submodule.spanFinrank (maximalIdeal (LocalOkaRing (Fin n))) : ℕ∞) ≤ n := by
  rw [maximalIdeal_eq_span_coord]
  refine le_trans (Submodule.spanFinrank_span_le_encard _) ?_
  rw [← Set.image_univ]
  refine le_trans (Set.encard_image_le _ _) ?_
  rw [Set.encard_univ]
  simp

/-- **The germ ring in `n` variables is a regular local ring.** Its maximal ideal is generated by
the `n` coordinates, and by `ringKrullDim_eq` that is exactly the Krull dimension. -/
theorem isRegularLocalRing_fin (n : ℕ) : IsRegularLocalRing (LocalOkaRing (Fin n)) := by
  refine IsRegularLocalRing.of_spanFinrank_maximalIdeal_le _ ?_
  rw [ringKrullDim_eq]
  exact_mod_cast WithBot.coe_le_coe.2 (spanFinrank_maximalIdeal_le n)

/-- **The germ ring is a regular local ring**, for an arbitrary finite set of variables. -/
instance instIsRegularLocalRing {ι : Type*} [Finite ι] : IsRegularLocalRing (LocalOkaRing ι) := by
  have := Fintype.ofFinite ι
  have := isRegularLocalRing_fin (Nat.card ι)
  exact IsRegularLocalRing.of_ringEquiv (congrEquiv (Finite.equivFin ι)).symm.toRingEquiv

/-- **The maximal ideal of `LocalOkaRing (Fin n)` needs exactly `n` generators**: `n` coordinates
suffice, and regularity says no smaller generating set exists. -/
theorem spanFinrank_maximalIdeal_eq (n : ℕ) :
    Submodule.spanFinrank (maximalIdeal (LocalOkaRing (Fin n))) = n := by
  have h := IsRegularLocalRing.spanFinrank_maximalIdeal (R := LocalOkaRing (Fin n))
  rw [ringKrullDim_eq] at h
  exact_mod_cast h

end LocalOkaRing
