/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.RegularLocalRing.Defs
import Oka.MaximalIdeal
import Oka.Noetherian

/-!
# Regularity of the germ ring, reduced to a single inequality

`LocalOkaRing (Fin n)` is a regular local ring of dimension `n`. This file does **not** prove
that. It proves the half that is free and packages the reduction, so that what remains is
exactly one inequality:

  `(n : WithBot ℕ∞) ≤ ringKrullDim (LocalOkaRing (Fin n))`.

`IsRegularLocalRing R` is `(IsLocalRing.maximalIdeal R).spanFinrank = ringKrullDim R`, and
Mathlib's `IsRegularLocalRing.of_spanFinrank_maximalIdeal_le` shows that the `≤` half suffices
given `IsLocalRing R` and `IsNoetherianRing R` — both of which the germ ring has, the second by
the Rückert basis theorem of `Oka/Noetherian.lean`. Since the maximal ideal is generated by the
`n` coordinates (`LocalOkaRing.maximalIdeal_eq_span_coord`, `Oka/MaximalIdeal.lean`), that half
is immediate, and it is `LocalOkaRing.spanFinrank_maximalIdeal_le` below.

## What remains, and where to start

The missing inequality is the statement that there is a strictly increasing chain of `n + 1`
prime ideals

  `(0) ⊊ (X₀) ⊊ (X₀, X₁) ⊊ ⋯ ⊊ (X₀, …, X_{n-1}) = 𝔪`.

The Mathlib entry point for turning such a chain into the bound is `Order.le_krullDim_iff`
(`n ≤ krullDim α ↔ ∃ l : LTSeries α, l.length = n`) or `LTSeries.length_le_krullDim`, applied to
the prime spectrum; `ringKrullDim` is by definition the `Order.krullDim` of that. The genuinely
open part is primality of the partial ideals, for which the natural route is a `ℂ`-algebra
isomorphism `LocalOkaRing (Fin n) ⧸ (X₀, …, X_{k-1}) ≃ₐ[ℂ] LocalOkaRing (Fin (n - k))` — "set the
first `k` variables to zero" — which would give primality from `LocalOkaRing.instIsDomain`. There
is currently no API in this development for setting a subset of the variables to zero.

## Main results

- `LocalOkaRing.spanFinrank_maximalIdeal_le`: the maximal ideal of `LocalOkaRing (Fin n)` is
  generated by at most `n` elements.
- `LocalOkaRing.isRegularLocalRing_of_le_ringKrullDim`: **given `n ≤ ringKrullDim`, the germ ring
  is a regular local ring.** This is the whole content of the reduction.
- `LocalOkaRing.isRegularLocalRing_fin_zero`: the case `n = 0`, which discharges the hypothesis
  outright and so witnesses that the reduction is not vacuous.

## References

- [Hans Grauert and Reinhold Remmert, *Analytische Stellenalgebren*][grauert-remmert1971], §I
-/

open IsLocalRing

namespace LocalOkaRing

/-- **The maximal ideal of `LocalOkaRing (Fin n)` is generated by at most `n` elements**, namely
the `n` coordinate functions. -/
theorem spanFinrank_maximalIdeal_le (n : ℕ) :
    (Submodule.spanFinrank (maximalIdeal (LocalOkaRing (Fin n))) : ℕ∞) ≤ n := by
  rw [maximalIdeal_eq_span_coord]
  refine le_trans (Submodule.spanFinrank_span_le_encard _) ?_
  rw [← Set.image_univ]
  refine le_trans (Set.encard_image_le _ _) ?_
  rw [Set.encard_univ]
  simp

/-- **The germ ring is a regular local ring as soon as its Krull dimension is at least `n`.**

Regularity is `spanFinrank 𝔪 = ringKrullDim`, and Mathlib's
`IsRegularLocalRing.of_spanFinrank_maximalIdeal_le` reduces it to `≤`; `spanFinrank_maximalIdeal_le`
supplies `spanFinrank 𝔪 ≤ n`, so the remaining hypothesis is the only thing standing between this
development and regularity of the germ ring.
See the module docstring for what proving it requires. -/
theorem isRegularLocalRing_of_le_ringKrullDim (n : ℕ)
    (h : (n : WithBot ℕ∞) ≤ ringKrullDim (LocalOkaRing (Fin n))) :
    IsRegularLocalRing (LocalOkaRing (Fin n)) :=
  IsRegularLocalRing.of_spanFinrank_maximalIdeal_le _
    (le_trans (by exact_mod_cast (WithBot.coe_le_coe.2 (spanFinrank_maximalIdeal_le n))) h)

/-- **The germ ring in no variables is a regular local ring**, of dimension `0` — it is a field.

Besides being the base case of the induction, this witnesses that the hypothesis of
`isRegularLocalRing_of_le_ringKrullDim` is satisfiable, so the reduction is not vacuous. -/
instance isRegularLocalRing_fin_zero : IsRegularLocalRing (LocalOkaRing (Fin 0)) :=
  isRegularLocalRing_of_le_ringKrullDim 0 (by
    simpa using ringKrullDim_nonneg_of_nontrivial (R := LocalOkaRing (Fin 0)))

end LocalOkaRing
