/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.AlgebraicGeometry.Modules.Sheaf
import Mathlib.AlgebraicGeometry.Noetherian
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Free
import Oka.AnalyticSpace.Relations
import Oka.RingTheory.Localization.Module

/-!
# The structure sheaf of a locally noetherian scheme is coherent

The algebraic counterpart of Oka's theorem, and the first thing in this repository that proves a
sheaf on a scheme to be coherent. On `Spec A` for a noetherian ring `A` this is
`AlgebraicGeometry.isCoherentStructureSheaf_spec`, which is the statement
`OkaTest/CoherentPresentation.lean` recorded as the missing input on the algebraic side, in a
paragraph this file's arrival rewrites.

## Strategy

Exactly the analytic one, and it runs on the same machinery:
`AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations` — near every point, the relations
between finitely many sections of `𝒪` are generated by finitely many of them — implies coherence
by `AlgebraicGeometry.LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations`, and it
mentions only open sets, sections and restriction maps, so there is no transport of sites
anywhere. What replaces Oka's coherence lemma is **noetherianity**, and the replacement is
shorter:

1. take any affine open `U ∋ x` (`AlgebraicGeometry.Scheme.isBasis_affineOpens`) and then a basic
   open `W = X.basicOpen t` of it, for some `t : Γ(X, U)`, with `x ∈ W ≤ V`
   (`AlgebraicGeometry.IsAffineOpen.exists_basicOpen_le`). A basic open of an affine open is
   affine, so `Γ(X, W)` is noetherian;
2. the relations between the restricted sections form a submodule of `Γ(X, W) ^ m`, which is a
   noetherian module, so they are generated by finitely many `g l` — **globally on `W`**, not
   merely locally;
3. for the local-generation clause, shrink again to a basic open `X.basicOpen h ⊆ W'` of `W`,
   over which `Γ` is a localisation of `Γ(X, W)`
   (`AlgebraicGeometry.IsAffineOpen.isLocalization_basicOpen`), and quote
   `IsLocalization.exists_fun_eq_sum_of_sum_mul_eq_zero`.

Steps 1 and 2 are quotations of Mathlib; **step 3 is the only one that needed a lemma this
repository had to prove**, and it is where the localisation lemma of
`Oka/RingTheory/Localization/Module.lean` is used. Note that the `∀ W' ≤ W` quantifier of
`HasLocalRelations` ranges over **arbitrary** open subsets of `W`, and it is the freedom to
shrink `W'` around a point that lets the argument stay inside basic opens throughout.

Note what step 2 gives that `HasLocalRelations` does not ask for, and what it does not. **At
`W' = W` it is sectionwise**: a relation between the `f i` over `W` itself is a `Γ(X, W)`-
combination of the `g l` outright, since that is what generation of the kernel means, and no
shrinking happens. **At a smaller `W'` it is not**: the restriction `Γ(X, W) → Γ(X, W')` is not a
localisation for a general open `W'`, which is why step 3 shrinks to a basic open around the
point. `HasLocalRelations` is stated in the local form because the analytic side cannot supply
the sectionwise one, and this file neither weakens nor strengthens it.

## Generality: locally noetherian schemes, not only affines

The argument never uses that `X` is affine — only that `x` has an affine open neighbourhood
whose ring is noetherian, which is `AlgebraicGeometry.IsLocallyNoetherian`. So the general
statement is proved and `Spec A` is a corollary, rather than the other way round; Mathlib's
instance `IsLocallyNoetherian (Spec A)` for `[IsNoetherianRing A]` is what makes the corollary
one line.

## This is not a mirror file, and the path says so

`HasLocalRelations` and `IsCoherentStructureSheaf` are defined in this repository
(`Oka/AnalyticSpace/Relations.lean`), as is `SheafOfModules.IsCoherent`, so by `README.md`'s two
tests the results here are not upstreamable as they stand and must not sit under a Mathlib path.
That is why this file is at the root of `Oka/` rather than under `Oka/AlgebraicGeometry/`, which
is a mirror directory: compare `Oka/StructureSheaf.lean` with
`Oka/AlgebraicGeometry/StructureSheaf.lean`, which is the same non-mirror/mirror pair. The one
piece of genuinely general commutative algebra extracted on the way *is* in the mirror tree, at
`Oka/RingTheory/Localization/Module.lean`.

## Main results

- `AlgebraicGeometry.Scheme.hasLocalRelations`: a locally noetherian scheme has locally finitely
  generated relations.
- `AlgebraicGeometry.Scheme.isCoherentStructureSheaf`: hence **its structure sheaf is coherent**.
- `AlgebraicGeometry.Scheme.isCoherent_unit`: the same at Mathlib's `Scheme.ringCatSheaf`
  spelling of the sheaf of rings, which is what `AlgebraicGeometry.Scheme.Modules` is defined
  over.
- `AlgebraicGeometry.Scheme.isCoherent_free`: a finite free sheaf on a locally noetherian scheme
  is coherent.
- `AlgebraicGeometry.isCoherentStructureSheaf_spec`: **`𝒪_{Spec A}` is coherent for noetherian
  `A`.**

## References

- [Jean-Pierre Serre, *Faisceaux algébriques cohérents*][serre1955], §2
- https://stacks.math.columbia.edu/tag/01XZ — on a locally noetherian scheme a quasi-coherent
  module of finite type is coherent, of which the theorem here is the case `ℱ = 𝒪_X`.
-/

open CategoryTheory Limits TopologicalSpace Opposite SheafOfModules

universe u

namespace AlgebraicGeometry

namespace Scheme

variable (X : Scheme.{u})

/-- The `algebraMap` onto the sections over a basic open subset is the restriction map.

`AlgebraicGeometry.Scheme.algebra_section_section_basicOpen` is defined as
`RingHom.toAlgebra` of that restriction map, so this is `RingHom.algebraMap_toAlgebra` and
nothing else; it is stated because the rest of the file mixes the two spellings and
`AlgebraicGeometry.LocallyRingedSpace.res` is this repository's abbreviation, not Mathlib's. -/
lemma algebraMap_basicOpen_eq_res {U : X.Opens} (f : Γ(X, U)) (r : Γ(X, U)) :
    algebraMap Γ(X, U) Γ(X, X.basicOpen f) r =
      X.toLocallyRingedSpace.res (X.basicOpen_le f) r := by
  rw [RingHom.algebraMap_toAlgebra]; rfl

/-- **A locally noetherian scheme has locally finitely generated relations.**

The three steps are described in the module docstring. The only inputs are that an affine open
has a noetherian ring of sections, that the basic opens of an affine open form a neighbourhood
basis at each of its points (`AlgebraicGeometry.IsAffineOpen.exists_basicOpen_le`), and that
they localise its ring of sections
(`AlgebraicGeometry.IsAffineOpen.isLocalization_basicOpen`). -/
theorem hasLocalRelations [IsLocallyNoetherian X] :
    X.toLocallyRingedSpace.HasLocalRelations := by
  classical
  intro V m f x hx
  obtain ⟨-, ⟨U, hUaff, rfl⟩, hxU, -⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
  obtain ⟨t, htV, hxt⟩ := hUaff.exists_basicOpen_le (V := V) ⟨x, hx⟩ hxU
  haveI hWaff : IsAffineOpen (X.basicOpen t) := hUaff.basicOpen t
  haveI : IsNoetherianRing Γ(X, X.basicOpen t) :=
    IsLocallyNoetherian.component_noetherian ⟨X.basicOpen t, hWaff⟩
  set fW : Fin m → Γ(X, X.basicOpen t) := fun i ↦ X.toLocallyRingedSpace.res htV (f i) with hfW
  -- the relations between the `fW i` are generated over the whole of `X.basicOpen t`
  obtain ⟨k, g, hrelg, hgen⟩ :
      ∃ (k : ℕ) (g : Fin k → (Fin m → Γ(X, X.basicOpen t))),
        (∀ l, ∑ i, g l i * fW i = 0) ∧
        (∀ b : Fin m → Γ(X, X.basicOpen t), ∑ i, b i * fW i = 0 →
          b ∈ Submodule.span Γ(X, X.basicOpen t) (Set.range g)) := by
    let φ : (Fin m → Γ(X, X.basicOpen t)) →ₗ[Γ(X, X.basicOpen t)] Γ(X, X.basicOpen t) :=
      { toFun := fun b ↦ ∑ i, b i * fW i
        map_add' := fun b c ↦ by simp [add_mul, Finset.sum_add_distrib]
        map_smul' := fun c b ↦ by simp [Finset.mul_sum, mul_assoc] }
    obtain ⟨k, g, hgspan⟩ :=
      Submodule.fg_iff_exists_fin_generating_family.1 (IsNoetherian.noetherian (LinearMap.ker φ))
    refine ⟨k, g, fun l ↦ ?_, fun b hb ↦ ?_⟩
    · have hg : g l ∈ Submodule.span Γ(X, X.basicOpen t) (Set.range g) :=
        Submodule.subset_span ⟨l, rfl⟩
      rw [hgspan] at hg
      exact hg
    · rw [hgspan]
      exact hb
  refine ⟨X.basicOpen t, htV, k, g, hxt, hrelg, ?_⟩
  intro W' hW'W a ha y hy
  -- shrink to a basic open of `X.basicOpen t` around `y`, over which `Γ` is a localisation
  obtain ⟨h, hhW', hyh⟩ := hWaff.exists_basicOpen_le (V := W') ⟨y, hy⟩ (hW'W hy)
  haveI : IsLocalization.Away h Γ(X, X.basicOpen h) := hWaff.isLocalization_basicOpen h
  refine ⟨X.basicOpen h, hhW', hyh, ?_⟩
  have hares : ∑ i, X.toLocallyRingedSpace.res hhW' (a i) *
      algebraMap Γ(X, X.basicOpen t) Γ(X, X.basicOpen h) (fW i) = 0 := by
    have hres := congrArg (X.toLocallyRingedSpace.res hhW') ha
    rw [LocallyRingedSpace.res_sum, LocallyRingedSpace.res_zero] at hres
    simp only [LocallyRingedSpace.res_mul, LocallyRingedSpace.res_res] at hres
    simpa only [algebraMap_basicOpen_eq_res, hfW, LocallyRingedSpace.res_res] using hres
  obtain ⟨c, hc⟩ := IsLocalization.exists_fun_eq_sum_of_sum_mul_eq_zero (Submonoid.powers h)
    fW g hgen (fun i ↦ X.toLocallyRingedSpace.res hhW' (a i)) hares
  exact ⟨c, by simpa only [algebraMap_basicOpen_eq_res, LocallyRingedSpace.res_res] using hc⟩

/-- **The structure sheaf of a locally noetherian scheme is coherent.** -/
theorem isCoherentStructureSheaf [IsLocallyNoetherian X] :
    X.toLocallyRingedSpace.IsCoherentStructureSheaf :=
  LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations X.hasLocalRelations

/-- **The same, at Mathlib's spelling of the sheaf of rings.**

`AlgebraicGeometry.Scheme.ringCatSheaf` and
`AlgebraicGeometry.LocallyRingedSpace.ringSheaf` differ in how the site is written and agree by
`rfl`; this statement is the one to quote at anything defined over
`AlgebraicGeometry.Scheme.Modules`, such as
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`, because instance search does
not cross the two spellings even though `exact` does. -/
theorem isCoherent_unit [IsLocallyNoetherian X] :
    (SheafOfModules.unit X.ringCatSheaf).IsCoherent :=
  X.isCoherentStructureSheaf

/-- **A finite free sheaf on a locally noetherian scheme is coherent.**

`SheafOfModules.IsCoherent.free` — an induction on the rank with no geometry in it — fed the
theorem above. This is the exact analogue of
`ComplexAnalytic.AnalyticSpace.isCoherent_free`. -/
theorem isCoherent_free [IsLocallyNoetherian X] (I : Type u) [Finite I] :
    (SheafOfModules.free (R := X.ringCatSheaf) I).IsCoherent :=
  haveI : (SheafOfModules.unit X.ringCatSheaf).IsCoherent := X.isCoherent_unit
  SheafOfModules.IsCoherent.free I

end Scheme

/-- **`𝒪_{Spec A}` is coherent for a noetherian ring `A`.**

The corollary the rest of this development wants, and the one three issue bodies and
`OkaTest/CoherentPresentation.lean` recorded as missing. It is `Scheme.isCoherentStructureSheaf`
at `Spec A`, using Mathlib's instance `IsLocallyNoetherian (Spec A)`; noetherianity of `A` enters
only through that instance, that is through noetherianity of `Γ(Spec A, U)` for `U` affine
open. -/
theorem isCoherentStructureSheaf_spec (A : CommRingCat.{u}) [IsNoetherianRing A] :
    (Spec A).toLocallyRingedSpace.IsCoherentStructureSheaf :=
  (Spec A).isCoherentStructureSheaf

end AlgebraicGeometry
