/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.OkaLemma

/-!
# Oka's coherence lemma

We state Oka's coherence lemma: the relations between finitely many holomorphic functions on an
open subset of `ℂ^ι` are, near every point, generated by finitely many of them. The statement is
made for vectors of holomorphic functions in `oka'`, and only assumed for the index type `Fin n`
in `oka_fin`; the general index type is reduced to this case by a linear change of coordinates.

The statement on `ℂ^n` for vectors of length `q` is packaged as the predicate `OkaStatement q n`,
so that it can be proved by induction on `n`: the inductive step for `q = 1` uses the statement
for all `q` in dimension `n`, which is available by `OkaStatement.of_one`.

The inductive step itself is carried out for rows of holomorphic functions, i.e. for the
predicate `OkaRowConclusion`, in `okaRowStatement_succ`. It rests on two geometric inputs:
`exists_isWeierstrassPolynomial_row`, which puts the row into Weierstrass form after a linear
change of coordinates, and `okaRowConclusion_toOkaRing`, which settles the case of a row of
Weierstrass polynomials using the induction hypothesis and Oka's bounded degree lemma.

This is the analytic input to the whole development. Everything else is deduced from it: see
`Oka.AnalyticSpace.Relations` for the structure sheaf of `ℂ^ι` and `Oka.AnalyticSpace.Coherent`
for arbitrary complex analytic spaces.
-/

open TopologicalSpace

variable {ι : Type*} [Fintype ι]
variable (U : Opens (ι → ℂ))

/-- Oka's coherence lemma on `ℂ^n`, for families `f` of `m` vectors of holomorphic functions,
each of length `q`: the relations `a` between the `f i`, i.e. the tuples `a` with
`∑ i, a i • f i = 0` in `(OkaRing W)^q`, are, near every point, generated by finitely many
relations `g l` defined on a fixed neighbourhood `V` of `x`.

Here `q` is the rank of the target of the linear map `a ↦ ∑ i, a i • f i` and `n` is the
dimension of the ambient space `ℂ^n`. -/
def OkaStatement (q n : ℕ) : Prop :=
  ∀ {m : ℕ} (U : Opens (Fin n → ℂ)) (f : Fin m → (Fin q → OkaRing U))
    (x : Fin n → ℂ), x ∈ U →
    ∃ (V : Opens (Fin n → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∀ j, ∑ i, g l i * OkaRing.restrict hV (f i j) = 0) ∧
      ∀ (W : Opens (Fin n → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∀ j, ∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i j) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (Fin n → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i)

/-- Composing the linear form given by `A : Fin k → Fin m → R` with the linear form given by
`F : Fin m → R`: the row `i ↦ ∑ l, c l * A l i` pairs with `F` as `c` pairs with the row
`l ↦ ∑ i, A l i * F i`. -/
private lemma sum_mul_sum_mul {R : Type*} [CommRing R] {k m : ℕ} (c : Fin k → R)
    (A : Fin k → Fin m → R) (F : Fin m → R) :
    ∑ i, (∑ l, c l * A l i) * F i = ∑ l, c l * ∑ i, A l i * F i := by
  simp only [Finset.sum_mul, Finset.mul_sum, mul_assoc]
  exact Finset.sum_comm

/-- In a fixed dimension `n`, the case `q = 1` of Oka's coherence lemma implies the case of
arbitrary `q`: by induction on `q`, the relations between the `f i` in `(OkaRing W)^q` are the
relations in the last coordinate between generators of the relations in the first `q - 1`
coordinates.

This is Section 1 of the argument: write `α : 𝒪^{q + 1} → 𝒪^q` and `β : 𝒪^{q + 1} → 𝒪` for the
projections to the first `q` coordinates and to the last one. Generators `A l` of `ker (α ∘ F)`
give `G : 𝒪^k₁ → 𝒪^m`, `G c = ∑ l, c l • A l`, and generators `B s` of the kernel of the scalar
row `L = β ∘ F ∘ G` then yield generators `G (B s)` of `ker F`. -/
theorem OkaStatement.of_one {n : ℕ} (h : OkaStatement 1 n) (q : ℕ) : OkaStatement q n := by
  induction q with
  | zero =>
    -- The case `q = 0` is immediate: the target is the zero module, so every tuple is a
    -- relation, and the standard basis of `𝒪^m` generates all of them.
    intro m U f x hx
    refine ⟨U, le_rfl, m, fun l i ↦ if l = i then 1 else 0, hx, fun l j ↦ j.elim0,
      fun W hWU a _ y hy ↦ ⟨W, le_rfl, hy, a, fun i ↦ ?_⟩⟩
    simp [apply_ite (OkaRing.restrict (le_rfl.trans hWU))]
  | succ q ih =>
    intro m U f x hx
    -- Generators `A l` of the relations for `α ∘ F`, the first `q` rows of `F`.
    obtain ⟨V₁, hV₁, k₁, A, hxV₁, hArel, hAgen⟩ := ih U (fun i j ↦ f i j.castSucc) x hx
    -- Generators `B s` of the relations for the scalar row `L = β ∘ F ∘ G`, where
    -- `G : 𝒪^k₁ → 𝒪^m` is `c ↦ ∑ l, c l • A l`.
    obtain ⟨V₂, hV₂, k₂, B, hxV₂, hBrel, hBgen⟩ :=
      h V₁ (fun l _ ↦ ∑ i, A l i * OkaRing.restrict hV₁ (f i (Fin.last q))) x hxV₁
    -- The vectors `G (B s)` generate the relations for `F`.
    refine ⟨V₂, hV₂.trans hV₁, k₂, fun s i ↦ ∑ l, B s l * OkaRing.restrict hV₂ (A l i), hxV₂,
      fun s j ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
    · -- `G (B s)` is a relation: it is one for the first `q` rows because every `A l` is, and
      -- one for the last row because `B s` is a relation for `L`.
      rw [sum_mul_sum_mul]
      have hres : ∀ l, ∑ i, OkaRing.restrict hV₂ (A l i) *
          OkaRing.restrict (hV₂.trans hV₁) (f i j) =
          OkaRing.restrict hV₂ (∑ i, A l i * OkaRing.restrict hV₁ (f i j)) := fun l ↦ by
        simp only [map_sum, map_mul, OkaRing.restrict_restrict]
      simp only [hres]
      induction j using Fin.lastCases with
      | last => exact hBrel s 0
      | cast j => simp [hArel]
    · -- Conversely, a relation `a` for `F` is in particular one for the first `q` rows, hence
      -- of the form `a = G c` near `y`.
      obtain ⟨W₁, hW₁, hyW₁, c, hc⟩ :=
        hAgen W (hWV.trans hV₂) a (fun j ↦ ha j.castSucc) y hy
      -- Since `a` is also a relation for the last row, `c` is a relation for `L`.
      have hcL : ∀ j : Fin 1, ∑ l, c l * OkaRing.restrict ((hW₁.trans hWV).trans hV₂)
          (∑ i, A l i * OkaRing.restrict hV₁ (f i (Fin.last q))) = 0 := by
        intro _
        have hres : ∀ l, OkaRing.restrict ((hW₁.trans hWV).trans hV₂)
            (∑ i, A l i * OkaRing.restrict hV₁ (f i (Fin.last q))) =
            ∑ i, OkaRing.restrict (hW₁.trans (hWV.trans hV₂)) (A l i) *
              OkaRing.restrict (hW₁.trans ((hWV.trans hV₂).trans hV₁)) (f i (Fin.last q)) :=
          fun l ↦ by simp only [map_sum, map_mul, OkaRing.restrict_restrict]
        simp only [hres, ← sum_mul_sum_mul, ← hc]
        simpa only [map_sum, map_mul, map_zero, OkaRing.restrict_restrict] using
          congrArg (OkaRing.restrict hW₁) (ha (Fin.last q))
      -- Expressing `c` in the `B s` expresses `a` in the `G (B s)`.
      obtain ⟨W', hW', hyW', e, he⟩ := hBgen W₁ (hW₁.trans hWV) c hcL y hyW₁
      refine ⟨W', hW'.trans hW₁, hyW', e, fun i ↦ ?_⟩
      have hres : ∀ s, OkaRing.restrict ((hW'.trans hW₁).trans hWV)
          (∑ l, B s l * OkaRing.restrict hV₂ (A l i)) =
          ∑ l, OkaRing.restrict (hW'.trans (hW₁.trans hWV)) (B s l) *
            OkaRing.restrict (hW'.trans (hW₁.trans (hWV.trans hV₂))) (A l i) :=
        fun s ↦ by simp only [map_sum, map_mul, OkaRing.restrict_restrict]
      simp only [hres, ← sum_mul_sum_mul, ← he]
      simpa only [map_sum, map_mul, OkaRing.restrict_restrict] using
        congrArg (OkaRing.restrict hW') (hc i)

/-- The case `n = 0` of Oka's coherence lemma: `ℂ^0` is a point, so everything reduces to linear
algebra over `ℂ`. -/
theorem okaStatement_zero (q : ℕ) : OkaStatement q 0 := by
  intro m U f x hx
  -- `ℂ^0` is a point, so evaluation identifies each `OkaRing V` with `ℂ`, and the relations
  -- between the `f i` are the kernel of a `ℂ`-linear map between finite dimensional spaces
  have hinj : ∀ {V : Opens (Fin 0 → ℂ)} {y : Fin 0 → ℂ} (hy : y ∈ V),
      Function.Injective (OkaRing.evalHom hy) := by
    intro V y hy u v huv
    refine OkaRing.ext (funext fun z ↦ ?_)
    rw [Subsingleton.elim z ⟨y, hy⟩]
    exact huv
  set T : (Fin m → ℂ) →ₗ[ℂ] (Fin q → ℂ) :=
    ∑ i, (LinearMap.proj i).smulRight (fun j ↦ OkaRing.evalHom hx (f i j)) with hT
  have hTapply : ∀ (a : Fin m → ℂ) (j : Fin q),
      T a j = ∑ i, a i * OkaRing.evalHom hx (f i j) := by
    intro a j
    simp [hT]
  obtain ⟨k, s, hs⟩ := Module.Finite.exists_fin (R := ℂ) (M := LinearMap.ker T)
  refine ⟨U, le_rfl, k, fun l i ↦ algebraMap ℂ (OkaRing U) ((s l : Fin m → ℂ) i), hx,
    fun l j ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · refine hinj hx ?_
    have h0 : ∑ i, (s l : Fin m → ℂ) i * OkaRing.evalHom hx (f i j) = 0 := by
      rw [← hTapply]
      exact congrFun (LinearMap.mem_ker.mp (s l).2) j
    simpa only [map_sum, map_mul, map_zero, OkaRing.restrict_self,
      OkaRing.evalHom_algebraMap] using h0
  · have hxW : x ∈ W := by rwa [Subsingleton.elim x y]
    have hker : (fun i ↦ OkaRing.evalHom hxW (a i)) ∈ LinearMap.ker T := by
      rw [LinearMap.mem_ker]
      funext j
      rw [hTapply]
      simpa only [map_sum, map_mul, map_zero, Pi.zero_apply, OkaRing.evalHom_restrict] using
        congrArg (OkaRing.evalHom hxW) (ha j)
    obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℂ).mp
      (hs ▸ Submodule.mem_top : (⟨_, hker⟩ : LinearMap.ker T) ∈ Submodule.span ℂ (Set.range s))
    refine ⟨W, le_rfl, hy, fun l ↦ algebraMap ℂ (OkaRing W) (c l), fun i ↦ ?_⟩
    refine hinj hxW ?_
    have hci : ∑ l, c l * (s l : Fin m → ℂ) i = OkaRing.evalHom hxW (a i) := by
      simpa using congrFun (congrArg Subtype.val hc) i
    simpa only [map_sum, map_mul, OkaRing.restrict_self, AlgHom.commutes,
      OkaRing.evalHom_algebraMap] using hci.symm

section InductiveStep

/-! ### The inductive step

Fix `n` and assume Oka's coherence lemma in dimension `n` for every target rank. Following
Section 3 of the argument, we prove the case `q = 1` in dimension `n + 1`.

Throughout we work with a *row* `f : Fin p → OkaRing U` rather than with a family of vectors of
length one; `OkaRowConclusion U f x` is the assertion of Oka's lemma for the row `f` at the
point `x`, and `OkaRowStatement n` collects it over all rows in dimension `n`. -/

open Polynomial

/-- The conclusion of Oka's coherence lemma for a row `f : Fin p → OkaRing U` of holomorphic
functions at a point `x` of `U`: on a neighbourhood `V` of `x` there are finitely many relations
`g l` between the `f i` which generate, near every point of every smaller open set, all the
relations between the `f i`.

This is the case `q = 1` of `OkaStatement`, with the vectors of length one replaced by their
unique entry. -/
def OkaRowConclusion {n p : ℕ} (U : Opens (Fin n → ℂ)) (f : Fin p → OkaRing U)
    (x : Fin n → ℂ) : Prop :=
  ∃ (V : Opens (Fin n → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin p → OkaRing V)),
    x ∈ V ∧ (∀ l, ∑ i, g l i * OkaRing.restrict hV (f i) = 0) ∧
    ∀ (W : Opens (Fin n → ℂ)) (hWV : W ≤ V) (a : Fin p → OkaRing W),
      ∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i) = 0 → ∀ y ∈ W,
        ∃ (W' : Opens (Fin n → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
          ∃ c : Fin k → OkaRing W', ∀ i,
            OkaRing.restrict hW' (a i) = ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i)

/-- Oka's coherence lemma on `ℂ^n` for rows of holomorphic functions. -/
def OkaRowStatement (n : ℕ) : Prop :=
  ∀ {p : ℕ} (U : Opens (Fin n → ℂ)) (f : Fin p → OkaRing U) (x : Fin n → ℂ),
    x ∈ U → OkaRowConclusion U f x

/-- The row statement is the case `q = 1` of `OkaStatement`. -/
theorem OkaRowStatement.okaStatement_one {n : ℕ} (h : OkaRowStatement n) : OkaStatement 1 n := by
  intro p U f x hx
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := h U (fun i ↦ f i 0) x hx
  refine ⟨V, hV, k, g, hxV, fun l j ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · rw [Subsingleton.elim j 0]
    exact hrel l
  · exact hgen W hWV a (ha 0) y hy

variable {n p : ℕ} {U : Opens (Fin n → ℂ)} {f : Fin p → OkaRing U} {x : Fin n → ℂ}

/-- Oka's lemma at `x` for the restriction of `f` to a smaller neighbourhood of `x` implies
Oka's lemma at `x` for `f`. -/
theorem OkaRowConclusion.of_le {W : Opens (Fin n → ℂ)} (hWU : W ≤ U)
    (h : OkaRowConclusion W (fun i ↦ OkaRing.restrict hWU (f i)) x) :
    OkaRowConclusion U f x := by
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := h
  exact ⟨V, hV.trans hWU, k, g, hxV, hrel, fun W' hW' a ha ↦ hgen W' hW' a ha⟩

/-- Oka's lemma at `x` for `f` implies Oka's lemma at `x` for the restriction of `f` to a
smaller neighbourhood of `x`. -/
theorem OkaRowConclusion.restrict {W : Opens (Fin n → ℂ)} (hWU : W ≤ U) (hxW : x ∈ W)
    (h : OkaRowConclusion U f x) :
    OkaRowConclusion W (fun i ↦ OkaRing.restrict hWU (f i)) x := by
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := h
  refine ⟨V ⊓ W, inf_le_right, k, fun l i ↦ OkaRing.restrict inf_le_left (g l i), ⟨hxV, hxW⟩,
    fun l ↦ ?_, fun W' hW' a ha y hy ↦ ?_⟩
  · simpa only [map_sum, map_mul, map_zero, OkaRing.restrict_restrict] using
      congrArg (OkaRing.restrict (inf_le_left : V ⊓ W ≤ V)) (hrel l)
  · obtain ⟨W'', hW'', hyW'', c, hc⟩ :=
      hgen W' (hW'.trans inf_le_left) a ha y hy
    exact ⟨W'', hW'', hyW'', c, hc⟩

/-- Multiplying the entries of a row by units does not affect Oka's lemma: the relations
between the `u i * f i` are the relations between the `f i`, rescaled by the `u i`. -/
theorem OkaRowConclusion.unit_mul {u : Fin p → OkaRing U} (hu : ∀ i, IsUnit (u i))
    (h : OkaRowConclusion U f x) :
    OkaRowConclusion U (fun i ↦ u i * f i) x := by
  choose w hw using fun i ↦ (hu i).exists_right_inv
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := h
  refine ⟨V, hV, k, fun l i ↦ g l i * OkaRing.restrict hV (w i), hxV, fun l ↦ ?_,
    fun W hWV a ha y hy ↦ ?_⟩
  · refine .trans (Finset.sum_congr rfl fun i _ ↦ ?_) (hrel l)
    rw [map_mul, show g l i * OkaRing.restrict hV (w i) *
      (OkaRing.restrict hV (u i) * OkaRing.restrict hV (f i)) =
        g l i * OkaRing.restrict hV (f i) *
          (OkaRing.restrict hV (u i) * OkaRing.restrict hV (w i)) from by ring,
      ← map_mul, hw i, map_one, mul_one]
  · have hb : ∑ i, (a i * OkaRing.restrict (hWV.trans hV) (u i)) *
        OkaRing.restrict (hWV.trans hV) (f i) = 0 := by
      refine .trans (Finset.sum_congr rfl fun i _ ↦ ?_) ha
      rw [map_mul]
      ring
    obtain ⟨W', hW', hyW', c, hc⟩ := hgen W hWV _ hb y hy
    refine ⟨W', hW', hyW', c, fun i ↦ ?_⟩
    have key : OkaRing.restrict (hW'.trans (hWV.trans hV)) (u i) *
        OkaRing.restrict (hW'.trans (hWV.trans hV)) (w i) = 1 := by
      rw [← map_mul, hw i, map_one]
    calc OkaRing.restrict hW' (a i)
        = OkaRing.restrict hW' (a i * OkaRing.restrict (hWV.trans hV) (u i)) *
            OkaRing.restrict (hW'.trans (hWV.trans hV)) (w i) := by
          rw [map_mul]
          simp only [OkaRing.restrict_restrict, mul_assoc, key, mul_one]
      _ = (∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i)) *
            OkaRing.restrict (hW'.trans (hWV.trans hV)) (w i) := by rw [hc i]
      _ = ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i * OkaRing.restrict hV (w i)) := by
          rw [Finset.sum_mul]
          refine Finset.sum_congr rfl fun l _ ↦ ?_
          rw [map_mul, mul_assoc]
          simp only [OkaRing.restrict_restrict]

/-- Oka's lemma at the origin for the translated row implies Oka's lemma at `x` for `f`.
This lets us assume that the point under consideration is the origin. -/
theorem OkaRowConclusion.of_shift
    (h : OkaRowConclusion (U.shift x) (fun i ↦ OkaRing.shift U x (f i)) 0) :
    OkaRowConclusion U f x := by
  obtain ⟨V', hV', k, g', h0V', hrel', hgen'⟩ := h
  obtain ⟨V, rfl⟩ : ∃ V, V.shift x = V' := ⟨V'.shift (-x), by simp [Opens.shift_shift]⟩
  have hV : V ≤ U := Opens.shift_le_shift_iff.mp hV'
  refine ⟨V, hV, k, fun l i ↦ (OkaRing.shift V x).symm (g' l i), by simpa using h0V',
    fun l ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · refine (OkaRing.shift V x).injective ?_
    simpa only [map_sum, map_mul, map_zero, AlgEquiv.apply_symm_apply, OkaRing.shift_restrict]
      using hrel' l
  · have ha' : ∑ i, OkaRing.shift W x (a i) *
        OkaRing.restrict ((Opens.shift_mono hWV).trans hV') (OkaRing.shift U x (f i)) = 0 := by
      simpa only [map_sum, map_mul, map_zero, OkaRing.shift_restrict] using
        congrArg (OkaRing.shift W x) ha
    obtain ⟨W'', hW'', hyW'', c', hc'⟩ :=
      hgen' (W.shift x) (Opens.shift_mono hWV) _ ha' (y - x) (by simpa using hy)
    obtain ⟨W', rfl⟩ : ∃ W', W'.shift x = W'' := ⟨W''.shift (-x), by simp [Opens.shift_shift]⟩
    refine ⟨W', Opens.shift_le_shift_iff.mp hW'', by simpa using hyW'',
      fun l ↦ (OkaRing.shift W' x).symm (c' l), fun i ↦ ?_⟩
    refine (OkaRing.shift W' x).injective ?_
    simpa only [map_sum, map_mul, AlgEquiv.apply_symm_apply, OkaRing.shift_restrict] using hc' i

/-- Oka's lemma for the row read in new linear coordinates implies Oka's lemma for the row
itself. This lets us choose the direction of the last coordinate axis. -/
theorem OkaRowConclusion.of_congr (φ : (Fin n → ℂ) ≃L[ℂ] (Fin n → ℂ))
    (h : OkaRowConclusion (φ.opensCongr U) (fun i ↦ OkaRing.congr φ U (f i)) (φ x)) :
    OkaRowConclusion U f x := by
  obtain ⟨V', hV', k, g', hxV', hrel', hgen'⟩ := h
  obtain ⟨V, rfl⟩ : ∃ V, φ.opensCongr V = V' :=
    ⟨φ.opensCongr.symm V', φ.opensCongr.apply_symm_apply V'⟩
  have hV : V ≤ U := φ.opensCongr.le_iff_le.mp hV'
  refine ⟨V, hV, k, fun l i ↦ (OkaRing.congr φ V).symm (g' l i), by simpa using hxV',
    fun l ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · refine (OkaRing.congr φ V).injective ?_
    simpa only [map_sum, map_mul, map_zero, AlgEquiv.apply_symm_apply, OkaRing.congr_restrict]
      using hrel' l
  · have ha' : ∑ i, OkaRing.congr φ W (a i) *
        OkaRing.restrict ((φ.opensCongr.monotone hWV).trans hV')
          (OkaRing.congr φ U (f i)) = 0 := by
      simpa only [map_sum, map_mul, map_zero, OkaRing.congr_restrict] using
        congrArg (OkaRing.congr φ W) ha
    obtain ⟨W'', hW'', hyW'', c', hc'⟩ :=
      hgen' (φ.opensCongr W) (φ.opensCongr.monotone hWV) _ ha' (φ y) (by simpa using hy)
    obtain ⟨W', rfl⟩ : ∃ W', φ.opensCongr W' = W'' :=
      ⟨φ.opensCongr.symm W'', φ.opensCongr.apply_symm_apply W''⟩
    refine ⟨W', φ.opensCongr.le_iff_le.mp hW'', by simpa using hyW'',
      fun l ↦ (OkaRing.congr φ W').symm (c' l), fun i ↦ ?_⟩
    refine (OkaRing.congr φ W').injective ?_
    simpa only [map_sum, map_mul, AlgEquiv.apply_symm_apply, OkaRing.congr_restrict] using hc' i

/-- A coordinate whose entry vanishes identically can be split off: Oka's lemma for the
remaining coordinates implies Oka's lemma for the whole row, the extra generator being the
standard basis vector at the removed coordinate. -/
theorem OkaRowConclusion.of_eq_zero {f : Fin (p + 1) → OkaRing U} (i₀ : Fin (p + 1))
    (h0 : f i₀ = 0) (h : OkaRowConclusion U (fun i ↦ f (i₀.succAbove i)) x) :
    OkaRowConclusion U f x := by
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := h
  refine ⟨V, hV, k + 1,
    Fin.cases (fun i ↦ if i = i₀ then 1 else 0) (fun l ↦ i₀.insertNth 0 (g l)), hxV,
    fun l ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · induction l using Fin.cases with
    | zero =>
      simp only [Fin.cases_zero, ite_mul, one_mul, zero_mul, Finset.sum_ite_eq',
        Finset.mem_univ, if_true, h0, map_zero]
    | succ l =>
      rw [Fin.sum_univ_succAbove _ i₀]
      simpa only [Fin.cases_succ, Fin.insertNth_apply_same, Fin.insertNth_apply_succAbove,
        zero_mul, zero_add] using hrel l
  · have ha' : ∑ j, a (i₀.succAbove j) *
        OkaRing.restrict (hWV.trans hV) (f (i₀.succAbove j)) = 0 := by
      rw [Fin.sum_univ_succAbove _ i₀] at ha
      simpa only [h0, map_zero, mul_zero, zero_add] using ha
    obtain ⟨W', hW', hyW', c, hc⟩ := hgen W hWV _ ha' y hy
    refine ⟨W', hW', hyW', Fin.cases (OkaRing.restrict hW' (a i₀)) c, fun i ↦ ?_⟩
    rw [Fin.sum_univ_succ]
    by_cases hi : i = i₀
    · subst hi
      simp
    · obtain ⟨j, rfl⟩ := Fin.exists_succAbove_eq hi
      simpa only [Fin.cases_zero, Fin.cases_succ, Fin.succAbove_ne, if_false,
        Fin.insertNth_apply_succAbove, map_zero, mul_zero, zero_add] using hc j

/-- Steps 3.1 and 3.2: the geometric input to the inductive step. Let `f` be a row of
holomorphic functions near the origin of `ℂ^{n+1}`, no entry of which vanishes identically near
the origin. Choosing a direction `v` outside the zero sets of the leading homogeneous terms of
the `f i` and making it the last coordinate direction, every `f i` becomes general in the last
variable; the Weierstrass preparation theorem then writes it, on a common neighbourhood `W` of
the origin contained in a cylinder over an open set `V ∋ 0` of `ℂ^n`, as a unit times a
Weierstrass polynomial in the last variable. -/
theorem exists_isWeierstrassPolynomial_row (U : Opens (Fin (n + 1) → ℂ)) (h0 : 0 ∈ U)
    (f : Fin p → OkaRing U)
    (hf : ∀ (i : Fin p) (W : Opens (Fin (n + 1) → ℂ)) (hWU : W ≤ U), 0 ∈ W →
      OkaRing.restrict hWU (f i) ≠ 0) :
    ∃ (φ : (Fin (n + 1) → ℂ) ≃L[ℂ] (Fin (n + 1) → ℂ)) (V : Opens (Fin n → ℂ))
      (W : Opens (Fin (n + 1) → ℂ)) (hWU : W ≤ φ.opensCongr U) (hWV : W ≤ V.extend')
      (Q : Fin p → (OkaRing V)[X]) (u : Fin p → OkaRing W),
      0 ∈ V ∧ 0 ∈ W ∧ (∀ i, IsWeierstrassPolynomial V (Q i)) ∧ (∀ i, IsUnit (u i)) ∧
        ∀ i, OkaRing.restrict hWU (OkaRing.congr φ U (f i)) =
          u i * OkaRing.restrict hWV (Polynomial.toOkaRing V (Q i)) := by
  classical
  -- Step 3.1: the germs at the origin do not vanish, so there is a direction `v`, transverse
  -- to the hyperplane of the first `n` coordinates, at which some homogeneous part of each
  -- germ is nonzero.
  have hgerm : ∀ i, OkaRing.germ h0 (f i) ≠ 0 := by
    intro i hzero
    obtain ⟨W, hWU, h0W, hres⟩ := OkaRing.exists_restrict_eq_zero h0 hzero
    exact hf i W hWU h0W hres
  have hcoe : ∀ i, ((OkaRing.germ h0 (f i) : LocalOkaRing (Fin (n + 1))) :
      MvPowerSeries (Fin (n + 1)) ℂ) ≠ 0 := fun i hc ↦ hgerm i (Subtype.ext hc)
  obtain ⟨v, hvlast, hv⟩ := MvPowerSeries.exists_direction
    (fun i ↦ ((OkaRing.germ h0 (f i) : LocalOkaRing (Fin (n + 1))) :
      MvPowerSeries (Fin (n + 1)) ℂ)) hcoe
  set φ : (Fin (n + 1) → ℂ) ≃L[ℂ] (Fin (n + 1) → ℂ) := lineEquiv v hvlast with hφ
  have h0U' : (0 : Fin (n + 1) → ℂ) ∈ φ.opensCongr U := by
    have h1 : φ 0 ∈ φ.opensCongr U := by simp [h0]
    rwa [map_zero] at h1
  set g : Fin p → OkaRing (φ.opensCongr U) := fun i ↦ OkaRing.congr φ U (f i) with hgdef
  -- Step 3.2: in the new coordinates every germ is general in the last variable.
  have hgen : ∀ i, ((OkaRing.germ h0U' (g i) : LocalOkaRing (Fin (n + 1))) :
      MvPowerSeries (Fin (n + 1)) ℂ).IsGeneralIn (Fin.last n) := by
    intro i hpe
    have hax := (OkaRing.germ_represents h0U' (g i)).eventually_axis_eq_zero (Fin.last n) hpe
    have hopen : ∀ᶠ t : ℂ in nhds 0,
        t • Pi.single (Fin.last n) (1 : ℂ) ∈ φ.opensCongr U := by
      have hcont : Continuous fun t : ℂ ↦ t • Pi.single (Fin.last n) (1 : ℂ) :=
        continuous_id.smul continuous_const
      have htend := hcont.tendsto 0
      rw [zero_smul] at htend
      exact htend.eventually ((φ.opensCongr U).isOpen.mem_nhds h0U')
    -- the vanishing along the last axis transports to vanishing of `f i` along `v`
    have hline : ∀ᶠ t : ℂ in nhds 0,
        (fun z ↦ (f i).toGlobalFun _ (z + 0)) (t • v) = 0 := by
      filter_upwards [hax, hopen] with t ht hmem
      have h2 : (g i).toGlobalFun _ (t • Pi.single (Fin.last n) (1 : ℂ) + 0) = 0 := ht
      rw [add_zero, (g i).toGlobalFun_apply hmem] at h2
      have hmemU : φ.symm (t • Pi.single (Fin.last n) (1 : ℂ)) ∈ U := hmem
      have h3 : (g i).toFun _ ⟨t • Pi.single (Fin.last n) (1 : ℂ), hmem⟩ =
          (f i).toGlobalFun _ (φ.symm (t • Pi.single (Fin.last n) (1 : ℂ))) := by
        rw [(f i).toGlobalFun_apply hmemU]
        rfl
      rw [h3] at h2
      have h4 : φ.symm (t • Pi.single (Fin.last n) (1 : ℂ)) = t • v :=
        lineEquiv_symm_smul_single v hvlast t
      rw [h4] at h2
      change (f i).toGlobalFun _ (t • v + 0) = 0
      rwa [add_zero]
    have hcontra := (OkaRing.germ_represents h0 (f i)).homogeneous_eval_eq_zero v hline
    obtain ⟨kk, hkk⟩ := hv i
    exact hkk (hcontra kk)
  -- apply the local Weierstrass preparation theorem to each germ
  choose uu huu gpoly hgpolyW hfac using fun i ↦
    localweierstrass_preparation (OkaRing.germ h0U' (g i)) (hgen i)
  -- realize the local Weierstrass polynomials near the origin of `ℂ^n`
  choose V₀ h0V₀ Q₀ hQmap hQW using fun i ↦
    LocalOkaRing.exists_isWeierstrassPolynomial_realize (hgpolyW i)
  set V : Opens (Fin n → ℂ) := Finset.univ.inf V₀ with hVdef
  have h0V : (0 : Fin n → ℂ) ∈ V := Opens.mem_finset_inf.mpr fun i _ ↦ h0V₀ i
  have hVle : ∀ i, V ≤ V₀ i := fun i ↦ Finset.inf_le (Finset.mem_univ i)
  set Q : Fin p → (OkaRing V)[X] :=
    fun i ↦ (Q₀ i).map (OkaRing.restrict (hVle i)).toRingHom with hQdef
  have hQWeier : ∀ i, IsWeierstrassPolynomial V (Q i) := fun i ↦
    (hQW i).map_restrict (hVle i) h0V
  have h0Ve : (0 : Fin (n + 1) → ℂ) ∈ V.extend' := Opens.zero_mem_extend'.mpr h0V
  -- the germ of the function attached to `Q i` is the germ Weierstrass polynomial
  have hgermQ : ∀ i, OkaRing.germ h0Ve (Polynomial.toOkaRing V (Q i)) =
      LocalOkaRing.fromPolynomial (gpoly i) := by
    intro i
    rw [OkaRing.germ_toOkaRing h0Ve (Q i)]
    congr 1
    have e2 : OkaRing.germPoly (Opens.mem_extend'.mp h0Ve)
        ((0 : Fin (n + 1) → ℂ) (Fin.last n)) (Q i) =
        (Q i).map (OkaRing.germ (Opens.mem_extend'.mp h0Ve)).toRingHom :=
      OkaRing.germPoly_zero _ (Q i)
    rw [e2]
    simp only [hQdef]
    rw [Polynomial.map_map]
    have hcomp : (OkaRing.germ (Opens.mem_extend'.mp h0Ve)).toRingHom.comp
        (OkaRing.restrict (hVle i)).toRingHom = (OkaRing.germ (h0V₀ i)).toRingHom :=
      RingHom.ext fun a ↦ OkaRing.germ_restrict (hVle i) (Opens.mem_extend'.mp h0Ve) a
    rw [hcomp]
    exact hQmap i
  -- realize the units near the origin
  choose Wu h0Wu uf huf using fun i ↦
    LocalOkaRing.exists_okaRing_germ (uu i) (0 : Fin (n + 1) → ℂ)
  have hufunit : ∀ i, IsUnit (OkaRing.germ (h0Wu i) (uf i)) := fun i ↦ by
    rw [huf i]
    exact huu i
  choose Wu' hWu'le h0Wu' huu' using fun i ↦
    OkaRing.exists_isUnit_restrict (h0Wu i) (hufunit i)
  -- assemble a common neighbourhood of the origin
  set W₁ : Opens (Fin (n + 1) → ℂ) :=
    (φ.opensCongr U ⊓ V.extend') ⊓ Finset.univ.inf Wu' with hW₁def
  have h0W₁ : (0 : Fin (n + 1) → ℂ) ∈ W₁ :=
    ⟨⟨h0U', h0Ve⟩, Opens.mem_finset_inf.mpr fun i _ ↦ h0Wu' i⟩
  have hW₁U' : W₁ ≤ φ.opensCongr U := le_trans inf_le_left inf_le_left
  have hW₁V : W₁ ≤ V.extend' := le_trans inf_le_left inf_le_right
  have hW₁u : ∀ i, W₁ ≤ Wu' i := fun i ↦
    le_trans inf_le_right (Finset.inf_le (Finset.mem_univ i))
  -- the two factorizations have the same germ at the origin
  have hgermeq : ∀ i, OkaRing.germ h0W₁ (OkaRing.restrict hW₁U' (g i)) =
      OkaRing.germ h0W₁
        (OkaRing.restrict (hW₁u i) (OkaRing.restrict (hWu'le i) (uf i)) *
          OkaRing.restrict hW₁V (Polynomial.toOkaRing V (Q i))) := by
    intro i
    calc OkaRing.germ h0W₁ (OkaRing.restrict hW₁U' (g i))
        = OkaRing.germ h0U' (g i) := OkaRing.germ_restrict _ _ _
      _ = LocalOkaRing.fromPolynomial (gpoly i) * uu i := hfac i
      _ = uu i * LocalOkaRing.fromPolynomial (gpoly i) := mul_comm _ _
      _ = OkaRing.germ h0W₁
            (OkaRing.restrict (hW₁u i) (OkaRing.restrict (hWu'le i) (uf i))) *
          OkaRing.germ h0W₁ (OkaRing.restrict hW₁V (Polynomial.toOkaRing V (Q i))) := by
          rw [OkaRing.germ_restrict, OkaRing.germ_restrict, OkaRing.germ_restrict]
          congr 1
          · exact (huf i).symm
          · exact (hgermQ i).symm
      _ = OkaRing.germ h0W₁
            (OkaRing.restrict (hW₁u i) (OkaRing.restrict (hWu'le i) (uf i)) *
              OkaRing.restrict hW₁V (Polynomial.toOkaRing V (Q i))) :=
          (map_mul _ _ _).symm
  -- the factorizations agree near the origin
  choose W₂ hW₂le h0W₂ hres using fun i ↦
    OkaRing.exists_restrict_eq_of_germ_eq h0W₁ (hgermeq i)
  set W : Opens (Fin (n + 1) → ℂ) := W₁ ⊓ Finset.univ.inf W₂ with hWdef
  have h0W : (0 : Fin (n + 1) → ℂ) ∈ W :=
    ⟨h0W₁, Opens.mem_finset_inf.mpr fun i _ ↦ h0W₂ i⟩
  have hWW₂ : ∀ i, W ≤ W₂ i := fun i ↦
    le_trans inf_le_right (Finset.inf_le (Finset.mem_univ i))
  have hWU' : W ≤ φ.opensCongr U := le_trans inf_le_left hW₁U'
  have hWV : W ≤ V.extend' := le_trans inf_le_left hW₁V
  refine ⟨φ, V, W, hWU', hWV, Q,
    fun i ↦ OkaRing.restrict (le_trans inf_le_left (hW₁u i))
      (OkaRing.restrict (hWu'le i) (uf i)),
    h0V, h0W, hQWeier, fun i ↦ (huu' i).map _, fun i ↦ ?_⟩
  have h5 := congrArg (OkaRing.restrict (hWW₂ i)) (hres i)
  simp only [OkaRing.restrict_restrict, map_mul] at h5
  exact h5

/-- The coefficients of `∑ j < d, C (a j) * X ^ j`. -/
private lemma coeff_sum_C_mul_X_pow {R : Type*} [CommRing R] {d : ℕ} (aa : Fin d → R)
    (kk : ℕ) :
    (∑ j : Fin d, Polynomial.C (aa j) * Polynomial.X ^ (j : ℕ)).coeff kk =
      if h : kk < d then aa ⟨kk, h⟩ else 0 := by
  rw [Polynomial.finsetSum_coeff]
  have h1 : ∀ j : Fin d, (Polynomial.C (aa j) * Polynomial.X ^ (j : ℕ)).coeff kk =
      if kk = (j : ℕ) then aa j else 0 := fun j ↦ by
    rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow, mul_ite, mul_one, mul_zero]
  rw [Finset.sum_congr rfl fun j _ ↦ h1 j]
  by_cases h : kk < d
  · rw [dif_pos h]
    rw [Finset.sum_eq_single (⟨kk, h⟩ : Fin d)]
    · rw [if_pos rfl]
    · intro j _ hj
      exact if_neg fun hc ↦ hj (Fin.ext hc.symm)
    · intro hc
      exact absurd (Finset.mem_univ _) hc
  · rw [dif_neg h]
    refine Finset.sum_eq_zero fun j _ ↦ if_neg fun hc : kk = (j : ℕ) ↦ h (hc ▸ j.2)

/-- A polynomial of degree `< d` is the sum of its `d` lowest monomials. -/
private lemma sum_C_coeff_mul_X_pow {R : Type*} [CommRing R] {d : ℕ} {P : R[X]}
    (hP : P.natDegree < d) :
    ∑ j : Fin d, Polynomial.C (P.coeff (j : ℕ)) * Polynomial.X ^ (j : ℕ) = P := by
  refine Polynomial.ext fun kk ↦ ?_
  rw [coeff_sum_C_mul_X_pow (fun j : Fin d ↦ P.coeff (j : ℕ)) kk]
  by_cases h : kk < d
  · rw [dif_pos h]
  · rw [dif_neg h]
    exact (Polynomial.coeff_eq_zero_of_natDegree_lt (by omega)).symm

/-- Reading off coefficients: for polynomial tuples of degree `< d`, the polynomial relation
`∑ i, P i * Q i = 0` is equivalent to the vanishing of the `2 * d` coefficient rows of the
associated linear system. -/
private lemma sum_C_mul_X_pow_mul_eq_zero_iff {n : ℕ} {V : Opens (Fin n → ℂ)} {p d : ℕ}
    (Q : Fin p → (OkaRing V)[X]) (hQd : ∀ i, (Q i).natDegree < d)
    {S : Type*} [CommRing S] (ψ : OkaRing V →+* S) (a : Fin (p * d) → S) :
    (∀ j : Fin (2 * d), ∑ c, a c *
        ψ ((Q (finProdFinEquiv.symm c).1 *
          Polynomial.X ^ ((finProdFinEquiv.symm c).2 : ℕ)).coeff j) = 0) ↔
      ∑ i, (∑ j : Fin d, Polynomial.C (a (finProdFinEquiv (i, j))) * Polynomial.X ^ (j : ℕ)) *
        ((Q i).map ψ) = 0 := by
  classical
  have hcoeff : ∀ kk : ℕ,
      (∑ i, (∑ j : Fin d, Polynomial.C (a (finProdFinEquiv (i, j))) *
        Polynomial.X ^ (j : ℕ)) * ((Q i).map ψ)).coeff kk =
      ∑ c, a c * ψ ((Q (finProdFinEquiv.symm c).1 *
        Polynomial.X ^ ((finProdFinEquiv.symm c).2 : ℕ)).coeff kk) := by
    intro kk
    rw [Polynomial.finsetSum_coeff]
    have h1 : ∀ i, ((∑ j : Fin d, Polynomial.C (a (finProdFinEquiv (i, j))) *
        Polynomial.X ^ (j : ℕ)) * ((Q i).map ψ)).coeff kk =
        ∑ j : Fin d, a (finProdFinEquiv (i, j)) *
          ψ ((Q i * Polynomial.X ^ (j : ℕ)).coeff kk) := by
      intro i
      rw [Finset.sum_mul, Polynomial.finsetSum_coeff]
      refine Finset.sum_congr rfl fun j _ ↦ ?_
      rw [mul_assoc, Polynomial.coeff_C_mul]
      congr 1
      rw [show Polynomial.X ^ (j : ℕ) * (Q i).map ψ = (Q i * Polynomial.X ^ (j : ℕ)).map ψ by
        rw [Polynomial.map_mul, Polynomial.map_pow, Polynomial.map_X, mul_comm]]
      rw [Polynomial.coeff_map]
    rw [Finset.sum_congr rfl fun i _ ↦ h1 i, ← Finset.sum_product',
      Finset.univ_product_univ]
    exact Fintype.sum_equiv finProdFinEquiv _ _ fun ij ↦ by simp
  constructor
  · intro h
    refine Polynomial.ext fun kk ↦ ?_
    rw [Polynomial.coeff_zero, hcoeff]
    by_cases hkk : kk < 2 * d
    · exact h ⟨kk, hkk⟩
    · refine Finset.sum_eq_zero fun c _ ↦ ?_
      have hdeg : (Q (finProdFinEquiv.symm c).1 *
          Polynomial.X ^ ((finProdFinEquiv.symm c).2 : ℕ)).natDegree < 2 * d := by
        refine lt_of_le_of_lt Polynomial.natDegree_mul_le ?_
        have h2 := hQd (finProdFinEquiv.symm c).1
        have h3 : (Polynomial.X ^ ((finProdFinEquiv.symm c).2 : ℕ) :
            (OkaRing V)[X]).natDegree ≤ ((finProdFinEquiv.symm c).2 : ℕ) :=
          Polynomial.natDegree_X_pow_le _
        have h4 : ((finProdFinEquiv.symm c).2 : ℕ) < d := (finProdFinEquiv.symm c).2.2
        omega
      rw [Polynomial.coeff_eq_zero_of_natDegree_lt (lt_of_lt_of_le hdeg (by omega)),
        map_zero, mul_zero]
  · intro h j
    rw [← hcoeff, h, Polynomial.coeff_zero]

/-- Step 3.3: Oka's coherence lemma for a row of Weierstrass polynomials in the last variable,
over a base open set `V` of `ℂ^n`.

This is where the induction hypothesis in dimension `n` and Oka's bounded degree lemma enter.
After shrinking to a polydisc `V × D_r` and choosing `d` larger than all the degrees of the
`Q i` and `m ≥ 3 * d`, the relations of degree `< m` between the `Q i` form the kernel of the
map `E_m^p → E_{m + d}`, `P ↦ ∑ i, Q i * P i`, between the modules of polynomials of bounded
degree. Reading off coefficients turns this into a holomorphic matrix `𝒪(V)^{m * p} → 𝒪(V)^{m
+ d}` on the `n`-dimensional base, so the induction hypothesis provides finitely many
polynomial vectors generating its kernel in every stalk; by `oka_lemma`, applied in the germs
at a point of `V × D_r`, these generate all relations between the `Q i`. -/
theorem okaRowConclusion_toOkaRing (hn : ∀ q, OkaStatement q n) (V : Opens (Fin n → ℂ))
    (Q : Fin p → (OkaRing V)[X]) (hQ : ∀ i, IsWeierstrassPolynomial V (Q i))
    (x : Fin (n + 1) → ℂ) (hx : x ∈ V.extend') :
    OkaRowConclusion V.extend' (fun i ↦ Polynomial.toOkaRing V (Q i)) x := by
  classical
  -- the degree bound and the coefficient matrix
  set d : ℕ := (Finset.univ.sup fun i ↦ (Q i).natDegree) + 1 with hddef
  have hd0 : 0 < d := Nat.succ_pos _
  have hQd : ∀ i, (Q i).natDegree < d := fun i ↦
    Nat.lt_succ_of_le (Finset.le_sup (f := fun i ↦ (Q i).natDegree) (Finset.mem_univ i))
  set M : Fin (p * d) → Fin (2 * d) → OkaRing V := fun c j ↦
    (Q (finProdFinEquiv.symm c).1 *
      Polynomial.X ^ ((finProdFinEquiv.symm c).2 : ℕ)).coeff j with hMdef
  -- Step 1: the induction hypothesis applied to the coefficient matrix at the base point
  obtain ⟨V₁, hV₁, k, g, hxV₁, hgrel, hggen⟩ :=
    hn (2 * d) V M (Fin.init x) (Opens.mem_extend'.mp hx)
  -- the generators, as polynomial vectors and as functions on the cylinder
  set G : Fin k → Fin p → (OkaRing V₁)[X] := fun l i ↦
    ∑ j : Fin d, Polynomial.C (g l (finProdFinEquiv (i, j))) * Polynomial.X ^ (j : ℕ)
    with hGdef
  have hGpoly : ∀ l, ∑ i, G l i * ((Q i).map (OkaRing.restrict hV₁).toRingHom) = 0 :=
    fun l ↦ (sum_C_mul_X_pow_mul_eq_zero_iff Q hQd (OkaRing.restrict hV₁).toRingHom
      (g l)).mp (hgrel l)
  refine ⟨V₁.extend', Opens.extend'_mono hV₁, k,
    fun l i ↦ Polynomial.toOkaRing V₁ (G l i), Opens.mem_extend'.mpr hxV₁, fun l ↦ ?_,
    fun W hW a ha y hy ↦ ?_⟩
  · -- the generators are relations
    calc ∑ i, Polynomial.toOkaRing V₁ (G l i) *
          OkaRing.restrict (Opens.extend'_mono hV₁) (Polynomial.toOkaRing V (Q i))
        = Polynomial.toOkaRing V₁
            (∑ i, G l i * ((Q i).map (OkaRing.restrict hV₁).toRingHom)) := by
          rw [map_sum]
          refine Finset.sum_congr rfl fun i _ ↦ ?_
          rw [map_mul, Polynomial.toOkaRing_map_restrict]
      _ = 0 := by rw [hGpoly l, map_zero]
  · -- generation at a point `y` of `W ≤ V₁.extend'`
    have hyV₁e : y ∈ V₁.extend' := hW hy
    have hy'V₁ : Fin.init y ∈ V₁ := Opens.mem_extend'.mp hyV₁e
    have hy'V : Fin.init y ∈ V := hV₁ hy'V₁
    have hyVe : y ∈ V.extend' := Opens.extend'_mono hV₁ hyV₁e
    -- the germ Weierstrass polynomials at `y`
    set Fp : Fin p → (LocalOkaRing (Fin n))[X] := fun i ↦
      OkaRing.germPoly hy'V (y (Fin.last n)) (Q i) with hFpdef
    have hFpmonic : ∀ i, (Fp i).Monic := fun i ↦
      OkaRing.monic_germPoly hy'V (y (Fin.last n)) (hQ i).monic
    have hFpdeg : ∀ i, (Fp i).degree < (d : WithBot ℕ) := fun i ↦
      lt_of_le_of_lt Polynomial.degree_le_natDegree (by
        exact_mod_cast lt_of_le_of_lt (OkaRing.natDegree_germPoly_le hy'V _ (Q i)) (hQd i))
    set F : Fin p → (Polynomial.degreeLT (LocalOkaRing (Fin n)) d) := fun i ↦
      ⟨Fp i, Polynomial.mem_degreeLT.mpr (hFpdeg i)⟩ with hFdef
    have hoka := oka_lemma p d F fun j ↦ hFpmonic j
    -- the germs of the given relation lie in the kernel
    have hF'eq : ∀ j, polyIncl (F j) =
        OkaRing.germ hyVe (Polynomial.toOkaRing V (Q j)) := by
      intro j
      rw [OkaRing.germ_toOkaRing hyVe (Q j)]
      rfl
    have hker : (fun i ↦ OkaRing.germ hy (a i)) ∈
        LinearMap.ker (linOfFun fun j ↦ polyIncl (F j)) := by
      rw [LinearMap.mem_ker, Module.Basis.constr_apply_fintype]
      simp only [Pi.basisFun_equivFun, LinearEquiv.refl_apply, smul_eq_mul]
      have hterm : ∀ i, OkaRing.germ hy (a i) * polyIncl (F i) =
          OkaRing.germ hy (a i * OkaRing.restrict (hW.trans (Opens.extend'_mono hV₁))
            (Polynomial.toOkaRing V (Q i))) := by
        intro i
        rw [map_mul, hF'eq i, OkaRing.germ_restrict]
      rw [Finset.sum_congr rfl fun i _ ↦ hterm i, ← map_sum, ha, map_zero]
    rw [hoka] at hker
    obtain ⟨T, cg, κs, hsum⟩ := Submodule.mem_span_set'.mp hker
    choose κ hκK hκval using fun t ↦ Submodule.mem_map.mp (κs t).2
    -- realize the coefficients of the `κ t` near the base point of `y`
    choose V₂ hy'V₂ R hRgerm hRdeg using fun (t : Fin T) (i : Fin p) ↦
      LocalOkaRing.exists_poly_germPoly ((κ t i : Polynomial.degreeLT _ d) :
        (LocalOkaRing (Fin n))[X]) (Fin.init y) (y (Fin.last n))
    set V₃ : Opens (Fin n → ℂ) :=
      V₁ ⊓ Finset.univ.inf (fun ti : Fin T × Fin p ↦ V₂ ti.1 ti.2) with hV₃def
    have hy'V₃ : Fin.init y ∈ V₃ :=
      ⟨hy'V₁, Opens.mem_finset_inf.mpr fun ti _ ↦ hy'V₂ ti.1 ti.2⟩
    have hV₃V₁ : V₃ ≤ V₁ := inf_le_left
    have hV₃V₂ : ∀ t i, V₃ ≤ V₂ t i := fun t i ↦
      le_trans inf_le_right (Finset.inf_le (Finset.mem_univ (t, i)))
    have hyV₃e : y ∈ V₃.extend' := Opens.mem_extend'.mpr hy'V₃
    set R' : Fin T → Fin p → (OkaRing V₃)[X] := fun t i ↦
      (R t i).map (OkaRing.restrict (hV₃V₂ t i)).toRingHom with hR'def
    have hR'germ : ∀ t i, OkaRing.germPoly hy'V₃ (y (Fin.last n)) (R' t i) =
        ((κ t i : Polynomial.degreeLT _ d) : (LocalOkaRing (Fin n))[X]) := by
      intro t i
      rw [hR'def]
      simp only
      rw [OkaRing.germPoly_map_restrict (hV₃V₂ t i) hy'V₃]
      exact hRgerm t i
    have hR'deg : ∀ t i, (R' t i).natDegree < d := by
      intro t i
      refine lt_of_le_of_lt Polynomial.natDegree_map_le ?_
      refine lt_of_le_of_lt (hRdeg t i) ?_
      exact Polynomial.natDegree_lt_of_mem_degreeLT hd0 (κ t i).2
    -- the realized relations vanish near `y` as functions on the cylinder
    set S : Fin T → (OkaRing V₃)[X] := fun t ↦
      ∑ i, R' t i * ((Q i).map (OkaRing.restrict (hV₃V₁.trans hV₁)).toRingHom) with hSdef
    have hSgerm : ∀ t, OkaRing.germ hyV₃e (Polynomial.toOkaRing V₃ (S t)) = 0 := by
      intro t
      rw [hSdef]
      simp only
      rw [map_sum, map_sum]
      have hterm : ∀ i, OkaRing.germ hyV₃e (Polynomial.toOkaRing V₃
          (R' t i * ((Q i).map (OkaRing.restrict (hV₃V₁.trans hV₁)).toRingHom))) =
          polyIncl (κ t i) * polyIncl (F i) := by
        intro i
        rw [map_mul, map_mul]
        congr 1
        · rw [OkaRing.germ_toOkaRing hyV₃e (R' t i)]
          have h6 : OkaRing.germPoly (Opens.mem_extend'.mp hyV₃e) (y (Fin.last n)) (R' t i) =
              ((κ t i : Polynomial.degreeLT _ d) : (LocalOkaRing (Fin n))[X]) := hR'germ t i
          rw [h6]
          rfl
        · rw [Polynomial.toOkaRing_map_restrict, OkaRing.germ_restrict, hF'eq i]
      rw [Finset.sum_congr rfl fun i _ ↦ hterm i]
      -- the sum vanishes since `κ t` is a relation between the `F i`
      have h7 := hκK t
      simp only [K_deg, LinearMap.mem_ker, LinearMap.coe_comp,
        LinearMap.coe_restrictScalars, Function.comp_apply,
        Module.Basis.constr_apply_fintype, Pi.basisFun_equivFun, LinearEquiv.refl_apply,
        smul_eq_mul] at h7
      exact h7
    -- localize and slice: the coefficients of `S t` vanish near the base point
    have hslice : ∀ t, ∃ (V₄ : Opens (Fin n → ℂ)) (hle : V₄ ≤ V₃), Fin.init y ∈ V₄ ∧
        (S t).map (OkaRing.restrict hle).toRingHom = 0 := by
      intro t
      obtain ⟨W₄, hW₄le, hyW₄, hW₄zero⟩ :=
        OkaRing.exists_restrict_eq_zero hyV₃e (hSgerm t)
      exact Polynomial.exists_map_restrict_eq_zero (S t) hW₄le hyW₄ hW₄zero
    choose V₄ hV₄le hy'V₄ hSzero using hslice
    set V₅ : Opens (Fin n → ℂ) := V₃ ⊓ Finset.univ.inf V₄ with hV₅def
    have hy'V₅ : Fin.init y ∈ V₅ :=
      ⟨hy'V₃, Opens.mem_finset_inf.mpr fun t _ ↦ hy'V₄ t⟩
    have hV₅V₄ : ∀ t, V₅ ≤ V₄ t := fun t ↦
      le_trans inf_le_right (Finset.inf_le (Finset.mem_univ t))
    have hV₅V₃ : V₅ ≤ V₃ := inf_le_left
    have hV₅V₁ : V₅ ≤ V₁ := hV₅V₃.trans hV₃V₁
    -- the coefficient tuples of the realized relations
    set b : Fin T → Fin (p * d) → OkaRing V₅ := fun t c ↦
      OkaRing.restrict hV₅V₃ ((R' t (finProdFinEquiv.symm c).1).coeff
        ((finProdFinEquiv.symm c).2 : ℕ)) with hbdef
    have hSzero' : ∀ t, ∑ i, ((R' t i).map (OkaRing.restrict hV₅V₃).toRingHom) *
        ((Q i).map (OkaRing.restrict (hV₅V₁.trans hV₁)).toRingHom) = 0 := by
      intro t
      have h9 : (S t).map ((OkaRing.restrict (hV₅V₄ t)).toRingHom.comp
          (OkaRing.restrict (hV₄le t)).toRingHom) = 0 := by
        rw [← Polynomial.map_map, hSzero t, Polynomial.map_zero]
      have h10 : (OkaRing.restrict (hV₅V₄ t)).toRingHom.comp
          (OkaRing.restrict (hV₄le t)).toRingHom = (OkaRing.restrict hV₅V₃).toRingHom :=
        RingHom.ext fun aa ↦ rfl
      rw [h10] at h9
      calc ∑ i, ((R' t i).map (OkaRing.restrict hV₅V₃).toRingHom) *
            ((Q i).map (OkaRing.restrict (hV₅V₁.trans hV₁)).toRingHom)
          = (S t).map (OkaRing.restrict hV₅V₃).toRingHom := by
            rw [hSdef]
            simp only
            rw [Polynomial.map_sum]
            refine Finset.sum_congr rfl fun i _ ↦ ?_
            have hcomp2 : (OkaRing.restrict hV₅V₃).toRingHom.comp
                (OkaRing.restrict (hV₃V₁.trans hV₁)).toRingHom =
                (OkaRing.restrict (hV₅V₁.trans hV₁)).toRingHom :=
              RingHom.ext fun aa ↦ rfl
            rw [Polynomial.map_mul]
            congr 1
            rw [Polynomial.map_map, hcomp2]
        _ = 0 := h9
    -- the coefficient rows of the realized relations are relations of the matrix
    have hrows : ∀ t (j : Fin (2 * d)),
        ∑ c, b t c * OkaRing.restrict (hV₅V₁.trans hV₁) (M c j) = 0 := by
      intro t
      refine (sum_C_mul_X_pow_mul_eq_zero_iff Q hQd
        (OkaRing.restrict (hV₅V₁.trans hV₁)).toRingHom (b t)).mpr ?_
      have hrecon : ∀ i, (∑ j : Fin d, Polynomial.C (b t (finProdFinEquiv (i, j))) *
          Polynomial.X ^ (j : ℕ)) = (R' t i).map (OkaRing.restrict hV₅V₃).toRingHom := by
        intro i
        have hb : ∀ j : Fin d, b t (finProdFinEquiv (i, j)) =
            ((R' t i).map (OkaRing.restrict hV₅V₃).toRingHom).coeff (j : ℕ) := by
          intro j
          have hsymm : finProdFinEquiv.symm (finProdFinEquiv (i, j)) = (i, j) :=
            Equiv.symm_apply_apply _ _
          simp only [hbdef, hsymm, Polynomial.coeff_map]
          rfl
        rw [Finset.sum_congr rfl fun j _ ↦ by rw [hb j]]
        exact sum_C_coeff_mul_X_pow
          (lt_of_le_of_lt Polynomial.natDegree_map_le (hR'deg t i))
      rw [Finset.sum_congr rfl fun i _ ↦ by rw [hrecon i]]
      exact hSzero' t
    -- apply the induction hypothesis at the base point of `y`
    choose W₅ hW₅le hy'W₅ c' hc' using fun t ↦
      hggen V₅ hV₅V₁ (b t) (hrows t) (Fin.init y) hy'V₅
    -- the realized relations are combinations of the generators, as polynomials
    have hpoly : ∀ t i, (R' t i).map (OkaRing.restrict ((hW₅le t).trans hV₅V₃)).toRingHom =
        ∑ l, Polynomial.C (c' t l) *
          (G l i).map (OkaRing.restrict ((hW₅le t).trans hV₅V₁)).toRingHom := by
      intro t i
      refine Polynomial.ext fun kk ↦ ?_
      rw [Polynomial.coeff_map, Polynomial.finsetSum_coeff]
      have hRr : ∀ l, (Polynomial.C (c' t l) *
          (G l i).map (OkaRing.restrict ((hW₅le t).trans hV₅V₁)).toRingHom).coeff kk =
          c' t l * OkaRing.restrict ((hW₅le t).trans hV₅V₁) ((G l i).coeff kk) := by
        intro l
        rw [Polynomial.coeff_C_mul, Polynomial.coeff_map]
        rfl
      rw [Finset.sum_congr rfl fun l _ ↦ hRr l]
      by_cases hkk : kk < d
      · have hGc : ∀ l, (G l i).coeff kk = g l (finProdFinEquiv (i, ⟨kk, hkk⟩)) := by
          intro l
          simp only [hGdef]
          rw [coeff_sum_C_mul_X_pow, dif_pos hkk]
        have hRc : (OkaRing.restrict ((hW₅le t).trans hV₅V₃)).toRingHom
            ((R' t i).coeff kk) =
            OkaRing.restrict (hW₅le t) (b t (finProdFinEquiv (i, ⟨kk, hkk⟩))) := by
          have hsymm : finProdFinEquiv.symm (finProdFinEquiv (i, (⟨kk, hkk⟩ : Fin d))) =
              (i, ⟨kk, hkk⟩) := Equiv.symm_apply_apply _ _
          simp only [hbdef, hsymm]
          rfl
        rw [hRc, hc' t (finProdFinEquiv (i, ⟨kk, hkk⟩))]
        refine Finset.sum_congr rfl fun l _ ↦ ?_
        rw [hGc l]
      · have hR0 : (R' t i).coeff kk = 0 :=
          Polynomial.coeff_eq_zero_of_natDegree_lt (by have := hR'deg t i; omega)
        have hG0 : ∀ l, (G l i).coeff kk = 0 := by
          intro l
          simp only [hGdef]
          rw [coeff_sum_C_mul_X_pow, dif_neg hkk]
        rw [hR0, map_zero]
        refine (Finset.sum_eq_zero fun l _ ↦ ?_).symm
        rw [hG0 l, map_zero, mul_zero]
    have hyW₅e : ∀ t, y ∈ (W₅ t).extend' := fun t ↦ Opens.mem_extend'.mpr (hy'W₅ t)
    -- expand the germ of each `κ` in the generators
    have hκexpand : ∀ t i, polyIncl (κ t i) =
        ∑ l, OkaRing.germ (hyW₅e t) (OkaRing.pullbackInit (W₅ t) (c' t l)) *
          OkaRing.germ hyV₁e (Polynomial.toOkaRing V₁ (G l i)) := by
      intro t i
      have h11 : polyIncl (κ t i) =
          OkaRing.germ hyV₃e (Polynomial.toOkaRing V₃ (R' t i)) := by
        rw [OkaRing.germ_toOkaRing hyV₃e (R' t i)]
        have h12 : OkaRing.germPoly (Opens.mem_extend'.mp hyV₃e) (y (Fin.last n)) (R' t i) =
            ((κ t i : Polynomial.degreeLT (LocalOkaRing (Fin n)) d) :
              (LocalOkaRing (Fin n))[X]) := hR'germ t i
        rw [h12]
        rfl
      have h13 : OkaRing.germ hyV₃e (Polynomial.toOkaRing V₃ (R' t i)) =
          OkaRing.germ (hyW₅e t) (Polynomial.toOkaRing (W₅ t)
            ((R' t i).map (OkaRing.restrict ((hW₅le t).trans hV₅V₃)).toRingHom)) := by
        rw [Polynomial.toOkaRing_map_restrict ((hW₅le t).trans hV₅V₃) (R' t i),
          OkaRing.germ_restrict]
      rw [h11, h13, hpoly t i, map_sum, map_sum]
      refine Finset.sum_congr rfl fun l _ ↦ ?_
      rw [map_mul, map_mul, Polynomial.toOkaRing_C, Polynomial.toOkaRing_map_restrict,
        OkaRing.germ_restrict]
    -- the germ of the relation `a` in the generators
    have hEsum : ∀ i, OkaRing.germ hy (a i) =
        ∑ l, (∑ t, cg t * OkaRing.germ (hyW₅e t) (OkaRing.pullbackInit (W₅ t) (c' t l))) *
          OkaRing.germ hyV₁e (Polynomial.toOkaRing V₁ (G l i)) := by
      intro i
      have h14 := congrFun hsum i
      rw [Finset.sum_apply] at h14
      have h15 : ∀ t, (cg t • (κs t : Fin p → LocalOkaRing (Fin (n + 1)))) i =
          cg t * polyIncl (κ t i) := by
        intro t
        rw [Pi.smul_apply, smul_eq_mul]
        congr 1
        rw [← hκval t]
        rfl
      rw [← h14, Finset.sum_congr rfl fun t _ ↦ h15 t,
        Finset.sum_congr rfl fun t _ ↦ by rw [hκexpand t i, Finset.mul_sum],
        Finset.sum_comm]
      refine Finset.sum_congr rfl fun l _ ↦ ?_
      rw [Finset.sum_mul]
      refine Finset.sum_congr rfl fun t _ ↦ ?_
      ring
    -- realize the coefficients near `y`
    choose O hyO CC hCC using fun l : Fin k ↦
      LocalOkaRing.exists_okaRing_germ
        (∑ t, cg t * OkaRing.germ (hyW₅e t) (OkaRing.pullbackInit (W₅ t) (c' t l))) y
    set W'' : Opens (Fin (n + 1) → ℂ) := W ⊓ Finset.univ.inf O with hW''def
    have hyW'' : y ∈ W'' := ⟨hy, Opens.mem_finset_inf.mpr fun l _ ↦ hyO l⟩
    have hW''W : W'' ≤ W := inf_le_left
    have hW''O : ∀ l, W'' ≤ O l := fun l ↦
      le_trans inf_le_right (Finset.inf_le (Finset.mem_univ l))
    have hW''V₁e : W'' ≤ V₁.extend' := hW''W.trans hW
    have hgermfinal : ∀ i, OkaRing.germ hyW'' (OkaRing.restrict hW''W (a i)) =
        OkaRing.germ hyW''
          (∑ l, OkaRing.restrict (hW''O l) (CC l) *
            OkaRing.restrict hW''V₁e (Polynomial.toOkaRing V₁ (G l i))) := by
      intro i
      rw [OkaRing.germ_restrict, map_sum, hEsum i]
      refine Finset.sum_congr rfl fun l _ ↦ ?_
      rw [map_mul, OkaRing.germ_restrict, OkaRing.germ_restrict, hCC l]
    choose W₆ hW₆le hyW₆ hres using fun i ↦
      OkaRing.exists_restrict_eq_of_germ_eq hyW'' (hgermfinal i)
    set W' : Opens (Fin (n + 1) → ℂ) := W'' ⊓ Finset.univ.inf W₆ with hW'def
    have hyW' : y ∈ W' := ⟨hyW'', Opens.mem_finset_inf.mpr fun i _ ↦ hyW₆ i⟩
    have hW'W₆ : ∀ i, W' ≤ W₆ i := fun i ↦
      le_trans inf_le_right (Finset.inf_le (Finset.mem_univ i))
    refine ⟨W', (inf_le_left : W' ≤ W'').trans hW''W, hyW',
      fun l ↦ OkaRing.restrict ((inf_le_left : W' ≤ W'').trans (hW''O l)) (CC l),
      fun i ↦ ?_⟩
    have h16 := congrArg (OkaRing.restrict (hW'W₆ i)) (hres i)
    simp only [OkaRing.restrict_restrict, map_sum, map_mul] at h16
    exact h16

/-- Section 3: the inductive step. Assuming Oka's coherence lemma in dimension `n` for every
target rank, it holds for rows of holomorphic functions in dimension `n + 1`. -/
theorem okaRowStatement_succ (hn : ∀ q, OkaStatement q n) : OkaRowStatement (n + 1) := by
  -- Translating the point to the origin, it suffices to argue at the origin.
  suffices H : ∀ (p : ℕ) (U : Opens (Fin (n + 1) → ℂ)), 0 ∈ U → ∀ f : Fin p → OkaRing U,
      OkaRowConclusion U f 0 by
    intro p U f x hx
    exact OkaRowConclusion.of_shift (H p (U.shift x) (by simpa using hx) _)
  intro p
  induction p with
  | zero =>
    -- the empty row has no relations at all
    intro U h0 f
    exact ⟨U, le_rfl, 0, fun l ↦ l.elim0, h0, fun l ↦ l.elim0,
      fun W _ _ _ y hy ↦ ⟨W, le_rfl, hy, fun l ↦ l.elim0, fun i ↦ i.elim0⟩⟩
  | succ p ih =>
    intro U h0 f
    by_cases hvan : ∃ (i₀ : Fin (p + 1)) (W : Opens (Fin (n + 1) → ℂ)) (hWU : W ≤ U),
        0 ∈ W ∧ OkaRing.restrict hWU (f i₀) = 0
    · -- An entry whose germ at the origin vanishes is zero on a neighbourhood of the origin;
      -- split off its coordinate and use the inductive hypothesis on `p`.
      obtain ⟨i₀, W, hWU, h0W, hzero⟩ := hvan
      exact OkaRowConclusion.of_le hWU (OkaRowConclusion.of_eq_zero i₀ hzero (ih W h0W _))
    · -- No entry vanishes near the origin: pass to Weierstrass polynomials and apply Step 3.3.
      push Not at hvan
      obtain ⟨φ, V, W, hWU, hWV, Q, u, h0V, h0W, hQ, hu, hfQ⟩ :=
        exists_isWeierstrassPolynomial_row U h0 f hvan
      refine OkaRowConclusion.of_congr φ ?_
      rw [map_zero]
      refine OkaRowConclusion.of_le hWU ?_
      simp only [hfQ]
      exact OkaRowConclusion.unit_mul hu
        ((okaRowConclusion_toOkaRing hn V Q hQ 0 (hWV h0W)).restrict hWV h0W)

end InductiveStep

/-- Oka's coherence lemma on `ℂ^n` in the case `q = 1`, by induction on `n`. In the inductive
step, the statement for all `q` in dimension `n` is available via `OkaStatement.of_one`. -/
theorem okaStatement_one (n : ℕ) : OkaStatement 1 n := by
  induction n with
  | zero => exact okaStatement_zero 1
  | succ n ih => exact OkaRowStatement.okaStatement_one (okaRowStatement_succ ih.of_one)

/-- Oka's coherence lemma on `ℂ^n`, for families of vectors of holomorphic functions of
length `q`. -/
theorem okaStatement (q n : ℕ) : OkaStatement q n := OkaStatement.of_one (okaStatement_one n) q

/-- Oka's coherence lemma on `ℂ^n`, for a family `f` of `m` vectors of holomorphic functions on
`U`, each of length `q`: the relations `a` between the `f i`, i.e. the tuples `a` with
`∑ i, a i • f i = 0` in `(OkaRing W)^q`, are, near every point, generated by finitely many
relations `g l` defined on a fixed neighbourhood `V` of `x`.

This is the analytic input; the case of an arbitrary finite index type is deduced from it in
`oka'` by a linear change of coordinates. -/
theorem oka_fin {n m q : ℕ} (U : Opens (Fin n → ℂ)) (f : Fin m → (Fin q → OkaRing U))
    (x : Fin n → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (Fin n → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∀ j, ∑ i, g l i * OkaRing.restrict hV (f i j) = 0) ∧
      ∀ (W : Opens (Fin n → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∀ j, ∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i j) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (Fin n → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) :=
  okaStatement q n U f x hx

/-- Oka's coherence lemma for a family `f` of `m` vectors of holomorphic functions on `U`, each
of length `q`: the relations `a` between the `f i`, i.e. the tuples `a` with
`∑ i, a i • f i = 0` in `(OkaRing W)^q`, are, near every point, generated by finitely many
relations `g l` defined on a fixed neighbourhood `V` of `x`.

This is deduced from `oka_fin` via the linear change of coordinates `ℂ^ι ≃ ℂ^{card ι}`. -/
theorem oka' {m q : ℕ} (f : Fin m → (Fin q → OkaRing U)) (x : ι → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∀ j, ∑ i, g l i * OkaRing.restrict hV (f i j) = 0) ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∀ j, ∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i j) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (ι → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) := by
  set φ := ContinuousLinearEquiv.piCongrLeft ℂ (fun _ : Fin (Fintype.card ι) ↦ ℂ)
    (Fintype.equivFin ι)
  obtain ⟨V', hV', k, g', hxV', hrel', hgen'⟩ :=
    oka_fin (φ.opensCongr U) (fun i j ↦ OkaRing.congr φ U (f i j)) (φ x) (by simp [hx])
  obtain ⟨V, rfl⟩ : ∃ V, φ.opensCongr V = V' :=
    ⟨φ.opensCongr.symm V', φ.opensCongr.apply_symm_apply V'⟩
  have hVU : V ≤ U := φ.opensCongr.le_iff_le.mp hV'
  refine ⟨V, hVU, k, fun l i ↦ (OkaRing.congr φ V).symm (g' l i), by simpa using hxV',
    fun l j ↦ ?_, fun W hWV a ha y hy ↦ ?_⟩
  · have h := congrArg (OkaRing.congr φ V).symm (hrel' l j)
    simpa [map_sum, OkaRing.congr_symm_restrict] using h
  · have ha' : ∀ j, ∑ i, OkaRing.congr φ W (a i) *
        OkaRing.restrict ((φ.opensCongr.monotone hWV).trans hV')
          (OkaRing.congr φ U (f i j)) = 0 := by
      intro j
      have h := congrArg (OkaRing.congr φ W) (ha j)
      simpa [map_sum, OkaRing.congr_restrict] using h
    obtain ⟨W', hW', hyW', c, hc⟩ :=
      hgen' (φ.opensCongr W) (φ.opensCongr.monotone hWV) (fun i ↦ OkaRing.congr φ W (a i)) ha'
        (φ y) (by simp [hy])
    obtain ⟨W₀, rfl⟩ : ∃ W₀, φ.opensCongr W₀ = W' :=
      ⟨φ.opensCongr.symm W', φ.opensCongr.apply_symm_apply W'⟩
    refine ⟨W₀, φ.opensCongr.le_iff_le.mp hW', by simpa using hyW',
      fun l ↦ (OkaRing.congr φ W₀).symm (c l), fun i ↦ ?_⟩
    have h := congrArg (OkaRing.congr φ W₀).symm (hc i)
    simpa [map_sum, OkaRing.congr_symm_restrict] using h

/-- Oka's coherence lemma: the relations between finitely many holomorphic functions on `U` are,
near every point, generated by finitely many of them. This is the case `q = 1` of `oka'`. -/
theorem oka {m : ℕ} (f : Fin m → OkaRing U) (x : ι → ℂ) (hx : x ∈ U) :
    ∃ (V : Opens (ι → ℂ)) (hV : V ≤ U) (k : ℕ) (g : Fin k → (Fin m → OkaRing V)),
      x ∈ V ∧ (∀ l, ∑ i, g l i * OkaRing.restrict hV (f i) = 0) ∧
      ∀ (W : Opens (ι → ℂ)) (hWV : W ≤ V) (a : Fin m → OkaRing W),
        (∑ i, a i * OkaRing.restrict (hWV.trans hV) (f i) = 0) → ∀ y ∈ W,
          ∃ (W' : Opens (ι → ℂ)) (hW' : W' ≤ W), y ∈ W' ∧
            ∃ c : Fin k → OkaRing W', ∀ i,
              OkaRing.restrict hW' (a i) =
                ∑ l, c l * OkaRing.restrict (hW'.trans hWV) (g l i) := by
  obtain ⟨V, hV, k, g, hxV, hrel, hgen⟩ := oka' U (q := 1) (fun i _ ↦ f i) x hx
  exact ⟨V, hV, k, g, hxV, fun l ↦ hrel l 0,
    fun W hWV a ha ↦ hgen W hWV a fun _ ↦ ha⟩
