/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.Topology.Sheaves.Functors
import Oka.Geometry.RingedSpace.ZeroLocus

/-!
# The structure sheaf of a subspace cut out by global sections

`Oka/Geometry/RingedSpace/ZeroLocus.lean` *constructs* a closed immersion `ι : Z ⟶ Y` whose
underlying set is the zero locus of a family `f : κ → Γ(Y, 𝒪_Y)` of global sections and whose
structure sheaf is the sheafified quotient `𝒪_Y ⧸ (f)`. This file proves the converse: **any**
closed immersion `i : X ⟶ Y` with those four properties — a closed embedding onto the zero
locus, surjective on stalks, with kernels the ideals generated by the germs of the `f j` — has
`i_* 𝒪_X ≅ 𝒪_Y ⧸ (f)`. Up to the structure sheaf, the four properties determine the subspace.

## The comparison morphism and the proof that it is invertible

`i.c : 𝒪_Y ⟶ i_* 𝒪_X` kills every `f j` — that is the hypothesis `hc` below, which in practice
comes from the description of the kernels on stalks. So it factors through the quotient
*presheaf* by `TopCat.Presheaf.quotientSpanDesc`, and then, since `i_* 𝒪_X` is a sheaf, through
its sheafification: that is `quotientSheafifyToPushforward`.

Invertibility is checked on stalks, and the two cases are genuinely different.

* **At `y = i x`.** The pushforward has the expected stalk, because `i` is inducing:
  `TopCat.Presheaf.stalkPushforward.stalkPushforward_iso_of_isInducing`. So the stalk of `i.c`
  at `y` is `i.stalkMap x` up to that isomorphism, hence surjective with kernel the ideal
  generated by the germs of the `f j` — and the projection onto the stalk of the quotient
  presheaf is surjective with exactly the same kernel
  (`Oka/Topology/Sheaves/QuotientPresheaf.lean`). A map out of a quotient by the kernel of a
  surjection is bijective.
* **At `y ∉ i(X)`.** Both stalks are the zero ring, for unrelated reasons. On the left, `y` is
  outside the zero locus, so some germ of some `f j` is a unit and the ideal it generates is
  everything. On the right, `(i(X))ᶜ` is an open neighbourhood of `y` whose preimage is empty,
  and the sections of a sheaf over `∅` form the terminal ring.

## What this file does not do, and where it is done

The mapping property of a subspace cut out by global sections — that a morphism `φ : Z ⟶ Y`
killing the `f j` factors through `i` — needs one more ingredient beyond the isomorphism proved
here: that `i_*` is **fully faithful**. That is not in Mathlib; it is
`TopCat.Presheaf.pushforwardFullyFaithful` in `Oka/Topology/Sheaves/Functors.lean`, and with it
the chain `Hom(𝒪_X, ψ_*𝒪_Z) ≅ Hom(i_*𝒪_X, φ_*𝒪_Z) ≅ Hom(𝒪_Y ⧸ (f), φ_*𝒪_Z)` closes, the last
step because `φ.c` also kills the `f j`. The assembly is analytic-side vocabulary and lives in
`Oka/AnalyticSpace/Factorisation.lean`; the same ingredient is what turns the isomorphism proved
here into "any two closed immersions cutting out the same sections are isomorphic", since the
isomorphism of structure sheaves is available *after* pushing forward and descending it along
`i_*` is exactly full faithfulness.

## Main definitions

- `AlgebraicGeometry.LocallyRingedSpace.quotientSpanToPushforward`: `𝒪_Y ⧸ (f) ⟶ i_* 𝒪_X` at the
  level of the quotient presheaf.
- `AlgebraicGeometry.LocallyRingedSpace.quotientSheafifyToPushforward`: the comparison morphism
  of sheaves, and `quotientSheafifyIsoPushforward`: the isomorphism it becomes.

## Main results

- `AlgebraicGeometry.LocallyRingedSpace.isIso_quotientSheafifyToPushforward`: the comparison
  morphism is an isomorphism.
- `AlgebraicGeometry.LocallyRingedSpace.bijective_stalkFunctor_map_quotientSpanToPushforward` and
  `subsingleton_stalk_pushforward_of_notMem_range`: the two stalkwise cases, stated separately
  because each is useful on its own.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984], §A
-/

open CategoryTheory Limits TopologicalSpace Opposite AlgebraicGeometry Topology
open scoped AlgebraicGeometry

universe v u

noncomputable section

namespace AlgebraicGeometry.LocallyRingedSpace

variable {X Y : LocallyRingedSpace.{u}} (i : X ⟶ Y) {κ : Type v}
  (f : κ → Y.presheaf.obj (op ⊤)) (hc : ∀ j, i.c.app (op ⊤) (f j) = 0)

section Comparison

/-- The morphism `𝒪_Y ⧸ (f) ⟶ i_* 𝒪_X` out of the quotient **presheaf**, obtained from
`i.c : 𝒪_Y ⟶ i_* 𝒪_X` by the universal property of the quotient. -/
def quotientSpanToPushforward : Y.presheaf.quotientSpan f ⟶ i.base _* X.presheaf :=
  Y.presheaf.quotientSpanDesc f i.c (Y.presheaf.spanIdeal_le_ker f i.c hc)

@[simp]
lemma toQuotientSpan_comp_quotientSpanToPushforward :
    Y.presheaf.toQuotientSpan f ≫ quotientSpanToPushforward i f hc = i.c :=
  Y.presheaf.toQuotientSpan_comp_quotientSpanDesc f _ _

/-- **The comparison morphism `𝒪_Y ⧸ (f) ⟶ i_* 𝒪_X`.**

The source is the *sheafified* quotient, which is what `Oka/Geometry/RingedSpace/ZeroLocus.lean`
uses as the structure sheaf of the zero locus; the factorisation through it exists because
`i_* 𝒪_X` is a sheaf. -/
def quotientSheafifyToPushforward : Y.quotientSheafify f ⟶ i.base _* X.presheaf :=
  show sheafify (Opens.grothendieckTopology Y.toTopCat) (Y.presheaf.quotientSpan f) ⟶
      i.base _* X.presheaf from
    sheafifyLift _ (quotientSpanToPushforward i f hc)
      (TopCat.Sheaf.pushforward_sheaf_of_sheaf i.base X.sheaf.2)

@[simp]
lemma toSheafify_comp_quotientSheafifyToPushforward :
    CategoryTheory.toSheafify (D := CommRingCat.{u})
        (Opens.grothendieckTopology Y.toTopCat) (Y.presheaf.quotientSpan f) ≫
        quotientSheafifyToPushforward i f hc = quotientSpanToPushforward i f hc :=
  toSheafify_sheafifyLift (Opens.grothendieckTopology Y.toTopCat)
    (quotientSpanToPushforward i f hc)
    (TopCat.Sheaf.pushforward_sheaf_of_sheaf i.base X.sheaf.2)

/-- Sheafification does not change stalks, so the stalk of the comparison morphism is the stalk
of the presheaf-level one, precomposed with `quotientSheafifyStalkIso`. -/
lemma stalkFunctor_map_quotientSheafifyToPushforward (y : Y.toTopCat) :
    (Y.quotientSheafifyStalkIso f y).hom ≫
        (TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map
          (quotientSheafifyToPushforward i f hc) =
      (TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map (quotientSpanToPushforward i f hc) := by
  rw [quotientSheafifyStalkIso_hom]
  exact ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map_comp _ _).symm.trans
    (congrArg _ (toSheafify_comp_quotientSheafifyToPushforward i f hc))

/-- The stalk of `i.c` factors through the stalk of the quotient presheaf. -/
lemma stalkFunctor_map_quotientSpanToPushforward (y : Y.toTopCat) :
    (TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map (Y.presheaf.toQuotientSpan f) ≫
        (TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map
          (quotientSpanToPushforward i f hc) =
      (TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map i.c :=
  ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map_comp _ _).symm.trans
    (congrArg _ (toQuotientSpan_comp_quotientSpanToPushforward i f hc))

/-- The sheafified quotient is a sheaf. -/
lemma isSheaf_quotientSheafify : (Y.quotientSheafify f).IsSheaf :=
  ((presheafToSheaf (Opens.grothendieckTopology Y.toTopCat) CommRingCat.{u}).obj
    (Y.presheaf.quotientSpan f)).property

end Comparison

section Stalks

variable (hind : IsInducing i.base)
  (hsurj : ∀ x, Function.Surjective (i.stalkMap x).hom)
  (hker : ∀ x, RingHom.ker (i.stalkMap x).hom =
    Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm (i.base x) (f j)))

include hind hsurj hker in
/-- **At a point of the image, the comparison morphism is bijective on stalks.**

Both `𝒪_{Y,y} ↠ (𝒪_Y ⧸ (f))_y` and `𝒪_{Y,y} ↠ 𝒪_{X,x}` are surjective with the same kernel, the
ideal generated by the germs of the `f j`; the map between their targets is therefore
bijective. -/
lemma bijective_stalkFunctor_map_quotientSpanToPushforward (x : X) :
    Function.Bijective ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} (i.base x)).map
      (quotientSpanToPushforward i f hc)).hom := by
  set A := ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} (i.base x)).map
    (quotientSpanToPushforward i f hc)).hom with hA
  set Q := ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} (i.base x)).map
    (Y.presheaf.toQuotientSpan f)).hom with hQ
  haveI : IsIso (X.presheaf.stalkPushforward CommRingCat.{u} i.base x) :=
    TopCat.Presheaf.stalkPushforward.stalkPushforward_iso_of_isInducing CommRingCat.{u} hind _ x
  have hP : Function.Bijective
      (X.presheaf.stalkPushforward CommRingCat.{u} i.base x).hom :=
    ConcreteCategory.bijective_of_isIso _
  set P := (X.presheaf.stalkPushforward CommRingCat.{u} i.base x).hom with hPdef
  have h1 : i.stalkMap x =
      ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} (i.base x)).map
          (Y.presheaf.toQuotientSpan f) ≫
        (TopCat.Presheaf.stalkFunctor CommRingCat.{u} (i.base x)).map
          (quotientSpanToPushforward i f hc)) ≫
        X.presheaf.stalkPushforward CommRingCat.{u} i.base x :=
    congrArg (fun z ↦ z ≫ X.presheaf.stalkPushforward CommRingCat.{u} i.base x)
      (stalkFunctor_map_quotientSpanToPushforward i f hc (i.base x)).symm
  have hS : ∀ s, (i.stalkMap x).hom s = P (A (Q s)) := fun s ↦
    ConcreteCategory.congr_hom h1 s
  have hQsurj : Function.Surjective Q :=
    Y.presheaf.surjective_stalkFunctor_map_toQuotientSpan f (i.base x)
  have hQker : RingHom.ker Q =
      Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm (i.base x) (f j)) :=
    Y.presheaf.ker_stalkFunctor_map_toQuotientSpan f (i.base x)
  have hkeq : RingHom.ker Q = RingHom.ker (i.stalkMap x).hom := hQker.trans (hker x).symm
  refine ⟨(injective_iff_map_eq_zero A).2 fun t ht ↦ ?_, fun t ↦ ?_⟩
  · obtain ⟨r, rfl⟩ := hQsurj t
    have hSr : (i.stalkMap x).hom r = 0 := (hS r).trans (by rw [ht]; exact map_zero P)
    have hmem : r ∈ RingHom.ker Q := by rw [hkeq]; exact hSr
    exact RingHom.mem_ker.1 hmem
  · obtain ⟨s, hsq⟩ := hsurj x (P t)
    exact ⟨Q s, hP.injective ((hS s).symm.trans hsq)⟩

end Stalks

section Vanishing

/-- Off the image of a closed embedding the pushforward of a sheaf has trivial stalks: the
complement of the image is an open neighbourhood whose preimage is empty, and the sections of a
sheaf over `∅` form the terminal ring. -/
lemma subsingleton_stalk_pushforward_of_notMem_range (hcl : IsClosed (Set.range i.base))
    {y : Y.toTopCat} (hy : y ∉ Set.range i.base) :
    Subsingleton ((i.base _* X.presheaf).stalk y) := by
  set U : Opens Y.toTopCat := ⟨(Set.range i.base)ᶜ, hcl.isOpen_compl⟩ with hU
  have hyU : y ∈ U := hy
  have hbot : (Opens.map i.base).obj U = ⊥ := by
    ext z
    simp only [Opens.map_coe, Set.mem_preimage, Opens.coe_bot, Set.mem_empty_iff_false,
      iff_false, hU]
    exact fun hz ↦ hz ⟨z, rfl⟩
  have hsub : Subsingleton ((i.base _* X.presheaf).obj (op U)) :=
    CommRingCat.subsingleton_of_isTerminal (X.sheaf.isTerminalOfEqEmpty hbot)
  refine subsingleton_of_zero_eq_one ?_
  have h1 : (1 : (i.base _* X.presheaf).stalk y) =
      (i.base _* X.presheaf).germ U y hyU 1 := (map_one _).symm
  have h0 : (i.base _* X.presheaf).germ U y hyU 0 = 0 := map_zero _
  rw [h1, show (1 : (i.base _* X.presheaf).obj (op U)) = 0 from Subsingleton.elim _ _, h0]

/-- Off the zero locus the stalk of the quotient presheaf is the zero ring: some `f j` has
invertible germ there, so the ideal generated by the germs is the whole stalk. -/
lemma subsingleton_stalk_quotientSpan_of_notMem_zeroLocus {y : Y.toTopCat}
    (hy : y ∉ Y.zeroLocus f) :
    Subsingleton ((Y.presheaf.quotientSpan f).stalk y) := by
  obtain ⟨j, hj⟩ : ∃ j, IsUnit (Y.presheaf.Γgerm y (f j)) := by
    by_contra h
    exact hy ((Y.mem_zeroLocus_iff_not_isUnit f).2 (not_exists.1 h))
  have htop : Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm y (f j)) = ⊤ :=
    Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ⟨j, rfl⟩) hj
  have : Subsingleton (Y.presheaf.stalk y ⧸
      Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm y (f j))) :=
    Ideal.Quotient.subsingleton_iff.2 htop
  exact (Y.presheaf.stalkQuotientSpanEquiv f y).surjective.subsingleton

end Vanishing

section Main

-- The same three hypotheses as in the previous section, together with the two topological ones.
-- They are re-declared rather than hoisted so that `section Stalks` and `section Vanishing`
-- state exactly what each of their lemmas needs.
variable (hind : IsInducing i.base)
  (hsurj : ∀ x, Function.Surjective (i.stalkMap x).hom)
  (hker : ∀ x, RingHom.ker (i.stalkMap x).hom =
    Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm (i.base x) (f j)))
  (hcl : IsClosed (Set.range i.base)) (hrange : Set.range i.base = Y.zeroLocus f)

include hind hsurj hker hcl hrange in
/-- The comparison morphism is an isomorphism on every stalk of the quotient presheaf. -/
lemma isIso_stalkFunctor_map_quotientSpanToPushforward (y : Y.toTopCat) :
    IsIso ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map
      (quotientSpanToPushforward i f hc)) := by
  by_cases hy : y ∈ Set.range i.base
  · obtain ⟨x, rfl⟩ := hy
    exact (ConcreteCategory.isIso_iff_bijective _).2
      (bijective_stalkFunctor_map_quotientSpanToPushforward i f hc hind hsurj hker x)
  · have hs1 : Subsingleton ((Y.presheaf.quotientSpan f).stalk y) :=
      subsingleton_stalk_quotientSpan_of_notMem_zeroLocus (Y := Y) f (hrange ▸ hy)
    have hs2 : Subsingleton ((i.base _* X.presheaf).stalk y) :=
      subsingleton_stalk_pushforward_of_notMem_range i hcl hy
    exact (ConcreteCategory.isIso_iff_bijective _).2
      ⟨fun a b _ ↦ hs1.elim a b, fun t ↦ ⟨0, hs2.elim _ t⟩⟩

include hind hsurj hker hcl hrange in
/-- **`i_* 𝒪_X ≅ 𝒪_Y ⧸ (f)` for a closed immersion cutting out the `f j`.**

The hypotheses are the four that characterise such an immersion — a closed embedding onto the
zero locus, surjective on stalks, with kernels the ideals generated by the germs of the `f j` —
taken one at a time rather than bundled, so that the statement is usable from any packaging of
them. -/
theorem isIso_quotientSheafifyToPushforward :
    IsIso (quotientSheafifyToPushforward i f hc) := by
  have hstalk : ∀ y : Y.toTopCat, IsIso ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map
      (quotientSheafifyToPushforward i f hc)) := by
    intro y
    have hα : IsIso ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map
        (quotientSpanToPushforward i f hc)) :=
      isIso_stalkFunctor_map_quotientSpanToPushforward i f hc hind hsurj hker hcl hrange y
    have heq := stalkFunctor_map_quotientSheafifyToPushforward i f hc y
    haveI : IsIso ((Y.quotientSheafifyStalkIso f y).hom ≫
        (TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map
          (quotientSheafifyToPushforward i f hc)) := by
      rw [heq]; exact hα
    exact IsIso.of_isIso_comp_left (Y.quotientSheafifyStalkIso f y).hom _
  let F : TopCat.Sheaf CommRingCat.{u} Y.toTopCat :=
    ⟨Y.quotientSheafify f, isSheaf_quotientSheafify f⟩
  let G : TopCat.Sheaf CommRingCat.{u} Y.toTopCat :=
    ⟨i.base _* X.presheaf, TopCat.Sheaf.pushforward_sheaf_of_sheaf i.base X.sheaf.2⟩
  let φ : F ⟶ G := ⟨quotientSheafifyToPushforward i f hc⟩
  haveI : ∀ y : Y.toTopCat, IsIso ((TopCat.Presheaf.stalkFunctor CommRingCat.{u} y).map φ.1) :=
    hstalk
  haveI : IsIso φ := TopCat.Presheaf.isIso_of_stalkFunctor_map_iso φ
  exact Functor.map_isIso (TopCat.Sheaf.forget CommRingCat.{u} Y.toTopCat) φ

include hind hsurj hker hcl hrange in
/-- `i_* 𝒪_X ≅ 𝒪_Y ⧸ (f)`, packaged as an isomorphism. -/
def quotientSheafifyIsoPushforward : Y.quotientSheafify f ≅ i.base _* X.presheaf :=
  @asIso _ _ _ _ _
    (isIso_quotientSheafifyToPushforward i f hc hind hsurj hker hcl hrange)

end Main

end AlgebraicGeometry.LocallyRingedSpace
