/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.Geometry.RingedSpace.LocallyRingedSpace
import Oka.Topology.Sheaves.Stalks

/-!
# Missing general lemmas on locally ringed spaces

Material for `Mathlib/Geometry/RingedSpace/LocallyRingedSpace.lean`; see `README.md` on the
mirror tree.

`homeoOfIso` is the exact analogue for `LocallyRingedSpace` of `AlgebraicGeometry.Scheme.homeoOfIso`
(`Mathlib/AlgebraicGeometry/Scheme.lean`), which exists only for schemes.

**The imports are the target itself and one other mirror file, and they cost the target nothing**:
the Mathlib part of this file's transitive closure is **1688** modules, which is exactly the
closure of `Mathlib/Geometry/RingedSpace/LocallyRingedSpace.lean`. That is what made this file
the right home for the section, open-subspace and germ API added below for taxis #905 — the
declarations were measured to compile against these two imports and nothing else, so putting them
here costs their destination no new import at all.

## Main definitions

- `AlgebraicGeometry.LocallyRingedSpace.res`: **restriction of a section of the structure sheaf
  to a smaller open subset**, with `res_self`, `res_res` and the three lemmas `res_sum`,
  `res_mul` and `res_zero` saying it is a ring homomorphism in applied form. It is an
  abbreviation for `Y.presheaf.map (homOfLE h).op` and exists because a statement quantifying
  over open subsets is unreadable without it.
- `AlgebraicGeometry.LocallyRingedSpace.imOpen` and
  `AlgebraicGeometry.LocallyRingedSpace.preOpen`: an open subset of an open subspace `X|U` read
  as an open subset of `X`, and back. `imOpen_le`, `imOpen_preOpen`, `preOpen_imOpen` and
  `preOpen_le_of_le_imOpen` are the four facts that make the pair usable, and `restrict_res` is
  the compatibility with restriction of sections.
- `AlgebraicGeometry.LocallyRingedSpace.homeoOfIso`: the underlying homeomorphism of an
  isomorphism of locally ringed spaces.
- `AlgebraicGeometry.LocallyRingedSpace.resAlgMap`: an algebra structure on the structure sheaf,
  recorded as a ring homomorphism into the global sections, restricted to an open subspace.
- `AlgebraicGeometry.LocallyRingedSpace.stalkAlgMap`: the same algebra structure, taken at a
  stalk.
- `AlgebraicGeometry.LocallyRingedSpace.toRestrictΓ`: **a section over `U`, as a global section
  of `X|U`.** The global sections of `X|U` are indexed by `U.functor.obj ⊤` rather than by `U`,
  so this is a restriction map and not a coercion; it is the spelling every statement below
  about sections on an open subspace is phrased in.
- `AlgebraicGeometry.LocallyRingedSpace.glueSection`: the global section a compatible family
  over an open cover glues to.
- `AlgebraicGeometry.LocallyRingedSpace.glueAlgMap`: **an algebra structure on `𝒪_X` glued from
  compatible algebra structures over an open cover.** The converse of `resAlgMap`, and unlike it
  a genuine gluing, because an algebra structure is a map into *global* sections.
- `AlgebraicGeometry.LocallyRingedSpace.comapAlgMap`: an algebra structure pulled back along an
  arbitrary morphism. `resAlgMap` is its special case at `ofRestrict`.
- `AlgebraicGeometry.LocallyRingedSpace.glueAlgMapRestrict`: `glueAlgMap` with the family indexed
  by the global sections of the open subspaces rather than by the opens, which is the indexing a
  cover by abstract spaces produces and the one in which no seam has to be crossed.

## Main results

- `AlgebraicGeometry.LocallyRingedSpace.germ_res`: the germ of a restricted section is the germ
  of the section.
- `AlgebraicGeometry.LocallyRingedSpace.exists_localCombination`: **if the germ of a section lies
  in the ideal generated by the germs of finitely many global sections, then the section is a
  combination of them on a neighbourhood.** Membership in a span is a statement about germs;
  this is what turns it back into a statement about sections.
- `AlgebraicGeometry.LocallyRingedSpace.exists_localLift`: **a morphism which is surjective on
  stalks lifts a section locally**, and
  `AlgebraicGeometry.LocallyRingedSpace.exists_localLift_family` lifts a finite family of them
  over one open set at once, which is the form a local model argument needs;
  `AlgebraicGeometry.LocallyRingedSpace.c_app_res` is the naturality it runs on.
- `AlgebraicGeometry.LocallyRingedSpace.restrictStalkIso_hom_stalkAlgMap`: the identification of
  the stalks of an open subspace with the stalks of the ambient space is compatible with the
  algebra structures.
- `AlgebraicGeometry.LocallyRingedSpace.Γ_map_comp_apply`: contravariant functoriality of the
  global sections, in applied form.
- `AlgebraicGeometry.LocallyRingedSpace.Γ_map_id_apply`: its identity companion, which is what
  collapses a pair of mutually inverse morphisms in such a computation.
- `AlgebraicGeometry.LocallyRingedSpace.Γ_map_inv_hom_apply` and
  `AlgebraicGeometry.LocallyRingedSpace.Γ_map_hom_inv_apply`: **crossing an isomorphism of
  locally ringed spaces in both directions is the identity on global sections**, proved without
  computing either direction.
- `AlgebraicGeometry.LocallyRingedSpace.hom_stalk_ext`: two morphisms with the same base map and
  the same maps on stalks are equal.
- `AlgebraicGeometry.LocallyRingedSpace.hom_ext_of_comp_eq`: **a morphism all of whose stalk maps
  are isomorphisms cancels on the right against two morphisms that have the same base map.** It
  is not a monomorphism statement — invertibility on germs says nothing about which point a
  competing morphism lands on — and the equality of base maps is a hypothesis and not a
  consequence.
- `AlgebraicGeometry.LocallyRingedSpace.resAlgMap_glueAlgMap`: restricting a glued algebra
  structure to a member of the cover returns the given one, across the
  `functor.obj ⊤`-versus-`U` seam.
- `AlgebraicGeometry.LocallyRingedSpace.resAlgMap_glueAlgMapRestrict`: the same for
  `glueAlgMapRestrict`, and there it is an equation of algebra structures on the nose.
- `AlgebraicGeometry.LocallyRingedSpace.comapAlgMap_ofRestrict`: pulling an algebra structure
  back along the inclusion of an open subspace is restricting it.
- `AlgebraicGeometry.LocallyRingedSpace.Γgerm_Γ_map`: the germ of the pullback of a global
  section is the image of its germ under the stalk map.
- `AlgebraicGeometry.LocallyRingedSpace.range_ofRestrict`: the image of an open subspace
  inclusion is that open subset.
- `AlgebraicGeometry.LocallyRingedSpace.range_ofRestrict_comp`: the image of the composite of two
  open subspace inclusions.
- `AlgebraicGeometry.LocallyRingedSpace.hom_ext_of_isEmpty`: any two morphisms out of a locally
  ringed space with no points are equal.
- `AlgebraicGeometry.LocallyRingedSpace.hom_ext_restrict_of_isEmpty`: its specialisation to the
  restriction to an open subset with no points, which is the form callers meet.
- `AlgebraicGeometry.LocallyRingedSpace.Γ_map_ofRestrict_apply`: pulling a global section back
  along the inclusion of an open subspace is restricting it.
- `AlgebraicGeometry.LocallyRingedSpace.section_ext_of_cover`: **two global sections which agree
  on every member of an open cover are equal.**
- `AlgebraicGeometry.LocallyRingedSpace.germ_eq_stalkMap_ofRestrict`: **a germ on an open
  subspace is the image of a germ upstairs** under the stalk map of the inclusion. This is what
  makes a section of `𝒪_{X|U}` computable from data on `X`, and every germ argument below runs
  through it.
- `AlgebraicGeometry.LocallyRingedSpace.Γ_map_over_ambient`: **pulling a section back along a
  morphism of open subspaces *over* `X` is restricting it.**
- `AlgebraicGeometry.LocallyRingedSpace.isIso_stalkMap_of_comp`: **two out of three for stalk
  maps along a factorisation** — if `f ≫ g = h` and both `f` and `h` are isomorphisms on the
  stalk at `x`, then `g` is one at `f.base x`. The point of stating it is that the two sides
  live over *different* points of the target until the factorisation is substituted, so a
  consumer that tries to assemble it in place meets a transport that is not there.
-/

open CategoryTheory TopologicalSpace Opposite

universe u

namespace AlgebraicGeometry.LocallyRingedSpace

variable {X Y : LocallyRingedSpace.{u}}

/-- **Contravariant functoriality of the global sections, applied to an element.**

`Γ.map_comp` is a statement about morphisms of `CommRingCat`; this is the form a computation of
the pullback of a global section along a composite actually needs. -/
lemma Γ_map_comp_apply {X Y Z : LocallyRingedSpace.{u}} (f : X ⟶ Y) (g : Y ⟶ Z)
    (a : Z.presheaf.obj (op ⊤)) :
    (Γ.map (f ≫ g).op).hom a = (Γ.map f.op).hom ((Γ.map g.op).hom a) := by
  rw [op_comp, Functor.map_comp]
  rfl

/-- **The identity acts as the identity on global sections**, in applied form.

The companion of `AlgebraicGeometry.LocallyRingedSpace.Γ_map_comp_apply`: together they are what
turns `e.inv ≫ e.hom = 𝟙` into a statement about a section, which is how one crosses an
isomorphism of locally ringed spaces without computing either of its two maps on sections. -/
lemma Γ_map_id_apply (X : LocallyRingedSpace.{u}) (a : X.presheaf.obj (op ⊤)) :
    (Γ.map (𝟙 X).op).hom a = a := by
  rw [op_id, CategoryTheory.Functor.map_id]
  rfl

/-- **Crossing an isomorphism of locally ringed spaces in both directions is the identity on
global sections** — proved without computing either direction.

Neither `Γ.map e.hom.op` nor `Γ.map e.inv.op` need be computable; in the case this was
extracted from — `e := X.restrictTopIso`, crossing between `X` and `X|⊤` — `Γ.map e.inv.op` is
an `eqToHom` between two *different* types of global-section ring, so no equation naming it
typechecks at all. **The technique is never to name it**: write the section as a pullback along
the direction that *is* a `rfl`, then collapse the resulting pair with this lemma, whose whole
proof is `Iso.inv_hom_id` read through
`AlgebraicGeometry.LocallyRingedSpace.Γ_map_comp_apply`.

For `restrictTopIso` the direction to write the section along is `hom`, because
`Γ.map X.restrictTopIso.hom.op` is *definitionally the restriction map*
`X.presheaf.map (homOfLE le_top).op` from `⊤` to the image of `⊤`. It is therefore a `rfl`
for any section whose presentation does not mention the open it lives on — a polynomial, a
constant, a coordinate — but **not** for a section given abstractly: the two sides then have
different types, `Γ(X, ⊤)` and `Γ(X, functor.obj ⊤)`, which are not definitionally equal even
for `X = ℂ^n`. `OkaTest/Factorisation.lean` carries the technique out at `ℂ²`, where
`nodeSection_eq` is the `rfl` in question, and checks both halves of this paragraph beside
it. -/
lemma Γ_map_inv_hom_apply (e : X ≅ Y) (a : Y.presheaf.obj (op ⊤)) :
    (Γ.map e.inv.op).hom ((Γ.map e.hom.op).hom a) = a :=
  (Γ_map_comp_apply e.inv e.hom a).symm.trans
    ((congrArg (fun m : Y ⟶ Y ↦ (Γ.map m.op).hom a) e.inv_hom_id).trans (Γ_map_id_apply Y a))

/-- The companion of `AlgebraicGeometry.LocallyRingedSpace.Γ_map_inv_hom_apply`, crossing in the
other order. Same proof with `Iso.hom_inv_id` in place of `Iso.inv_hom_id`. -/
lemma Γ_map_hom_inv_apply (e : X ≅ Y) (a : X.presheaf.obj (op ⊤)) :
    (Γ.map e.hom.op).hom ((Γ.map e.inv.op).hom a) = a :=
  (Γ_map_comp_apply e.hom e.inv a).symm.trans
    ((congrArg (fun m : X ⟶ X ↦ (Γ.map m.op).hom a) e.hom_inv_id).trans (Γ_map_id_apply X a))

/-- **Two morphisms of locally ringed spaces with the same base map and the same maps on stalks
are equal.**

`AlgebraicGeometry.SheafedSpace.hom_stalk_ext` reflected along
`AlgebraicGeometry.LocallyRingedSpace.forgetToSheafedSpace`, which is faithful. Mathlib has the
`SheafedSpace` statement and the `Scheme` one but not this one.

The `TopCat.Presheaf.stalkCongr` in the hypothesis is unavoidable: the two stalk maps have
sources `Y.presheaf.stalk (f.base x)` and `Y.presheaf.stalk (g.base x)`, which are equal only
propositionally. `TopCat.Presheaf.stalkCongr_hom_germ` is what evaluates it on a germ. -/
lemma hom_stalk_ext (f g : X ⟶ Y) (h : f.base = g.base)
    (h' : ∀ x, f.stalkMap x = (Y.presheaf.stalkCongr (h ▸ rfl)).hom ≫ g.stalkMap x) :
    f = g :=
  forgetToSheafedSpace.map_injective (SheafedSpace.hom_stalk_ext _ _ h h')

/-- **A morphism whose stalk maps are all isomorphisms cancels on the right, once the base maps
are known to agree**: if `f ≫ p = g ≫ p` and `f` and `g` have the same base map, then `f = g`.

**This is not `p` being a monomorphism**, and the difference is the whole of the base-map
hypothesis. What the stalk hypothesis gives is that `p` is invertible on germs, and germs at a
point say nothing about which point a competing morphism lands on — so the base maps have to be
compared separately, and this statement asks for that comparison rather than deriving it. A
covering map of positive degree is the standard example of a morphism this applies to and is not
monic; that example is a reason for the hypothesis and is not compiled anywhere here.

**The hypothesis is not that `p` is a local isomorphism, and at this generality it does not imply
one.** Being a local isomorphism is two conditions — a local homeomorphism of base spaces, and
invertible stalk maps — and only the second is assumed here. Over an arbitrary locally ringed
space the first does not follow, and the standard witness is the canonical morphism from `Spec`
of the local ring of the affine line over `ℂ` at a closed point to that line. Its source has two
points and both its stalk maps are identities — of that local ring at the closed point, of the
function field at the generic one — so every one of them is an isomorphism. Its image is those
two points of the line, and no set of that shape is open there, the complement of a non-empty
open set being finite. What makes the implication tempting is downstream: the complex analytic
development this mirror file serves bundles the two conditions into a single class. That
bundling is a definition and neither implication between its fields is proved there either, so
it is not a source for the direction this paragraph says is unavailable.

**The two transports are `AlgebraicGeometry.LocallyRingedSpace.stalkMap_congr_point` and
`AlgebraicGeometry.LocallyRingedSpace.stalkMap_congr_hom`, and they are what keeps the proof to
a rewrite rather than a `subst` argument.** `hom_stalk_ext` leaves a goal comparing
`f.stalkMap x` with `g.stalkMap x`, whose sources are the stalks of `Y` at `f.base x` and at
`g.base x` — propositionally equal points, so a `TopCat.Presheaf.stalkCongr` stands between them.
Composing with the isomorphism `p.stalkMap (f.base x)` on the left turns each side into a stalk
map of a composite: `stalkMap_congr_point` moves that isomorphism past the transport, and
`stalkMap_congr_hom` at `hcomp` closes what is left. Neither transport is discharged by hand and
neither point is substituted. -/
lemma hom_ext_of_comp_eq {Z : LocallyRingedSpace.{u}} (p : Y ⟶ Z)
    [∀ y, IsIso (p.stalkMap y)] (f g : X ⟶ Y) (hb : f.base = g.base)
    (hcomp : f ≫ p = g ≫ p) : f = g := by
  refine hom_stalk_ext f g hb fun x ↦ ?_
  have hpt : f.base x = g.base x := by rw [hb]
  rw [← cancel_epi (p.stalkMap (f.base x)), ← stalkMap_comp]
  simp only [TopCat.Presheaf.stalkCongr_hom]
  rw [← Category.assoc, stalkMap_congr_point p _ _ hpt, Category.assoc, ← stalkMap_comp]
  exact stalkMap_congr_hom _ _ hcomp x

/-- The underlying homeomorphism of an isomorphism of locally ringed spaces. -/
noncomputable def homeoOfIso (e : X ≅ Y) : X ≃ₜ Y :=
  TopCat.homeoOfIso (LocallyRingedSpace.forgetToTop.mapIso e)

@[simp]
lemma homeoOfIso_apply (e : X ≅ Y) (x : X) : homeoOfIso e x = e.hom.base x :=
  rfl

/-- An `R`-algebra structure on the structure sheaf of a locally ringed space is recorded as a
ring homomorphism `α : R →+* Γ(X, 𝒪_X)` into the global sections; the ring of sections over
every open subset then becomes an `R`-algebra via restriction. In particular `α` induces an
`R`-algebra structure on every open subspace of `X`, which this definition provides. -/
noncomputable def resAlgMap {R : Type*} [NonAssocSemiring R] (X : LocallyRingedSpace.{u})
    (α : R →+* X.presheaf.obj (op ⊤)) (U : Opens X) :
    R →+* (X.restrict U.isOpenEmbedding).presheaf.obj (op ⊤) :=
  (X.presheaf.map (homOfLE le_top).op).hom.comp α

/-- **An algebra structure on the structure sheaf of `Y`, pulled back along a morphism
`f : X ⟶ Y`.**

`resAlgMap` is the special case `f = X.ofRestrict U` — see `comapAlgMap_ofRestrict` — and this
is the form needed when the subspace arrives as an abstract space mapping in by an open
immersion rather than as a `restrict`. Nothing here is about open immersions: pulling a global
section back along any morphism is `Γ.map`, and the ring axioms are its.

Note that `f` determines the pulled-back structure, and conversely: two structures on `Γ(X, 𝒪_X)`
that are both `f`-compatible with one and the same structure on `Γ(Y, 𝒪_Y)` are equal, because
each of them *is* this composite. That is `ComplexAnalytic.IsCLinearHom.eq`.

**Two places wrote this composite out before it had a name** and are left as they are:
`ComplexAnalytic.polyToGlobal` and the statement of
`ComplexAnalytic.Γ_map_comp_ofMvPolynomial`, both at `R = MvPolynomial (ULift (Fin n)) ℂ`. They
are not rephrased because the second is a theorem *statement* that several proofs consume in its
current spelling; a caller writing a new one should use this. -/
noncomputable def comapAlgMap {R : Type*} [NonAssocSemiring R] (f : X ⟶ Y)
    (α : R →+* Y.presheaf.obj (op ⊤)) : R →+* X.presheaf.obj (op ⊤) :=
  (Γ.map f.op).hom.comp α

/-- The `R`-algebra structure a ring homomorphism `α : R →+* Γ(X, 𝒪_X)` induces on the stalk at
a point: the germ there of the constant sections. -/
noncomputable def stalkAlgMap {R : Type*} [NonAssocSemiring R] (X : LocallyRingedSpace.{u})
    (α : R →+* X.presheaf.obj (op ⊤)) (x : X) : R →+* X.presheaf.stalk x :=
  (X.presheaf.Γgerm x).hom.comp α

/-- `stalkAlgMap` unfolded: the constant `c` becomes the germ at `x` of the global section
`α c`. -/
lemma stalkAlgMap_apply {R : Type*} [NonAssocSemiring R] (X : LocallyRingedSpace.{u})
    (α : R →+* X.presheaf.obj (op ⊤)) (x : X) (c : R) :
    X.stalkAlgMap α x c = X.presheaf.germ ⊤ x trivial (α c) :=
  rfl

/-- **The stalks of an open subspace are the stalks of the ambient space, compatibly with the
algebra structures**: the germ at `x` of the constant section `c` on `U` is its germ on `X`. -/
lemma restrictStalkIso_hom_stalkAlgMap {R : Type*} [NonAssocSemiring R]
    (X : LocallyRingedSpace.{u}) (α : R →+* X.presheaf.obj (op ⊤)) (U : Opens X)
    (x : X.restrict U.isOpenEmbedding) (c : R) :
    (X.restrictStalkIso U.isOpenEmbedding x).hom
        ((X.restrict U.isOpenEmbedding).stalkAlgMap (X.resAlgMap α U) x c) =
      X.stalkAlgMap α x.1 c := by
  change (X.restrictStalkIso U.isOpenEmbedding x).hom
      ((X.restrict U.isOpenEmbedding).presheaf.germ ⊤ x trivial
        ((X.presheaf.map (homOfLE le_top).op).hom (α c))) = _
  rw [restrictStalkIso_hom_eq_germ_apply]
  exact X.presheaf.germ_res_apply (homOfLE le_top) x.1 _ (α c)

/-- **The germ of the pullback of a global section is the image of its germ under the stalk
map.**

This is `AlgebraicGeometry.LocallyRingedSpace.stalkMap_germ_apply` specialised to `U = ⊤` and
read from right to left, which is the direction a computation with `Γ.map` wants. The
specialisation costs nothing because `(Opens.map φ.base).obj ⊤` and `⊤` are definitionally
equal, and so are `φ.c.app (op ⊤)` and `Γ.map φ.op`. -/
lemma Γgerm_Γ_map (φ : X ⟶ Y) (a : Y.presheaf.obj (op ⊤)) (x : X) :
    X.presheaf.Γgerm x ((Γ.map φ.op).hom a) = (φ.stalkMap x).hom (Y.presheaf.Γgerm (φ.base x) a) :=
  (stalkMap_germ_apply φ ⊤ x trivial a).symm

/-- **The image of an open subspace inclusion is that open subset.**

It lives here, next to the composite version below, rather than in
`Oka/Geometry/RingedSpace/OpenImmersion.lean` where `restrictLE` consumes it: nothing about it
needs open-immersion theory, and `LocallyRingedSpace.ofRestrict` — the thing it is about — is
mirrored from the Mathlib file this one mirrors. -/
theorem range_ofRestrict (X : LocallyRingedSpace.{u}) (V : Opens X) :
    Set.range (X.ofRestrict V.isOpenEmbedding).base = (V : Set X) :=
  Subtype.range_val

/-- **The image of the composite of two open subspace inclusions** `X|S|T ⟶ X|S ⟶ X` is the
image of `T` under the inclusion of `S`.

The point of stating it this way rather than as `S ⊓ T'` for `T` the preimage of some `T'` is
that `T` is an arbitrary open of `X|S`, which is the shape a chart of a restricted analytic
space arrives in. -/
lemma range_ofRestrict_comp (A : LocallyRingedSpace.{u}) (S : Opens A)
    (T : Opens (A.restrict S.isOpenEmbedding)) :
    Set.range (((A.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding ≫
        A.ofRestrict S.isOpenEmbedding).base) =
      ((S.isOpenEmbedding.isOpenMap.functor.obj T : Opens A) : Set A) := by
  ext z
  constructor
  · rintro ⟨w, rfl⟩
    exact ⟨w.1, w.2, rfl⟩
  · rintro ⟨y, hy, rfl⟩
    exact ⟨⟨y, hy⟩, rfl⟩

/-- **Any two morphisms out of a locally ringed space with no points are equal.**

There are no points, so the base maps agree and `hom_stalk_ext`'s remaining obligation is
vacuous. `hom_ext_restrict_of_isEmpty` below is the specialisation callers actually meet, but
this is the statement the proof makes: `restrict` plays no part in it.

Beyond generality for its own sake, it is the form needed to discharge the compatibility
hypothesis of `AlgebraicGeometry.LocallyRingedSpace.OpenCover.existsUnique_glueMorphisms`, which
is an equation of morphisms out of the *categorical pullback* — a space that is not a `restrict`
of anything and whose emptiness is what
`AlgebraicGeometry.LocallyRingedSpace.IsOpenImmersion.range_pullback_to_base_of_left` computes.

The hypothesis is explicit rather than an `[IsEmpty X]` instance because the carrier of
`X.restrict V` for an empty `V` is not something instance search finds, so the wrapper below
would have to build the term regardless. -/
theorem hom_ext_of_isEmpty {X Y : LocallyRingedSpace.{u}} (hX : IsEmpty X) (f g : X ⟶ Y) :
    f = g :=
  hom_stalk_ext f g (ConcreteCategory.hom_ext _ _ fun x ↦ (hX.elim x)) fun x ↦ (hX.elim x)

/-- **Any two morphisms out of the restriction to an empty open subset are equal.**

This is what makes a compatibility condition on a *disjoint* pair of members of an open cover
free — see `existsUnique_glueMorphisms_of_opens` in
`Oka/Geometry/RingedSpace/PresheafedSpace/Gluing.lean`. Stated with the carrier being empty
rather than with `V = ⊥` so that no transport along an equation of opens is needed; that, and
not the emptiness argument, is the whole reason it exists beside `hom_ext_of_isEmpty`. -/
theorem hom_ext_restrict_of_isEmpty {V : Opens X} (hV : (V : Set X) = ∅)
    (f g : X.restrict V.isOpenEmbedding ⟶ Y) : f = g :=
  hom_ext_of_isEmpty (X := X.restrict V.isOpenEmbedding)
    ⟨fun x ↦ Set.eq_empty_iff_forall_notMem.1 hV x.1 x.2⟩ f g

/-- **Pulling a global section back along the inclusion of an open subspace is restricting
it.**

Both sides are the map `𝒪_X(⊤) ⟶ 𝒪_X(U)` and `Opens X` is a preorder category, so there is only
one such map; the proof is the same `change`/`congr` as
`ComplexAnalytic.isCLinearHom_ofRestrict`. The open indexing the right-hand side is
`U.isOpenEmbedding.isOpenMap.functor.obj ⊤` rather than `U`, because that is how the global
sections of `X|U` are indexed — the two have the same points and are not definitionally
equal. -/
lemma Γ_map_ofRestrict_apply (X : LocallyRingedSpace.{u}) (U : Opens X)
    (s : X.presheaf.obj (op ⊤)) :
    (Γ.map (X.ofRestrict U.isOpenEmbedding).op).hom s =
      (X.presheaf.map (homOfLE (le_top :
        U.isOpenEmbedding.isOpenMap.functor.obj ⊤ ≤ ⊤)).op).hom s := by
  change ((X.ofRestrict U.isOpenEmbedding).c.app (op ⊤)).hom s = _
  change (X.presheaf.map _).hom s = (X.presheaf.map _).hom s
  congr 2

/-- **Pulling an algebra structure back along a composite is pulling it back twice.**
`Γ_map_comp_apply` at each constant. -/
lemma comapAlgMap_comp {R : Type*} [NonAssocSemiring R] {Z : LocallyRingedSpace.{u}} (f : X ⟶ Y)
    (g : Y ⟶ Z) (γ : R →+* Z.presheaf.obj (op ⊤)) :
    comapAlgMap (f ≫ g) γ = comapAlgMap f (comapAlgMap g γ) :=
  RingHom.ext fun c ↦ Γ_map_comp_apply f g (γ c)

/-- **Pulling an algebra structure back along an isomorphism loses nothing.**

Two structures on `Γ(Y, 𝒪_Y)` with the same pullback along `e.hom` are equal, because
`Γ.map e.inv.op` undoes `Γ.map e.hom.op` — `Γ_map_inv_hom_apply`, which is proved without
computing either direction. This is what says that transporting an algebra structure across an
identification of two presentations of the same space is a bijection and not merely a map. -/
lemma comapAlgMap_hom_injective {R : Type*} [NonAssocSemiring R] (e : X ≅ Y) :
    Function.Injective fun α : R →+* Y.presheaf.obj (op ⊤) ↦ comapAlgMap e.hom α :=
  fun α α' h ↦ RingHom.ext fun c ↦ by
    have h' : (Γ.map e.hom.op).hom (α c) = (Γ.map e.hom.op).hom (α' c) :=
      congrArg (fun m : R →+* X.presheaf.obj (op ⊤) ↦ m c) h
    have h'' := congrArg (fun a ↦ (Γ.map e.inv.op).hom a) h'
    rw [Γ_map_inv_hom_apply, Γ_map_inv_hom_apply] at h''
    exact h''

/-- **Pulling an algebra structure back along the inclusion of an open subspace is restricting
it**: `AlgebraicGeometry.LocallyRingedSpace.comapAlgMap` at `ofRestrict` is
`AlgebraicGeometry.LocallyRingedSpace.resAlgMap`.

This is `Γ_map_ofRestrict_apply` at each constant, and it is what lets a statement about an
abstract open subspace be read as a statement about a restriction. -/
lemma comapAlgMap_ofRestrict {R : Type*} [NonAssocSemiring R] (X : LocallyRingedSpace.{u})
    (α : R →+* X.presheaf.obj (op ⊤)) (U : Opens X) :
    comapAlgMap (X.ofRestrict U.isOpenEmbedding) α = X.resAlgMap α U :=
  RingHom.ext fun c ↦ X.Γ_map_ofRestrict_apply U (α c)

/-- **The germ on `X|U` of the restriction of a global section is its germ on `X`**, across the
identification of the stalks of an open subspace with the stalks of the ambient space.

This is `restrictStalkIso_hom_stalkAlgMap` with an arbitrary global section in place of a
constant, and it is proved the same way. -/
lemma germ_Γ_map_ofRestrict (X : LocallyRingedSpace.{u}) (U : Opens X)
    (s : X.presheaf.obj (op ⊤)) (x : X.restrict U.isOpenEmbedding) :
    (X.restrictStalkIso U.isOpenEmbedding x).hom
        ((X.restrict U.isOpenEmbedding).presheaf.germ ⊤ x trivial
          ((Γ.map (X.ofRestrict U.isOpenEmbedding).op).hom s)) =
      X.presheaf.germ ⊤ x.1 trivial s := by
  rw [Γ_map_ofRestrict_apply, restrictStalkIso_hom_eq_germ_apply]
  exact X.presheaf.germ_res_apply (homOfLE le_top) x.1 _ s

/-- **Two global sections which agree on every member of an open cover are equal.**

The structure sheaf is a sheaf, so `TopCat.Presheaf.section_ext` reduces this to an equality of
germs, and `germ_Γ_map_ofRestrict` reads the germ of a restricted section off the germ of the
section. The cover is given as a family of opens together with the statement that every point
lies in one of them, which is the shape `existsUnique_glueMorphisms_of_opens` takes and so the
shape a caller already has.

Stated with the restrictions spelled as `Γ.map (X.ofRestrict _).op` rather than as
`X.presheaf.map`, because that is the spelling in which a morphism out of `X|U` produces
them. -/
theorem section_ext_of_cover (X : LocallyRingedSpace.{u}) {ι : Type*} (U : ι → Opens X)
    (hU : ∀ x : X, ∃ i, x ∈ U i) (s t : X.presheaf.obj (op ⊤))
    (h : ∀ i, (Γ.map (X.ofRestrict (U i).isOpenEmbedding).op).hom s =
      (Γ.map (X.ofRestrict (U i).isOpenEmbedding).op).hom t) :
    s = t := by
  refine TopCat.Presheaf.section_ext X.sheaf ⊤ s t fun x _ ↦ ?_
  obtain ⟨i, hi⟩ := hU x
  have key := congrArg (fun a ↦ (X.restrictStalkIso (U i).isOpenEmbedding
      (⟨x, hi⟩ : X.restrict (U i).isOpenEmbedding)).hom
    ((X.restrict (U i).isOpenEmbedding).presheaf.germ ⊤ ⟨x, hi⟩ trivial a)) (h i)
  exact (X.germ_Γ_map_ofRestrict (U i) s ⟨x, hi⟩).symm.trans
    (key.trans (X.germ_Γ_map_ofRestrict (U i) t ⟨x, hi⟩))

/-! ### Sections over an open subset, as global sections of the open subspace

The three inequalities between opens that the section below runs on are all Mathlib's, and are
spelled inline at their call sites rather than restated here:

* `U.functor.obj ⊤ ≤ U` is `(TopologicalSpace.Opens.isOpenEmbedding_obj_top U).le`. The
  underlying **equation** `U.functor.obj ⊤ = U` is a Mathlib `@[simp]` lemma, so it is free; what
  is not free is *transporting* along it, which is why only the `≤` is ever used.
* `O₁ ≤ O₂ → U.functor.obj O₁ ≤ U.functor.obj O₂` is functoriality,
  `(U.isOpenEmbedding.isOpenMap.functor.map (homOfLE h)).le`.
* `O ≤ (Opens.map ι).obj (U.functor.obj O)` is the unit of `IsOpenMap.adjunction`,
  `(U.isOpenEmbedding.isOpenMap.adjunction.unit.app O).le`.
-/

/-- **A section over `U` as a global section of `X|U`.**

The global sections of `X|U` are indexed by `U.isOpenEmbedding.isOpenMap.functor.obj ⊤`, which
has the same points as `U` and is not definitionally equal to it, so the two rings are different
types and a section over `U` has to be *restricted* to become a global section of `X|U`. An
`abbrev`, so that a caller holding the restriction map recognises it without unfolding. -/
abbrev toRestrictΓ (X : LocallyRingedSpace.{u}) (U : Opens X) (u : X.presheaf.obj (op U)) :
    (X.restrict U.isOpenEmbedding).presheaf.obj (op ⊤) :=
  (X.presheaf.map (homOfLE (Opens.isOpenEmbedding_obj_top U).le).op).hom u

/-- **A germ on an open subspace is the image of a germ upstairs**, under the stalk map of the
inclusion.

This is the one tool every germ computation about open subspaces in this file and in
`Oka/AnalyticSpace/Restrict.lean` runs through. Its point is that it needs **no equation of
opens**: `germ_res_apply` moves a germ across the unit of `IsOpenMap.adjunction`, and the
leftover restriction map
is the identity because `Opens X` is a preorder and there is only one morphism
`U.functor.obj O ⟶ U.functor.obj O`. -/
lemma germ_eq_stalkMap_ofRestrict (X : LocallyRingedSpace.{u}) (U : Opens X)
    (O : Opens (X.restrict U.isOpenEmbedding)) (w : X.restrict U.isOpenEmbedding) (hO : w ∈ O)
    (b : (X.restrict U.isOpenEmbedding).presheaf.obj (op O)) :
    (X.restrict U.isOpenEmbedding).presheaf.germ O w hO b =
      ((X.ofRestrict U.isOpenEmbedding).stalkMap w).hom
        (X.presheaf.germ (U.isOpenEmbedding.isOpenMap.functor.obj O) w.1 ⟨w, hO, rfl⟩ b) := by
  have hid : ∀ f : op (U.isOpenEmbedding.isOpenMap.functor.obj O) ⟶
      op (U.isOpenEmbedding.isOpenMap.functor.obj O), (X.presheaf.map f).hom b = b := by
    intro f
    rw [Subsingleton.elim f (𝟙 _)]
    exact (ConcreteCategory.congr_hom (X.presheaf.map_id
      (op (U.isOpenEmbedding.isOpenMap.functor.obj O))) b).trans (ConcreteCategory.id_apply _)
  refine Eq.trans ?_ (stalkMap_germ_apply (X.ofRestrict U.isOpenEmbedding)
    (U.isOpenEmbedding.isOpenMap.functor.obj O) w ⟨w, hO, rfl⟩ b).symm
  refine Eq.trans ?_ ((X.restrict U.isOpenEmbedding).presheaf.germ_res_apply
    (homOfLE (U.isOpenEmbedding.isOpenMap.adjunction.unit.app O).le) w hO _)
  refine congrArg ((X.restrict U.isOpenEmbedding).presheaf.germ O w hO) ?_
  change b = (X.presheaf.map _).hom ((X.presheaf.map _).hom b)
  rw [← ConcreteCategory.comp_apply, ← X.presheaf.map_comp]
  exact (hid _).symm

/-- `germ_eq_stalkMap_ofRestrict` at the top open, for a section written as a
`toRestrictΓ`. -/
lemma Γgerm_toRestrictΓ (X : LocallyRingedSpace.{u}) (U : Opens X)
    (u : X.presheaf.obj (op U)) (w : X.restrict U.isOpenEmbedding) :
    (X.restrict U.isOpenEmbedding).presheaf.Γgerm w (X.toRestrictΓ U u) =
      ((X.ofRestrict U.isOpenEmbedding).stalkMap w).hom (X.presheaf.germ U w.1 w.2 u) :=
  (X.germ_eq_stalkMap_ofRestrict U ⊤ w trivial _).trans
    (congrArg ((X.ofRestrict U.isOpenEmbedding).stalkMap w).hom
      (X.presheaf.germ_res_apply (homOfLE (Opens.isOpenEmbedding_obj_top U).le) w.1
        ⟨w, trivial, rfl⟩ u))

/-- Two restrictions composed is one restriction. The three inequalities are unrelated inputs:
`Opens X` is a preorder, so any two morphisms with the same source and target are equal. -/
lemma map_map_apply (X : LocallyRingedSpace.{u}) {O₁ O₂ O₃ : Opens X} (h₁ : O₁ ≤ O₂)
    (h₂ : O₂ ≤ O₃) (h₃ : O₁ ≤ O₃) (s : X.presheaf.obj (op O₃)) :
    (X.presheaf.map (homOfLE h₁).op).hom ((X.presheaf.map (homOfLE h₂).op).hom s) =
      (X.presheaf.map (homOfLE h₃).op).hom s := by
  rw [← ConcreteCategory.comp_apply, ← X.presheaf.map_comp]
  congr 2

/-- **Restriction on `X|U` is restriction on `X`**, between the corresponding opens. -/
lemma restrict_map_apply (X : LocallyRingedSpace.{u}) (U : Opens X)
    {O₁ O₂ : Opens (X.restrict U.isOpenEmbedding)} (h : O₁ ≤ O₂)
    (h' : U.isOpenEmbedding.isOpenMap.functor.obj O₁ ≤
      U.isOpenEmbedding.isOpenMap.functor.obj O₂)
    (s : (X.restrict U.isOpenEmbedding).presheaf.obj (op O₂)) :
    ((X.restrict U.isOpenEmbedding).presheaf.map (homOfLE h).op).hom s =
      (X.presheaf.map (homOfLE h').op).hom s := by
  change (X.presheaf.map _).hom s = _
  congr 2

/-- **Pulling a section back along a morphism of open subspaces over `X` restricts it.**

`α` is any morphism `X|W ⟶ X|U|T` commuting with the two inclusions into `X`; no assumption is
made about how it was built, and in the intended application it is an
`IsOpenImmersion.lift`, whose sheaf map is not otherwise computable. The proof is entirely on
stalks: `germ_eq_stalkMap_ofRestrict` twice, `stalkMap_congr_hom` against the factorisation, and
`stalkCongr_hom_germ` to move the germ to the point the factorisation names. -/
lemma Γ_map_over_ambient (X : LocallyRingedSpace.{u}) (S : Opens X)
    (T : Opens (X.restrict S.isOpenEmbedding)) (W : Opens X)
    (hW : W ≤ S.isOpenEmbedding.isOpenMap.functor.obj T)
    (α : X.restrict W.isOpenEmbedding ⟶
      (X.restrict S.isOpenEmbedding).restrict T.isOpenEmbedding)
    (hα : α ≫ ((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding ≫
      X.ofRestrict S.isOpenEmbedding) = X.ofRestrict W.isOpenEmbedding)
    (a : (X.restrict S.isOpenEmbedding).presheaf.obj (op T)) :
    (Γ.map α.op).hom ((X.restrict S.isOpenEmbedding).toRestrictΓ T a) =
      X.toRestrictΓ W ((X.presheaf.map (homOfLE hW).op).hom a) := by
  refine TopCat.Presheaf.section_ext (X.restrict W.isOpenEmbedding).sheaf ⊤ _ _ fun y _ ↦ ?_
  have hcomp : ((X.ofRestrict S.isOpenEmbedding).stalkMap
        (((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding).base (α.base y)) ≫
      ((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding).stalkMap (α.base y) ≫
        α.stalkMap y) =
      (X.presheaf.stalkCongr (Inseparable.of_eq
        (congrArg (fun m : X.restrict W.isOpenEmbedding ⟶ X ↦
          (ConcreteCategory.hom m.base) y) hα))).hom ≫
        (X.ofRestrict W.isOpenEmbedding).stalkMap y :=
    (congrArg (fun m ↦ (X.ofRestrict S.isOpenEmbedding).stalkMap
        (((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding).base (α.base y)) ≫ m)
      (stalkMap_comp α ((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding) y).symm).trans
      ((stalkMap_comp (α ≫ (X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding)
          (X.ofRestrict S.isOpenEmbedding) y).symm.trans
        (stalkMap_congr_hom _ _ ((Category.assoc α
          ((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding)
          (X.ofRestrict S.isOpenEmbedding)).trans hα) y))
  refine Eq.trans (Γgerm_Γ_map α _ y) ?_
  refine Eq.trans (congrArg (fun b ↦ (α.stalkMap y).hom b)
    ((X.restrict S.isOpenEmbedding).Γgerm_toRestrictΓ T a (α.base y))) ?_
  refine Eq.trans (congrArg (fun b ↦ (α.stalkMap y).hom
      ((((X.restrict S.isOpenEmbedding).ofRestrict T.isOpenEmbedding).stalkMap (α.base y)).hom b))
    (X.germ_eq_stalkMap_ofRestrict S T (α.base y).1 (α.base y).2 a)) ?_
  refine Eq.trans (ConcreteCategory.comp_apply _ _ _).symm ?_
  refine Eq.trans (ConcreteCategory.comp_apply _ _ _).symm ?_
  refine Eq.trans (congrArg (fun m ↦ m.hom (X.presheaf.germ
      (S.isOpenEmbedding.isOpenMap.functor.obj T) _ ⟨(α.base y).1, (α.base y).2, rfl⟩ a)) hcomp) ?_
  refine Eq.trans (ConcreteCategory.comp_apply _ _ _) ?_
  refine Eq.trans (congrArg ((X.ofRestrict W.isOpenEmbedding).stalkMap y).hom
    (TopCat.Presheaf.stalkCongr_hom_germ X.presheaf _
      (S.isOpenEmbedding.isOpenMap.functor.obj T) _ (hW y.2) a)) ?_
  refine Eq.trans ?_ (X.Γgerm_toRestrictΓ W _ y).symm
  exact (congrArg ((X.ofRestrict W.isOpenEmbedding).stalkMap y).hom
    (X.presheaf.germ_res_apply (homOfLE hW) y.1 y.2 a)).symm

/-! ### Gluing an algebra structure over an open cover

`resAlgMap` restricts an algebra structure from a space to an open subspace. This section is the
converse, and the asymmetry between the two is the point: `resAlgMap` is a composition and costs
nothing, while going back is a **gluing** and needs the sheaf condition, because an algebra
structure is a map into *global* sections.

Everything here is `TopCat.Sheaf.existsUnique_gluing'` at `V = ⊤`. The only thing worth saying is
how the ring homomorphism is obtained: **not** by gluing a homomorphism, but by gluing the section
`α c` for each `c` separately and then reading the four ring axioms off the *uniqueness* half —
both sides of each axiom restrict to the same thing on every member of the cover, so they are
equal. Trying it the other way round means carrying the axioms through the gluing.

The opens are indexed as `U i` here rather than as `(U i).functor.obj ⊤`, which is the opposite of
the convention in the section above; `resAlgMap_glueAlgMap` is where the two meet, and it is the
only place in this section that has to cross that seam.
-/

variable {ι : Type*} {U : ι → Opens X}

/-- **A compatible family of sections over an open cover of `X` glues to a unique global
section.** `TopCat.Sheaf.existsUnique_gluing'` at `V = ⊤`. -/
theorem existsUnique_glueSection (hU : ⨆ i, U i = ⊤)
    (s : ∀ i, X.presheaf.obj (op (U i)))
    (h : TopCat.Presheaf.IsCompatible X.presheaf U s) :
    ∃! t : X.presheaf.obj (op ⊤),
      ∀ i, (X.presheaf.map (homOfLE (le_top : U i ≤ ⊤)).op).hom t = s i :=
  X.sheaf.existsUnique_gluing' U ⊤ (fun _ ↦ homOfLE le_top) (le_of_eq hU.symm) s h

/-- The global section a compatible family glues to. -/
noncomputable def glueSection (hU : ⨆ i, U i = ⊤) (s : ∀ i, X.presheaf.obj (op (U i)))
    (h : TopCat.Presheaf.IsCompatible X.presheaf U s) : X.presheaf.obj (op ⊤) :=
  (existsUnique_glueSection hU s h).choose

@[simp]
lemma map_glueSection (hU : ⨆ i, U i = ⊤) (s : ∀ i, X.presheaf.obj (op (U i)))
    (h : TopCat.Presheaf.IsCompatible X.presheaf U s) (i : ι) :
    (X.presheaf.map (homOfLE (le_top : U i ≤ ⊤)).op).hom (glueSection hU s h) = s i :=
  (existsUnique_glueSection hU s h).choose_spec.1 i

/-- **Anything restricting to the family on every member of the cover is the gluing.** This is
the uniqueness half, and it is what proves the ring axioms of `glueAlgMap` below. -/
lemma glueSection_eq (hU : ⨆ i, U i = ⊤) (s : ∀ i, X.presheaf.obj (op (U i)))
    (h : TopCat.Presheaf.IsCompatible X.presheaf U s) (t : X.presheaf.obj (op ⊤))
    (ht : ∀ i, (X.presheaf.map (homOfLE (le_top : U i ≤ ⊤)).op).hom t = s i) :
    glueSection hU s h = t :=
  ((existsUnique_glueSection hU s h).choose_spec.2 t ht).symm

/-- **The restrictions of one global section to the members of a cover form a compatible
family.** Both sides of the compatibility condition are the restriction to `U i ⊓ U j`, and
`Opens X` is a preorder category, so there is only one such map. -/
lemma isCompatible_map_le_top (t : X.presheaf.obj (op ⊤)) :
    TopCat.Presheaf.IsCompatible X.presheaf U
      fun i ↦ (X.presheaf.map (homOfLE (le_top : U i ≤ ⊤)).op).hom t := fun i j ↦ by
  change ((X.presheaf.map _) ≫ (X.presheaf.map _)).hom t =
    ((X.presheaf.map _) ≫ (X.presheaf.map _)).hom t
  rw [← X.presheaf.map_comp, ← X.presheaf.map_comp]
  congr 2

/-- **Gluing the restrictions of a global section returns that section.** The round trip, and
the cheapest witness that `glueSection` is not vacuous. -/
@[simp]
lemma glueSection_map_le_top (hU : ⨆ i, U i = ⊤) (t : X.presheaf.obj (op ⊤)) :
    glueSection hU _ (isCompatible_map_le_top t) = t :=
  glueSection_eq _ _ _ t fun _ ↦ rfl

/-- **Restricting in two steps.** `resAlgMap` restricts a global section all the way to
`U.functor.obj ⊤`; this factors that through the sections over `U`, which is the indexing a
family given on the members of a cover arrives in. -/
lemma resAlgMap_eq_comp {R : Type*} [NonAssocSemiring R] (α : R →+* X.presheaf.obj (op ⊤))
    (V : Opens X) :
    X.resAlgMap α V =
      (X.presheaf.map (homOfLE (Opens.isOpenEmbedding_obj_top V).le).op).hom.comp
        ((X.presheaf.map (homOfLE (le_top : V ≤ ⊤)).op).hom.comp α) :=
  RingHom.ext fun c ↦ by
    change (X.presheaf.map _).hom _ = (X.presheaf.map _).hom ((X.presheaf.map _).hom (α c))
    change _ = ((X.presheaf.map _) ≫ (X.presheaf.map _)).hom _
    rw [← X.presheaf.map_comp]
    congr 2

section GlueAlgMap

variable {R : Type*} [CommRing R] (hU : ⨆ i, U i = ⊤) (α : ∀ i, R →+* X.presheaf.obj (op (U i)))
  (h : ∀ c : R, TopCat.Presheaf.IsCompatible X.presheaf U fun i ↦ α i c)

/-- **An algebra structure on `𝒪_X` glued from compatible algebra structures over an open
cover.**

The underlying function sends `c` to the gluing of the family `α i c`; each of the four ring
axioms is an instance of `glueSection_eq`, because both sides restrict to the same section on
every member of the cover. -/
noncomputable def glueAlgMap : R →+* X.presheaf.obj (op ⊤) where
  toFun c := glueSection hU (fun i ↦ α i c) (h c)
  map_one' := glueSection_eq _ _ _ 1 fun i ↦ (map_one _).trans (map_one (α i)).symm
  map_mul' a b := glueSection_eq _ _ _ _ fun i ↦ (map_mul _ _ _).trans
    ((congrArg₂ (· * ·) (map_glueSection hU _ (h a) i)
      (map_glueSection hU _ (h b) i)).trans (map_mul (α i) a b).symm)
  map_zero' := glueSection_eq _ _ _ 0 fun i ↦ (map_zero _).trans (map_zero (α i)).symm
  map_add' a b := glueSection_eq _ _ _ _ fun i ↦ (map_add _ _ _).trans
    ((congrArg₂ (· + ·) (map_glueSection hU _ (h a) i)
      (map_glueSection hU _ (h b) i)).trans (map_add (α i) a b).symm)

@[simp]
lemma map_glueAlgMap (i : ι) (c : R) :
    (X.presheaf.map (homOfLE (le_top : U i ≤ ⊤)).op).hom (glueAlgMap hU α h c) = α i c :=
  map_glueSection hU (fun i ↦ α i c) (h c) i

/-- **Restricting the glued algebra structure to a member of the cover returns the given one**,
across the `functor.obj ⊤`-versus-`U i` seam.

`resAlgMap` lands in `Γ(X|U i)`, indexed by `(U i).functor.obj ⊤`; the family `α` is indexed by
`U i`. The two are not definitionally equal, so the statement cannot be `= α i` and the
right-hand side has to carry the restriction `Γ(X, U i) ⟶ Γ(X, (U i).functor.obj ⊤)`. This is the
same map `toRestrictΓ` is, and this lemma is what lets a caller feed a family of algebra
structures on the members of a cover to `ComplexAnalytic.AnalyticSpace.ofOpens`. -/
lemma resAlgMap_glueAlgMap (i : ι) :
    X.resAlgMap (glueAlgMap hU α h) (U i) =
      (X.presheaf.map (homOfLE (Opens.isOpenEmbedding_obj_top (U i)).le).op).hom.comp (α i) :=
  RingHom.ext fun c ↦ by
    change (X.presheaf.map _).hom _ = (X.presheaf.map _).hom ((α i) c)
    rw [← map_glueAlgMap hU α h i c]
    change _ = ((X.presheaf.map _) ≫ (X.presheaf.map _)).hom _
    rw [← X.presheaf.map_comp]
    congr 2

end GlueAlgMap

section GlueAlgMapRestrict

/-- **A family of opens and the family of images of the global opens of the corresponding open
subspaces have the same supremum** — indeed they are the same family, by
`TopologicalSpace.Opens.isOpenEmbedding_obj_top` at each index. It is stated because the two
spellings index the two sides of the seam this section exists to cross. -/
lemma iSup_isOpenEmbedding_obj_top {ι : Type*} (U : ι → Opens X) :
    ⨆ i, (U i).isOpenEmbedding.isOpenMap.functor.obj ⊤ = ⨆ i, U i :=
  iSup_congr fun i ↦ Opens.isOpenEmbedding_obj_top (U i)

variable {R : Type*} [CommRing R] {ι : Type*} {U : ι → Opens X}

/-- **An algebra structure on `𝒪_X` glued from algebra structures on the global sections of the
members of an open cover.**

`glueAlgMap` takes the family indexed by the opens `U i` themselves; this variant takes it
indexed by `Γ(X|U i, 𝒪)`, which is `X.presheaf.obj (op ((U i).functor.obj ⊤))` and *not*
`X.presheaf.obj (op (U i))`. The two differ by the seam this file's gluing section documents,
and the point of stating the variant is that **the seam then never has to be crossed**:
`resAlgMap_glueAlgMapRestrict` below is an equation on the nose, where `resAlgMap_glueAlgMap`
has to carry a restriction map on its right-hand side.

That is the indexing a cover whose members are *abstract* spaces produces — the structure one
has is on the global sections of the member, and no open of `X` is involved in stating it. -/
noncomputable def glueAlgMapRestrict (hU : ⨆ i, U i = ⊤)
    (β : ∀ i, R →+* (X.restrict (U i).isOpenEmbedding).presheaf.obj (op ⊤))
    (h : ∀ c : R, TopCat.Presheaf.IsCompatible X.presheaf
      (fun i ↦ (U i).isOpenEmbedding.isOpenMap.functor.obj ⊤) fun i ↦ β i c) :
    R →+* X.presheaf.obj (op ⊤) :=
  glueAlgMap ((iSup_isOpenEmbedding_obj_top U).trans hU) β h

/-- **Restricting the glued algebra structure to a member of the cover returns the given one.**

Unlike `resAlgMap_glueAlgMap` this is an equation of the two algebra structures themselves, with
no restriction map in the way: both sides land in `Γ(X|U i, 𝒪)`, and the restriction `resAlgMap`
applies is the very one `map_glueAlgMap` computes. -/
@[simp]
lemma resAlgMap_glueAlgMapRestrict (hU : ⨆ i, U i = ⊤)
    (β : ∀ i, R →+* (X.restrict (U i).isOpenEmbedding).presheaf.obj (op ⊤))
    (h : ∀ c : R, TopCat.Presheaf.IsCompatible X.presheaf
      (fun i ↦ (U i).isOpenEmbedding.isOpenMap.functor.obj ⊤) fun i ↦ β i c) (i : ι) :
    X.resAlgMap (glueAlgMapRestrict hU β h) (U i) = β i :=
  RingHom.ext fun c ↦ map_glueAlgMap ((iSup_isOpenEmbedding_obj_top U).trans hU) β h i c

end GlueAlgMapRestrict

section Sections

variable (Y : LocallyRingedSpace.{u})

/-- Restriction of a section of the structure sheaf to a smaller open subset. -/
abbrev res {U V : Opens Y} (h : U ≤ V) (s : Y.presheaf.obj (op V)) : Y.presheaf.obj (op U) :=
  Y.presheaf.map (homOfLE h).op s

@[simp]
lemma res_self {U : Opens Y} (s : Y.presheaf.obj (op U)) : Y.res le_rfl s = s := by
  rw [res, show (homOfLE (le_refl U)).op = 𝟙 (op U) from Subsingleton.elim _ _,
    show Y.presheaf.map (𝟙 (op U)) = 𝟙 _ from Y.presheaf.map_id _]
  rfl

@[simp]
lemma res_res {U V W : Opens Y} (h₁ : U ≤ V) (h₂ : V ≤ W) (s : Y.presheaf.obj (op W)) :
    Y.res h₁ (Y.res h₂ s) = Y.res (h₁.trans h₂) s := by
  rw [res, res, res, ← ConcreteCategory.comp_apply, ← Functor.map_comp]
  rfl

lemma res_sum {U V : Opens Y} (h : U ≤ V) {κ : Type*} (t : Finset κ)
    (u : κ → Y.presheaf.obj (op V)) : Y.res h (∑ i ∈ t, u i) = ∑ i ∈ t, Y.res h (u i) :=
  map_sum (Y.presheaf.map (homOfLE h).op).hom u t

lemma res_mul {U V : Opens Y} (h : U ≤ V) (s t : Y.presheaf.obj (op V)) :
    Y.res h (s * t) = Y.res h s * Y.res h t :=
  map_mul (Y.presheaf.map (homOfLE h).op).hom s t

lemma res_zero {U V : Opens Y} (h : U ≤ V) : Y.res h (0 : Y.presheaf.obj (op V)) = 0 :=
  map_zero (Y.presheaf.map (homOfLE h).op).hom

end Sections

section Restrict

variable {X : LocallyRingedSpace.{u}} (U : Opens X)

/-- An open subset of the open subspace `U`, viewed as an open subset of `X`. -/
abbrev imOpen (W : Opens (X.restrict U.isOpenEmbedding)) : Opens X :=
  U.isOpenEmbedding.isOpenMap.functor.obj W

/-- An open subset of `X`, viewed as an open subset of the open subspace `U`. -/
abbrev preOpen (V : Opens X) : Opens (X.restrict U.isOpenEmbedding) :=
  ⟨Subtype.val ⁻¹' (V : Set X), V.isOpen.preimage continuous_subtype_val⟩

@[simp]
lemma restrict_res {W W' : Opens (X.restrict U.isOpenEmbedding)} (h : W' ≤ W)
    (s : (X.restrict U.isOpenEmbedding).presheaf.obj (op W)) :
    (X.restrict U.isOpenEmbedding).res h s = X.res (Set.image_mono h) s :=
  rfl

lemma imOpen_le (W : Opens (X.restrict U.isOpenEmbedding)) : imOpen U W ≤ U := by
  rintro x ⟨y, _, rfl⟩; exact y.2

lemma imOpen_preOpen {V : Opens X} (hVU : V ≤ U) : imOpen U (preOpen U V) = V := by
  ext x
  exact ⟨by rintro ⟨y, hy, rfl⟩; exact hy, fun hx ↦ ⟨⟨x, hVU hx⟩, hx, rfl⟩⟩

lemma preOpen_le_of_le_imOpen {V : Opens X} {W : Opens (X.restrict U.isOpenEmbedding)}
    (h : V ≤ imOpen U W) : preOpen U V ≤ W := by
  intro z hz
  obtain ⟨w, hw, hwz⟩ := h hz
  exact (Subtype.val_injective hwz) ▸ hw

lemma preOpen_imOpen (V : Opens (X.restrict U.isOpenEmbedding)) : preOpen U (imOpen U V) = V := by
  ext z
  exact ⟨by rintro ⟨w, hw, hwz⟩; exact (Subtype.val_injective hwz) ▸ hw,
    fun hz ↦ ⟨z, hz, rfl⟩⟩

end Restrict

section LocalModel

variable {Y : LocallyRingedSpace.{u}}

lemma germ_res {U V : Opens Y} (h : U ≤ V) (y : Y) (hy : y ∈ U) (s : Y.presheaf.obj (op V)) :
    Y.presheaf.germ U y hy (Y.res h s) = Y.presheaf.germ V y (h hy) s :=
  TopCat.Presheaf.germ_res_apply _ (homOfLE h) y hy s

/-- If the germ at `y` of a section `t` lies in the ideal generated by the germs of global
sections `f₁, …, f_k`, then on a neighbourhood of `y` the section `t` is an `𝒪_Y`-combination
of the `fⱼ`. -/
lemma exists_localCombination {A : Opens Y} (t : Y.presheaf.obj (op A)) {k : ℕ}
    (f : Fin k → Y.presheaf.obj (op ⊤)) (y : Y) (hy : y ∈ A)
    (h : Y.presheaf.germ A y hy t ∈
      Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm y (f j))) :
    ∃ (A' : Opens Y) (hA' : A' ≤ A), y ∈ A' ∧ ∃ c : Fin k → Y.presheaf.obj (op A'),
      Y.res hA' t = ∑ j, c j * Y.res le_top (f j) := by
  classical
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).1 h
  choose A₀ hA₀ c₀ hc₀ using fun j ↦ Y.presheaf.exists_germ_eq (c j)
  set A' : Opens Y := ⟨(A : Set Y) ∩ ⋂ j, {z : Y | z ∈ A₀ j},
    A.isOpen.inter (isOpen_iInter_of_finite fun j ↦ (A₀ j).isOpen)⟩ with hA'def
  have hyA' : y ∈ A' := ⟨hy, Set.mem_iInter.2 hA₀⟩
  have hA'A : A' ≤ A := fun z hz ↦ hz.1
  have hA'j : ∀ j, A' ≤ (A₀ j : Opens Y) := fun j z hz ↦ Set.mem_iInter.1 hz.2 j
  have key : Y.presheaf.germ A' y hyA' (Y.res hA'A t) =
      Y.presheaf.germ A' y hyA' (∑ j, Y.res (hA'j j) (c₀ j) * Y.res le_top (f j)) := by
    rw [germ_res, map_sum]
    have hterm : ∀ j, Y.presheaf.germ A' y hyA'
        (Y.res (hA'j j) (c₀ j) * Y.res le_top (f j)) = c j * Y.presheaf.Γgerm y (f j) := by
      intro j
      rw [map_mul, germ_res, germ_res, hc₀ j]
      rfl
    simp only [hterm, ← hc, smul_eq_mul]
  obtain ⟨W, hyW, iU, iV, hW⟩ := Y.presheaf.germ_eq y hyA' hyA' _ _ key
  refine ⟨W, (leOfHom iU).trans hA'A, hyW,
    fun j ↦ Y.res (leOfHom iV) (Y.res (hA'j j) (c₀ j)), ?_⟩
  have h1 : Y.res (leOfHom iU) (Y.res hA'A t) =
      Y.res (leOfHom iV) (∑ j, Y.res (hA'j j) (c₀ j) * Y.res le_top (f j)) := hW
  rw [res_res] at h1
  rw [h1, res_sum]
  exact Finset.sum_congr rfl fun j _ ↦ by simp only [res_mul, res_res]


variable {M Y : LocallyRingedSpace.{u}} (i : M ⟶ Y)

/-- If `i : M ⟶ Y` is surjective on stalks, then every section of `𝒪_M` is, near each point of
its domain, the pullback along `i` of a section of `𝒪_Y`. -/
lemma exists_localLift (hsurj : ∀ x, Function.Surjective (i.stalkMap x).hom)
    {B : Opens M} (t : M.presheaf.obj (op B)) (x : M) (hx : x ∈ B) :
    ∃ (A : Opens Y) (_ : i.base x ∈ A) (u : Y.presheaf.obj (op A)) (B' : Opens M)
      (hB'B : B' ≤ B) (hB'A : B' ≤ (Opens.map i.base).obj A),
      x ∈ B' ∧ M.res hB'A (i.c.app (op A) u) = M.res hB'B t := by
  obtain ⟨v, hv⟩ := hsurj x (M.presheaf.germ B x hx t)
  obtain ⟨A, hA, u, hu⟩ := Y.presheaf.exists_germ_eq v
  have hgerm : M.presheaf.germ ((Opens.map i.base).obj A) x hA (i.c.app (op A) u) =
      M.presheaf.germ B x hx t := by
    rw [← LocallyRingedSpace.stalkMap_germ_apply i A x hA u, hu]
    exact hv
  obtain ⟨W, hxW, iU, iV, hW⟩ :=
    M.presheaf.germ_eq x hA hx (i.c.app (op A) u) t hgerm
  exact ⟨A, hA, u, W, leOfHom iV, leOfHom iU, hxW, hW⟩

/-- Pulling back along `i` commutes with restriction. -/
lemma c_app_res {A A' : Opens Y} (h : A' ≤ A) (u : Y.presheaf.obj (op A)) :
    i.c.app (op A') (Y.res h u) =
      M.res (show (Opens.map i.base).obj A' ≤ (Opens.map i.base).obj A from fun _ hz ↦ h hz)
        (i.c.app (op A) u) := by
  have h1 := ConcreteCategory.congr_hom (i.c.naturality (homOfLE h).op) u
  simp only [ConcreteCategory.comp_apply] at h1
  exact h1

/-- Simultaneous local lifting of finitely many sections along a morphism which is surjective
on stalks. -/
lemma exists_localLift_family (hsurj : ∀ x, Function.Surjective (i.stalkMap x).hom)
    {B₀ : Opens M} {m : ℕ} (s : Fin m → M.presheaf.obj (op B₀)) (x : M) (hx : x ∈ B₀) :
    ∃ (A : Opens Y) (_ : i.base x ∈ A) (t : Fin m → Y.presheaf.obj (op A))
      (B : Opens M) (hBB₀ : B ≤ B₀) (hBA : B ≤ (Opens.map i.base).obj A),
      x ∈ B ∧ ∀ j, M.res hBA (i.c.app (op A) (t j)) = M.res hBB₀ (s j) := by
  classical
  choose A hA u B hBB₀ hBA hxB hres using fun j ↦ exists_localLift i hsurj (s j) x hx
  set A' : Opens Y := ⟨⋂ j, {z : Y | z ∈ A j}, isOpen_iInter_of_finite fun j ↦ (A j).isOpen⟩
    with hA'def
  set B' : Opens M := ⟨(B₀ : Set M) ∩ ⋂ j, {z : M | z ∈ B j},
    B₀.isOpen.inter (isOpen_iInter_of_finite fun j ↦ (B j).isOpen)⟩ with hB'def
  have hA'j : ∀ j, A' ≤ A j := fun j z hz ↦ Set.mem_iInter.1 hz j
  have hB'j : ∀ j, B' ≤ B j := fun j z hz ↦ Set.mem_iInter.1 hz.2 j
  refine ⟨A', Set.mem_iInter.2 hA, fun j ↦ Y.res (hA'j j) (u j), B', fun z hz ↦ hz.1,
    fun z hz ↦ Set.mem_iInter.2 fun j ↦ hBA j (Set.mem_iInter.1 hz.2 j),
    ⟨hx, Set.mem_iInter.2 hxB⟩, fun j ↦ ?_⟩
  rw [c_app_res]
  have h1 := congrArg (M.res (hB'j j)) (hres j)
  simp only [res_res] at h1 ⊢
  exact h1

end LocalModel

/-! ### Stalk maps along a factorisation -/

/-- **Two out of three for stalk maps along a factorisation.** If `f ≫ g = h` and both `f` and
`h` induce isomorphisms on the stalk at `x`, then `g` induces one at `f.base x`.

`AlgebraicGeometry.LocallyRingedSpace.stalkMap_comp` supplies the factorisation of the stalk
maps and `CategoryTheory.IsIso.of_isIso_fac_right` cancels; the whole content is that the
composite is taken in the *opposite* order, `h.stalkMap x = g.stalkMap (f.base x) ≫ f.stalkMap x`,
because a stalk map runs from the target's stalk to the source's.

**Why the factorisation is an argument rather than something the caller rewrites with.**
`h.stalkMap x` lives over `h.base x` and `g.stalkMap (f.base x)` over `g.base (f.base x)`. Those
two points are equal only propositionally — the equality is `congrArg (·.base x)` applied to
`w` — so the two morphisms have equal but not definitionally equal types, and
`rw [← w]` on a hypothesis `IsIso (h.stalkMap x)` fails on the motive. Taking `w` as a hypothesis
with `h` a variable lets `subst` do it, and `subst` is the only tactic here that can: after it,
both sides are literally about `f ≫ g`. `AlgebraicGeometry.LocallyRingedSpace.stalkMap_congr_hom`
is the alternative and it produces a `TopCat.Presheaf.stalkSpecializes` that then has to be shown
invertible, which is more work for the same conclusion.

`hh` is explicit rather than instance-implicit because after `subst` its statement is about
`f ≫ g`, and instance search runs at reducible transparency and would not connect it to a goal
stated at `h`. -/
theorem isIso_stalkMap_of_comp {X Y Z : LocallyRingedSpace.{u}} (f : X ⟶ Y) (g : Y ⟶ Z)
    (h : X ⟶ Z) (w : f ≫ g = h) (x : X) [IsIso (f.stalkMap x)] (hh : IsIso (h.stalkMap x)) :
    IsIso (g.stalkMap (f.base x)) := by
  subst w
  exact IsIso.of_isIso_fac_right (hh := hh) (stalkMap_comp f g x).symm

end AlgebraicGeometry.LocallyRingedSpace
