/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.Geometry.RingedSpace.OpenImmersion
import Oka.ComplexSpace
import Oka.Geometry.RingedSpace.LocallyRingedSpace

/-!
# Complex analytic spaces

We define complex analytic spaces following the definition of `AlgebraicGeometry.Scheme` in
mathlib: an analytic space is a locally ringed space, equipped with a `ℂ`-algebra structure
on its structure sheaf, every point of which has an open neighbourhood which is — compatibly
with the `ℂ`-algebra structures — a *local model*.

A local model is the common zero locus `A` of finitely many holomorphic functions
`f₁, …, f_k` on an open subset `U ⊆ ℂ^n`, equipped with the structure sheaf
`(𝒪_U / (f₁, …, f_k))|_A`. Rather than constructing this quotient sheaf, we characterise the
result by the closed immersion `i : A ⟶ U` it comes with, in the style of
`AlgebraicGeometry.IsClosedImmersion`: the underlying map of `i` is a closed embedding onto
the zero locus of the `fⱼ`, the maps on stalks are surjective, and their kernels are the
ideals generated by the germs of the `fⱼ`. This determines `(A, 𝒪_A)` up to isomorphism and
is what the classical definition amounts to.

The `ℂ`-algebra structure is recorded as a ring homomorphism `ℂ →+* Γ(X, 𝒪_X)` into the
global sections; the ring of sections over every open subset then becomes a `ℂ`-algebra via
restriction. It cannot be omitted: a ring isomorphism between sheaves of holomorphic
functions may be conjugate-linear (complex conjugation is a ring automorphism of `ℂ`), so
locally ringed spaces which are merely locally isomorphic to local models also include
spaces glued along antiholomorphic transition maps — dianalytic spaces such as Klein
surfaces — and plain morphisms of locally ringed spaces include antiholomorphic maps such
as complex conjugation itself. Requiring charts (`AnalyticSpace.local_model`) and morphisms
(`AnalyticSpace.Hom`) to pull constant functions back to constants is precisely the
classical condition that a complex space is a `ℂ`-ringed space and that its morphisms are
morphisms of `ℂ`-ringed spaces.

As for `AlgebraicGeometry.Scheme`, no separation axiom is imposed; the Hausdorffness
assumed by most classical treatments should be added as a mixin where needed.

## Main definitions

- `ComplexAnalytic.IsCutOutBy i f`: the closed immersion `i : X ⟶ Y` exhibits `X` as the
  analytic subspace of `Y` cut out by the global sections `f`.
- `ComplexAnalytic.IsLocalModel X`: `X` is a local model, i.e. an analytic subspace of an open
  subset of some `ℂ^n`, as a locally ringed space.
- `ComplexAnalytic.IsCutOutBy.baseLift`: a morphism into `Y` killing the sections which cut out
  `X` factors uniquely through `X` on underlying topological spaces.
- `ComplexAnalytic.IsCutOutBy.mono`: such a closed immersion is a monomorphism, so the
  factorisation is unique as a morphism of locally ringed spaces
  (`ComplexAnalytic.IsCutOutBy.hom_ext`).
- `ComplexAnalytic.AnalyticSpace.mono_of_isCutOutBy`: the same for a morphism of analytic
  spaces.
- `ComplexAnalytic.constantsAlgMap`: the constant functions as the canonical `ℂ`-algebra
  structure on an open subspace of `ℂ^n`, and
  `ComplexAnalytic.constantsAlgMap_eq_resAlgMap`, which identifies it with the restriction of
  the structure on `ℂ^n`.
- `ComplexAnalytic.IsCLinearHom i α β`: a morphism of locally ringed spaces is `ℂ`-linear
  with respect to `ℂ`-algebra structures on its source and target.
- `ComplexAnalytic.IsCLinearHom.of_comp`: a morphism over a common target is `ℂ`-linear for the
  algebra structures pulled back from that target.
- `ComplexAnalytic.AnalyticSpace`: a complex analytic space.
- `ComplexAnalytic.AnalyticSpace.complexAffineSpace`: `ℂ^n` as a complex analytic space.

## Main results

The `ℂ`-linearity API, which is used throughout `Oka/AnalyticSpace/` and lived in three
different files until it was collected here.

- `ComplexAnalytic.isCLinearHom_comapAlgMap` and `ComplexAnalytic.IsCLinearHom.eq`: the pullback
  of a structure along a morphism is `ℂ`-linear over it, and **is the only structure that is** —
  so `ℂ`-linearity over a fixed target structure *determines* the source structure, which is
  what makes a structure obtained by any route identifiable.
- `ComplexAnalytic.isCLinearHom_ofRestrict`: **the inclusion of an open subspace is `ℂ`-linear**
  for the restricted structure — the previous item in the spelling open subspaces are written
  in. `Oka/AnalyticSpace/LocalModel.lean` restates it for an open subset of `ℂ^n` and the
  constants there, which is a different spelling of the same fact and not a second result.

And statements about the category of analytic spaces itself, rather than about linearity over the
constants.

- `ComplexAnalytic.AnalyticSpace.bijective_base_of_isIso`: **an isomorphism of analytic spaces is
  bijective on points**, which is the homeomorphism the functor to locally ringed spaces produces,
  read as a map of sets.
- `ComplexAnalytic.AnalyticSpace.surjective_base_of_isIso`: **an isomorphism of analytic spaces is
  surjective on points**, which is what turns a non-surjectivity into a `¬ IsIso`. It says nothing
  about whether the two spaces are isomorphic by some *other* morphism, and every consumer of it
  owes that caveat.
- `ComplexAnalytic.AnalyticSpace.preconnectedSpace_of_surjective_base`: **preconnectedness of the
  underlying space passes along a morphism that is surjective on points**, so an isomorphism
  transports it in either direction. This is the invariant that separates two covers of the same
  degree, which the degree cannot.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984]
- [Hans Grauert and Reinhold Remmert, *Theory of Stein spaces*][grauert-remmert1979]
-/

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Topology

universe u

namespace ComplexAnalytic

variable {X Y Z : LocallyRingedSpace.{u}}

/-- A closed immersion `i : X ⟶ Y` of locally ringed spaces *cuts out* `X` by the global
sections `f₁, …, f_k` of `𝒪_Y` if `X` is the common zero locus of the `fⱼ` and `𝒪_X` is the
quotient of `𝒪_Y` by the ideal they generate.

This is the intrinsic characterisation of the locally ringed space `(V(f), (𝒪_Y/(f))|_{V(f)})`:
any two closed immersions cutting out the same sections are canonically isomorphic. -/
structure IsCutOutBy (i : X ⟶ Y) {k : ℕ} (f : Fin k → Y.presheaf.obj (op ⊤)) : Prop where
  /-- `i` is a closed embedding of topological spaces. -/
  isClosedEmbedding : IsClosedEmbedding i.base
  /-- The image of `i` is the common zero locus of the `fⱼ`, i.e. the set of points at which
  every germ of every `fⱼ` is not a unit. -/
  range_base : Set.range i.base =
    {y | ∀ j, Y.presheaf.Γgerm y (f j) ∈ IsLocalRing.maximalIdeal (Y.presheaf.stalk y)}
  /-- The structure sheaf of `X` is a quotient of the structure sheaf of `Y`. -/
  surjective_stalkMap : ∀ x, Function.Surjective (i.stalkMap x).hom
  /-- The kernel of `𝒪_Y → 𝒪_X` is the ideal generated by the germs of the `fⱼ`. -/
  ker_stalkMap : ∀ x, RingHom.ker (i.stalkMap x).hom =
    Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm (i.base x) (f j))

/-- A locally ringed space is a **local model** for complex analytic geometry if it is the
common zero locus of finitely many holomorphic functions on an open subset of some `ℂ^n`,
equipped with the corresponding quotient of the structure sheaf.

This is the analytic analogue of an affine scheme. -/
def IsLocalModel (X : LocallyRingedSpace.{u}) : Prop :=
  ∃ (n k : ℕ) (U : Opens (complexAffineSpace.{u} n))
    (i : X ⟶ (complexAffineSpace.{u} n).restrict U.isOpenEmbedding)
    (f : Fin k → ((complexAffineSpace.{u} n).restrict U.isOpenEmbedding).presheaf.obj (op ⊤)),
    IsCutOutBy i f

/-- Cutting out by a family of sections is invariant under precomposition with an isomorphism:
if `i : X ⟶ Y` cuts out `X` by `f` and `e : X' ≅ X`, then `e.hom ≫ i` cuts out `X'` by `f`. -/
theorem IsCutOutBy.comp_iso {X' : LocallyRingedSpace.{u}} {i : X ⟶ Y} {k : ℕ}
    {f : Fin k → Y.presheaf.obj (op ⊤)} (hf : IsCutOutBy i f) (e : X' ≅ X) :
    IsCutOutBy (e.hom ≫ i) f := by
  have hstalk (x : X') : Function.Bijective (e.hom.stalkMap x).hom :=
    ConcreteCategory.bijective_of_isIso _
  have hcomp (x : X') (a : Y.presheaf.stalk ((e.hom ≫ i).base x)) :
      ((e.hom ≫ i).stalkMap x).hom a =
        (e.hom.stalkMap x).hom ((i.stalkMap (e.hom.base x)).hom a) := by
    rw [LocallyRingedSpace.stalkMap_comp]
    rfl
  have hsurj : Function.Surjective ⇑e.hom.base :=
    (LocallyRingedSpace.homeoOfIso e).surjective
  refine ⟨hf.isClosedEmbedding.comp (LocallyRingedSpace.homeoOfIso e).isClosedEmbedding, ?_,
    fun x ↦ ?_, fun x ↦ ?_⟩
  · rw [show ⇑(e.hom ≫ i).base = ⇑i.base ∘ ⇑e.hom.base from rfl, Set.range_comp,
      hsurj.range_eq, Set.image_univ]
    exact hf.range_base
  · rw [show ⇑((e.hom ≫ i).stalkMap x).hom =
      ⇑(e.hom.stalkMap x).hom ∘ ⇑(i.stalkMap (e.hom.base x)).hom from funext (hcomp x)]
    exact (hstalk x).surjective.comp (hf.surjective_stalkMap _)
  · have hker : RingHom.ker ((e.hom ≫ i).stalkMap x).hom =
        RingHom.ker (i.stalkMap (e.hom.base x)).hom := by
      ext a
      simp only [RingHom.mem_ker, hcomp x a]
      exact ⟨fun h ↦ (hstalk x).injective (h.trans (map_zero _).symm),
        fun h ↦ by rw [h, map_zero]⟩
    rw [hker]
    exact hf.ker_stalkMap _

/-- The sections cutting out `X` inside `Y` pull back to zero on `X`. -/
lemma IsCutOutBy.c_app_eq_zero {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (j : Fin k) :
    i.c.app (op ⊤) (f j) = 0 := by
  refine TopCat.Presheaf.section_ext X.sheaf _ _ _ fun x _ ↦ ?_
  have hker : Y.presheaf.Γgerm (i.base x) (f j) ∈ RingHom.ker (i.stalkMap x).hom := by
    rw [hcut.ker_stalkMap x]
    exact Submodule.subset_span ⟨j, rfl⟩
  have h0 : (i.stalkMap x) (Y.presheaf.Γgerm (i.base x) (f j)) = 0 := hker
  exact ((LocallyRingedSpace.stalkMap_germ_apply i ⊤ x trivial (f j)).symm.trans h0).trans
    (map_zero _).symm


/-- **A global section pulling back to zero on `Z` has non-unit germ everywhere on the image of
`Z`.** No `IsCutOutBy` hypothesis is involved: this is just the fact that a ring homomorphism
carries units to units, applied to the stalk map of `φ`, whose target is a local ring and hence
nontrivial.

Together with `IsCutOutBy.range_base` this is what puts the image of `φ` inside the subspace cut
out by the `f j`; see `IsCutOutBy.mem_range_base`. -/
theorem Γgerm_mem_maximalIdeal_of_c_app_eq_zero {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (φ : Z ⟶ Y) (hφ : ∀ j, φ.c.app (op ⊤) (f j) = 0) (z : Z) (j : Fin k) :
    Y.presheaf.Γgerm (φ.base z) (f j) ∈
      IsLocalRing.maximalIdeal (Y.presheaf.stalk (φ.base z)) := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
  intro hu
  have h0 : (φ.stalkMap z) (Y.presheaf.Γgerm (φ.base z) (f j)) = 0 :=
    (LocallyRingedSpace.stalkMap_germ_apply φ ⊤ z trivial (f j)).trans
      ((congrArg (Z.presheaf.germ ((Opens.map φ.base).obj ⊤) z trivial) (hφ j)).trans (map_zero _))
  have : IsUnit (0 : Z.presheaf.stalk z) := by rw [← h0]; exact hu.map _
  exact not_isUnit_zero this

/-- A morphism into `Y` which kills the sections cutting out `X` lands, pointwise, in the image
of `X`. This is the topological half of the mapping property of `IsCutOutBy`. -/
theorem IsCutOutBy.mem_range_base {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (φ : Z ⟶ Y) (hφ : ∀ j, φ.c.app (op ⊤) (f j) = 0) (z : Z) :
    φ.base z ∈ Set.range i.base := by
  rw [hcut.range_base]
  exact fun j ↦ Γgerm_mem_maximalIdeal_of_c_app_eq_zero φ hφ z j

/-- **The underlying continuous map of the factorisation.** A morphism `φ : Z ⟶ Y` killing the
sections which cut out `X` factors, on underlying spaces, uniquely through `X`.

Continuity is `IsInducing.continuous_iff`: `i` is a closed embedding, so a map into `X` is
continuous as soon as its composite with `i` is, and that composite is `φ` itself
(`IsCutOutBy.base_baseLift`).

This is only the topological half. Producing an actual morphism of locally ringed spaces
additionally needs the map on structure sheaves, which the stalkwise conditions of `IsCutOutBy`
do not by themselves assemble; see the tracking issue. -/
noncomputable def IsCutOutBy.baseLift {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (φ : Z ⟶ Y) (hφ : ∀ j, φ.c.app (op ⊤) (f j) = 0) : C(Z, X) where
  toFun z := (hcut.mem_range_base φ hφ z).choose
  continuous_toFun :=
    hcut.isClosedEmbedding.isEmbedding.isInducing.continuous_iff.2 (by
      have h : ⇑i.base ∘ (fun z ↦ (hcut.mem_range_base φ hφ z).choose) = ⇑φ.base :=
        funext fun z ↦ (hcut.mem_range_base φ hφ z).choose_spec
      rw [h]
      exact φ.base.hom.continuous)

@[simp]
lemma IsCutOutBy.base_baseLift {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (φ : Z ⟶ Y) (hφ : ∀ j, φ.c.app (op ⊤) (f j) = 0) (z : Z) :
    i.base (hcut.baseLift φ hφ z) = φ.base z :=
  (hcut.mem_range_base φ hφ z).choose_spec

/-- The topological factorisation is unique, because `i` is a closed embedding and so injective.
Uniqueness of the factorisation as a morphism of locally ringed spaces will follow from this
together with `IsCutOutBy.surjective_stalkMap`. -/
theorem IsCutOutBy.baseLift_unique {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (φ : Z ⟶ Y) (hφ : ∀ j, φ.c.app (op ⊤) (f j) = 0) (g : Z → X)
    (hg : ∀ z, i.base (g z) = φ.base z) (z : Z) : g z = hcut.baseLift φ hφ z :=
  hcut.isClosedEmbedding.injective ((hg z).trans (hcut.base_baseLift φ hφ z).symm)

/-- **A closed immersion witnessing `IsCutOutBy` is a monomorphism.**

Only two of the four conditions are used: the underlying map is injective because it is a closed
embedding, and the maps on stalks are epimorphisms because they are surjective. Mathlib's
`AlgebraicGeometry.SheafedSpace.mono_of_base_injective_of_stalk_epi` turns that pair into a
monomorphism of sheafed spaces, and `forgetToSheafedSpace`, being faithful, reflects it.

Note the detour through `forgetToSheafedSpace`: `LocallyRingedSpace.Hom.toShHom` is an
`InducedCategory.Hom`, so `i.toShHom.base` does not project and the hypotheses cannot be stated
that way. -/
theorem IsCutOutBy.mono {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) : Mono i := by
  have hb : Function.Injective (LocallyRingedSpace.forgetToSheafedSpace.map i).hom.base :=
    hcut.isClosedEmbedding.injective
  have hs : ∀ x, Epi ((LocallyRingedSpace.forgetToSheafedSpace.map i).hom.stalkMap x) := fun x ↦
    ConcreteCategory.epi_of_surjective _ (hcut.surjective_stalkMap x)
  exact LocallyRingedSpace.forgetToSheafedSpace.mono_of_mono_map
    (SheafedSpace.mono_of_base_injective_of_stalk_epi _ hb hs)

/-- **The factorisation through a subspace cut out by global sections is unique**, when it
exists. Together with `IsCutOutBy.baseLift` this is the uniqueness half of the mapping property
of `IsCutOutBy`; existence of the map on structure sheaves is not proved here. -/
theorem IsCutOutBy.hom_ext {i : X ⟶ Y} {k : ℕ} {f : Fin k → Y.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy i f) (ψ₁ ψ₂ : Z ⟶ X) (h : ψ₁ ≫ i = ψ₂ ≫ i) : ψ₁ = ψ₂ :=
  haveI := hcut.mono
  (cancel_mono i).1 h

/-- Being a local model is invariant under isomorphism of locally ringed spaces. -/
theorem IsLocalModel.of_iso {M N : LocallyRingedSpace.{u}} (e : N ≅ M) (hM : IsLocalModel M) :
    IsLocalModel N := by
  obtain ⟨n, k, U, i, f, hcut⟩ := hM
  exact ⟨n, k, U, e.hom ≫ i, f, hcut.comp_iso e⟩

section CAlgebraStructure

/-- The canonical `ℂ`-algebra structure on an open subspace of `ℂ^n`: the constant
holomorphic functions. This is the reference structure which the charts of an analytic space
are required to respect. -/
noncomputable def constantsAlgMap (n : ℕ) (V : Opens (complexAffineSpace.{u} n)) :
    ℂ →+* ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op ⊤) :=
  Algebra.algebraMap ℂ (OkaRing (V.isOpenEmbedding.isOpenMap.functor.obj ⊤))

/-- **The reference structure on an open subspace of `ℂ^n` is the restriction of the reference
structure on `ℂ^n`.** Both sides are the constant function with value `c` on the open subset, so
this is `rfl`; it is stated because the two spellings arise from different places — the left
from `AnalyticSpace.local_model`, the right from
`AlgebraicGeometry.LocallyRingedSpace.resAlgMap` — and nothing else says they agree. -/
lemma constantsAlgMap_eq_resAlgMap (n : ℕ) (V : Opens (complexAffineSpace.{u} n)) :
    constantsAlgMap n V =
      (complexAffineSpace.{u} n).resAlgMap
        (Algebra.algebraMap ℂ (OkaRing (⊤ : Opens (ULift.{u} (Fin n) → ℂ)))) V :=
  rfl

/-- A morphism `i : X ⟶ Y` of locally ringed spaces whose structure sheaves carry `ℂ`-algebra
structures `α` and `β` is **`ℂ`-linear** if pulling back global sections intertwines `β` and
`α`. Since the `ℂ`-algebra structure on the sections over any open subset is the restriction
of the global one, this makes every component of `i.c` a `ℂ`-algebra homomorphism.

Without this condition a morphism of locally ringed spaces between complex analytic spaces
may be antiholomorphic: complex conjugation is a ring automorphism of the sheaf of
holomorphic functions, but it is not `ℂ`-linear. -/
def IsCLinearHom {X Y : LocallyRingedSpace.{u}} (i : X ⟶ Y)
    (α : ℂ →+* X.presheaf.obj (op ⊤)) (β : ℂ →+* Y.presheaf.obj (op ⊤)) : Prop :=
  ∀ c : ℂ, LocallyRingedSpace.Γ.map i.op (β c) = α c

lemma IsCLinearHom.id {X : LocallyRingedSpace.{u}} (α : ℂ →+* X.presheaf.obj (op ⊤)) :
    IsCLinearHom (𝟙 X) α α := fun c ↦ by
  rw [op_id, CategoryTheory.Functor.map_id]
  rfl

lemma IsCLinearHom.comp {X Y Z : LocallyRingedSpace.{u}} {f : X ⟶ Y} {g : Y ⟶ Z}
    {α : ℂ →+* X.presheaf.obj (op ⊤)} {β : ℂ →+* Y.presheaf.obj (op ⊤)}
    {γ : ℂ →+* Z.presheaf.obj (op ⊤)}
    (hf : IsCLinearHom f α β) (hg : IsCLinearHom g β γ) :
    IsCLinearHom (f ≫ g) α γ := fun c ↦ by
  rw [op_comp, Functor.map_comp, ConcreteCategory.comp_apply, hg c, hf c]

/-- **A morphism over a common target is `ℂ`-linear** for the algebra structures pulled back
from that target.

If `p : P ⟶ A` and `q : Q ⟶ A` are `ℂ`-linear for `αP` and `αQ` over one and the same `α` on
`A`, then any `g : P ⟶ Q` with `g ≫ q = p` is `ℂ`-linear for `αP` and `αQ`. Nothing is assumed
about `g`: the conclusion is `Γ.map g.op (αQ c) = αP c`, and `αQ c` is `α c` pulled back along
`q`, so the claim is contravariant functoriality of `Γ` applied to the factorisation.

This is what carries `ℂ`-linearity across an identification of two presentations of the same
open subspace, where `g` is an isomorphism over the ambient space and the two algebra
structures are both restrictions of the ambient one. -/
lemma IsCLinearHom.of_comp {P Q A : LocallyRingedSpace.{u}} {g : P ⟶ Q} {q : Q ⟶ A} {p : P ⟶ A}
    (hfac : g ≫ q = p) {αP : ℂ →+* P.presheaf.obj (op ⊤)} {αQ : ℂ →+* Q.presheaf.obj (op ⊤)}
    {α : ℂ →+* A.presheaf.obj (op ⊤)} (hp : IsCLinearHom p αP α) (hq : IsCLinearHom q αQ α) :
    IsCLinearHom g αP αQ := fun c ↦ by
  rw [← hq c, ← LocallyRingedSpace.Γ_map_comp_apply, hfac]
  exact hp c

/-- **Two `ℂ`-algebra structures on the source of a morphism which are `ℂ`-linear over one and
the same structure on its target are equal.**

`IsCLinearHom i α β` says that `α` *is* `β` pulled back along `i`, so it determines `α`. This is
the uniqueness that makes `ComplexAnalytic.AnalyticSpace.ofOpenCover`'s output identifiable: a
structure recognised as `ℂ`-linear over the ambient one is the restriction of the ambient one,
whatever route produced it. -/
lemma IsCLinearHom.eq {i : X ⟶ Y} {α α' : ℂ →+* X.presheaf.obj (op ⊤)}
    {β : ℂ →+* Y.presheaf.obj (op ⊤)}
    (h : IsCLinearHom i α β) (h' : IsCLinearHom i α' β) : α = α' :=
  RingHom.ext fun c ↦ (h c).symm.trans (h' c)

/-- **A pulled-back `ℂ`-algebra structure is `ℂ`-linear**, by definition of
`AlgebraicGeometry.LocallyRingedSpace.comapAlgMap`: both sides of `IsCLinearHom` are the same
term.

Together with `ComplexAnalytic.IsCLinearHom.eq` this says that `IsCLinearHom i · β` has exactly
one witness, so a structure recognised as `ℂ`-linear over `β` *is* the pullback of `β` and not
merely comparable to it. -/
lemma isCLinearHom_comapAlgMap (i : X ⟶ Y) (β : ℂ →+* Y.presheaf.obj (op ⊤)) :
    IsCLinearHom i (LocallyRingedSpace.comapAlgMap i β) β :=
  fun _ ↦ rfl

/-- **The inclusion of an open subspace is `ℂ`-linear** for the `ℂ`-algebra structure obtained
by restricting sections, essentially by definition: both sides are the restriction map
`𝒪_X(⊤) ⟶ 𝒪_X(U)`, and `Opens X` is a preorder category, so there is only one such map. -/
theorem isCLinearHom_ofRestrict (X : LocallyRingedSpace.{u}) (α : ℂ →+* X.presheaf.obj (op ⊤))
    (U : Opens X) : IsCLinearHom (X.ofRestrict U.isOpenEmbedding) (X.resAlgMap α U) α := by
  intro c
  change ((X.ofRestrict U.isOpenEmbedding).c.app (op ⊤)).hom (α c) = _
  change (X.presheaf.map _).hom (α c) = (X.presheaf.map _).hom (α c)
  congr 2

/-- **A `ℂ`-linear morphism is `ℂ`-linear on stalks**: the map on stalks carries the germ of the
constant `c` upstairs to the germ of the constant `c` downstairs.

This is the form in which `ℂ`-linearity is used, `IsCLinearHom` itself being a statement about
global sections only. -/
lemma IsCLinearHom.stalkAlgMap {X Y : LocallyRingedSpace.{u}} {i : X ⟶ Y}
    {α : ℂ →+* X.presheaf.obj (op ⊤)} {β : ℂ →+* Y.presheaf.obj (op ⊤)}
    (h : IsCLinearHom i α β) (x : X) (c : ℂ) :
    (i.stalkMap x).hom (Y.stalkAlgMap β (i.base x) c) = X.stalkAlgMap α x c := by
  change (i.stalkMap x) (Y.presheaf.germ ⊤ (i.base x) trivial (β c)) = _
  rw [LocallyRingedSpace.stalkMap_germ_apply]
  exact congrArg (X.presheaf.germ ⊤ x trivial) (h c)

end CAlgebraStructure

/-- A **complex analytic space** is a locally ringed space `X`, together with a `ℂ`-algebra
structure on its structure sheaf, such that every point of `X` has an open neighbourhood
which is — compatibly with the `ℂ`-algebra structures — cut out by finitely many holomorphic
functions inside an open subset of some `ℂ^n`, i.e. a neighbourhood which is a local model as
a `ℂ`-ringed space.

Since being cut out transfers along isomorphisms (`IsCutOutBy.comp_iso`), requiring the
restriction of `X` itself to be cut out is equivalent to requiring an isomorphism onto a
local model; stating it directly for the restriction avoids transporting the `ℂ`-algebra
structure through the isomorphism.

The `ℂ`-linearity of the charts cannot be dropped: an isomorphism of locally ringed spaces
onto a local model may be conjugate-linear, so without it the definition would also admit
spaces glued along antiholomorphic maps (dianalytic spaces such as Klein surfaces), which are
not complex analytic spaces.

Compare `AlgebraicGeometry.Scheme`, where the local models are the spectra of commutative
rings. As there, no separation axiom is imposed; the Hausdorffness assumed by most classical
treatments should be added as a mixin where needed. -/
structure AnalyticSpace extends LocallyRingedSpace.{u} where
  /-- The `ℂ`-algebra structure on the structure sheaf, as a ring homomorphism into the
  global sections. -/
  algebraMap : ℂ →+* toLocallyRingedSpace.presheaf.obj (op ⊤)
  /-- Every point has a neighbourhood which, compatibly with the `ℂ`-algebra structures, is
  cut out by finitely many holomorphic functions inside an open subset of some `ℂ^n`. -/
  local_model : ∀ x : toLocallyRingedSpace, ∃ (U : OpenNhds x) (n k : ℕ)
    (V : Opens (complexAffineSpace.{u} n))
    (i : toLocallyRingedSpace.restrict U.1.isOpenEmbedding ⟶
      (complexAffineSpace.{u} n).restrict V.isOpenEmbedding)
    (f : Fin k → ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op ⊤)),
    IsCutOutBy i f ∧
      IsCLinearHom i (toLocallyRingedSpace.resAlgMap algebraMap U.1) (constantsAlgMap n V)

namespace AnalyticSpace

instance : CoeSort AnalyticSpace (Type u) where
  coe X := X.carrier

/-- The type of open sets of a complex analytic space. -/
abbrev Opens (X : AnalyticSpace.{u}) : Type u := TopologicalSpace.Opens X

/-- A morphism of complex analytic spaces is a morphism of the underlying locally ringed
spaces which is `ℂ`-linear, i.e. compatible with the `ℂ`-algebra structures on the structure
sheaves. Plain morphisms of locally ringed spaces would also include antiholomorphic maps
such as complex conjugation. -/
@[ext]
structure Hom (X Y : AnalyticSpace.{u}) extends
  toLRSHom' : X.toLocallyRingedSpace.Hom Y.toLocallyRingedSpace where
  /-- Pulling back sections is `ℂ`-linear. -/
  isCLinear : IsCLinearHom toLRSHom' X.algebraMap Y.algebraMap

/-- Cast a morphism of analytic spaces to a morphism of locally ringed spaces. -/
abbrev Hom.toLRSHom {X Y : AnalyticSpace.{u}} (f : X.Hom Y) :
    X.toLocallyRingedSpace ⟶ Y.toLocallyRingedSpace :=
  f.toLRSHom'

/-- Complex analytic spaces form a (non-full) subcategory of locally ringed spaces. -/
instance : Category AnalyticSpace.{u} where
  Hom := Hom
  id X := ⟨𝟙 X.toLocallyRingedSpace, IsCLinearHom.id X.algebraMap⟩
  comp f g := ⟨f.toLRSHom ≫ g.toLRSHom, f.isCLinear.comp g.isCLinear⟩

/-- The forgetful functor from complex analytic spaces to locally ringed spaces. -/
def forgetToLocallyRingedSpace : AnalyticSpace.{u} ⥤ LocallyRingedSpace.{u} where
  obj X := X.toLocallyRingedSpace
  map f := f.toLRSHom

instance : forgetToLocallyRingedSpace.Faithful where
  map_injective {_ _ f g} h := by
    cases f
    cases g
    cases h
    rfl

/-- **The pullback of a global section of `𝒪_Y` along `φ : X ⟶ Y`.**

This is `AlgebraicGeometry.LocallyRingedSpace.Γ.map φ.toLRSHom.op` with its target written as
`presheaf.obj (op ⊤)` rather than as `Γ.obj`. The two are definitionally equal, and the
distinction is not cosmetic — **`Γ.obj (op X.toLocallyRingedSpace)` is not syntactically
`X.presheaf.obj (op ⊤)`, and instance search does not cross that**:

```lean
example {X Y : AnalyticSpace} (φ : X ⟶ Y) (a : X.presheaf.obj (op ⊤))
    (s : Y.presheaf.obj (op ⊤)) : X.presheaf.obj (op ⊤) :=
  a * (LocallyRingedSpace.Γ.map φ.toLRSHom.op).hom s
-- failed to synthesize instance of type class
--   HMul ↑(X.presheaf.obj (op ⊤)) ↑(LocallyRingedSpace.Γ.obj (op X.toLocallyRingedSpace)) ?m
```

`OkaTest/AnalytificationDistinguishedOpen.lean` records that the same product *does* elaborate
through this declaration. The knock-on effect is what actually costs a proof: a `rw` which puts a
raw `Γ.map … |>.hom` term inside a product elaborated at the other spelling leaves a goal that is
not type-correct under the `instances` transparency level, and every later `rw` on that goal is
rejected with "did not find an occurrence of the pattern".

An `abbrev`, so that a caller holding `(Γ.map φ.toLRSHom.op).hom s` recognises it without
unfolding. `ComplexAnalytic.AnalyticSpace.coordPullback` and
`ComplexAnalytic.AnalyticSpace.resΓ` are this at particular morphisms; they are stated
independently and each is definitionally this one, so a lemma about either applies to the
other. -/
abbrev Hom.pullbackΓ {X Y : AnalyticSpace.{u}} (φ : X ⟶ Y) (s : Y.presheaf.obj (op ⊤)) :
    X.presheaf.obj (op ⊤) :=
  (LocallyRingedSpace.Γ.map φ.toLRSHom.op).hom s

/-- **A morphism of analytic spaces whose underlying morphism cuts out its source is a
monomorphism**, hence the factorisation through it is unique when it exists
(`CategoryTheory.cancel_mono`).

This is `ComplexAnalytic.IsCutOutBy.mono` reflected along `forgetToLocallyRingedSpace`, which is
faithful; no `ℂ`-linearity bookkeeping is needed, because faithfulness already knows that a
morphism of analytic spaces is determined by its underlying morphism. -/
theorem mono_of_isCutOutBy {B C : AnalyticSpace.{u}} (j : B ⟶ C) {k : ℕ}
    {f : Fin k → C.toLocallyRingedSpace.presheaf.obj (op ⊤)}
    (hcut : IsCutOutBy j.toLRSHom f) : Mono j :=
  forgetToLocallyRingedSpace.mono_of_mono_map hcut.mono

/-- **An isomorphism of analytic spaces is bijective on points.**

`AlgebraicGeometry.LocallyRingedSpace.homeoOfIso` at the image of `f` under
`ComplexAnalytic.AnalyticSpace.forgetToLocallyRingedSpace`. That is the same bridge
`ComplexAnalytic.IsCutOutBy.comp_iso` above spends, reached through the functor rather than
restated, and it is a homeomorphism rather than only a surjection — so **bijectivity is what that
bridge gives and surjectivity is a projection of it**, which is why
`ComplexAnalytic.AnalyticSpace.surjective_base_of_isIso` below is now this statement's
`.surjective` and no longer a second call of the same one-liner.

**Nothing has to be established about the functor.** `CategoryTheory.Functor.map_isIso` is an
instance: *every* functor preserves isomorphisms, so `forgetToLocallyRingedSpace.map f` is an
isomorphism of locally ringed spaces for free and `CategoryTheory.asIso` packages it. What would
need an argument is **reflection** — that a morphism of analytic spaces whose underlying morphism is
invertible is itself invertible — and that is *not* the direction this proof uses and is not claimed
anywhere here. `ComplexAnalytic.AnalyticSpace.Hom` is a structure over
`AlgebraicGeometry.LocallyRingedSpace.Hom` carrying an `ComplexAnalytic.IsCLinearHom` field, so an
`IsIso` in the ambient category is not on its face an `IsIso` here, and
`ComplexAnalytic.IsCutOutBy.comp_iso` — whose isomorphism is one of locally ringed spaces — cannot
quote this statement in the other direction.

**What it does not say.** `¬ IsIso f` for one morphism `f` is not a statement that `X` and `Y` are
non-isomorphic: two spaces can be isomorphic by a morphism other than the one in hand.
`ComplexAnalytic.AnalyticSpace.not_surjective_sigmaι_base`
(`Oka/AnalyticSpace/Sigma.lean`) already writes that caveat for its own statement, and every
consumer of this one inherits it.

**Which half a consumer needs is not a matter of taste.** A non-surjectivity refutes `IsIso` and
wants the surjection; a *fibre count* wants the injection as well, because `Nat.card` of a
preimage is preserved by a bijection and by nothing weaker —
`ComplexAnalytic.AnalyticSpace.degree_isIso_comp` (`Oka/AnalyticSpace/Degree.lean`) is the
consumer that made this statement rather than the one below the one to prove. -/
theorem bijective_base_of_isIso {X Y : AnalyticSpace.{u}} (f : X ⟶ Y) [IsIso f] :
    Function.Bijective (f.toLRSHom.base : X → Y) :=
  (LocallyRingedSpace.homeoOfIso (asIso (forgetToLocallyRingedSpace.map f))).bijective

/-- **An isomorphism of analytic spaces is surjective on points.**

The surjectivity half of `ComplexAnalytic.AnalyticSpace.bijective_base_of_isIso` above, which is
where the argument and every caveat now live. It is kept as a separate name because it has
consumers — `ComplexAnalytic.AnalyticSpace.not_isIso_sigmaι` (`Oka/AnalyticSpace/Sigma.lean`) and
`ComplexAnalytic.not_isIso_lineRefineToBase` (`OkaTest/RefineDatumUnitFamily.lean`) both spend it
— and because a non-surjectivity is the shape that refutes an `IsIso`, which is what both of them
are doing. -/
theorem surjective_base_of_isIso {X Y : AnalyticSpace.{u}} (f : X ⟶ Y) [IsIso f] :
    Function.Surjective (f.toLRSHom.base : X → Y) :=
  (bijective_base_of_isIso f).surjective

/-- **Preconnectedness passes along a morphism that is surjective on points.**

A continuous map with dense range carries a preconnected source to a preconnected target
(`DenseRange.preconnectedSpace`), and a surjection has dense range; the continuity is the base
map's own, the `base` field of a morphism of locally ringed spaces being a map in `TopCat`.
**Nothing analytic is used and nothing about the structure sheaves is read here** — this is the
topological statement, spelled at a morphism of analytic spaces because that is where its
consumers are.

**Stated at a surjection rather than at an `[IsIso f]`**, although every consumer so far supplies
the surjection by `ComplexAnalytic.AnalyticSpace.surjective_base_of_isIso` above. The hypothesis
the proof uses is dense range, of which surjectivity is the first weakening anyone reaches for;
asking for an isomorphism would put an invertible morphism in a statement that never inverts one.

**What this buys is an invariant of a cover that the degree is not.**
`ComplexAnalytic.AnalyticSpace.FiniteEtaleOver.degree_eq_of_iso`
(`Oka/AnalyticSpace/FiniteEtaleOver.lean`) separates covers by a number, and two covers of the
same degree are beyond it — at the punctured line the squaring map and the trivial two-sheeted
cover both have degree `2`. Preconnectedness of the *total space* is the classical separator, and
this is the transport that makes it one: an isomorphism of covers is in particular a morphism of
analytic spaces surjective on points, so a preconnected total space cannot be isomorphic to a
disconnected one. -/
theorem preconnectedSpace_of_surjective_base {X Y : AnalyticSpace.{u}} [PreconnectedSpace X]
    (f : X ⟶ Y) (hf : Function.Surjective (f.toLRSHom.base : X → Y)) :
    PreconnectedSpace Y :=
  hf.denseRange.preconnectedSpace f.toLRSHom.base.hom.continuous

end AnalyticSpace

section ComplexAffineSpace

variable (n : ℕ)

/-- The identity of the top open subspace of `ℂ^n` cuts it out inside itself by the empty
family of holomorphic functions. -/
theorem isCutOutBy_id_restrict_top :
    IsCutOutBy (𝟙 ((complexAffineSpace.{u} n).restrict
      (⊤ : Opens (complexAffineSpace.{u} n)).isOpenEmbedding)) Fin.elim0 := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · simpa using IsClosedEmbedding.id
  · simp
  · intro x
    simp only [LocallyRingedSpace.stalkMap_id]
    exact fun y ↦ ⟨y, rfl⟩
  · intro x
    simp only [LocallyRingedSpace.stalkMap_id, Set.range_eq_empty, Ideal.span_empty]
    ext a
    exact Iff.rfl

/-- Complex affine `n`-space, restricted to its top open subset, is a local model: it is cut
out inside itself by the empty family of holomorphic functions. -/
theorem isLocalModel_complexAffineSpace_restrict_top :
    IsLocalModel ((complexAffineSpace.{u} n).restrict
      (⊤ : Opens (complexAffineSpace.{u} n)).isOpenEmbedding) :=
  ⟨n, 0, ⊤, 𝟙 _, Fin.elim0, isCutOutBy_id_restrict_top n⟩

/-- The identity chart of `ℂ^n` is `ℂ`-linear: the constant functions restrict to the
constant functions. -/
theorem isCLinearHom_id_restrict_top :
    IsCLinearHom (𝟙 ((complexAffineSpace.{u} n).restrict
        (⊤ : Opens (complexAffineSpace.{u} n)).isOpenEmbedding))
      ((_root_.complexAffineSpace.{u} n).resAlgMap (Algebra.algebraMap ℂ (OkaRing ⊤)) ⊤)
      (constantsAlgMap n ⊤) := fun c ↦ by
  rw [op_id, CategoryTheory.Functor.map_id]
  rfl

/-- Complex affine `n`-space `ℂ^n` as a complex analytic space, with the constant functions
as `ℂ`-algebra structure. -/
noncomputable def AnalyticSpace.complexAffineSpace (n : ℕ) : AnalyticSpace.{u} where
  toLocallyRingedSpace := _root_.complexAffineSpace.{u} n
  algebraMap := Algebra.algebraMap ℂ (OkaRing ⊤)
  local_model _ :=
    ⟨⟨⊤, trivial⟩, n, 0, ⊤, 𝟙 _, Fin.elim0, isCutOutBy_id_restrict_top n,
      isCLinearHom_id_restrict_top n⟩

end ComplexAffineSpace

end ComplexAnalytic
