/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Free
import Oka.AnalyticSpace.Basic
import Oka.AnalyticSpace.Relations

/-!
# Coherence of the structure sheaf of a complex analytic space

We deduce from Oka's coherence theorem for `ℂ^n` that the structure sheaf of an arbitrary
complex analytic space is coherent.

## Strategy

Coherence is reached through the concrete condition
`AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations` of `Oka.AnalyticSpace.Relations`,
which implies coherence and, unlike `SheafOfModules.IsCoherent`, mentions only open subsets,
sections and restriction maps. It is therefore a local condition
(`hasLocalRelations_of_openCover`), and no transport of sites is needed anywhere.

Since every point of an analytic space has a neighbourhood which is a local model, it
remains to see that the structure sheaf of a local model has locally finitely generated
relations. This is `ComplexAnalytic.IsLocalModel.hasLocalRelations`, proved below, and it is
where Oka's theorem for `ℂ^n` enters: a local model is cut out by finitely many holomorphic
functions `f₁, …, f_k` inside an open subset `Y` of some `ℂ^n`, and near a point of it a
relation between sections `s₁, …, s_m` of `𝒪_M` is obtained by lifting the `sᵢ` to sections
`t₁, …, t_m` of `𝒪_Y` and applying Oka's theorem to the family `t₁, …, t_m, f₁, …, f_k`: the
relations of that family generate, and projecting away the last `k` coordinates gives the
relations between the `sᵢ`.

## Main results

- `ComplexAnalytic.AnalyticSpace.isCoherentStructureSheaf`: the structure sheaf of any complex
  analytic space is coherent.
- `ComplexAnalytic.AnalyticSpace.isCoherent_free`: **a finite free sheaf of modules on a complex
  analytic space is coherent**, which is Oka's theorem in every finite rank rather than in rank
  one. It is `SheafOfModules.IsCoherent.free` — an induction on the rank with no analysis in it
  — fed the theorem above.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984], §A
- [Jean-Pierre Serre, *Faisceaux algébriques cohérents*][serre1955], §2
-/

open CategoryTheory TopologicalSpace Opposite Limits SheafOfModules AlgebraicGeometry
open AlgebraicGeometry.LocallyRingedSpace

universe u

namespace ComplexAnalytic

/-- The structure sheaf of a local model has locally finitely generated relations.

This is the geometric heart of the deduction, and the point at which Oka's coherence theorem
for `ℂ^n` is used. Writing the local model as a closed immersion `i : X|_U ⟶ Y` into an open
subset `Y` of `ℂ^n` cutting out `X|_U` by `f₁, …, f_k`:

1. near a point, finitely many sections `s₁, …, s_m` of `𝒪_X` lift along the surjection
   `𝒪_Y ↠ i_*𝒪_{X|_U}` to sections `t₁, …, t_m` of `𝒪_Y`;
2. `𝒪_Y` has locally finitely generated relations, by `hasLocalRelations_complexSpace`
   restricted to `Y`, so the relations between `t₁, …, t_m, f₁, …, f_k` are generated by
   finitely many of them;
3. discarding the last `k` coordinates of those generators gives generators for the relations
   between the `sᵢ`, since a relation `∑ aᵢ sᵢ = 0` lifts to `∑ aᵢ tᵢ ∈ (f₁, …, f_k)`.

Note that `HasLocalRelationsOn` asks only for *local* generation: a relation between the `sᵢ`
over an open set need be a combination of the generators only near each of its points. This is
what step 1 delivers, since `𝒪_Y ↠ i_*𝒪_M` is surjective on stalks and not on sections, and it
is the reason `SheafOfModules.isCoherent_of_forall_kernel_of_locally` was proved: the
sectionwise variant of this statement would be a vanishing statement for `H¹` on arbitrary open
sets and is not available. -/
theorem IsLocalModel.hasLocalRelations {M : LocallyRingedSpace.{u}} (hM : IsLocalModel M) :
    M.HasLocalRelations := by
  classical
  obtain ⟨n, k, V, i, f, hcut⟩ := hM
  have hY : ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).HasLocalRelations :=
    HasLocalRelations.restrict V (hasLocalRelations_complexSpace _)
  intro V₀ m s x hx
  obtain ⟨A, hAx, t, B, hBV₀, hBA, hxB, hlift⟩ :=
    exists_localLift_family i hcut.surjective_stalkMap s x hx
  set F : Fin (m + k) →
      ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op A) :=
    Fin.append t (fun j ↦ res _ le_top (f j)) with hFdef
  obtain ⟨A₁, hA₁A, r, G, hxA₁, hGrel, hGgen⟩ := hY A (m + k) F (i.base x) hAx
  set W : Opens M := B ⊓ (Opens.map i.base).obj A₁ with hWdef
  have hWB : W ≤ B := inf_le_left
  have hWA₁ : W ≤ (Opens.map i.base).obj A₁ := inf_le_right
  -- the pullback-and-restrict ring homomorphism
  set π : ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op A₁) →+*
      M.presheaf.obj (op W) :=
    (M.presheaf.map (homOfLE hWA₁).op).hom.comp (i.c.app (op A₁)).hom with hπdef
  have hπ : ∀ v, π v = M.res hWA₁ (i.c.app (op A₁) v) := fun _ ↦ rfl
  -- the `f`-block of `F` dies under `π`
  have hzero : ∀ j : Fin k, π (res _ hA₁A (F (Fin.natAdd m j))) = 0 := by
    intro j
    have hz : i.c.app (op ⊤) (f j) = 0 := hcut.c_app_eq_zero j
    rw [hπ, hFdef]
    simp only [Fin.append_right]
    rw [res_res, c_app_res, res_res]
    exact (congrArg (M.res _) hz).trans (map_zero _)
  -- the `t`-block of `F` restricts to the given sections
  have htee : ∀ j : Fin m, π (res _ hA₁A (F (Fin.castAdd k j))) =
      M.res (hWB.trans hBV₀) (s j) := by
    intro j
    rw [hπ, hFdef]
    simp only [Fin.append_left]
    rw [c_app_res, res_res]
    have h3 := congrArg (M.res hWB) (hlift j)
    simp only [res_res] at h3
    exact h3
  refine ⟨W, hWB.trans hBV₀, r, fun l j ↦ π (G l (Fin.castAdd k j)), ⟨hxB, hxA₁⟩, ?_, ?_⟩
  · intro l
    have h2 : π (∑ p : Fin (m + k), G l p * res _ hA₁A (F p)) = 0 := by
      rw [hGrel l, map_zero]
    rw [map_sum] at h2
    simp only [map_mul] at h2
    rw [Fin.sum_univ_add] at h2
    rw [show (∑ j : Fin k, π (G l (Fin.natAdd m j)) * π (res _ hA₁A (F (Fin.natAdd m j)))) = 0 from
      Finset.sum_eq_zero fun j _ ↦ by rw [hzero j, mul_zero], add_zero] at h2
    refine Eq.trans ?_ h2
    exact Finset.sum_congr rfl fun j _ ↦ by rw [htee j]
  · intro W' hW'W a ha y hy
    -- lift the coefficients `a` near `y`
    obtain ⟨A₂, hA₂y, α, B₂, hB₂W', hB₂A₂, hyB₂, hlift₂⟩ :=
      exists_localLift_family i hcut.surjective_stalkMap a y hy
    set A₃ : Opens _ := A₂ ⊓ A₁ with hA₃def
    have hA₃A₂ : A₃ ≤ A₂ := inf_le_left
    have hA₃A₁ : A₃ ≤ A₁ := inf_le_right
    have hA₃A : A₃ ≤ A := hA₃A₁.trans hA₁A
    have hyA₃ : i.base y ∈ A₃ := ⟨hA₂y, (hW'W.trans hWA₁) hy⟩
    have hB₂A₃ : B₂ ≤ (Opens.map i.base).obj A₃ :=
      fun z hz ↦ ⟨hB₂A₂ hz, (hB₂W'.trans (hW'W.trans hWA₁)) hz⟩
    set w : _ := ∑ j : Fin m, res _ hA₃A₂ (α j) * res _ hA₃A (F (Fin.castAdd k j)) with hwdef
    -- `w` pulls back to zero near `y`
    set π₂ : _ →+* M.presheaf.obj (op B₂) :=
      (M.presheaf.map (homOfLE hB₂A₃).op).hom.comp (i.c.app (op A₃)).hom with hπ₂def
    have hπ₂ : ∀ v, π₂ v = M.res hB₂A₃ (i.c.app (op A₃) v) := fun _ ↦ rfl
    have hα : ∀ j, π₂ (res _ hA₃A₂ (α j)) = M.res hB₂W' (a j) := by
      intro j
      rw [hπ₂, c_app_res, res_res]
      exact hlift₂ j
    have hts : ∀ j : Fin m, π₂ (res _ hA₃A (F (Fin.castAdd k j))) =
        M.res (hB₂W'.trans (hW'W.trans (hWB.trans hBV₀))) (s j) := by
      intro j
      rw [hπ₂, hFdef]
      simp only [Fin.append_left]
      rw [c_app_res, res_res]
      have h3 := congrArg (M.res (hB₂W'.trans (hW'W.trans hWB))) (hlift j)
      simp only [res_res] at h3
      exact h3
    have hw0 : π₂ w = 0 := by
      set ρ : M.presheaf.obj (op W') →+* M.presheaf.obj (op B₂) :=
        (M.presheaf.map (homOfLE hB₂W').op).hom with hρdef
      have hρ : ∀ v, ρ v = M.res hB₂W' v := fun _ ↦ rfl
      have h4 := congrArg ρ ha
      rw [map_sum, map_zero] at h4
      simp only [map_mul] at h4
      rw [hwdef, map_sum]
      simp only [map_mul, hα, hts]
      simpa only [hρ, res_res, map_zero] using h4
    -- hence the germ of `w` lies in the ideal generated by the germs of the `f`
    have hker : ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.germ A₃
        (i.base y) hyA₃ w ∈ Ideal.span (Set.range fun j ↦
          ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.Γgerm
            (i.base y) (f j)) := by
      rw [← hcut.ker_stalkMap y]
      change (i.stalkMap y) _ = 0
      rw [LocallyRingedSpace.stalkMap_germ_apply i A₃ y hyA₃ w,
        ← germ_res hB₂A₃ y hyB₂ (i.c.app (op A₃) w)]
      rw [show M.res hB₂A₃ (i.c.app (op A₃) w) = π₂ w from rfl, hw0, map_zero]
    obtain ⟨A₄, hA₄A₃, hyA₄, c, hc⟩ :=
      exists_localCombination w f (i.base y) hyA₃ hker
    have hA₄A₁ : A₄ ≤ A₁ := hA₄A₃.trans hA₃A₁
    have hA₄A : A₄ ≤ A := hA₄A₃.trans hA₃A
    set σ : ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op A₃) →+*
        ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op A₄) :=
      (((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.map
        (homOfLE hA₄A₃).op).hom with hσdef
    have hσ : ∀ v, σ v = res _ hA₄A₃ v := fun _ ↦ rfl
    set β : Fin (m + k) → _ :=
      Fin.append (fun j ↦ res _ (hA₄A₃.trans hA₃A₂) (α j)) (fun l ↦ -(c l)) with hβdef
    have hβrel : ∑ p : Fin (m + k), β p * res _ hA₄A (F p) = 0 := by
      rw [Fin.sum_univ_add]
      have e1 : ∑ j : Fin m, β (Fin.castAdd k j) * res _ hA₄A (F (Fin.castAdd k j)) = σ w := by
        rw [hwdef, map_sum]
        refine Finset.sum_congr rfl fun j _ ↦ ?_
        rw [map_mul, hσ, hσ, hβdef]
        simp only [Fin.append_left]
        rw [res_res, res_res]
      have e2 : ∑ l : Fin k, β (Fin.natAdd m l) * res _ hA₄A (F (Fin.natAdd m l)) =
          -∑ l : Fin k, c l * res _ le_top (f l) := by
        rw [← Finset.sum_neg_distrib]
        refine Finset.sum_congr rfl fun l _ ↦ ?_
        rw [hβdef, hFdef]
        simp only [Fin.append_right]
        rw [res_res, neg_mul]
      rw [e1, e2, hσ, hc, add_neg_cancel]
    obtain ⟨A₅, hA₅A₄, hyA₅, d, hd⟩ := hGgen A₄ hA₄A₁ β hβrel (i.base y) hyA₄
    set W'' : Opens M := B₂ ⊓ (Opens.map i.base).obj A₅ with hW''def
    have hW''B₂ : W'' ≤ B₂ := inf_le_left
    have hW''A₅ : W'' ≤ (Opens.map i.base).obj A₅ := inf_le_right
    set π₅ : ((complexAffineSpace.{u} n).restrict V.isOpenEmbedding).presheaf.obj (op A₅) →+*
        M.presheaf.obj (op W'') :=
      (M.presheaf.map (homOfLE hW''A₅).op).hom.comp (i.c.app (op A₅)).hom with hπ₅def
    have hπ₅ : ∀ v, π₅ v = M.res hW''A₅ (i.c.app (op A₅) v) := fun _ ↦ rfl
    refine ⟨W'', hW''B₂.trans hB₂W', ⟨hyB₂, hyA₅⟩, fun l ↦ π₅ (d l), fun j ↦ ?_⟩
    have h6 := congrArg π₅ (hd (Fin.castAdd k j))
    rw [map_sum] at h6
    simp only [map_mul] at h6
    have hL : π₅ (res _ hA₅A₄ (β (Fin.castAdd k j))) =
        M.res (hW''B₂.trans hB₂W') (a j) := by
      rw [hβdef]
      simp only [Fin.append_left]
      rw [hπ₅, res_res, c_app_res, res_res]
      have h7 := congrArg (M.res hW''B₂) (hlift₂ j)
      simp only [res_res] at h7
      exact h7
    have hR : ∀ l, π₅ (res _ (hA₅A₄.trans hA₄A₁) (G l (Fin.castAdd k j))) =
        M.res ((hW''B₂.trans hB₂W').trans hW'W) (π (G l (Fin.castAdd k j))) := by
      intro l
      rw [hπ₅, c_app_res, res_res, hπ, res_res]
    rw [hL] at h6
    simp only [hR] at h6
    exact h6


/-- **Coherence of the structure sheaf of a complex analytic space.**

Every point of an analytic space has a neighbourhood which is a local model, whose
structure sheaf has locally finitely generated relations; since that condition is local it
holds on all of `X`, and hence `𝒪_X` is coherent. The `ℂ`-algebra structure plays no role
here: coherence is a statement about the underlying locally ringed space. -/
theorem AnalyticSpace.isCoherentStructureSheaf (X : AnalyticSpace.{u}) :
    X.toLocallyRingedSpace.IsCoherentStructureSheaf := by
  choose U n k V i f h using X.local_model
  refine LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations
    (LocallyRingedSpace.hasLocalRelations_of_openCover
      (fun x : X.toLocallyRingedSpace ↦ (U x).1) (fun x ↦ ⟨x, (U x).2⟩) fun x ↦ ?_)
  exact LocallyRingedSpace.HasLocalRelations.hasLocalRelationsOn _
    (IsLocalModel.hasLocalRelations ⟨n x, k x, V x, i x, f x, (h x).1⟩)

/-- **A finite free sheaf of modules on a complex analytic space is coherent.**

`ComplexAnalytic.AnalyticSpace.isCoherentStructureSheaf` is this at rank one, and
`SheafOfModules.IsCoherent.free` is the induction on the rank, which has no analysis in it. This
is the form a *presentation* is pushed through: the target of a presentation is a finite free
sheaf, and `SheafOfModules.IsCoherent.cokernel` needs its target coherent.

`AlgebraicGeometry.LocallyRingedSpace.IsCoherentStructureSheaf` is a `def`, so instance search will not unfold it and
the coherence of `𝒪_X` has to be introduced in its unfolded form — the same step
`AlgebraicGeometry.LocallyRingedSpace.isCoherent_idealSheaf` documents. -/
theorem AnalyticSpace.isCoherent_free (X : AnalyticSpace.{u}) (I : Type u) [Finite I] :
    (SheafOfModules.free (R := X.toLocallyRingedSpace.ringSheaf) I).IsCoherent :=
  haveI : (SheafOfModules.unit X.toLocallyRingedSpace.ringSheaf).IsCoherent :=
    X.isCoherentStructureSheaf
  SheafOfModules.IsCoherent.free I

end ComplexAnalytic
