/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.AnalyticSpace.LocalIso

/-!
# A local isomorphism restricted to subspaces cut out by a family and by its pullbacks

Let `p : E ⟶ B` be a local isomorphism of complex analytic spaces, let `iX : X ⟶ B` cut out `X`
inside `B` by global sections `f`, and let `iY : Y ⟶ E` cut out `Y` inside `E` by the **pullbacks
of the same sections along `p`**. Then any `q : Y ⟶ X` over `p` — that is, with
`q ≫ iX = iY ≫ p` — is itself a local isomorphism
(`ComplexAnalytic.AnalyticSpace.isLocalIso_of_isCutOutBy_pullbackΓ`).

This is the sibling of `ComplexAnalytic.AnalyticSpace.isLocalIso_restrictHom`
(`Oka/AnalyticSpace/OpenSubspace.lean`), which transports the class along a change of source and
target given by an *open* subspace. Here the change is given by a *closed* one, and — as there —
nothing in the statement mentions a polynomial, a presentation or an étale morphism.

## Why the hypothesis is `q ≫ iX = iY ≫ p` and not the existence of a factorisation

`ComplexAnalytic.IsCutOutBy` does **not** produce the morphism `q`. Its mapping property is
`ComplexAnalytic.IsCutOutBy.baseLift` on underlying spaces and
`ComplexAnalytic.IsCutOutBy.hom_ext` for uniqueness; `Oka/AnalyticSpace/Basic.lean` says in terms
that *"existence of the map on structure sheaves is not proved here"*. So `q` is a hypothesis and
the square is a hypothesis, which is what a caller holding an analytified structure map already
has. Uniqueness is free from `ComplexAnalytic.IsCutOutBy.hom_ext`, so there is no ambiguity about
which `q` the conclusion is about.

## What each field costs

**The topological field is not local on `p`, and is proved from an open map plus local
injectivity.** The range identity
`ComplexAnalytic.AnalyticSpace.range_base_of_isCutOutBy_pullbackΓ` — the image of `iY` is the
`p`-preimage of the image of `iX` — **asks nothing of `p`**: a stalk map of a morphism of locally
ringed spaces is a local ring homomorphism, so it reflects as well as preserves units, and
membership of a germ in the maximal ideal transfers in both directions. With it,
`q` is an **open** map for any `p` which is one
(`ComplexAnalytic.AnalyticSpace.isOpenMap_base_of_isCutOutBy_pullbackΓ`), because the image of a
basic open of `Y` is the `iX`-preimage of an open of `B`. Local injectivity is the only place the
local-homeomorphism field of `p` is spent, and it is spent through
`IsLocalHomeomorph.isLocallyInjective`.

**The stalk field is ring theory and uses that `p` is an isomorphism on stalks twice.** Once for
surjectivity, and once to move the ideal generated by the germs of `f` across: the kernel of the
stalk map of `iY ≫ p` is the contraction along `p`'s stalk isomorphism of the ideal generated by
the germs of the pullbacks, and `Ideal.comap_map_of_surjective` turns that back into the ideal
generated by the germs of `f` themselves, which is the kernel of `iX`'s stalk map by hypothesis.
So the stalk map of `q` is a surjection whose composite with a surjection has the same kernel as
that surjection, hence bijective.

**The square is used by rewriting a whole proposition along it, not by comparing stalk maps at
two points.** The
two spellings of the point of `B` under `y` — `iX.base (q.base y)` and `p.base (iY.base y)` — are
equal only propositionally, so a lemma stated at one of them cannot be `rw`n into a goal stated at
the other without a `AlgebraicGeometry.LocallyRingedSpace.stalkMap_congr_hom` and the
specialisation map it introduces. Rewriting the whole proposition along `q ≫ iX = iY ≫ p`, whose
motive is a function of the *morphism* and so is type-correct, avoids that entirely.

## Main results

- `ComplexAnalytic.AnalyticSpace.stalkMap_Γgerm_pullbackΓ`: **the stalk map carries the germ of a
  global section to the germ of its pullback.**
- `ComplexAnalytic.AnalyticSpace.range_base_of_isCutOutBy_pullbackΓ`: **the subspace cut out by
  the pullbacks is the preimage of the subspace cut out by the sections**, on underlying spaces,
  for an arbitrary `p`.
- `ComplexAnalytic.AnalyticSpace.isOpenMap_base_of_isCutOutBy_pullbackΓ`: **the induced map is
  open** whenever `p` is.
- `ComplexAnalytic.AnalyticSpace.isLocalHomeomorph_base_of_isCutOutBy_pullbackΓ` and
  `ComplexAnalytic.AnalyticSpace.bijective_stalkMap_of_isCutOutBy_pullbackΓ`: the two fields.
- `ComplexAnalytic.AnalyticSpace.isLocalIso_of_isCutOutBy_pullbackΓ`: **the induced map between
  the cut-out subspaces is a local isomorphism.**

## What is not here

* **No converse.** Nothing below says that a local isomorphism `q` between subspaces forces `p`
  to be one along the image, and the two-out-of-three position it would occupy is the one
  `ComplexAnalytic.AnalyticSpace.isLocalIso_of_comp`'s docstring says should not be expected.
* **No `IsFiniteEtale`.** Finiteness does not transport this way — a closed immersion is finite
  and the statement would be about `q` alone — and nothing here touches that field.
* **No construction of `q`.** See the paragraph above; the square is a hypothesis.
-/

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry Topology

universe u

namespace ComplexAnalytic.AnalyticSpace

variable {X Y E B : AnalyticSpace.{u}}

/-- **The stalk map carries the germ of a global section to the germ of its pullback.**

`AlgebraicGeometry.LocallyRingedSpace.stalkMap_germ_apply` at the top open, and nothing else:
`TopCat.Presheaf.Γgerm` is the germ at `⊤` by definition, `(Opens.map p.toLRSHom.base).obj ⊤`
is `⊤`, and `ComplexAnalytic.AnalyticSpace.Hom.pullbackΓ` is `p.toLRSHom.c.app (op ⊤)`, so the
whole statement is that lemma up to definitional unfolding and no `Opens.map_top` appears.

**A term and not `rw [TopCat.Presheaf.Γgerm, …]`, and the reason is measurable rather than
stylistic.** Rewriting by the name of a Mathlib definition generates its equation lemma on demand,
and `scripts/DumpOkaDecls.lean` then attributes `TopCat.Presheaf.Γgerm.eq_1` to **this** module —
a declaration in a namespace this repository does not own, appearing in a declaration diff as
though the branch had added it. `Oka/Analytification/StandardEtaleLocalIso.lean` records the same
mechanism at a rewrite of its own where it does *not* fire; here it did, and the term avoids
it.

**And the repository already had this lemma one level down**, which the paragraph above did not
say: `AlgebraicGeometry.LocallyRingedSpace.Γgerm_Γ_map`
(`Oka/Geometry/RingedSpace/LocallyRingedSpace.lean`) is the same statement for a morphism of
locally ringed spaces, read in the other direction, and its own docstring makes the same point
about `⊤` costing nothing. The two proof *terms* are definitionally equal — `p.pullbackΓ` is
`ComplexAnalytic.AnalyticSpace.Hom.pullbackΓ`, an `abbrev` for `Γ.map p.toLRSHom.op`, so
`stalkMap_Γgerm_pullbackΓ p e s` and `(Γgerm_Γ_map p.toLRSHom s e).symm` are the same proof.
**This declaration is kept rather than retired** because it is the spelling in
`ComplexAnalytic.AnalyticSpace`'s own binders, which is what the file below consumes and what
`ComplexAnalytic.IsCutOutBy` — stated at `LocallyRingedSpace` — does not reach; a consumer at
the lower level should use `Γgerm_Γ_map` and not this. -/
theorem stalkMap_Γgerm_pullbackΓ (p : E ⟶ B) (e : E) (s : B.presheaf.obj (op ⊤)) :
    p.toLRSHom.stalkMap e (B.presheaf.Γgerm (p.toLRSHom.base e) s) =
      E.presheaf.Γgerm e (p.pullbackΓ s) :=
  LocallyRingedSpace.stalkMap_germ_apply p.toLRSHom ⊤ e trivial s

variable {k : ℕ} {f : Fin k → B.presheaf.obj (op ⊤)} {p : E ⟶ B} {iX : X ⟶ B} {iY : Y ⟶ E}

/-- **The subspace cut out by the pullbacks of a family is the preimage of the subspace cut out
by the family**, on underlying spaces.

**Nothing is asked of `p`.** `ComplexAnalytic.IsCutOutBy.range_base` describes each image as the
set of points at which every germ of the family lies in the maximal ideal, and a stalk map of a
morphism of locally ringed spaces is a **local** ring homomorphism, so `isUnit_map_iff` reads in
both directions: a germ upstairs is a unit exactly when the germ it comes from is. That is the
whole content, and it is why this lemma is stated separately from the two fields below, which do
spend hypotheses on `p`. -/
theorem range_base_of_isCutOutBy_pullbackΓ (p : E ⟶ B)
    (hX : IsCutOutBy iX.toLRSHom f)
    (hY : IsCutOutBy iY.toLRSHom (fun j ↦ p.pullbackΓ (f j))) :
    Set.range iY.toLRSHom.base = p.toLRSHom.base ⁻¹' Set.range iX.toLRSHom.base := by
  rw [hX.range_base, hY.range_base]
  ext e
  simp only [Set.mem_setOf_eq, Set.mem_preimage]
  refine forall_congr' fun j ↦ ?_
  rw [IsLocalRing.mem_maximalIdeal, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff,
    mem_nonunits_iff, ← stalkMap_Γgerm_pullbackΓ p e (f j),
    isUnit_map_iff (p.toLRSHom.stalkMap e).hom]

section

variable {q : Y ⟶ X} (hq : q ≫ iX = iY ≫ p)

include hq in
/-- **The induced map is open** whenever `p` is.

The image of an open `iY⁻¹ A` of `Y` is the `iX`-preimage of the open `p '' A` of `B`. The
inclusion that is not formal is the other one: a point of `A` lying over the image of `iX` lies
in the image of `iY`, which is `ComplexAnalytic.AnalyticSpace.range_base_of_isCutOutBy_pullbackΓ`
read from right to left, and the point of `Y` it comes from is the preimage wanted.

**Every open of `Y` has this form**, because `iY` is a closed embedding and hence inducing, so
the `rintro … rfl` loses no generality. -/
theorem isOpenMap_base_of_isCutOutBy_pullbackΓ
    (hX : IsCutOutBy iX.toLRSHom f)
    (hY : IsCutOutBy iY.toLRSHom (fun j ↦ p.pullbackΓ (f j)))
    (hp : IsOpenMap p.toLRSHom.base) : IsOpenMap q.toLRSHom.base := by
  have hbase (y : Y) :
      iX.toLRSHom.base (q.toLRSHom.base y) = p.toLRSHom.base (iY.toLRSHom.base y) :=
    congrFun (congrArg (fun m : Y ⟶ B => (m.toLRSHom.base : Y → B)) hq) y
  intro O hO
  obtain ⟨A, hA, rfl⟩ := hY.isClosedEmbedding.isEmbedding.isInducing.isOpen_iff.mp hO
  have himg : q.toLRSHom.base '' (iY.toLRSHom.base ⁻¹' A) =
      iX.toLRSHom.base ⁻¹' (p.toLRSHom.base '' A) := by
    ext x
    constructor
    · rintro ⟨y, hy, rfl⟩
      exact ⟨iY.toLRSHom.base y, hy, (hbase y).symm⟩
    · rintro ⟨e, heA, he⟩
      have hmem : e ∈ Set.range iY.toLRSHom.base := by
        rw [range_base_of_isCutOutBy_pullbackΓ p hX hY]
        exact ⟨x, he.symm⟩
      obtain ⟨y, rfl⟩ := hmem
      exact ⟨y, heA, hX.isClosedEmbedding.injective (by rw [hbase y, he])⟩
  rw [himg]
  exact (hp A hA).preimage iX.toLRSHom.base.hom.continuous

include hq in
/-- **The topological field**: the induced map is a local homeomorphism.

Openness is the lemma above and is global. What is local is injectivity, and it is the only use
of `p`'s own local-homeomorphism field: on the `iY`-preimage of an open on which `p` is injective,
two points of `Y` with the same image under `q` have the same image under `iX ∘ q = p ∘ iY`, hence
under `iY`, hence are equal because `iY` is a closed embedding. A continuous injective open map is
an open embedding, and an open embedding on a neighbourhood of every point is exactly
`isLocalHomeomorph_iff_isOpenEmbedding_restrict`. -/
theorem isLocalHomeomorph_base_of_isCutOutBy_pullbackΓ [IsLocalIso p]
    (hX : IsCutOutBy iX.toLRSHom f)
    (hY : IsCutOutBy iY.toLRSHom (fun j ↦ p.pullbackΓ (f j))) :
    IsLocalHomeomorph q.toLRSHom.base := by
  have hbase (y : Y) :
      iX.toLRSHom.base (q.toLRSHom.base y) = p.toLRSHom.base (iY.toLRSHom.base y) :=
    congrFun (congrArg (fun m : Y ⟶ B => (m.toLRSHom.base : Y → B)) hq) y
  have hp : IsLocalHomeomorph p.toLRSHom.base := IsLocalIso.isLocalHomeomorph
  have hopen := isOpenMap_base_of_isCutOutBy_pullbackΓ hq hX hY hp.isOpenMap
  rw [isLocalHomeomorph_iff_isOpenEmbedding_restrict]
  intro y
  obtain ⟨U, hU, hyU, hinj⟩ := hp.isLocallyInjective (iY.toLRSHom.base y)
  have hWopen : IsOpen (iY.toLRSHom.base ⁻¹' U) := hU.preimage iY.toLRSHom.base.hom.continuous
  refine ⟨iY.toLRSHom.base ⁻¹' U, hWopen.mem_nhds hyU,
    IsOpenEmbedding.of_continuous_injective_isOpenMap
      (q.toLRSHom.base.hom.continuous.comp continuous_subtype_val) ?_ (hopen.restrict hWopen)⟩
  rintro ⟨y₁, h₁⟩ ⟨y₂, h₂⟩ hh
  simp only [Set.restrict_apply] at hh
  exact Subtype.ext (hY.isClosedEmbedding.injective
    (hinj h₁ h₂ (by rw [← hbase y₁, ← hbase y₂, hh])))

include hq in
/-- **The stalk field**: the induced map is bijective on stalks.

Both halves are read off the composite `iY ≫ p`, whose stalk map at `y` splits as `p`'s stalk
isomorphism followed by `iY`'s quotient map, and are then transported to `q ≫ iX` by rewriting
along the square. **That rewrite is the reason the proof is arranged this way**: the source object
of the stalk map depends on the morphism, so the propositional equality of the two points is not
available to `rw`, while the equality of the two *morphisms* is.

The kernel computation is `RingHom.comap_ker` followed by `Ideal.comap_map_of_surjective`: the
germs of the pullbacks are the images of the germs of `f` under `p`'s stalk isomorphism
(`ComplexAnalytic.AnalyticSpace.stalkMap_Γgerm_pullbackΓ`), so contracting the ideal they generate
returns the ideal generated by the germs of `f` up to the kernel of that isomorphism, which is
`⊥`. -/
theorem bijective_stalkMap_of_isCutOutBy_pullbackΓ [IsLocalIso p]
    (hX : IsCutOutBy iX.toLRSHom f)
    (hY : IsCutOutBy iY.toLRSHom (fun j ↦ p.pullbackΓ (f j))) (y : Y) :
    Function.Bijective (q.toLRSHom.stalkMap y).hom := by
  set φ := (p.toLRSHom.stalkMap (iY.toLRSHom.base y)).hom
  have hbij : Function.Bijective φ :=
    ConcreteCategory.bijective_of_isIso (p.toLRSHom.stalkMap (iY.toLRSHom.base y))
  have hsplit : ((iY ≫ p).toLRSHom.stalkMap y) =
      p.toLRSHom.stalkMap (iY.toLRSHom.base y) ≫ iY.toLRSHom.stalkMap y :=
    LocallyRingedSpace.stalkMap_comp iY.toLRSHom p.toLRSHom y
  have hsurj : Function.Surjective ((iY ≫ p).toLRSHom.stalkMap y).hom := by
    rw [hsplit]
    exact (hY.surjective_stalkMap y).comp hbij.2
  have hkerc : RingHom.ker ((iY ≫ p).toLRSHom.stalkMap y).hom =
      Ideal.span (Set.range fun j ↦ B.presheaf.Γgerm ((iY ≫ p).toLRSHom.base y) (f j)) := by
    have hker : RingHom.ker ((iY ≫ p).toLRSHom.stalkMap y).hom =
        Ideal.comap φ (RingHom.ker (iY.toLRSHom.stalkMap y).hom) := by
      rw [hsplit, RingHom.comap_ker]
      rfl
    have himg : (Set.range fun j ↦ E.presheaf.Γgerm (iY.toLRSHom.base y) (p.pullbackΓ (f j))) =
        φ '' (Set.range fun j ↦ B.presheaf.Γgerm ((iY ≫ p).toLRSHom.base y) (f j)) := by
      rw [← Set.range_comp]
      exact congrArg Set.range (funext fun j ↦ (stalkMap_Γgerm_pullbackΓ p _ (f j)).symm)
    have hbot : Ideal.comap φ (⊥ : Ideal _) = ⊥ := (RingHom.injective_iff_ker_eq_bot φ).mp hbij.1
    rw [hker, hY.ker_stalkMap y, himg, ← Ideal.map_span,
      Ideal.comap_map_of_surjective φ hbij.2, hbot, sup_bot_eq]
    rfl
  rw [← hq] at hsurj hkerc
  have hcomp : ((q ≫ iX).toLRSHom.stalkMap y) =
      iX.toLRSHom.stalkMap (q.toLRSHom.base y) ≫ q.toLRSHom.stalkMap y :=
    LocallyRingedSpace.stalkMap_comp q.toLRSHom iX.toLRSHom y
  rw [hcomp] at hsurj hkerc
  have hkey : RingHom.ker ((iX.toLRSHom.stalkMap (q.toLRSHom.base y) ≫
        q.toLRSHom.stalkMap y)).hom =
      RingHom.ker (iX.toLRSHom.stalkMap (q.toLRSHom.base y)).hom := by
    rw [hX.ker_stalkMap (q.toLRSHom.base y)]
    exact hkerc
  refine ⟨?_, Function.Surjective.of_comp
    (g := (iX.toLRSHom.stalkMap (q.toLRSHom.base y)).hom) hsurj⟩
  rw [injective_iff_map_eq_zero]
  intro t ht
  obtain ⟨s, rfl⟩ := hX.surjective_stalkMap (q.toLRSHom.base y) t
  have hs : s ∈ RingHom.ker ((iX.toLRSHom.stalkMap (q.toLRSHom.base y) ≫
      q.toLRSHom.stalkMap y)).hom := ht
  rw [hkey] at hs
  exact hs

include hq in
/-- **A local isomorphism restricted to subspaces cut out by a family and by its pullbacks is a
local isomorphism.**

The two fields are the two lemmas above and nothing is added here. What the statement asks of the
caller is a square `q ≫ iX = iY ≫ p` and two cut-out data whose families are related by
`ComplexAnalytic.AnalyticSpace.Hom.pullbackΓ`; what it asks of the geometry is only that `p` is a
local isomorphism. In particular the number `k` of cutting sections is arbitrary and the same on
both sides, which is what makes this usable where a statement about a *single* cutting section
is not. -/
theorem isLocalIso_of_isCutOutBy_pullbackΓ [IsLocalIso p]
    (hX : IsCutOutBy iX.toLRSHom f)
    (hY : IsCutOutBy iY.toLRSHom (fun j ↦ p.pullbackΓ (f j))) :
    IsLocalIso q where
  isLocalHomeomorph := isLocalHomeomorph_base_of_isCutOutBy_pullbackΓ hq hX hY
  isIso_stalkMap y :=
    (ConcreteCategory.isIso_iff_bijective _).2
      (bijective_stalkMap_of_isCutOutBy_pullbackΓ hq hX hY y)

end

end ComplexAnalytic.AnalyticSpace
