/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.AnalyticSpace.Evaluation

/-!
# A germ on `ℂ^ι` is determined by where the coordinates go

Taxis #653 asks for two things: that evaluation is natural in the space, and that a morphism of
analytic spaces `Z ⟶ ℂ^n` is determined by the pullbacks of the coordinate functions. The first
is done, in `Oka/AnalyticSpace/Evaluation.lean`
(`ComplexAnalytic.AnalyticSpace.evalStalk_stalkMap` and `eval_c_app`). This file is **the
algebraic heart of the second, and not the second itself**; see `## What this file does not do`.

What it proves is that a local `ℂ`-algebra homomorphism out of a stalk of `𝒪_{ℂ^ι}`, into a
Noetherian local ring, is determined by the images of the germs of the coordinate functions —
`ComplexAnalytic.okaStalk_ringHom_ext`. That is the statement the injectivity of
`Hom(Z, ℂ^n) → Γ(Z, 𝒪_Z)^n` reduces to once the morphisms are compared on stalks.

## Why it is true, and where each hypothesis is used

The general fact is `IsLocalRing.IsCoefficientField.ringHom_ext`, in the mirror tree: for `S`
local with a coefficient field `α : K →+* S` and a **finitely generated** maximal ideal, and `A`
local **Noetherian**, two homomorphisms `S → A` with `θ` local agreeing on the constants and on
generators of `𝔪_S` are equal. The proof is an induction: an element is a constant plus an
`S`-combination of the generators, so `θ x - θ' x` is a sum of terms `θ (v i) * (θ q - θ' q)`
with the second factor in `𝔪_A ^ k` by induction and the first in `𝔪_A` because `θ` is local.
Krull's intersection theorem, which is where Noetherianness enters, then kills the difference.

Only `θ` need be local — the induction pushes everything through `θ` — and `S` itself need not
be Noetherian.

Applying it at a stalk of `𝒪_{ℂ^ι}` needs the maximal ideal to be finitely generated *by
elements a morphism can be tested on*, which is
`ComplexAnalytic.maximalIdeal_stalk_eq_span_stalkCoord`: it is generated by the germs of the
coordinate functions normalised to vanish at the point. That is
`LocalOkaRing.maximalIdeal_eq_span_coord` transported along `okaStalkEquiv`, and the transport
needs one computation which was not in the development —
`OkaRing.germ_ofMvPolynomial_X`, that the Taylor series of `zᵢ` at `y` is `yᵢ + Xᵢ`.

## What this file does not do

**It does not prove that a morphism `Z ⟶ ℂ^n` is determined by the pullbacks of the
coordinates.** Of the four steps of taxis #653's route, this file and
`Oka/AnalyticSpace/Evaluation.lean` do steps 1, 3 and 4; step 2 is missing. Precisely, what
remains is to go from "the stalk maps of `φ` and `ψ` at every point agree" to `φ = ψ`, which is
`AlgebraicGeometry.SheafedSpace.hom_stalk_ext` (`Mathlib/Geometry/RingedSpace/SheafedSpace.lean`)
transported through `LocallyRingedSpace.forgetToSheafedSpace` and
`ComplexAnalytic.AnalyticSpace.forgetToLocallyRingedSpace`, both faithful. Its statement carries
a `TopCat.Presheaf.stalkCongr` transport along the equality of base maps, and it is that
transport, not the algebra, that is left.

The base maps do agree, and that half is available: by
`ComplexAnalytic.AnalyticSpace.eval_c_app` the `j`-th coordinate of `φ.base z` is the value at
`z` of the pullback of the `j`-th coordinate function, so equal pullbacks give equal base maps.

## Main results

- `OkaRing.germ_ofMvPolynomial_X`: the Taylor series of the `i`-th coordinate function at `y` is
  `y i + Xᵢ`.
- `ComplexAnalytic.maximalIdeal_stalk_eq_span_stalkCoord`: the maximal ideal of a stalk of
  `𝒪_{ℂ^ι}` is generated by the normalised coordinate germs.
- `ComplexAnalytic.okaStalk_ringHom_ext`: **a local `ℂ`-algebra map out of such a stalk into a
  Noetherian local ring is determined by the images of the coordinate germs.**

## References

- [Hans Grauert and Reinhold Remmert, *Analytische Stellenalgebren*][grauert-remmert1971], §I
-/

open CategoryTheory TopologicalSpace Opposite AlgebraicGeometry IsLocalRing

universe u

noncomputable section

namespace OkaRing

variable {ι : Type u} [Fintype ι] {U : Opens (ι → ℂ)} {y : ι → ℂ}

/-- **The Taylor series of the `i`-th coordinate function at `y` is `y i + Xᵢ`.** -/
lemma germ_ofMvPolynomial_X (hy : y ∈ U) (i : ι) :
    OkaRing.germ hy (OkaRing.ofMvPolynomial U (MvPolynomial.X i)) =
      algebraMap ℂ (LocalOkaRing ι) (y i) + LocalOkaRing.coord i := by
  refine OkaRing.germ_eq_of_represents hy ?_
  have hcoe : ((algebraMap ℂ (LocalOkaRing ι) (y i) + LocalOkaRing.coord i :
        LocalOkaRing ι) : MvPowerSeries ι ℂ) =
      algebraMap ℂ (MvPowerSeries ι ℂ) (y i) + MvPowerSeries.X i := by
    rw [Subalgebra.coe_add, LocalOkaRing.coe_coord]
    rfl
  rw [hcoe]
  refine ((MvPowerSeries.represents_algebraMap (ι := ι) (y i)).add
    (MvPowerSeries.represents_X i)).congr ?_
  have hnhds : ∀ᶠ z : ι → ℂ in nhds (0 : ι → ℂ), z + y ∈ U := by
    have htend : Filter.Tendsto (fun z : ι → ℂ ↦ z + y) (nhds 0) (nhds y) := by
      simpa using (continuous_add_const y).tendsto (0 : ι → ℂ)
    exact htend (U.isOpen.mem_nhds hy)
  filter_upwards [hnhds] with z hz
  rw [Pi.add_apply, Function.const_apply,
    OkaRing.toGlobalFun_ofMvPolynomial (U := U) hz (MvPolynomial.X i), MvPolynomial.eval_X,
    Pi.add_apply, add_comm]

end OkaRing

namespace ComplexAnalytic

variable {ι : Type u} [Fintype ι]

/-- The germ at `y` of the `i`-th coordinate function, normalised to vanish at `y`: a generator
of the maximal ideal of the stalk of `𝒪_{ℂ^ι}` at `y`. -/
def stalkCoord (y : ι → ℂ) (i : ι) : (okaCommPresheaf ι).stalk y :=
  ((okaCommPresheaf ι).germ ⊤ y trivial).hom
      (OkaRing.ofMvPolynomial ⊤ (MvPolynomial.X i)) -
    ((okaCommPresheaf ι).germ ⊤ y trivial).hom (algebraMap ℂ (OkaRing ⊤) (y i))

/-- Under the Taylor expansion isomorphism, `stalkCoord` is the coordinate of `LocalOkaRing`. -/
@[simp]
lemma okaStalkEquiv_stalkCoord (y : ι → ℂ) (i : ι) :
    okaStalkEquiv y (stalkCoord y i) = LocalOkaRing.coord i := by
  rw [stalkCoord, map_sub, okaStalkEquiv_germ, okaStalkEquiv_germ_algebraMap,
    OkaRing.germ_ofMvPolynomial_X, add_sub_cancel_left]

/-- **The maximal ideal of a stalk of `𝒪_{ℂ^ι}` is generated by the normalised coordinates.**

`LocalOkaRing.maximalIdeal_eq_span_coord` transported along `okaStalkEquiv`. -/
lemma maximalIdeal_stalk_eq_span_stalkCoord (y : ι → ℂ) :
    maximalIdeal ((okaCommPresheaf ι).stalk y) = Ideal.span (Set.range (stalkCoord y)) := by
  have hsymm : Ideal.map ((okaStalkEquiv y).symm : LocalOkaRing ι →+* _)
      (maximalIdeal (LocalOkaRing ι)) = maximalIdeal ((okaCommPresheaf ι).stalk y) :=
    IsLocalRing.map_ringEquiv_maximalIdeal _
  rw [← hsymm, LocalOkaRing.maximalIdeal_eq_span_coord, Ideal.map_span, ← Set.range_comp]
  refine congrArg Ideal.span (congrArg Set.range (funext fun i ↦ ?_))
  exact ((okaStalkEquiv y).symm_apply_eq).2 (okaStalkEquiv_stalkCoord y i).symm

/-- **A local `ℂ`-algebra homomorphism out of a stalk of `𝒪_{ℂ^ι}`, into a Noetherian local
ring, is determined by the images of the germs of the coordinate functions.**

This is `IsLocalRing.IsCoefficientField.ringHom_ext` at the stalk, with
`ComplexAnalytic.maximalIdeal_stalk_eq_span_stalkCoord` supplying the generators of the maximal
ideal and `ComplexAnalytic.isCoefficientField_germ_algebraMap` the coefficient field. Note that
only `θ` is required to be local: the argument writes an element as a constant plus a
combination of the generators and pushes the difference into `𝔪 ^ k`, and only one of the two
maps has to carry non-units to non-units for that. -/
theorem okaStalk_ringHom_ext {y : ι → ℂ} {A : Type*} [CommRing A] [IsLocalRing A]
    [IsNoetherianRing A] {θ θ' : (okaCommPresheaf ι).stalk y →+* A} [IsLocalHom θ]
    (hconst : ∀ c : ℂ, θ (((okaCommPresheaf ι).germ ⊤ y trivial).hom
          (algebraMap ℂ (OkaRing ⊤) c)) =
        θ' (((okaCommPresheaf ι).germ ⊤ y trivial).hom (algebraMap ℂ (OkaRing ⊤) c)))
    (hcoord : ∀ i : ι, θ (((okaCommPresheaf ι).germ ⊤ y trivial).hom
          (OkaRing.ofMvPolynomial ⊤ (MvPolynomial.X i))) =
        θ' (((okaCommPresheaf ι).germ ⊤ y trivial).hom
          (OkaRing.ofMvPolynomial ⊤ (MvPolynomial.X i)))) :
    θ = θ' :=
  (isCoefficientField_germ_algebraMap (U := ⊤) (y := y) trivial).ringHom_ext
    (maximalIdeal_stalk_eq_span_stalkCoord y) hconst fun i ↦ by
      rw [stalkCoord, map_sub, map_sub, hconst, hcoord]

end ComplexAnalytic
