/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Stability
import Oka.AnalyticSpace.Coherent

/-!
# Coherence of finitely generated ideal sheaves

`ComplexAnalytic.AnalyticSpace.isCoherentStructureSheaf` says that `𝒪_X` is coherent over
itself. This file turns that into the statement downstream users need: the ideal sheaf generated
by finitely many global sections of `𝒪_X` is coherent, and the sheaf of relations between them
is of finite type.

The mechanism is the two-out-of-three stability of coherence, applied to
`sectionsHom : 𝒪 ^ I ⟶ 𝒪`. The only subtlety is that **no coherence of `𝒪 ^ I` is available or
needed**: `SheafOfModules.IsCoherent.image_of_isFiniteType` asks only that the *source* be of
finite type, because the image is a quotient of the source (hence of finite type) and a finite
type subsheaf of a coherent sheaf is coherent. A finite free sheaf of modules is of finite type
by `SheafOfModules.isFiniteType_free`, so nothing more is required.

## Main definitions

- `AlgebraicGeometry.LocallyRingedSpace.sectionsHom`: the morphism `𝒪_Y ^ I ⟶ 𝒪_Y` given by
  multiplication by a family of global sections, computed on sections over an open set by
  `AlgebraicGeometry.LocallyRingedSpace.val_app_sectionsHom`.
- `AlgebraicGeometry.LocallyRingedSpace.idealSheaf`: the ideal sheaf they generate, defined as
  the image of `sectionsHom`, with its inclusion `idealSheafι` into `𝒪_Y`.

## Main results

- `AlgebraicGeometry.LocallyRingedSpace.isCoherent_idealSheaf`: on a locally ringed space with
  coherent structure sheaf, a finitely generated ideal sheaf is coherent.
- `AlgebraicGeometry.LocallyRingedSpace.isFiniteType_kernel_sectionsHom`: the sheaf of relations
  between finitely many global sections is of finite type. On `ℂ^n` this is Oka's coherence
  lemma, read through the sheaf-of-modules formalism.
- `AlgebraicGeometry.LocallyRingedSpace.isCoherent_cokernel_sectionsHom`: the quotient
  `𝒪_Y ⧸ (f₁, …, f_k)` is coherent.
- `ComplexAnalytic.AnalyticSpace.isCoherent_idealSheaf`: the same for a complex analytic space,
  where the hypothesis is discharged by the main theorem.

## Implementation notes

`LocallyRingedSpace.IsCoherentStructureSheaf` is a `def`, not an `abbrev`, so instance search
does not unfold it; coherence of `𝒪_Y` has to be introduced in its unfolded form
`(SheafOfModules.unit Y.ringSheaf).IsCoherent` before the stability lemmas will fire. The same
reducibility boundary is why `Oka/AnalyticSpace/Noetherian.lean` registers two forms of the
stalk instance.

## References

- [Jean-Pierre Serre, *Faisceaux algébriques cohérents*][serre1955], §2
- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984], §A
-/

open CategoryTheory Limits TopologicalSpace Opposite AlgebraicGeometry

universe u

namespace AlgebraicGeometry.LocallyRingedSpace

variable (Y : LocallyRingedSpace.{u})

/-- The morphism `𝒪_Y ^ I ⟶ 𝒪_Y` of sheaves of modules given by multiplication by a family
`f : I → Γ(Y, 𝒪_Y)` of global sections. -/
noncomputable def sectionsHom {I : Type u} (f : I → Y.presheaf.obj (op ⊤)) :
    SheafOfModules.free (R := Y.ringSheaf) I ⟶ SheafOfModules.unit Y.ringSheaf :=
  (SheafOfModules.freeHomEquiv _).symm
    (fun i ↦ SheafOfModules.sectionOfTerminal isTerminalTop _ (f i))

@[simp]
lemma freeHomEquiv_sectionsHom {I : Type u} (f : I → Y.presheaf.obj (op ⊤)) (i : I) :
    SheafOfModules.freeHomEquiv _ (Y.sectionsHom f) i =
      SheafOfModules.sectionOfTerminal isTerminalTop _ (f i) :=
  congrFun (Equiv.apply_symm_apply _ _) i

/-- `sectionsHom` on sections over an open set `V`: it sends a tuple to the corresponding
`𝒪_Y(V)`-combination of the restrictions of the `f i` to `V`.

`freeHomEquiv_sectionsHom` already pins the morphism down, since `freeHomEquiv` is an `Equiv`,
but this is the elementwise form a downstream proof will want. The scalar action has to be `•`
and not `*`: `Y.ringSheaf.obj.obj (op V)` and `Y.presheaf.obj (op V)` share a carrier but are
not the same type as far as elaboration is concerned. -/
@[simp]
lemma val_app_sectionsHom {I : Type u} [Fintype I] [DecidableEq I]
    (f : I → Y.presheaf.obj (op ⊤)) (V : Opens Y)
    (b : (SheafOfModules.free (R := Y.ringSheaf) I).val.obj (op V)) :
    (Y.sectionsHom f).val.app (op V) b =
      ∑ i : I, SheafOfModules.freeEval (R := Y.ringSheaf) (I := I) (op V) b i •
        (SheafOfModules.unit Y.ringSheaf).val.map (homOfLE (le_top (a := V))).op
          ((f i : Y.presheaf.obj (op ⊤)) : (SheafOfModules.unit Y.ringSheaf).val.obj (op ⊤)) := by
  rw [SheafOfModules.val_app_eq_sum]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [Y.freeHomEquiv_sectionsHom f i]
  rfl

/-- The ideal sheaf generated by a family of global sections of the structure sheaf: the image
of `sectionsHom`, i.e. the subsheaf of `𝒪_Y` whose sections over `V` are, locally on `V`, the
`𝒪_Y`-combinations of the `f i`. -/
noncomputable def idealSheaf {I : Type u} (f : I → Y.presheaf.obj (op ⊤)) :
    SheafOfModules.{u} Y.ringSheaf :=
  Abelian.image (Y.sectionsHom f)

/-- The inclusion of the ideal sheaf into the structure sheaf. -/
noncomputable def idealSheafι {I : Type u} (f : I → Y.presheaf.obj (op ⊤)) :
    Y.idealSheaf f ⟶ SheafOfModules.unit Y.ringSheaf :=
  Abelian.image.ι (Y.sectionsHom f)

instance {I : Type u} (f : I → Y.presheaf.obj (op ⊤)) : Mono (Y.idealSheafι f) :=
  inferInstanceAs (Mono (Abelian.image.ι _))

/-- **A finitely generated ideal sheaf on a locally ringed space with coherent structure sheaf
is coherent.**

The point is that no coherence of `𝒪_Y ^ I` is needed: the ideal sheaf is a quotient of it,
hence of finite type, and a finite type subsheaf of a coherent sheaf is coherent. -/
theorem isCoherent_idealSheaf (h : Y.IsCoherentStructureSheaf) {I : Type u} [Finite I]
    (f : I → Y.presheaf.obj (op ⊤)) : (Y.idealSheaf f).IsCoherent :=
  -- `IsCoherentStructureSheaf` is a `def`, so instance search will not unfold it: the
  -- coherence of `𝒪_Y` has to be introduced in its unfolded form.
  haveI : (SheafOfModules.unit Y.ringSheaf).IsCoherent := h
  SheafOfModules.IsCoherent.image_of_isFiniteType _

/-- **The sheaf of relations between finitely many global sections is of finite type**, on a
locally ringed space with coherent structure sheaf.

On `ℂ^n` this is Oka's coherence lemma (`theorem oka` of `Oka/Statement.lean`) read through the
sheaf-of-modules formalism: the relations between finitely many holomorphic functions are, near
every point, generated by finitely many of them. -/
theorem isFiniteType_kernel_sectionsHom (h : Y.IsCoherentStructureSheaf) {I : Type u} [Finite I]
    (f : I → Y.presheaf.obj (op ⊤)) : (kernel (Y.sectionsHom f)).IsFiniteType :=
  haveI : (SheafOfModules.unit Y.ringSheaf).IsCoherent := h
  SheafOfModules.isFiniteType_kernel_of_isCoherent _

/-- **The quotient of the structure sheaf by a finitely generated ideal sheaf is coherent**, on
a locally ringed space with coherent structure sheaf.

This is the third leg of two-out-of-three, `SheafOfModules.IsCoherent.cokernel`, and again only
the finite type of the source `𝒪_Y ^ I` is used. The quotient is the structure sheaf of the
closed subspace cut out by the `f i`, so this is what makes the theory of coherent sheaves
available on an analytic subspace rather than only on the ambient space. -/
theorem isCoherent_cokernel_sectionsHom (h : Y.IsCoherentStructureSheaf) {I : Type u} [Finite I]
    (f : I → Y.presheaf.obj (op ⊤)) : (cokernel (Y.sectionsHom f)).IsCoherent :=
  haveI : (SheafOfModules.unit Y.ringSheaf).IsCoherent := h
  SheafOfModules.IsCoherent.cokernel _

end AlgebraicGeometry.LocallyRingedSpace

namespace ComplexAnalytic.AnalyticSpace

variable (X : AnalyticSpace.{u})

/-- **The ideal sheaf generated by finitely many global holomorphic functions on a complex
analytic space is coherent.**

This is the first consequence of `ComplexAnalytic.AnalyticSpace.isCoherentStructureSheaf`, and
the form in which coherence is used: everything about analytic subsets starts by applying the
two-out-of-three stability properties to a morphism `𝒪_X ^ k ⟶ 𝒪_X`. -/
theorem isCoherent_idealSheaf {I : Type u} [Finite I]
    (f : I → X.presheaf.obj (op ⊤)) :
    (X.toLocallyRingedSpace.idealSheaf f).IsCoherent :=
  X.toLocallyRingedSpace.isCoherent_idealSheaf X.isCoherentStructureSheaf f

/-- **The sheaf of relations between finitely many global holomorphic functions on a complex
analytic space is of finite type.** -/
theorem isFiniteType_kernel_sectionsHom {I : Type u} [Finite I]
    (f : I → X.presheaf.obj (op ⊤)) :
    (kernel (X.toLocallyRingedSpace.sectionsHom f)).IsFiniteType :=
  X.toLocallyRingedSpace.isFiniteType_kernel_sectionsHom X.isCoherentStructureSheaf f

/-- **The quotient of the structure sheaf of a complex analytic space by a finitely generated
ideal sheaf is coherent.** -/
theorem isCoherent_cokernel_sectionsHom {I : Type u} [Finite I]
    (f : I → X.presheaf.obj (op ⊤)) :
    (cokernel (X.toLocallyRingedSpace.sectionsHom f)).IsCoherent :=
  X.toLocallyRingedSpace.isCoherent_cokernel_sectionsHom X.isCoherentStructureSheaf f

end ComplexAnalytic.AnalyticSpace
