/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.Algebra.Category.ModuleCat.Sheaf.PullbackFree
import Oka.Topology.Category.TopCat.Opens
import Oka.ComplexSpace
import Oka.Coherent

/-!
# Coherence of the structure sheaf from local relations

Coherence of a sheaf of modules is defined by a condition on every object of the site and on
every one of its slice sites, which makes it awkward to transport between a space and its open
subspaces. This file provides a concrete replacement:
`AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations` says that, near every point, the
relations between finitely many sections of `𝒪_Y` are generated by finitely many of them. It
mentions only open subsets, sections and restriction maps, so it is manifestly local.

The main theorem `isCoherentStructureSheaf_of_hasLocalRelations` shows this concrete condition
implies coherence, by the argument of `Oka.Coherent` carried out over an arbitrary locally
ringed space instead of `ℂ^ι`.

## Main definitions

- `AlgebraicGeometry.LocallyRingedSpace.ringSheaf`: the structure sheaf as a sheaf of rings.
- `AlgebraicGeometry.LocallyRingedSpace.Hom.toRingSheafHom`: the induced morphism of sheaves of
  rings, and `AlgebraicGeometry.LocallyRingedSpace.Hom.pullbackModules`, the pullback of
  `𝒪`-modules along it, and `AlgebraicGeometry.LocallyRingedSpace.Hom.pullbackModulesUnitToUnit`,
  the canonical map from the pullback of `𝒪_Y` to `𝒪_X` — **which is an isomorphism**,
  `AlgebraicGeometry.LocallyRingedSpace.isIso_pullbackModulesUnitToUnit`, and with it pullback
  sends free sheaves to free sheaves. Material for a Mathlib file that does
  not exist — Mathlib has these for schemes only, `AlgebraicGeometry.Scheme.Hom.toRingCatSheafHom`
  among them — and they live here, next to `ringSheaf`, because they must agree with it on how
  the site is spelled; see `ringSheaf`'s docstring.
- `AlgebraicGeometry.LocallyRingedSpace.IsCoherentStructureSheaf`: `𝒪_Y` is coherent over itself.
- `AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations`: the concrete relations condition.

## Main results

- `isCoherentStructureSheaf_of_hasLocalRelations`: local relations imply coherence.
- `hasLocalRelations_complexSpace`: `oka` says exactly that `ℂ^ι` has local relations.
-/

open CategoryTheory Limits TopologicalSpace Opposite SheafOfModules AlgebraicGeometry

universe u

namespace AlgebraicGeometry.LocallyRingedSpace

variable (Y : LocallyRingedSpace.{u})

/-- The structure sheaf of a locally ringed space, viewed as a sheaf of rings rather than of
commutative rings. This is the form in which the theory of `SheafOfModules` and coherence
applies.

**The site is spelled `↑Y.toPresheafedSpace` rather than `↑Y`, and that is load-bearing.** The
two are definitionally equal, but `TopologicalSpace.Opens.map f.base` — for `f` a morphism of
locally ringed spaces — carries its implicit type arguments in the first spelling, and instance
search does not cross the two. `↑Y` elaborates to `↑Y.toTopCat`, and that is what makes the two
discrimination-tree keys differ, since the key is built from the elaborated implicit arguments;
so with `↑Y` here, Mathlib's

`instance : (Opens.map f).IsContinuous (Opens.grothendieckTopology Y)
  (Opens.grothendieckTopology X)`

is not found for `f.base`. Measured in three sessions.

**The consequence is a cost and not an impossibility, which is a correction of what this
docstring used to say.** The missing instance can be declared by hand — `inferInstanceAs` from
the `↑Y.toPresheafedSpace` spelling of the same statement transports it — and with it
`AlgebraicGeometry.LocallyRingedSpace.Hom.toRingSheafHom` below can be stated at the `↑Y` site
after all; without it, it cannot, and that half was measured too. So the old spelling costs one
transported instance, which every consumer would then need, where the spelling used here costs
none and is what `Opens.map` produces anyway. **Do not tidy it back.** -/
noncomputable def ringSheaf :
    Sheaf (Opens.grothendieckTopology ↑Y.toPresheafedSpace) RingCat.{u} :=
  ⟨Y.presheaf ⋙ forget₂ CommRingCat.{u} RingCat.{u},
    (TopCat.Presheaf.isSheaf_iff_isSheaf_comp
      (forget₂ CommRingCat.{u} RingCat.{u}) Y.presheaf).1 Y.IsSheaf⟩

/-- Sheafification is available at the site `AlgebraicGeometry.LocallyRingedSpace.ringSheaf` uses.

Mathlib has this for `Opens.grothendieckTopology ↑Y.toTopCat`; the two spellings are
definitionally equal and instance search does not cross them, for the reason above. -/
instance hasSheafify_toPresheafedSpace :
    HasSheafify (Opens.grothendieckTopology ↑Y.toPresheafedSpace) AddCommGrpCat.{u} :=
  inferInstanceAs (HasSheafify (Opens.grothendieckTopology ↑Y.toTopCat) AddCommGrpCat.{u})

variable {Y} in
/-- **The morphism of sheaves of rings attached to a morphism of locally ringed spaces.**

Mathlib has this for schemes, as `AlgebraicGeometry.Scheme.Hom.toRingCatSheafHom`, and not for
locally ringed spaces; this is that definition verbatim. It is what
`SheafOfModules.pullback` consumes, and hence what makes the pullback of
`𝒪`-modules along a morphism of locally ringed spaces — the analytification of a sheaf, among
other things — available at all. -/
noncomputable def Hom.toRingSheafHom {X : LocallyRingedSpace.{u}} (f : X ⟶ Y) :
    Y.ringSheaf ⟶ ((Opens.map f.base).sheafPushforwardContinuous
      RingCat.{u} _ _).obj X.ringSheaf where
  hom := Functor.whiskerRight f.c _

variable {Y} in
/-- **Pullback of `𝒪`-modules along a morphism of locally ringed spaces.**

`SheafOfModules.pullback`, which Mathlib defines as the left adjoint of
`SheafOfModules.pushforward` for any morphism of sheaves of rings over a continuous functor of
sites, applied to `AlgebraicGeometry.LocallyRingedSpace.Hom.toRingSheafHom`. Mathlib uses exactly
this to make `AlgebraicGeometry.Scheme.Modules` functorial; nothing about it is special to
schemes, and the only thing that had to be supplied for locally ringed spaces is the morphism of
sheaves of rings above. -/
noncomputable def Hom.pullbackModules {X : LocallyRingedSpace.{u}} (f : X ⟶ Y) :
    SheafOfModules.{u} Y.ringSheaf ⥤ SheafOfModules.{u} X.ringSheaf :=
  SheafOfModules.pullback.{u} f.toRingSheafHom

variable {Y} in
/-- **Pullback is left adjoint to pushforward**, which is what determines it: it is defined as
that left adjoint, so this is the adjunction and not a theorem about it. -/
noncomputable def Hom.pullbackModulesAdj {X : LocallyRingedSpace.{u}} (f : X ⟶ Y) :
    f.pullbackModules ⊣ SheafOfModules.pushforward.{u} f.toRingSheafHom :=
  SheafOfModules.pullbackPushforwardAdjunction.{u} f.toRingSheafHom

variable {Y} in
/-- **The pullback of the structure sheaf maps canonically to the structure sheaf.**

`SheafOfModules.pullbackObjUnitToUnit`, which needs no hypothesis on `f` beyond the adjunction
that defines the pullback. This is the map that makes `𝒪_X` an algebra over the pullback of
`𝒪_Y`, and it is what a comparison theorem between the two structure sheaves is a statement
about. -/
noncomputable def Hom.pullbackModulesUnitToUnit {X : LocallyRingedSpace.{u}} (f : X ⟶ Y) :
    f.pullbackModules.obj (SheafOfModules.unit Y.ringSheaf) ⟶ SheafOfModules.unit X.ringSheaf :=
  SheafOfModules.pullbackObjUnitToUnit.{u} f.toRingSheafHom

variable {Y} in
/-- **The pullback of `𝒪_Y` is `𝒪_X`**: the canonical map above is an isomorphism.

Mathlib proves this for a *final* functor between the sites
(`Mathlib/Algebra/Category/ModuleCat/Sheaf/PullbackFree.lean`), and here that functor is
`TopologicalSpace.Opens.map f.base`, which is final because `Opens` is filtered —
`TopologicalSpace.Opens.final_map`.

**The `inferInstanceAs` is load-bearing and the universe annotation on it is too.**
`Hom.pullbackModulesUnitToUnit` is a plain `def`, so instance search does not unfold it; and
`SheafOfModules.pullbackObjUnitToUnit` written without `.{u}` elaborates with a universe
metavariable, at which the instance does not fire either. Both were measured, and the second is
the one that looks like a missing instance and is not. -/
instance isIso_pullbackModulesUnitToUnit {X : LocallyRingedSpace.{u}} (f : X ⟶ Y) :
    IsIso (Hom.pullbackModulesUnitToUnit.{u} f) :=
  inferInstanceAs (IsIso (SheafOfModules.pullbackObjUnitToUnit.{u} f.toRingSheafHom))

variable {Y} in
/-- **The pullback of the structure sheaf is the structure sheaf**, as an isomorphism. -/
noncomputable def Hom.pullbackModulesUnitIso {X : LocallyRingedSpace.{u}} (f : X ⟶ Y) :
    f.pullbackModules.obj (SheafOfModules.unit Y.ringSheaf) ≅ SheafOfModules.unit X.ringSheaf :=
  asIso (Hom.pullbackModulesUnitToUnit.{u} f)

variable {Y} in
/-- **The pullback of a free sheaf of modules is free**, on the same index type — which need not
be finite. Mathlib's `SheafOfModules.pullbackObjFreeIso` at `Hom.toRingSheafHom`. -/
noncomputable def Hom.pullbackModulesFreeIso {X : LocallyRingedSpace.{u}} (f : X ⟶ Y)
    (I : Type u) :
    f.pullbackModules.obj (SheafOfModules.free I) ≅ SheafOfModules.free I :=
  SheafOfModules.pullbackObjFreeIso.{u} f.toRingSheafHom I

variable {Y} in
/-- **Pullback of `𝒪`-modules commutes with the free-sheaf functor**, naturally. -/
noncomputable def Hom.freeFunctorCompPullbackModulesIso {X : LocallyRingedSpace.{u}}
    (f : X ⟶ Y) :
    SheafOfModules.freeFunctor ⋙ f.pullbackModules ≅ SheafOfModules.freeFunctor :=
  SheafOfModules.freeFunctorCompPullbackIso.{u} f.toRingSheafHom

/-- A locally ringed space has **coherent structure sheaf** if `𝒪_Y` is coherent as a sheaf of
modules over itself. -/
def IsCoherentStructureSheaf : Prop :=
  (SheafOfModules.unit Y.ringSheaf).IsCoherent


/-- Restriction of a section of the structure sheaf to a smaller open subset. -/
abbrev res {U V : Opens Y} (h : U ≤ V) (s : Y.presheaf.obj (op V)) : Y.presheaf.obj (op U) :=
  Y.presheaf.map (homOfLE h).op s

@[simp]
lemma res_self {U : Opens Y} (s : Y.presheaf.obj (op U)) : Y.res le_rfl s = s := by
  rw [res, show (homOfLE (le_refl U)).op = 𝟙 (op U) from Subsingleton.elim _ _,
    show Y.presheaf.map (𝟙 (op U)) = 𝟙 _ from Y.presheaf.map_id _]
  rfl

@[simp]
lemma res_res {U V W : Opens Y} (h₁ : U ≤ V) (h₂ : V ≤ W) (s : Y.presheaf.obj (op W)) :
    Y.res h₁ (Y.res h₂ s) = Y.res (h₁.trans h₂) s := by
  rw [res, res, res, ← ConcreteCategory.comp_apply, ← Functor.map_comp]
  rfl

/-- The structure sheaf of `Y` has **locally finitely generated relations**: every finite
family `f₁, …, f_m` of sections of `𝒪_Y` over `V` admits, near every point of `V`, finitely
many relations `g₁, …, g_k` which generate all relations locally.

"Locally" is essential: a relation between the `fᵢ` over an open set `W'` is required only to
be a combination of the `gₗ` on a neighbourhood of each point of `W'`, not on all of `W'`. The
sectionwise variant would amount to a vanishing statement for `H¹` on arbitrary open sets and
is not available.

Unlike coherence stated via `SheafOfModules.IsCoherent`, this refers only to open subsets,
sections and restriction maps, so it is manifestly local and needs no transport of sites. -/
def HasLocalRelations : Prop :=
  ∀ (V : Opens Y) (m : ℕ) (f : Fin m → Y.presheaf.obj (op V)) (x : Y), x ∈ V →
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → (Fin m → Y.presheaf.obj (op W))),
      x ∈ W ∧ (∀ l, ∑ i, g l i * Y.res hWV (f i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin m → Y.presheaf.obj (op W')),
        (∑ i, a i * Y.res (hW'.trans hWV) (f i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i)

lemma res_sum {U V : Opens Y} (h : U ≤ V) {κ : Type*} (t : Finset κ)
    (u : κ → Y.presheaf.obj (op V)) : Y.res h (∑ i ∈ t, u i) = ∑ i ∈ t, Y.res h (u i) :=
  map_sum (Y.presheaf.map (homOfLE h).op).hom u t

lemma res_mul {U V : Opens Y} (h : U ≤ V) (s t : Y.presheaf.obj (op V)) :
    Y.res h (s * t) = Y.res h s * Y.res h t :=
  map_mul (Y.presheaf.map (homOfLE h).op).hom s t

lemma res_zero {U V : Opens Y} (h : U ≤ V) : Y.res h (0 : Y.presheaf.obj (op V)) = 0 :=
  map_zero (Y.presheaf.map (homOfLE h).op).hom


/-- The structure sheaf of `Y` has locally finitely generated relations **over the open set
`U`**: the condition of `HasLocalRelations` for families of sections defined on open subsets
of `U`. -/
def HasLocalRelationsOn (U : Opens Y) : Prop :=
  ∀ (V : Opens Y), V ≤ U → ∀ (m : ℕ) (f : Fin m → Y.presheaf.obj (op V)) (x : Y), x ∈ V →
    ∃ (W : Opens Y) (hWV : W ≤ V) (k : ℕ) (g : Fin k → (Fin m → Y.presheaf.obj (op W))),
      x ∈ W ∧ (∀ l, ∑ i, g l i * Y.res hWV (f i) = 0) ∧
      ∀ (W' : Opens Y) (hW' : W' ≤ W) (a : Fin m → Y.presheaf.obj (op W')),
        (∑ i, a i * Y.res (hW'.trans hWV) (f i) = 0) → ∀ y ∈ W',
          ∃ (W'' : Opens Y) (hW'' : W'' ≤ W'), y ∈ W'' ∧
            ∃ c : Fin k → Y.presheaf.obj (op W''),
              ∀ i, Y.res hW'' (a i) = ∑ l, c l * Y.res (hW''.trans hW') (g l i)

variable {Y}

/-- `HasLocalRelations` is `HasLocalRelationsOn` for the whole space. -/
lemma HasLocalRelationsOn.hasLocalRelations (h : Y.HasLocalRelationsOn ⊤) :
    Y.HasLocalRelations :=
  fun V m f x hx ↦ h V le_top m f x hx

/-- Having locally finitely generated relations may be checked on an open cover. -/
theorem hasLocalRelations_of_openCover {A : Type*} (U : A → Opens Y)
    (hU : ∀ x : Y, ∃ a, x ∈ U a) (h : ∀ a, Y.HasLocalRelationsOn (U a)) :
    Y.HasLocalRelations := by
  intro V m f x hx
  obtain ⟨a, ha⟩ := hU x
  obtain ⟨W, hWV, k, g, hxW, hrel, hgen⟩ :=
    h a (V ⊓ U a) inf_le_right m (fun i ↦ Y.res inf_le_left (f i)) x ⟨hx, ha⟩
  refine ⟨W, hWV.trans inf_le_left, k, g, hxW, ?_, ?_⟩
  · simpa only [res_res] using hrel
  · intro W' hW' aa haa y hy
    exact hgen W' hW' aa (by simpa only [res_res] using haa) y hy

variable (Y)

variable {Y}

set_option maxHeartbeats 1000000 in
-- the proof repeatedly identifies sections of the (iterated) restrictions of the sheaves of
-- modules involved with sections of the structure sheaf, which is definitionally expensive
/-- A locally ringed space whose structure sheaf has locally finitely generated relations has
coherent structure sheaf. -/
theorem isCoherentStructureSheaf_of_hasLocalRelations (h : Y.HasLocalRelations) :
    Y.IsCoherentStructureSheaf := by
  classical
  haveI : (unit Y.ringSheaf).IsFiniteType := by apply SheafOfModules.isFiniteType_unit
  refine isCoherent_of_forall_kernel_of_locally (M := unit Y.ringSheaf) ?_
  intro X I hI φ
  haveI := hI
  haveI : Fintype I := Fintype.ofFinite I
  obtain ⟨m, ⟨e⟩⟩ := Finite.exists_equiv_fin I
  set f : Fin m → Y.presheaf.obj (op X) := fun i ↦
    PresheafOfModules.sections.eval (freeHomEquiv _ φ (e.symm i)) (op (Over.mk (𝟙 X))) with hf
  choose V hVX k g hxV hrel hgen using fun (x : X) ↦ h X m f x.1 x.2
  refine ⟨↥X, fun a ↦ Over.mk (homOfLE (hVX a)),
    coversTop_over X V hVX (fun x hx ↦ ⟨⟨x, hx⟩, hxV ⟨x, hx⟩⟩), fun a ↦ ?_⟩
  set Ya : Over X := Over.mk (homOfLE (hVX a))
  set L := ULift.{u} (Fin (k a))
  have hWV : ∀ W : (Over Ya)ᵒᵖ, W.unop.left.left ≤ V a := fun W ↦ leOfHom W.unop.hom.left
  have hWX : ∀ W : (Over Ya)ᵒᵖ, W.unop.left.left ≤ X := fun W ↦ (hWV W).trans (hVX a)
  set ψ : free L ⟶ (free I).over Ya :=
    (freeHomEquiv _).symm (fun l ↦ sectionOfTerminal Over.mkIdTerminal ((free I).over Ya)
      (freeEvalSymm (R := Y.ringSheaf.over X) (I := I) (op (Over.mk (𝟙 Ya)).left)
        (fun i ↦ g a l.down (e i)))) with hψ
  have key_φ : ∀ (W : (Over Ya)ᵒᵖ) (b : ((free I).over Ya).val.obj W)
      (bc : I → Y.presheaf.obj (op W.unop.left.left))
      (_ : ∀ i, bc i = freeEval (op W.unop.left) b i)
      (v : Y.presheaf.obj (op W.unop.left.left)) (_ : v = (φ.over Ya).val.app W b),
      v = ∑ i : I, bc i * Y.res (hWX W) (f (e i)) := by
    intro W b bc hbc v hv
    have hsec : ∀ i : I, (PresheafOfModules.sections.eval (freeHomEquiv _ φ i)
        (op W.unop.left) : Y.presheaf.obj (op W.unop.left.left)) =
        Y.res (hWX W) (f (e i)) := by
      intro i
      simp only [hf, Equiv.symm_apply_apply]
      exact (PresheafOfModules.sections_property (freeHomEquiv _ φ i)
        (Over.mkIdTerminal.from W.unop.left).op).symm
    rw [hv, show (φ.over Ya).val.app W b = φ.val.app (op W.unop.left) b from rfl,
      val_app_eq_sum]
    refine Finset.sum_congr rfl (fun i _ ↦ ?_)
    rw [hbc i, ← hsec i]
    rfl
  have key_ψ : ∀ (W : (Over Ya)ᵒᵖ) (c : (free L).val.obj W)
      (cc : L → Y.presheaf.obj (op W.unop.left.left)) (_ : ∀ l, cc l = freeEval W c l) (i : I)
      (v : Y.presheaf.obj (op W.unop.left.left))
      (_ : v = freeEval (op W.unop.left) (ψ.val.app W c) i),
      v = ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i)) := by
    intro W c cc hcc i v hv
    obtain ⟨cc', hcc'⟩ : ∃ cc' : L → (Y.ringSheaf.over X).obj.obj (op W.unop.left),
        ∀ l, cc' l = cc l := ⟨fun l ↦ cc l, fun _ ↦ rfl⟩
    obtain ⟨vv, hvv⟩ : ∃ vv : L → I → (Y.ringSheaf.over X).obj.obj (op W.unop.left),
        ∀ l i, vv l i = Y.res (hWV W) (g a l.down (e i)) :=
      ⟨fun l i ↦ Y.res (hWV W) (g a l.down (e i)), fun _ _ ↦ rfl⟩
    have hsec : ∀ l : L, PresheafOfModules.sections.eval (freeHomEquiv _ ψ l) W =
        freeEvalSymm (op W.unop.left) (vv l) := by
      intro l
      rw [hψ, Equiv.apply_symm_apply, sectionOfTerminal_val,
        show vv l = fun i ↦ Y.res (hWV W) (g a l.down (e i)) from funext (hvv l)]
      exact map_freeEvalSymm (R := Y.ringSheaf.over X) (I := I)
        ((Over.mkIdTerminal.from W.unop).left).op (fun i ↦ g a l.down (e i))
    have h1 : ψ.val.app W c = freeEvalSymm (op W.unop.left)
        (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) := by
      have hrhs : freeEvalSymm (R := Y.ringSheaf.over X) (I := I) (op W.unop.left)
          (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) =
          ∑ l : L, cc' l • freeEvalSymm (op W.unop.left) (vv l) := by
        have hpi : (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) =
            ∑ l : L, cc' l • vv l := by
          funext i
          rw [Finset.sum_apply]
          refine Finset.sum_congr rfl (fun l _ ↦ ?_)
          rw [Pi.smul_apply, hcc', hvv]
          rfl
        refine (congrArg (freeEvalSymm (R := Y.ringSheaf.over X) (I := I)
          (op W.unop.left)) hpi).trans ((map_sum _ _ _).trans ?_)
        exact Finset.sum_congr rfl (fun l _ ↦ map_smul _ _ _)
      rw [val_app_eq_sum, hrhs]
      simp only [hsec, hcc', hcc]
      rfl
    rw [hv, h1]
    exact congrFun (freeEval_freeEvalSymm _ _) i
  have hgker : ∀ (W' : Opens Y) (hh : W' ≤ V a) (l : Fin (k a)),
      ∑ j : Fin m, Y.res hh (g a l j) * Y.res (hh.trans (hVX a)) (f j) = 0 := by
    intro W' hh l
    have h0 := congrArg (Y.res hh) (hrel a l)
    simp only [res_sum, res_mul, res_res, res_zero] at h0
    exact h0
  refine ⟨L, inferInstance, ψ, ?_, ?_⟩
  · ext W c
    obtain ⟨cc, hcc⟩ : ∃ cc : L → Y.presheaf.obj (op W.unop.left.left),
        ∀ l, cc l = freeEval W c l := ⟨fun l ↦ freeEval W c l, fun _ ↦ rfl⟩
    obtain ⟨v, hv⟩ : ∃ v : Y.presheaf.obj (op W.unop.left.left),
        v = (φ.over Ya).val.app W (ψ.val.app W c) := ⟨_, rfl⟩
    have h0 : v = 0 := by
      rw [key_φ W (ψ.val.app W c)
        (fun i ↦ ∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i)))
        (fun i ↦ (key_ψ W c cc hcc i _ rfl).symm) v hv]
      have hterm : ∀ i : I, (∑ l : L, cc l * Y.res (hWV W) (g a l.down (e i))) *
            Y.res (hWX W) (f (e i)) =
          ∑ l : L, cc l * (Y.res (hWV W) (g a l.down (e i)) * Y.res (hWX W) (f (e i))) := by
        intro i
        rw [Finset.sum_mul]
        exact Finset.sum_congr rfl (fun l _ ↦ mul_assoc _ _ _)
      simp only [hterm]
      rw [Finset.sum_comm]
      refine Finset.sum_eq_zero (fun l _ ↦ ?_)
      rw [← Finset.mul_sum, Equiv.sum_comp e (fun j : Fin m ↦
        Y.res (hWV W) (g a l.down j) * Y.res (hWX W) (f j)),
        hgker _ (hWV W) l.down, mul_zero]
    exact hv.symm.trans h0
  · intro Z b hb
    obtain ⟨bc, hbc⟩ : ∃ bc : I → Y.presheaf.obj (op Z.left.left),
        ∀ i, bc i = freeEval (op Z.left) b i :=
      ⟨fun i ↦ freeEval (op Z.left) b i, fun _ ↦ rfl⟩
    have hrelb : ∑ j : Fin m, bc (e.symm j) * Y.res (hWX (op Z)) (f j) = 0 := by
      rw [← Equiv.sum_comp e (fun j : Fin m ↦ bc (e.symm j) * Y.res (hWX (op Z)) (f j))]
      obtain ⟨v, hv⟩ : ∃ v : Y.presheaf.obj (op Z.left.left),
          v = (φ.over Ya).val.app (op Z) b := ⟨_, rfl⟩
      have h0 : v = 0 := hv.trans hb
      rw [key_φ (op Z) b bc hbc v hv] at h0
      simpa only [Equiv.symm_apply_apply] using h0
    choose Wy hWyle hyWy cy hcy using fun (y : Z.left.left) ↦
      hgen a Z.left.left (hWV (op Z)) (fun j ↦ bc (e.symm j)) hrelb y.1 y.2
    set S₀ : Sieve (Z.left.left : Opens Y) :=
      ⟨fun Wo _ ↦ ∃ y : Z.left.left, Wo ≤ Wy y, by
        rintro W₁ W₂ f₁ ⟨y, hy⟩ gg; exact ⟨y, (leOfHom gg).trans hy⟩⟩ with hS₀def
    have hS₀mem : S₀ ∈ Opens.grothendieckTopology Y Z.left.left := by
      intro x hx
      exact ⟨Wy ⟨x, hx⟩, homOfLE (hWyle ⟨x, hx⟩), ⟨⟨x, hx⟩, le_rfl⟩, hyWy ⟨x, hx⟩⟩
    refine ⟨(Sieve.overEquiv Z).symm ((Sieve.overEquiv Z.left).symm S₀), ?_, ?_⟩
    · rw [GrothendieckTopology.mem_over_iff, OrderIso.apply_symm_apply,
        GrothendieckTopology.mem_over_iff, OrderIso.apply_symm_apply]
      exact hS₀mem
    · intro Z' ff hff
      rw [Sieve.overEquiv_symm_iff, Sieve.overEquiv_symm_iff] at hff
      obtain ⟨y, hy⟩ := hff
      have hle : Z'.left.left ≤ Wy y := hy
      refine ⟨freeEvalSymm (op Z') (fun l : L ↦ Y.res hle (cy y l.down)), ?_⟩
      refine freeEval_injective (op Z'.left) (funext fun i ↦ ?_)
      have h1 := key_ψ (op Z')
        (freeEvalSymm (op Z') (fun l : L ↦ Y.res hle (cy y l.down)))
        (fun l ↦ Y.res hle (cy y l.down))
        (fun l ↦ (congrFun (freeEval_freeEvalSymm (R := (Y.ringSheaf.over X).over Ya) (I := L)
          (op Z') (fun l : L ↦ Y.res hle (cy y l.down))) l).symm) i _ rfl
      have hsum : (∑ l : L, Y.res hle (cy y l.down) *
          Y.res (hWV (op Z')) (g a l.down (e i))) =
          ∑ l : Fin (k a), Y.res hle (cy y l) * Y.res (hWV (op Z')) (g a l (e i)) :=
        Fintype.sum_equiv Equiv.ulift _ _ (fun _ ↦ rfl)
      have h3 : freeEval (op Z'.left) (((free I).over Ya).val.map ff.op b) i =
          Y.res (leOfHom ff.left.left) (bc i) := by
        rw [show (((free I).over Ya).val.map ff.op) b =
          (free I).val.map (ff.left).op b from rfl, freeEval_naturality, hbc i]
        rfl
      have h4 : (∑ l : Fin (k a), Y.res hle (cy y l) *
          Y.res (hWV (op Z')) (g a l (e i))) = Y.res (leOfHom ff.left.left) (bc i) := by
        have h5 := hcy y (e i)
        simp only [Equiv.symm_apply_apply] at h5
        have h6 := congrArg (Y.res hle) h5
        simp only [res_sum, res_mul, res_res] at h6
        exact h6.symm
      rw [h3, h1, hsum, h4]

section Restrict

variable {X : LocallyRingedSpace.{u}} (U : Opens X)

/-- An open subset of the open subspace `U`, viewed as an open subset of `X`. -/
abbrev imOpen (W : Opens (X.restrict U.isOpenEmbedding)) : Opens X :=
  U.isOpenEmbedding.isOpenMap.functor.obj W

/-- An open subset of `X`, viewed as an open subset of the open subspace `U`. -/
abbrev preOpen (V : Opens X) : Opens (X.restrict U.isOpenEmbedding) :=
  ⟨Subtype.val ⁻¹' (V : Set X), V.isOpen.preimage continuous_subtype_val⟩

@[simp]
lemma restrict_res {W W' : Opens (X.restrict U.isOpenEmbedding)} (h : W' ≤ W)
    (s : (X.restrict U.isOpenEmbedding).presheaf.obj (op W)) :
    (X.restrict U.isOpenEmbedding).res h s = X.res (Set.image_mono h) s :=
  rfl

lemma imOpen_le (W : Opens (X.restrict U.isOpenEmbedding)) : imOpen U W ≤ U := by
  rintro x ⟨y, _, rfl⟩; exact y.2

lemma imOpen_preOpen {V : Opens X} (hVU : V ≤ U) : imOpen U (preOpen U V) = V := by
  ext x
  exact ⟨by rintro ⟨y, hy, rfl⟩; exact hy, fun hx ↦ ⟨⟨x, hVU hx⟩, hx, rfl⟩⟩

lemma preOpen_le_of_le_imOpen {V : Opens X} {W : Opens (X.restrict U.isOpenEmbedding)}
    (h : V ≤ imOpen U W) : preOpen U V ≤ W := by
  intro z hz
  obtain ⟨w, hw, hwz⟩ := h hz
  exact (Subtype.val_injective hwz) ▸ hw

/-- Having locally finitely generated relations transfers from an open subspace of `X` to `X`
itself, over that open set. -/
theorem HasLocalRelations.hasLocalRelationsOn
    (h : (X.restrict U.isOpenEmbedding).HasLocalRelations) :
    X.HasLocalRelationsOn U := by
  intro V hVU m f x hx
  have hV : imOpen U (preOpen U V) = V := imOpen_preOpen U hVU
  obtain ⟨W', hW'V', k, g, hxW', hrel, hgen⟩ :=
    h (preOpen U V) m (fun i ↦ X.res hV.le (f i)) ⟨x, hVU hx⟩ hx
  refine ⟨imOpen U W', (Set.image_mono hW'V').trans hV.le, k, g,
    ⟨⟨x, hVU hx⟩, hxW', rfl⟩, fun l ↦ ?_, fun W2 hW2le a ha y hy ↦ ?_⟩
  · have h1 := hrel l
    simp only [restrict_res, res_res] at h1
    exact h1
  · have hW2 : imOpen U (preOpen U W2) = W2 :=
      imOpen_preOpen U (hW2le.trans (imOpen_le U W'))
    have hpre : preOpen U W2 ≤ W' := preOpen_le_of_le_imOpen U hW2le
    have hyU : y ∈ U := (hW2le.trans (imOpen_le U W')) hy
    have hrel2 : ∑ i, X.res hW2.le (a i) *
        X.res (Set.image_mono (hpre.trans hW'V')) (X.res hV.le (f i)) = 0 := by
      have h2 := congrArg (X.res hW2.le) ha
      simp only [res_sum, res_mul, res_res, res_zero] at h2
      simpa only [res_res] using h2
    obtain ⟨W3, hW3, hyW3, c, hc⟩ :=
      hgen (preOpen U W2) hpre (fun i ↦ X.res hW2.le (a i)) hrel2 ⟨y, hyU⟩ hy
    refine ⟨imOpen U W3, (Set.image_mono hW3).trans hW2.le, ⟨⟨y, hyU⟩, hyW3, rfl⟩,
      c, fun i ↦ ?_⟩
    have h3 := hc i
    simp only [restrict_res, res_res] at h3
    exact h3

lemma preOpen_imOpen (V : Opens (X.restrict U.isOpenEmbedding)) : preOpen U (imOpen U V) = V := by
  ext z
  exact ⟨by rintro ⟨w, hw, hwz⟩; exact (Subtype.val_injective hwz) ▸ hw,
    fun hz ↦ ⟨z, hz, rfl⟩⟩

/-- Having locally finitely generated relations passes to open subspaces. -/
theorem HasLocalRelations.restrict (h : X.HasLocalRelations) :
    (X.restrict U.isOpenEmbedding).HasLocalRelations := by
  intro V m f x hx
  obtain ⟨W, hWV, k, g, hxW, hrel, hgen⟩ := h (imOpen U V) m f x.1 ⟨x, hx, rfl⟩
  have hWU : W ≤ U := hWV.trans (imOpen_le U V)
  have hW : imOpen U (preOpen U W) = W := imOpen_preOpen U hWU
  refine ⟨preOpen U W, preOpen_le_of_le_imOpen U hWV, k, fun l i ↦ X.res hW.le (g l i),
    hxW, fun l ↦ ?_, fun W2 hW2 a ha y hy ↦ ?_⟩
  · have h1 := congrArg (X.res hW.le) (hrel l)
    simp only [res_sum, res_mul, res_res, res_zero] at h1
    simp only [restrict_res]
    exact h1
  · have him : imOpen U W2 ≤ W := (Set.image_mono hW2).trans hW.le
    obtain ⟨a', ha'⟩ : ∃ a' : Fin m → X.presheaf.obj (op (imOpen U W2)), ∀ i, a' i = a i :=
      ⟨fun i ↦ a i, fun _ ↦ rfl⟩
    have ha2 : ∑ i, a' i * X.res (him.trans hWV) (f i) = 0 := by
      simp only [ha']
      simp only [restrict_res] at ha
      exact ha
    obtain ⟨W3, hW3, hyW3, c, hc⟩ := hgen (imOpen U W2) him a' ha2 y.1 ⟨y, hy, rfl⟩
    have hW3U : W3 ≤ U := hW3.trans (imOpen_le U W2)
    have hW3e : imOpen U (preOpen U W3) = W3 := imOpen_preOpen U hW3U
    refine ⟨preOpen U W3, preOpen_le_of_le_imOpen U hW3, hyW3,
      fun l ↦ X.res hW3e.le (c l), fun i ↦ ?_⟩
    have h3 := congrArg (X.res hW3e.le) (hc i)
    simp only [res_sum, res_mul, res_res, ha'] at h3
    simp only [restrict_res, res_res]
    exact h3

end Restrict

section LocalModel

lemma germ_res {U V : Opens Y} (h : U ≤ V) (y : Y) (hy : y ∈ U) (s : Y.presheaf.obj (op V)) :
    Y.presheaf.germ U y hy (Y.res h s) = Y.presheaf.germ V y (h hy) s :=
  TopCat.Presheaf.germ_res_apply _ (homOfLE h) y hy s

/-- If the germ at `y` of a section `t` lies in the ideal generated by the germs of global
sections `f₁, …, f_k`, then on a neighbourhood of `y` the section `t` is an `𝒪_Y`-combination
of the `fⱼ`. -/
lemma exists_localCombination {A : Opens Y} (t : Y.presheaf.obj (op A)) {k : ℕ}
    (f : Fin k → Y.presheaf.obj (op ⊤)) (y : Y) (hy : y ∈ A)
    (h : Y.presheaf.germ A y hy t ∈
      Ideal.span (Set.range fun j ↦ Y.presheaf.Γgerm y (f j))) :
    ∃ (A' : Opens Y) (hA' : A' ≤ A), y ∈ A' ∧ ∃ c : Fin k → Y.presheaf.obj (op A'),
      Y.res hA' t = ∑ j, c j * Y.res le_top (f j) := by
  classical
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).1 h
  choose A₀ hA₀ c₀ hc₀ using fun j ↦ Y.presheaf.exists_germ_eq (c j)
  set A' : Opens Y := ⟨(A : Set Y) ∩ ⋂ j, {z : Y | z ∈ A₀ j},
    A.isOpen.inter (isOpen_iInter_of_finite fun j ↦ (A₀ j).isOpen)⟩ with hA'def
  have hyA' : y ∈ A' := ⟨hy, Set.mem_iInter.2 hA₀⟩
  have hA'A : A' ≤ A := fun z hz ↦ hz.1
  have hA'j : ∀ j, A' ≤ (A₀ j : Opens Y) := fun j z hz ↦ Set.mem_iInter.1 hz.2 j
  have key : Y.presheaf.germ A' y hyA' (Y.res hA'A t) =
      Y.presheaf.germ A' y hyA' (∑ j, Y.res (hA'j j) (c₀ j) * Y.res le_top (f j)) := by
    rw [germ_res, map_sum]
    have hterm : ∀ j, Y.presheaf.germ A' y hyA'
        (Y.res (hA'j j) (c₀ j) * Y.res le_top (f j)) = c j * Y.presheaf.Γgerm y (f j) := by
      intro j
      rw [map_mul, germ_res, germ_res, hc₀ j]
      rfl
    simp only [hterm, ← hc, smul_eq_mul]
  obtain ⟨W, hyW, iU, iV, hW⟩ := Y.presheaf.germ_eq y hyA' hyA' _ _ key
  refine ⟨W, (leOfHom iU).trans hA'A, hyW,
    fun j ↦ Y.res (leOfHom iV) (Y.res (hA'j j) (c₀ j)), ?_⟩
  have h1 : Y.res (leOfHom iU) (Y.res hA'A t) =
      Y.res (leOfHom iV) (∑ j, Y.res (hA'j j) (c₀ j) * Y.res le_top (f j)) := hW
  rw [res_res] at h1
  rw [h1, res_sum]
  exact Finset.sum_congr rfl fun j _ ↦ by simp only [res_mul, res_res]


variable {M Y : LocallyRingedSpace.{u}} (i : M ⟶ Y)

/-- If `i : M ⟶ Y` is surjective on stalks, then every section of `𝒪_M` is, near each point of
its domain, the pullback along `i` of a section of `𝒪_Y`. -/
lemma exists_localLift (hsurj : ∀ x, Function.Surjective (i.stalkMap x).hom)
    {B : Opens M} (t : M.presheaf.obj (op B)) (x : M) (hx : x ∈ B) :
    ∃ (A : Opens Y) (_ : i.base x ∈ A) (u : Y.presheaf.obj (op A)) (B' : Opens M)
      (hB'B : B' ≤ B) (hB'A : B' ≤ (Opens.map i.base).obj A),
      x ∈ B' ∧ M.res hB'A (i.c.app (op A) u) = M.res hB'B t := by
  obtain ⟨v, hv⟩ := hsurj x (M.presheaf.germ B x hx t)
  obtain ⟨A, hA, u, hu⟩ := Y.presheaf.exists_germ_eq v
  have hgerm : M.presheaf.germ ((Opens.map i.base).obj A) x hA (i.c.app (op A) u) =
      M.presheaf.germ B x hx t := by
    rw [← LocallyRingedSpace.stalkMap_germ_apply i A x hA u, hu]
    exact hv
  obtain ⟨W, hxW, iU, iV, hW⟩ :=
    M.presheaf.germ_eq x hA hx (i.c.app (op A) u) t hgerm
  exact ⟨A, hA, u, W, leOfHom iV, leOfHom iU, hxW, hW⟩

/-- Pulling back along `i` commutes with restriction. -/
lemma c_app_res {A A' : Opens Y} (h : A' ≤ A) (u : Y.presheaf.obj (op A)) :
    i.c.app (op A') (Y.res h u) =
      M.res (show (Opens.map i.base).obj A' ≤ (Opens.map i.base).obj A from fun _ hz ↦ h hz)
        (i.c.app (op A) u) := by
  have h1 := ConcreteCategory.congr_hom (i.c.naturality (homOfLE h).op) u
  simp only [ConcreteCategory.comp_apply] at h1
  exact h1

/-- Simultaneous local lifting of finitely many sections along a morphism which is surjective
on stalks. -/
lemma exists_localLift_family (hsurj : ∀ x, Function.Surjective (i.stalkMap x).hom)
    {B₀ : Opens M} {m : ℕ} (s : Fin m → M.presheaf.obj (op B₀)) (x : M) (hx : x ∈ B₀) :
    ∃ (A : Opens Y) (_ : i.base x ∈ A) (t : Fin m → Y.presheaf.obj (op A))
      (B : Opens M) (hBB₀ : B ≤ B₀) (hBA : B ≤ (Opens.map i.base).obj A),
      x ∈ B ∧ ∀ j, M.res hBA (i.c.app (op A) (t j)) = M.res hBB₀ (s j) := by
  classical
  choose A hA u B hBB₀ hBA hxB hres using fun j ↦ exists_localLift i hsurj (s j) x hx
  set A' : Opens Y := ⟨⋂ j, {z : Y | z ∈ A j}, isOpen_iInter_of_finite fun j ↦ (A j).isOpen⟩
    with hA'def
  set B' : Opens M := ⟨(B₀ : Set M) ∩ ⋂ j, {z : M | z ∈ B j},
    B₀.isOpen.inter (isOpen_iInter_of_finite fun j ↦ (B j).isOpen)⟩ with hB'def
  have hA'j : ∀ j, A' ≤ A j := fun j z hz ↦ Set.mem_iInter.1 hz j
  have hB'j : ∀ j, B' ≤ B j := fun j z hz ↦ Set.mem_iInter.1 hz.2 j
  refine ⟨A', Set.mem_iInter.2 hA, fun j ↦ Y.res (hA'j j) (u j), B', fun z hz ↦ hz.1,
    fun z hz ↦ Set.mem_iInter.2 fun j ↦ hBA j (Set.mem_iInter.1 hz.2 j),
    ⟨hx, Set.mem_iInter.2 hxB⟩, fun j ↦ ?_⟩
  rw [c_app_res]
  have h1 := congrArg (M.res (hB'j j)) (hres j)
  simp only [res_res] at h1 ⊢
  exact h1

end LocalModel

end AlgebraicGeometry.LocallyRingedSpace

open AlgebraicGeometry

/-- The structure sheaf of `ℂ^ι` as a locally ringed space is the sheaf of rings `okaSheaf ι`. -/
lemma complexSpace_ringSheaf (ι : Type u) [Fintype ι] :
    (complexSpace ι).ringSheaf = okaSheaf ι :=
  rfl

/-- **Oka's coherence lemma** gives that the structure sheaf of `ℂ^ι` has locally finitely
generated relations. -/
theorem hasLocalRelations_complexSpace (ι : Type u) [Fintype ι] :
    (complexSpace ι).HasLocalRelations := by
  intro V m f x hx
  obtain ⟨W, hWV, k, g, hxW, hrel, hgen⟩ := oka (U := V) f x hx
  exact ⟨W, hWV, k, g, hxW, hrel, hgen⟩

/-- **Oka's coherence theorem**, for `ℂ^ι` as a locally ringed space. -/
theorem isCoherentStructureSheaf_complexSpace (ι : Type u) [Fintype ι] :
    (complexSpace ι).IsCoherentStructureSheaf :=
  LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations
    (hasLocalRelations_complexSpace ι)

/-- **Oka's coherence theorem**: the structure sheaf of `ℂ^ι` is a coherent sheaf of modules
over itself. -/
theorem isCoherent_unit_okaSheaf (ι : Type u) [Fintype ι] :
    (SheafOfModules.unit (okaSheaf ι)).IsCoherent :=
  isCoherentStructureSheaf_complexSpace ι

/-- The structure sheaf of `ℂ^n` is a coherent sheaf of modules over itself. -/
theorem isCoherent_unit_okaSheaf_fin (n : ℕ) :
    (SheafOfModules.unit (okaSheaf (Fin n))).IsCoherent :=
  isCoherent_unit_okaSheaf _

/-- Complex affine `n`-space has coherent structure sheaf. -/
theorem isCoherentStructureSheaf_complexAffineSpace (n : ℕ) :
    (complexAffineSpace.{u} n).IsCoherentStructureSheaf :=
  isCoherentStructureSheaf_complexSpace _
