/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.ComplexSpace
import Oka.Statement
import Oka.Geometry.RingedSpace.LocallyRingedSpace.Coherent

/-!
# `ℂ^ι` has locally finitely generated relations, hence a coherent structure sheaf

**Oka's coherence lemma is exactly the hypothesis of a general theorem**, and this file is the
three lines that say so. `oka` (`Oka/Statement.lean`) says that near every point the relations
between finitely many holomorphic functions are generated by finitely many of them;
`AlgebraicGeometry.LocallyRingedSpace.HasLocalRelations`
(`Oka/Geometry/RingedSpace/LocallyRingedSpace/Coherent.lean`) is that condition for an arbitrary
locally ringed space, and
`AlgebraicGeometry.LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations` deduces
coherence from it over any such space.

So the content here is the identification of the two statements, and everything general it used
to sit beside is now in the mirror tree — see the *Provenance* note below, and `README.md` on
what the mirror tree is for.

## Main results

- `hasLocalRelations_complexSpace`: **`oka` says exactly that `ℂ^ι` has locally finitely
  generated relations.** The proof is the destructuring of one existential against another.
- `isCoherentStructureSheaf_complexSpace`, and its restatements
  `isCoherent_unit_okaSheaf`, `isCoherent_unit_okaSheaf_fin` and
  `isCoherentStructureSheaf_complexAffineSpace`: **the structure sheaf of `ℂ^ι` is coherent**,
  at the four spellings of the sheaf that consumers hold.
- `complexSpace_ringSheaf`: the structure sheaf of `ℂ^ι` as a locally ringed space is `okaSheaf`,
  by `rfl`. It is what lets the general statement be read as a statement about `okaSheaf`.

## Provenance

Until taxis #905 this file was 660 lines, of which 575 were general locally-ringed-space theory
declared into `AlgebraicGeometry.LocallyRingedSpace` — the definition of `HasLocalRelations`, the
coherence theorem, the module theory over `𝒪`, and the section and germ API all three run on.
That material mentions nothing analytic, and while it was here every general consumer of it had
to import `Oka.ComplexSpace` to reach it: `Oka/AlgebraicGeometry/Modules/Coherent.lean`, the
scheme-side theorem, was kept out of the mirror tree for exactly that reason. It is now in
`Oka/Geometry/RingedSpace/LocallyRingedSpace.lean`,
`Oka/Geometry/RingedSpace/LocallyRingedSpace/Modules.lean` and
`Oka/Geometry/RingedSpace/LocallyRingedSpace/Coherent.lean`, unchanged.
-/

open CategoryTheory Limits TopologicalSpace Opposite SheafOfModules AlgebraicGeometry

universe u

/-- The structure sheaf of `ℂ^ι` as a locally ringed space is the sheaf of rings `okaSheaf ι`. -/
lemma complexSpace_ringSheaf (ι : Type u) [Fintype ι] :
    (complexSpace ι).ringSheaf = okaSheaf ι :=
  rfl

/-- **Oka's coherence lemma** gives that the structure sheaf of `ℂ^ι` has locally finitely
generated relations. -/
theorem hasLocalRelations_complexSpace (ι : Type u) [Fintype ι] :
    (complexSpace ι).HasLocalRelations := by
  intro V m f x hx
  obtain ⟨W, hWV, k, g, hxW, hrel, hgen⟩ := oka (U := V) f x hx
  exact ⟨W, hWV, k, g, hxW, hrel, hgen⟩

/-- **Oka's coherence theorem**, for `ℂ^ι` as a locally ringed space. -/
theorem isCoherentStructureSheaf_complexSpace (ι : Type u) [Fintype ι] :
    (complexSpace ι).IsCoherentStructureSheaf :=
  LocallyRingedSpace.isCoherentStructureSheaf_of_hasLocalRelations
    (hasLocalRelations_complexSpace ι)

/-- **Oka's coherence theorem**: the structure sheaf of `ℂ^ι` is a coherent sheaf of modules
over itself. -/
theorem isCoherent_unit_okaSheaf (ι : Type u) [Fintype ι] :
    (SheafOfModules.unit (okaSheaf ι)).IsCoherent :=
  isCoherentStructureSheaf_complexSpace ι

/-- The structure sheaf of `ℂ^n` is a coherent sheaf of modules over itself. -/
theorem isCoherent_unit_okaSheaf_fin (n : ℕ) :
    (SheafOfModules.unit (okaSheaf (Fin n))).IsCoherent :=
  isCoherent_unit_okaSheaf _

/-- Complex affine `n`-space has coherent structure sheaf. -/
theorem isCoherentStructureSheaf_complexAffineSpace (n : ℕ) :
    (complexAffineSpace.{u} n).IsCoherentStructureSheaf :=
  isCoherentStructureSheaf_complexSpace _
