/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.RingTheory.MvPolynomial.Ideal
import Oka.Algebra.MvPolynomial.Taylor

/-!
# The maximal ideal of a point of affine space

Material for `Mathlib/RingTheory/MvPolynomial/Ideal.lean`; see `README.md` on the mirror tree.

`MvPolynomial.idealOfVars σ R` is the ideal generated by the variables. Over a field it is the
kernel of evaluation at the origin, hence maximal — which is what lets one localise at it and
speak of the local ring of affine space at the origin. Mathlib describes the powers of this ideal
(`MvPolynomial.mem_pow_idealOfVars_iff'`) but says nothing about the ideal being prime or maximal.

The same holds at any point `z`, where the ideal is the kernel of evaluation at `z`, and
**shifting the variables by `z` carries one to the other**: `MvPolynomial.taylorEquiv z` is an
automorphism of `MvPolynomial σ K` taking the polynomials vanishing at `z` to the polynomials
vanishing at the origin. That is what reduces a statement about the local ring at `z` to the
corresponding statement at the origin.

## Main results

- `MvPolynomial.idealOfVars_eq_ker_eval_zero`: it is the kernel of evaluation at the origin.
- `MvPolynomial.idealOfVars.isMaximal`: hence, over a field, it is maximal.
- `MvPolynomial.ker_eval.isMaximal`: the same at any point.
- `MvPolynomial.comap_taylorAlgHom_idealOfVars` and
  `MvPolynomial.map_taylorEquiv_primeCompl`: shifting the variables by `z` identifies the maximal
  ideal at `z` with the one at the origin, and their complements. The second is the form
  `IsLocalization.algEquivOfAlgEquiv` consumes.
-/

namespace MvPolynomial

variable {σ K : Type*} [Field K]

/-- The ideal generated by the variables is the kernel of evaluation at the origin. -/
theorem idealOfVars_eq_ker_eval_zero :
    idealOfVars σ K = RingHom.ker (eval (fun _ : σ ↦ (0 : K))) := by
  ext f
  rw [RingHom.mem_ker, ← pow_one (idealOfVars σ K), mem_pow_idealOfVars_iff']
  constructor
  · intro hf
    simpa [constantCoeff_eq] using hf 0 (by simp)
  · intro hf d hd
    have hd0 : d = 0 := by rw [← Finsupp.degree_eq_zero_iff]; omega
    subst hd0
    simpa [constantCoeff_eq] using hf

/-- **The ideal generated by the variables is maximal**, over a field: the quotient is the field
of values at the origin. -/
instance idealOfVars.isMaximal : (idealOfVars σ K).IsMaximal := by
  rw [idealOfVars_eq_ker_eval_zero]
  exact RingHom.ker_isMaximal_of_surjective _ fun c ↦ ⟨C c, by simp⟩

/-- **The polynomials vanishing at a point form a maximal ideal**, over a field: the quotient is
the field of values at that point. At the origin this is `MvPolynomial.idealOfVars.isMaximal`. -/
instance ker_eval.isMaximal (z : σ → K) : (RingHom.ker (eval z)).IsMaximal :=
  RingHom.ker_isMaximal_of_surjective _ fun c ↦ ⟨C c, by simp⟩

/-- **Shifting the variables by `z` turns vanishing at `z` into vanishing at the origin.** -/
theorem taylorAlgHom_mem_idealOfVars_iff (z : σ → K) (p : MvPolynomial σ K) :
    taylorAlgHom z p ∈ idealOfVars σ K ↔ p ∈ RingHom.ker (eval z) := by
  have hz : ((fun _ ↦ (0 : K)) + z) = z := by funext i; simp
  rw [idealOfVars_eq_ker_eval_zero, RingHom.mem_ker, RingHom.mem_ker, eval_taylorAlgHom, hz]

/-- `MvPolynomial.taylorAlgHom_mem_idealOfVars_iff` as an equality of ideals. -/
theorem comap_taylorAlgHom_idealOfVars (z : σ → K) :
    Ideal.comap (taylorAlgHom z) (idealOfVars σ K) = RingHom.ker (eval z) :=
  Ideal.ext (taylorAlgHom_mem_idealOfVars_iff z)

/-- Shifting the variables by `z` carries the polynomials **not** vanishing at `z` onto those not
vanishing at the origin. This is the hypothesis of `IsLocalization.algEquivOfAlgEquiv`, and hence
what identifies the local ring of affine space at `z` with the one at the origin. -/
theorem map_taylorEquiv_primeCompl (z : σ → K) :
    Submonoid.map (taylorEquiv z) (RingHom.ker (eval z)).primeCompl =
      (idealOfVars σ K).primeCompl := by
  ext q
  refine ⟨?_, fun hq ↦ ⟨(taylorEquiv z).symm q, ?_, (taylorEquiv z).apply_symm_apply q⟩⟩
  · rintro ⟨p, hp, rfl⟩
    exact fun hcon ↦ hp ((taylorAlgHom_mem_idealOfVars_iff z p).mp hcon)
  · intro hcon
    refine hq ?_
    have := (taylorAlgHom_mem_idealOfVars_iff z ((taylorEquiv z).symm q)).mpr hcon
    rwa [show taylorAlgHom z ((taylorEquiv z).symm q) = q from
      (taylorEquiv z).apply_symm_apply q] at this

end MvPolynomial
