/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The ideal of variables is the maximal ideal of the origin

Material for `Mathlib/RingTheory/MvPolynomial/Ideal.lean`; see `README.md` on the mirror tree.

`MvPolynomial.idealOfVars σ R` is the ideal generated by the variables. Over a field it is the
kernel of evaluation at the origin, hence maximal — which is what lets one localise at it and
speak of the local ring of affine space at the origin. Mathlib describes the powers of this ideal
(`MvPolynomial.mem_pow_idealOfVars_iff'`) but says nothing about the ideal being prime or maximal.

## Main results

- `MvPolynomial.idealOfVars_eq_ker_eval_zero`: it is the kernel of evaluation at the origin.
- `MvPolynomial.idealOfVars.isMaximal`: hence, over a field, it is maximal.
-/

namespace MvPolynomial

variable {σ K : Type*} [Field K]

/-- The ideal generated by the variables is the kernel of evaluation at the origin. -/
theorem idealOfVars_eq_ker_eval_zero :
    idealOfVars σ K = RingHom.ker (eval (fun _ : σ ↦ (0 : K))) := by
  ext f
  rw [RingHom.mem_ker, ← pow_one (idealOfVars σ K), mem_pow_idealOfVars_iff']
  constructor
  · intro hf
    simpa [constantCoeff_eq] using hf 0 (by simp)
  · intro hf d hd
    have hd0 : d = 0 := by rw [← Finsupp.degree_eq_zero_iff]; omega
    subst hd0
    simpa [constantCoeff_eq] using hf

/-- **The ideal generated by the variables is maximal**, over a field: the quotient is the field
of values at the origin. -/
instance idealOfVars.isMaximal : (idealOfVars σ K).IsMaximal := by
  rw [idealOfVars_eq_ker_eval_zero]
  exact RingHom.ker_isMaximal_of_surjective _ fun c ↦ ⟨C c, by simp⟩

end MvPolynomial
