/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Heights.LatticeEisenstein
import Oka.Uniformization.DeckGroup

/-!
# The deck group is generated by two edge pairings

Let `Λ = ℤ t + ℤ` (`t ∈ ℍ`) and let `ψ : ℍ → ℂ ∖ Λ` be a holomorphic universal covering with deck
group `Γ` (`Oka/Uniformization/DeckGroup.lean`). Write `z = x + y t` (`x = cx z`, `y = cy z`)
and let `K` be the closed fundamental parallelogram `[0, 1] + [0, 1] t` minus its four corners,
as the union of the convex pieces `K₁ = [0, 1] × (0, 1)` and `K₂ = (0, 1) × [0, 1]`. Lift `K`
through `ψ` (`sK`). The element `A ∈ Γ` pairs the lifted left edge with the lifted right edge
(`A • sK k = sK (k + 1)`), and `B ∈ Γ` pairs the bottom edge with the top edge
(`B • sK k = sK (k + t)`).

**Theorem** (`Generators.deckGroup_le`): `Γ ⊆ ⟨A, B, -1⟩`.

The translates `γ • sK K`, `γ ∈ Γ`, cover `ℍ`; two of them meet only if they differ by one of
`±1, ±A^{±1}, ±B^{±1}` (`mem_H_of_smul_eq`); and near every point of `sK K` the tiles are the
translates of `sK K` by `1, A^{±1}, B^{±1}` (`exists_nhds_tiles`). So the union of the tiles
`h • sK K` with `h ∈ ⟨A, B, -1⟩` and the union of the other tiles are disjoint open sets covering
the connected `ℍ`.
-/

open Complex Metric Set Filter Topology
open UpperHalfPlane hiding I I_re I_im
open scoped MatrixGroups Pointwise

namespace Uniformization

namespace Generators

variable (t : ℍ)

/-- The lattice `ℤ t + ℤ`. -/
noncomputable abbrev Lt : PeriodPair := Heights.periodPairOfUpperHalfPlane t

/-- The `t`-coordinate: `z = cx z + cy z * t`. -/
noncomputable def cy (z : ℂ) : ℝ := z.im / t.im

/-- The `1`-coordinate: `z = cx z + cy z * t`. -/
noncomputable def cx (z : ℂ) : ℝ := z.re - cy t z * t.re

theorem eq_cx_cy (z : ℂ) : z = cx t z + cy t z * (t : ℂ) := by
  have ht := t.im_pos.ne'
  apply Complex.ext
  · simp only [cx, cy, add_re, ofReal_re, mul_re, ofReal_im, zero_mul, sub_zero,
      UpperHalfPlane.coe_re]; ring
  · simp only [cx, cy, add_im, ofReal_im, mul_im, ofReal_re, zero_add, zero_mul, add_zero,
      UpperHalfPlane.coe_im]
    field_simp

theorem cy_add (z w : ℂ) : cy t (z + w) = cy t z + cy t w := by simp [cy, add_div]
theorem cx_add (z w : ℂ) : cx t (z + w) = cx t z + cx t w := by
  simp [cx, cy_add]; ring
theorem cy_smul (a : ℝ) (z : ℂ) : cy t (a • z) = a * cy t z := by
  simp [cy, mul_div_assoc]
theorem cx_smul (a : ℝ) (z : ℂ) : cx t (a • z) = a * cx t z := by
  unfold cx; rw [cy_smul]; simp; ring
theorem cy_one : cy t 1 = 0 := by simp [cy]
theorem cx_one : cx t 1 = 1 := by simp [cx, cy]
theorem cy_t : cy t t = 1 := by simp [cy, t.im_pos.ne']
theorem cx_t : cx t t = 0 := by simp [cx, cy, t.im_pos.ne']
theorem cy_neg (z : ℂ) : cy t (-z) = -cy t z := by simp [cy, neg_div]
theorem cx_neg (z : ℂ) : cx t (-z) = -cx t z := by simp [cx, cy_neg]; ring
theorem cy_sub (z w : ℂ) : cy t (z - w) = cy t z - cy t w := by
  rw [sub_eq_add_neg, cy_add, cy_neg]; ring
theorem cx_sub (z w : ℂ) : cx t (z - w) = cx t z - cx t w := by
  rw [sub_eq_add_neg, cx_add, cx_neg]; ring

theorem continuous_cy : Continuous (cy t) := by unfold cy; fun_prop
theorem continuous_cx : Continuous (cx t) := by unfold cx cy; fun_prop

theorem ext_cx_cy {z w : ℂ} (h1 : cx t z = cx t w) (h2 : cy t z = cy t w) : z = w := by
  rw [eq_cx_cy t z, eq_cx_cy t w, h1, h2]

theorem mem_lattice_iff (z : ℂ) :
    z ∈ (Lt t).lattice ↔ ∃ m n : ℤ, cy t z = m ∧ cx t z = n := by
  rw [PeriodPair.mem_lattice]
  constructor
  · rintro ⟨m, n, rfl⟩
    refine ⟨m, n, ?_, ?_⟩
    · simp only [Heights.periodPairOfUpperHalfPlane_ω₁, Heights.periodPairOfUpperHalfPlane_ω₂,
        mul_one]
      rw [cy_add, show ((m : ℂ) * t) = (m : ℝ) • (t : ℂ) by simp,
        show ((n : ℂ)) = (n : ℝ) • (1 : ℂ) by simp, cy_smul, cy_smul, cy_t, cy_one]; ring
    · simp only [Heights.periodPairOfUpperHalfPlane_ω₁, Heights.periodPairOfUpperHalfPlane_ω₂,
        mul_one]
      rw [cx_add, show ((m : ℂ) * t) = (m : ℝ) • (t : ℂ) by simp,
        show ((n : ℂ)) = (n : ℝ) • (1 : ℂ) by simp, cx_smul, cx_smul, cx_t, cx_one]; ring
  · rintro ⟨m, n, hm, hn⟩
    refine ⟨m, n, ?_⟩
    simp only [Heights.periodPairOfUpperHalfPlane_ω₁, Heights.periodPairOfUpperHalfPlane_ω₂,
      mul_one]
    rw [eq_cx_cy t z, hm, hn]; push_cast; ring

theorem one_mem : (1 : ℂ) ∈ (Lt t).lattice := (Lt t).ω₂_mem_lattice
theorem t_mem : (t : ℂ) ∈ (Lt t).lattice := (Lt t).ω₁_mem_lattice

/-! ### The fundamental parallelogram -/

/-- `[0, 1] × (0, 1)` in lattice coordinates. -/
def K₁ : Set ℂ := {z | 0 ≤ cx t z ∧ cx t z ≤ 1 ∧ 0 < cy t z ∧ cy t z < 1}
/-- `(0, 1) × [0, 1]` in lattice coordinates. -/
def K₂ : Set ℂ := {z | 0 < cx t z ∧ cx t z < 1 ∧ 0 ≤ cy t z ∧ cy t z ≤ 1}
/-- The closed parallelogram minus its corners. -/
def K : Set ℂ := K₁ t ∪ K₂ t

theorem convex_K₁ : Convex ℝ (K₁ t) := by
  intro z hz w hw a b ha hb hab
  obtain ⟨h1, h2, h3, h4⟩ := hz
  obtain ⟨h5, h6, h7, h8⟩ := hw
  simp only [K₁, mem_setOf_eq, cx_add, cy_add, cx_smul, cy_smul]
  refine ⟨by positivity, by nlinarith, ?_⟩
  rcases ha.lt_or_eq with ha' | ha'
  · constructor <;> nlinarith
  · subst ha'; rw [zero_add] at hab; subst hab; simpa using ⟨h7, h8⟩

theorem convex_K₂ : Convex ℝ (K₂ t) := by
  intro z hz w hw a b ha hb hab
  obtain ⟨h1, h2, h3, h4⟩ := hz
  obtain ⟨h5, h6, h7, h8⟩ := hw
  simp only [K₂, mem_setOf_eq, cx_add, cy_add, cx_smul, cy_smul]
  refine ⟨?_, ?_, by positivity, by nlinarith⟩
  · rcases ha.lt_or_eq with ha' | ha'
    · nlinarith
    · subst ha'; rw [zero_add] at hab; subst hab; simpa using h5
  · rcases ha.lt_or_eq with ha' | ha'
    · nlinarith
    · subst ha'; rw [zero_add] at hab; subst hab; simpa using h6

theorem K_notMem_lattice {k : ℂ} (hk : k ∈ K t) : k ∉ (Lt t).lattice := by
  rw [mem_lattice_iff]
  rintro ⟨m, n, hm, hn⟩
  rcases hk with ⟨h1, h2, h3, h4⟩ | ⟨h1, h2, h3, h4⟩
  · rw [hm] at h3 h4
    have : (0 : ℤ) < m := by exact_mod_cast h3
    have : m < (1 : ℤ) := by exact_mod_cast h4
    omega
  · rw [hn] at h1 h2
    have : (0 : ℤ) < n := by exact_mod_cast h1
    have : n < (1 : ℤ) := by exact_mod_cast h2
    omega

theorem K_subset : K t ⊆ ((Lt t).lattice : Set ℂ)ᶜ := fun _ hk ↦ K_notMem_lattice t hk

/-- The centre of the parallelogram. -/
noncomputable def c₀ : ℂ := (1 + t) / 2

theorem cx_c₀ : cx t (c₀ t) = 1 / 2 := by
  rw [c₀, show (1 + (t : ℂ)) / 2 = (1 / 2 : ℝ) • (1 : ℂ) + (1 / 2 : ℝ) • (t : ℂ) by
      rw [Complex.real_smul, Complex.real_smul]; push_cast; ring,
    cx_add, cx_smul, cx_smul, cx_one, cx_t]; ring

theorem cy_c₀ : cy t (c₀ t) = 1 / 2 := by
  rw [c₀, show (1 + (t : ℂ)) / 2 = (1 / 2 : ℝ) • (1 : ℂ) + (1 / 2 : ℝ) • (t : ℂ) by
      rw [Complex.real_smul, Complex.real_smul]; push_cast; ring,
    cy_add, cy_smul, cy_smul, cy_one, cy_t]; ring

theorem c₀_mem₁ : c₀ t ∈ K₁ t := by
  simp only [K₁, mem_setOf_eq, cx_c₀, cy_c₀]; norm_num

theorem c₀_mem₂ : c₀ t ∈ K₂ t := by
  simp only [K₂, mem_setOf_eq, cx_c₀, cy_c₀]; norm_num

/-- Every point of `ℂ ∖ Λ` is a lattice translate of a point of `K`. -/
theorem exists_mem_K {w : ℂ} (hw : w ∉ (Lt t).lattice) :
    ∃ k ∈ K t, w - k ∈ (Lt t).lattice := by
  set k : ℂ := (Int.fract (cx t w) : ℝ) • (1 : ℂ) + (Int.fract (cy t w) : ℝ) • (t : ℂ)
  have hkx : cx t k = Int.fract (cx t w) := by
    simp only [k, cx_add, cx_smul, cx_one, cx_t]; ring
  have hky : cy t k = Int.fract (cy t w) := by
    simp only [k, cy_add, cy_smul, cy_one, cy_t]; ring
  have hdiff : w - k ∈ (Lt t).lattice := by
    rw [mem_lattice_iff]
    refine ⟨⌊cy t w⌋, ⌊cx t w⌋, ?_, ?_⟩
    · rw [cy_sub, hky, Int.fract]; ring
    · rw [cx_sub, hkx, Int.fract]; ring
  refine ⟨k, ?_, hdiff⟩
  have hx0 := Int.fract_nonneg (cx t w)
  have hx1 := Int.fract_lt_one (cx t w)
  have hy0 := Int.fract_nonneg (cy t w)
  have hy1 := Int.fract_lt_one (cy t w)
  rcases hx0.lt_or_eq with hx | hx
  · right; exact ⟨hkx ▸ hx, hkx ▸ hx1, hky ▸ hy0, hky ▸ hy1.le⟩
  rcases hy0.lt_or_eq with hy | hy
  · left; exact ⟨hkx ▸ hx0, hkx ▸ hx1.le, hky ▸ hy, hky ▸ hy1⟩
  exfalso
  have hc0 : cy t 0 = 0 := by simp [cy]
  have hk0 : k = 0 := ext_cx_cy t (by rw [hkx, ← hx]; simp [cx, hc0])
    (by rw [hky, ← hy, hc0])
  rw [hk0, sub_zero] at hdiff
  exact hw hdiff


/-! ### Lifting the parallelogram -/

variable {t} (U : Unif (Lt t))

theorem K₁_subset : K₁ t ⊆ K t := subset_union_left
theorem K₂_subset : K₂ t ⊆ K t := subset_union_right

/-- The base point over the centre `c₀`. -/
noncomputable def e₀ : ℍ :=
  (U.surj (c₀ t) (K_notMem_lattice t (K₁_subset (c₀_mem₁ t)))).choose

theorem ψ_e₀ : U.ψ (e₀ U) = c₀ t :=
  (U.surj (c₀ t) (K_notMem_lattice t (K₁_subset (c₀_mem₁ t)))).choose_spec

theorem exists_s (C : Set ℂ) (hC : Convex ℝ C) (hCK : C ⊆ K t) (hc₀ : c₀ t ∈ C) :
    ∃ s : ℂ → ℍ, ContinuousOn s C ∧ (∀ k ∈ C, U.ψ (s k) = k) ∧ s (c₀ t) = e₀ U :=
  U.covering.exists_lift_of_convex hC continuousOn_id (fun _ hk ↦ K_subset t (hCK hk)) hc₀
    (ψ_e₀ U)

/-- The lift of `K₁`. -/
noncomputable def s₁ : ℂ → ℍ := (exists_s U _ (convex_K₁ t) K₁_subset (c₀_mem₁ t)).choose
/-- The lift of `K₂`. -/
noncomputable def s₂ : ℂ → ℍ := (exists_s U _ (convex_K₂ t) K₂_subset (c₀_mem₂ t)).choose

theorem s₁_spec : ContinuousOn (s₁ U) (K₁ t) ∧ (∀ k ∈ K₁ t, U.ψ (s₁ U k) = k) ∧
    s₁ U (c₀ t) = e₀ U := (exists_s U _ (convex_K₁ t) K₁_subset (c₀_mem₁ t)).choose_spec

theorem s₂_spec : ContinuousOn (s₂ U) (K₂ t) ∧ (∀ k ∈ K₂ t, U.ψ (s₂ U k) = k) ∧
    s₂ U (c₀ t) = e₀ U := (exists_s U _ (convex_K₂ t) K₂_subset (c₀_mem₂ t)).choose_spec

theorem s₁_eq_s₂ : EqOn (s₁ U) (s₂ U) (K₁ t ∩ K₂ t) :=
  U.covering.eqOn_of_lift ((convex_K₁ t).inter (convex_K₂ t)).isPreconnected
    ((s₁_spec U).1.mono inter_subset_left) ((s₂_spec U).1.mono inter_subset_right)
    (fun k hk ↦ by
      change U.ψ (s₁ U k) ∈ _
      rw [(s₁_spec U).2.1 k hk.1]; exact K_subset t (K₁_subset hk.1))
    (fun k hk ↦ by
      change U.ψ (s₁ U k) = U.ψ (s₂ U k)
      rw [(s₁_spec U).2.1 k hk.1, (s₂_spec U).2.1 k hk.2])
    ⟨c₀_mem₁ t, c₀_mem₂ t⟩ ((s₁_spec U).2.2.trans (s₂_spec U).2.2.symm)

/-- The lift `sK : K → ℍ` of the parallelogram. -/
noncomputable def sK (k : ℂ) : ℍ := by
  classical
  exact if k ∈ K₁ t then s₁ U k else s₂ U k

theorem sK_of_mem₁ {k : ℂ} (hk : k ∈ K₁ t) : sK U k = s₁ U k := by simp [sK, hk]

theorem sK_of_mem₂ {k : ℂ} (hk : k ∈ K₂ t) : sK U k = s₂ U k := by
  by_cases h : k ∈ K₁ t
  · rw [sK_of_mem₁ U h]; exact s₁_eq_s₂ U ⟨h, hk⟩
  · simp [sK, h]

theorem ψ_sK {k : ℂ} (hk : k ∈ K t) : U.ψ (sK U k) = k := by
  rcases hk with hk | hk
  · rw [sK_of_mem₁ U hk]; exact (s₁_spec U).2.1 k hk
  · rw [sK_of_mem₂ U hk]; exact (s₂_spec U).2.1 k hk

theorem continuousOn_sK₁ : ContinuousOn (sK U) (K₁ t) :=
  (s₁_spec U).1.congr fun _ hk ↦ sK_of_mem₁ U hk

theorem continuousOn_sK₂ : ContinuousOn (sK U) (K₂ t) :=
  (s₂_spec U).1.congr fun _ hk ↦ sK_of_mem₂ U hk

theorem sK_c₀ : sK U (c₀ t) = e₀ U := by rw [sK_of_mem₁ U (c₀_mem₁ t)]; exact (s₁_spec U).2.2

/-! ### The edge pairings -/

/-- The midpoint of the left edge. -/
noncomputable def pL (t : ℍ) : ℂ := (1 / 2 : ℝ) • (t : ℂ)
/-- The midpoint of the bottom edge. -/
noncomputable def pB : ℂ := (1 / 2 : ℝ) • (1 : ℂ)

theorem cx_pL : cx t (pL t) = 0 := by rw [pL, cx_smul, cx_t, mul_zero]
theorem cy_pL : cy t (pL t) = 1 / 2 := by rw [pL, cy_smul, cy_t, mul_one]
theorem cx_pB : cx t pB = 1 / 2 := by rw [pB, cx_smul, cx_one, mul_one]
theorem cy_pB : cy t pB = 0 := by rw [pB, cy_smul, cy_one, mul_zero]

theorem pL_mem : pL t ∈ K₁ t := by
  simp only [K₁, mem_setOf_eq, cx_pL, cy_pL]; norm_num
theorem pL_add_mem : pL t + 1 ∈ K₁ t := by
  simp only [K₁, mem_setOf_eq, cx_add, cy_add, cx_pL, cy_pL, cx_one, cy_one]; norm_num
theorem pB_mem : pB ∈ K₂ t := by
  simp only [K₂, mem_setOf_eq, cx_pB, cy_pB]; norm_num
theorem pB_add_mem : pB + t ∈ K₂ t := by
  simp only [K₂, mem_setOf_eq, cx_add, cy_add, cx_pB, cy_pB, cx_t, cy_t]; norm_num

theorem exists_A : ∃ A ∈ U.deckGroup, A • sK U (pL t) = sK U (pL t + 1) :=
  U.exists_mem_deckGroup (by
    rw [ψ_sK U (K₁_subset pL_add_mem), ψ_sK U (K₁_subset pL_mem), add_sub_cancel_left]
    exact one_mem t)

theorem exists_B : ∃ B ∈ U.deckGroup, B • sK U pB = sK U (pB + t) :=
  U.exists_mem_deckGroup (by
    rw [ψ_sK U (K₂_subset pB_add_mem), ψ_sK U (K₂_subset pB_mem), add_sub_cancel_left]
    exact t_mem t)

/-- The edge pairing of the left and right edges. -/
noncomputable def A : SL(2, ℝ) := (exists_A U).choose
/-- The edge pairing of the bottom and top edges. -/
noncomputable def B : SL(2, ℝ) := (exists_B U).choose

theorem A_mem : A U ∈ U.deckGroup := (exists_A U).choose_spec.1
theorem A_smul_pL : A U • sK U (pL t) = sK U (pL t + 1) := (exists_A U).choose_spec.2
theorem B_smul_pB : B U • sK U pB = sK U (pB + t) := (exists_B U).choose_spec.2
theorem B_mem : B U ∈ U.deckGroup := (exists_B U).choose_spec.1

theorem ψ_A_smul (τ : ℍ) : U.ψ (A U • τ) = U.ψ τ + 1 := by
  obtain ⟨l, hl, h⟩ := A_mem U
  have h0 := h (sK U (pL t))
  rw [A_smul_pL] at h0
  change U.ψ (sK U (pL t + 1)) = _ at h0
  rw [ψ_sK U (K₁_subset pL_add_mem), ψ_sK U (K₁_subset pL_mem)] at h0
  have : l = 1 := by linear_combination -h0
  rw [h, this]

theorem ψ_B_smul (τ : ℍ) : U.ψ (B U • τ) = U.ψ τ + t := by
  obtain ⟨l, hl, h⟩ := B_mem U
  have h0 := h (sK U pB)
  rw [B_smul_pB] at h0
  change U.ψ (sK U (pB + t)) = _ at h0
  rw [ψ_sK U (K₂_subset pB_add_mem), ψ_sK U (K₂_subset pB_mem)] at h0
  have : l = t := by linear_combination -h0
  rw [h, this]

theorem ψ_A_inv_smul (τ : ℍ) : U.ψ ((A U)⁻¹ • τ) = U.ψ τ - 1 := by
  have := ψ_A_smul U ((A U)⁻¹ • τ); rw [smul_inv_smul] at this; rw [this]; ring

theorem ψ_B_inv_smul (τ : ℍ) : U.ψ ((B U)⁻¹ • τ) = U.ψ τ - t := by
  have := ψ_B_smul U ((B U)⁻¹ • τ); rw [smul_inv_smul] at this; rw [this]; ring

/-- The open left edge. -/
def EL (t : ℍ) : Set ℂ := {z | cx t z = 0 ∧ 0 < cy t z ∧ cy t z < 1}
/-- The open bottom edge. -/
def EB (t : ℍ) : Set ℂ := {z | cy t z = 0 ∧ 0 < cx t z ∧ cx t z < 1}

theorem convex_EL : Convex ℝ (EL t) := by
  intro z hz w hw a b ha hb hab
  obtain ⟨h1, h2, h3⟩ := hz; obtain ⟨h4, h5, h6⟩ := hw
  simp only [EL, mem_setOf_eq, cx_add, cy_add, cx_smul, cy_smul, h1, h4, mul_zero, add_zero,
    true_and]
  rcases ha.lt_or_eq with ha' | ha'
  · constructor <;> nlinarith
  · subst ha'; rw [zero_add] at hab; subst hab; simpa using ⟨h5, h6⟩

theorem convex_EB : Convex ℝ (EB t) := by
  intro z hz w hw a b ha hb hab
  obtain ⟨h1, h2, h3⟩ := hz; obtain ⟨h4, h5, h6⟩ := hw
  simp only [EB, mem_setOf_eq, cx_add, cy_add, cx_smul, cy_smul, h1, h4, mul_zero, add_zero,
    true_and]
  rcases ha.lt_or_eq with ha' | ha'
  · constructor <;> nlinarith
  · subst ha'; rw [zero_add] at hab; subst hab; simpa using ⟨h5, h6⟩

theorem EL_subset {z : ℂ} (hz : z ∈ EL t) : z ∈ K₁ t := by
  obtain ⟨h1, h2, h3⟩ := hz; exact ⟨h1.ge, by rw [h1]; norm_num, h2, h3⟩

theorem EL_add_subset {z : ℂ} (hz : z ∈ EL t) : z + 1 ∈ K₁ t := by
  obtain ⟨h1, h2, h3⟩ := hz
  simp only [K₁, mem_setOf_eq, cx_add, cy_add, h1, cx_one, cy_one]; norm_num; exact ⟨h2, h3⟩

theorem EB_subset {z : ℂ} (hz : z ∈ EB t) : z ∈ K₂ t := by
  obtain ⟨h1, h2, h3⟩ := hz; exact ⟨h2, h3, h1.ge, by rw [h1]; norm_num⟩

theorem EB_add_subset {z : ℂ} (hz : z ∈ EB t) : z + t ∈ K₂ t := by
  obtain ⟨h1, h2, h3⟩ := hz
  simp only [K₂, mem_setOf_eq, cx_add, cy_add, h1, cx_t, cy_t]; norm_num; exact ⟨h2, h3⟩

/-- **Edge relation for `A`.** -/
theorem A_smul_sK {k : ℂ} (hk : k ∈ EL t) : A U • sK U k = sK U (k + 1) := by
  have := U.covering.eqOn_of_lift ((convex_EL (t := t))).isPreconnected
    (σ₁ := fun p ↦ A U • sK U p) (σ₂ := fun p ↦ sK U (p + 1))
    ((continuous_const_smul _).comp_continuousOn ((continuousOn_sK₁ U).mono fun _ h ↦ EL_subset h))
    ((continuousOn_sK₁ U).comp (continuous_add_const 1).continuousOn fun _ h ↦ EL_add_subset h)
    (fun p hp ↦ by
      change U.ψ (A U • sK U p) ∈ _
      rw [ψ_A_smul, ψ_sK U (K₁_subset (EL_subset hp))]
      exact K_subset t (K₁_subset (EL_add_subset hp)))
    (fun p hp ↦ by
      change U.ψ (A U • sK U p) = U.ψ (sK U (p + 1))
      rw [ψ_A_smul, ψ_sK U (K₁_subset (EL_subset hp)),
        ψ_sK U (K₁_subset (EL_add_subset hp))])
    (a₀ := pL t) ⟨cx_pL, by rw [cy_pL]; norm_num, by rw [cy_pL]; norm_num⟩
    (A_smul_pL U)
  exact this hk

/-- **Edge relation for `B`.** -/
theorem B_smul_sK {k : ℂ} (hk : k ∈ EB t) : B U • sK U k = sK U (k + t) := by
  have := U.covering.eqOn_of_lift ((convex_EB (t := t))).isPreconnected
    (σ₁ := fun p ↦ B U • sK U p) (σ₂ := fun p ↦ sK U (p + t))
    ((continuous_const_smul _).comp_continuousOn ((continuousOn_sK₂ U).mono fun _ h ↦ EB_subset h))
    ((continuousOn_sK₂ U).comp (continuous_add_const _).continuousOn fun _ h ↦ EB_add_subset h)
    (fun p hp ↦ by
      change U.ψ (B U • sK U p) ∈ _
      rw [ψ_B_smul, ψ_sK U (K₂_subset (EB_subset hp))]
      exact K_subset t (K₂_subset (EB_add_subset hp)))
    (fun p hp ↦ by
      change U.ψ (B U • sK U p) = U.ψ (sK U (p + t))
      rw [ψ_B_smul, ψ_sK U (K₂_subset (EB_subset hp)),
        ψ_sK U (K₂_subset (EB_add_subset hp))])
    (a₀ := pB) ⟨cy_pB, by rw [cx_pB]; norm_num, by rw [cx_pB]; norm_num⟩
    (B_smul_pB U)
  exact this hk

end Generators

end Uniformization
