/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Heights.VariableChangePoint
import Heights.WeierstrassDifferential
import Heights.WeierstrassSurjectivity
import Oka.Uniformization.CommutatorTrace

/-!
# Uniformisation of once-punctured elliptic curves

**Theorem** (`Uniformization.uniformization_oncePunctured`). For every elliptic curve `W` over `ℂ`
there are `A, B ∈ SL(2, ℝ)` with `tr [A, B] = -2` and `tr A ≠ 0`, and a map `π : ℂ → ℂ × ℂ`,
holomorphic with nonvanishing derivative on `ℍ`, mapping `ℍ` onto the affine points of `W`, whose
fibres on `ℍ` are exactly the orbits of `⟨A, B⟩`.

That is, `ℍ / ⟨A, B⟩ ≅ E(ℂ) ∖ {O}` with `⟨A, B⟩` a once-punctured torus group (signature `(1; ∞)`).

Proof: `W` is isomorphic by a change of variables to the lattice curve of some `τ ∈ ℍ`
(surjectivity of the modular `j`-function and `WeierstrassCurve.exists_variableChange_of_j_eq`),
whose affine points are `(℘(z), ℘'(z)/2)` for `z ∉ Λ = ℤτ + ℤ`, with fibres the `Λ`-cosets
(`heights`). Compose with the universal covering `ψ : ℍ → ℂ ∖ Λ`
(`Uniformization.PeriodPair.exists_uniformization`): the fibres of the composite are the orbits of
the deck group `Γ`, which is generated by the edge pairings `A`, `B` and `-1`
(`Generators.deckGroup_le`), and `tr [A, B] = -2` (`Peripheral.trace_Cm`). The derivative does not
vanish because `ψ′ ≠ 0` and `℘′`, `℘''` have no common zero off `Λ` (the cubic `4X³ - g₂X - g₃` has
simple roots).

This is the statement U1 of `lana-agents/orbicurve-cores`, Blueprint §2.3a, with
`OrbicurveCores.tr A = Matrix.trace (A : Matrix (Fin 2) (Fin 2) ℝ)`.
-/

open Complex Metric Set Filter Topology
open UpperHalfPlane hiding I I_re I_im
open scoped MatrixGroups

namespace Uniformization

open Generators Peripheral

variable (τ₀ : ℍ)

/-- The Weierstrass point map `z ↦ (℘(z), ℘'(z)/2)` of the lattice `ℤτ₀ + ℤ`. -/
noncomputable def wpt (z : ℂ) : ℂ × ℂ := ((Lt τ₀).weierstrassP z, (Lt τ₀).derivWeierstrassP z / 2)

theorem wpt_equation {z : ℂ} (hz : z ∉ (Lt τ₀).lattice) :
    (Heights.latticeWeierstrassCurve τ₀).toAffine.Equation (wpt τ₀ z).1 (wpt τ₀ z).2 :=
  Heights.weierstrassP_on_latticeWeierstrassCurve τ₀ z hz

theorem latticePointMap_eq_mk {z : ℂ} (hz : z ∉ (Lt τ₀).lattice) :
    Heights.latticePointMap τ₀ z = WeierstrassCurve.Affine.Point.mk (wpt_equation τ₀ hz) := by
  rw [Heights.latticePointMap_of_notMem τ₀ z hz]; rfl

theorem wpt_eq_iff {z w : ℂ} (hz : z ∉ (Lt τ₀).lattice) (hw : w ∉ (Lt τ₀).lattice) :
    wpt τ₀ z = wpt τ₀ w ↔ z - w ∈ (Lt τ₀).lattice := by
  rw [← Heights.latticePointMap_eq_iff_sub_mem, latticePointMap_eq_mk τ₀ hz,
    latticePointMap_eq_mk τ₀ hw]
  constructor
  · intro h
    simp only [WeierstrassCurve.Affine.Point.mk]
    congr 1 <;> simp [h]
  · intro h
    simp only [WeierstrassCurve.Affine.Point.mk, WeierstrassCurve.Affine.Point.some.injEq] at h
    exact Prod.ext h.1 h.2

theorem exists_wpt_eq {X Y : ℂ} (h : (Heights.latticeWeierstrassCurve τ₀).toAffine.Equation X Y) :
    ∃ z ∉ (Lt τ₀).lattice, wpt τ₀ z = (X, Y) := by
  obtain ⟨z, hz⟩ := Heights.latticePointMap_surjective τ₀ (WeierstrassCurve.Affine.Point.mk h)
  by_cases hzl : z ∈ (Lt τ₀).lattice
  · rw [Heights.latticePointMap_of_mem τ₀ z hzl] at hz
    exact absurd hz.symm (WeierstrassCurve.Affine.Point.some_ne_zero _)
  · refine ⟨z, hzl, ?_⟩
    rw [latticePointMap_eq_mk τ₀ hzl] at hz
    simp only [WeierstrassCurve.Affine.Point.mk, WeierstrassCurve.Affine.Point.some.injEq] at hz
    exact Prod.ext hz.1 hz.2

/-- `℘′` and `℘''` have no common zero off the lattice. -/
theorem not_deriv_deriv_eq_zero {z : ℂ} (hz : z ∉ (Lt τ₀).lattice)
    (h1 : (Lt τ₀).derivWeierstrassP z = 0) :
    deriv (Lt τ₀).derivWeierstrassP z ≠ 0 := by
  rw [Heights.deriv_derivWeierstrassP _ z hz]
  intro h2
  have hsq := (Lt τ₀).derivWeierstrassP_sq z hz
  rw [h1] at hsq
  set e := (Lt τ₀).weierstrassP z
  have hg₂ : (Lt τ₀).g₂ = 12 * e ^ 2 := by linear_combination -2 * h2
  have hg₃ : (Lt τ₀).g₃ = -8 * e ^ 3 := by rw [hg₂] at hsq; linear_combination hsq
  apply Heights.periodPair_invariant_discriminant_ne_zero τ₀
  change (Lt τ₀).g₂ ^ 3 - 27 * (Lt τ₀).g₃ ^ 2 = 0
  rw [hg₂, hg₃]; ring

theorem hasDerivAt_wp {z : ℂ} (hz : z ∉ (Lt τ₀).lattice) :
    HasDerivAt (Lt τ₀).weierstrassP ((Lt τ₀).derivWeierstrassP z) z := by
  have := ((Lt τ₀).analyticOnNhd_weierstrassP z hz).differentiableAt.hasDerivAt
  rwa [PeriodPair.deriv_weierstrassP] at this

theorem hasDerivAt_wp' {z : ℂ} (hz : z ∉ (Lt τ₀).lattice) :
    HasDerivAt (Lt τ₀).derivWeierstrassP (deriv (Lt τ₀).derivWeierstrassP z) z :=
  ((Lt τ₀).analyticOnNhd_derivWeierstrassP z hz).differentiableAt.hasDerivAt

/-- The uniformisation map `z ↦ C⁻¹ (℘(ψ z), ℘'(ψ z)/2)` of `W = E_{τ₀}^C`, for the chosen
uniformisation `ψ` of `ℂ ∖ Λ_{τ₀}` and a change of variables `C`. -/
noncomputable def uniformizationMap (C : WeierstrassCurve.VariableChange ℂ) (z : ℂ) : ℂ × ℂ :=
  ((C.u⁻¹ : ℂ) ^ 2 * ((wpt τ₀ ((unifOf (Lt τ₀)).Ψ z)).1 - C.r),
    (C.u⁻¹ : ℂ) ^ 3 * ((wpt τ₀ ((unifOf (Lt τ₀)).Ψ z)).2 - C.s * ((wpt τ₀ ((unifOf (Lt τ₀)).Ψ z)).1
      - C.r) - C.t))

/-- **Uniformisation of `W = E_{τ₀}^C`** by the explicit map `uniformizationMap τ₀ C`. -/
theorem uniformization_of_variableChange (W : WeierstrassCurve ℂ) [W.IsElliptic]
    (C : WeierstrassCurve.VariableChange ℂ)
    (hC : C • Heights.latticeWeierstrassCurve τ₀ = W) :
    Matrix.trace ((A (unifOf (Lt τ₀)) * B (unifOf (Lt τ₀)) * (A (unifOf (Lt τ₀)))⁻¹ *
        (B (unifOf (Lt τ₀)))⁻¹ : SL(2, ℝ)) : Matrix (Fin 2) (Fin 2) ℝ) = -2 ∧
      Matrix.trace (A (unifOf (Lt τ₀)) : Matrix (Fin 2) (Fin 2) ℝ) ≠ 0 ∧
      (∀ z : ℍ, DifferentiableAt ℂ (uniformizationMap τ₀ C) z ∧
        deriv (uniformizationMap τ₀ C) z ≠ 0) ∧
      (∀ z : ℍ, W.toAffine.Equation (uniformizationMap τ₀ C z).1
        (uniformizationMap τ₀ C z).2) ∧
      (∀ x y : ℂ, W.toAffine.Equation x y → ∃ z : ℍ, uniformizationMap τ₀ C z = (x, y)) ∧
      (∀ z w : ℍ, uniformizationMap τ₀ C z = uniformizationMap τ₀ C w ↔
        ∃ γ ∈ Subgroup.closure {A (unifOf (Lt τ₀)), B (unifOf (Lt τ₀))}, γ • z = w) := by
  set U := unifOf (Lt τ₀)
  set u : ℂ := (C.u : ℂ)
  have hu : u ≠ 0 := C.u.ne_zero
  set r := C.r; set s := C.s; set t := C.t
  -- the coordinate change `E_τ₀ → W`
  set T : ℂ × ℂ → ℂ × ℂ := fun P ↦ (u⁻¹ ^ 2 * (P.1 - r), u⁻¹ ^ 3 * (P.2 - s * (P.1 - r) - t))
  have hT : ∀ X Y : ℂ, W.toAffine.Equation (T (X, Y)).1 (T (X, Y)).2 ↔
      (Heights.latticeWeierstrassCurve τ₀).toAffine.Equation X Y := by
    intro X Y
    rw [← hC, WeierstrassCurve.variableChange_equation_iff]
    have e1 : u ^ 2 * (u⁻¹ ^ 2 * (X - r)) + r = X := by field_simp; ring
    have e2 : u ^ 3 * (u⁻¹ ^ 3 * (Y - s * (X - r) - t)) + u ^ 2 * s * (u⁻¹ ^ 2 * (X - r)) + t =
        Y := by
      field_simp; ring
    simp only [T]; rw [e1, e2]
  have hTinj : ∀ P Q, T P = T Q → P = Q := by
    rintro ⟨X, Y⟩ ⟨X', Y'⟩ h
    simp only [T, Prod.mk.injEq] at h
    have hX : X = X' := by
      have := h.1; field_simp at this; linear_combination this
    subst hX
    have := h.2; field_simp at this
    exact Prod.ext rfl (by linear_combination this)
  set π : ℂ → ℂ × ℂ := fun z ↦ T (wpt τ₀ (U.Ψ z))
  have hπdef : uniformizationMap τ₀ C = π := rfl
  rw [hπdef]
  have hΨ : ∀ z : ℍ, U.Ψ z ∉ (Lt τ₀).lattice := fun z ↦ U.notMem z z.im_pos
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · -- the commutator trace
    rw [← trSL_eq_trace, show A U * B U * (A U)⁻¹ * (B U)⁻¹ =
      (A U * B U) * ((A U)⁻¹ * (B U)⁻¹) by group, trSL_mul_comm, ← trace_Cm U, Cm]
    congr 1; group
  · rw [← trSL_eq_trace]; exact trSL_A_ne_zero U
  · -- holomorphic with nonvanishing derivative
    intro z
    have hz : 0 < (z : ℂ).im := z.im_pos
    have hΨd : HasDerivAt U.Ψ (deriv U.Ψ z) z :=
      (U.differentiableOn.differentiableAt (isOpen_upper.mem_nhds hz)).hasDerivAt
    set w := U.Ψ z
    have hw := hΨ z
    have h1 : HasDerivAt (fun z ↦ u⁻¹ ^ 2 * ((Lt τ₀).weierstrassP (U.Ψ z) - r))
        (u⁻¹ ^ 2 * ((Lt τ₀).derivWeierstrassP w * deriv U.Ψ z)) z :=
      (((hasDerivAt_wp τ₀ hw).comp _ hΨd).sub_const r).const_mul _
    have h2 : HasDerivAt (fun z ↦ u⁻¹ ^ 3 * ((Lt τ₀).derivWeierstrassP (U.Ψ z) / 2 -
        s * ((Lt τ₀).weierstrassP (U.Ψ z) - r) - t))
        (u⁻¹ ^ 3 * (deriv (Lt τ₀).derivWeierstrassP w * deriv U.Ψ z / 2 -
          s * ((Lt τ₀).derivWeierstrassP w * deriv U.Ψ z))) z :=
      (((((hasDerivAt_wp' τ₀ hw).comp _ hΨd).div_const 2).sub
        ((((hasDerivAt_wp τ₀ hw).comp _ hΨd).sub_const r).const_mul s)).sub_const t).const_mul _
    have hπ : HasDerivAt π (u⁻¹ ^ 2 * ((Lt τ₀).derivWeierstrassP w * deriv U.Ψ z),
        u⁻¹ ^ 3 * (deriv (Lt τ₀).derivWeierstrassP w * deriv U.Ψ z / 2 -
          s * ((Lt τ₀).derivWeierstrassP w * deriv U.Ψ z))) z := h1.prodMk h2
    refine ⟨hπ.differentiableAt, ?_⟩
    rw [hπ.deriv]
    intro h0
    simp only [Prod.mk_eq_zero] at h0
    obtain ⟨h01, h02⟩ := h0
    have hd := U.deriv_ne_zero z hz
    have hu2 : u⁻¹ ^ 2 ≠ 0 := by simp [hu]
    have hu3 : u⁻¹ ^ 3 ≠ 0 := by simp [hu]
    have hp1 : (Lt τ₀).derivWeierstrassP w = 0 := by
      rcases mul_eq_zero.mp h01 with h | h
      · exact absurd h hu2
      · rcases mul_eq_zero.mp h with h | h
        · exact h
        · exact absurd h hd
    rw [hp1] at h02
    have : deriv (Lt τ₀).derivWeierstrassP w = 0 := by
      rcases mul_eq_zero.mp h02 with h | h
      · exact absurd h hu3
      · simp only [zero_mul, mul_zero, sub_zero, div_eq_zero_iff, mul_eq_zero] at h
        rcases h with (h | h) | h
        · exact h
        · exact absurd h hd
        · norm_num at h
    exact not_deriv_deriv_eq_zero τ₀ hw hp1 this
  · -- points of `W`
    intro z
    exact (hT _ _).mpr (wpt_equation τ₀ (hΨ z))
  · -- onto the affine points
    intro x y hxy
    set X := u ^ 2 * x + r; set Y := u ^ 3 * y + u ^ 2 * s * x + t
    have hTXY : T (X, Y) = (x, y) := by
      simp only [T, X, Y, Prod.mk.injEq]
      constructor <;> field_simp <;> ring
    have hE : (Heights.latticeWeierstrassCurve τ₀).toAffine.Equation X Y := by
      rw [← hT, hTXY]; exact hxy
    obtain ⟨z₀, hz₀, hwz⟩ := exists_wpt_eq τ₀ hE
    obtain ⟨z, hz⟩ := U.surj z₀ hz₀
    exact ⟨z, by simp only [π]; rw [hz, hwz, hTXY]⟩
  · -- the fibres are the orbits of `⟨A, B⟩`
    intro z w
    have key : π z = π w ↔ U.ψ w - U.ψ z ∈ (Lt τ₀).lattice := by
      constructor
      · intro h
        have := (wpt_eq_iff τ₀ (hΨ w) (hΨ z)).mp (hTinj _ _ h.symm)
        exact this
      · intro h
        simp only [π]
        rw [(wpt_eq_iff τ₀ (hΨ z) (hΨ w)).mpr (by
          have := neg_mem h; rwa [neg_sub] at this)]
    rw [key]
    -- elements of `H = ⟨A, B, -1⟩` act as elements of `⟨A, B⟩`
    have hHAB : ∀ g ∈ H U, ∃ h ∈ Subgroup.closure {A U, B U}, ∀ σ : ℍ, h • σ = g • σ := by
      intro g hg
      induction hg using Subgroup.closure_induction with
      | mem g hg =>
        simp only [mem_insert_iff, mem_singleton_iff] at hg
        rcases hg with rfl | rfl | rfl
        · exact ⟨A U, Subgroup.subset_closure (by simp), fun σ ↦ rfl⟩
        · exact ⟨B U, Subgroup.subset_closure (by simp), fun σ ↦ rfl⟩
        · exact ⟨1, one_mem _, fun σ ↦ by rw [one_smul, neg_one_smul']⟩
      | one => exact ⟨1, one_mem _, fun σ ↦ rfl⟩
      | mul g₁ g₂ _ _ ih₁ ih₂ =>
        obtain ⟨h₁, hh₁, e₁⟩ := ih₁
        obtain ⟨h₂, hh₂, e₂⟩ := ih₂
        exact ⟨h₁ * h₂, mul_mem hh₁ hh₂, fun σ ↦ by rw [mul_smul, mul_smul, e₂, e₁]⟩
      | inv g _ ih =>
        obtain ⟨h, hh, e⟩ := ih
        refine ⟨h⁻¹, inv_mem hh, fun σ ↦ ?_⟩
        have := e (g⁻¹ • σ)
        rw [smul_inv_smul] at this
        rw [inv_smul_eq_iff, this]
    have hABΓ : Subgroup.closure {A U, B U} ≤ U.deckGroup := by
      rw [Subgroup.closure_le]
      intro g hg
      simp only [mem_insert_iff, mem_singleton_iff] at hg
      rcases hg with rfl | rfl
      exacts [A_mem U, B_mem U]
    constructor
    · intro h
      obtain ⟨g, hg, hgz⟩ := U.exists_mem_deckGroup h
      obtain ⟨h', hh', e⟩ := hHAB g (deckGroup_le U hg)
      exact ⟨h', hh', by rw [e, hgz]⟩
    · rintro ⟨γ, hγ, rfl⟩
      exact U.smul_mem_iff (hABΓ hγ) z

/-- **Uniformisation of once-punctured elliptic curves** (U1 of [CanLift] Prop. 2.7). -/
theorem uniformization_oncePunctured (W : WeierstrassCurve ℂ) [W.IsElliptic] :
    ∃ (A B : SL(2, ℝ)) (π : ℂ → ℂ × ℂ),
      Matrix.trace ((A * B * A⁻¹ * B⁻¹ : SL(2, ℝ)) : Matrix (Fin 2) (Fin 2) ℝ) = -2 ∧
      Matrix.trace (A : Matrix (Fin 2) (Fin 2) ℝ) ≠ 0 ∧
      (∀ z : ℍ, DifferentiableAt ℂ π z ∧ deriv π z ≠ 0) ∧
      (∀ z : ℍ, W.toAffine.Equation (π z).1 (π z).2) ∧
      (∀ x y : ℂ, W.toAffine.Equation x y → ∃ z : ℍ, π z = (x, y)) ∧
      (∀ z w : ℍ, π z = π w ↔ ∃ γ ∈ Subgroup.closure {A, B}, γ • z = w) := by
  obtain ⟨τ₀, hτ₀⟩ := Heights.modularJ_surjective W.j
  obtain ⟨C, hC⟩ := WeierstrassCurve.exists_variableChange_of_j_eq
    (Heights.latticeWeierstrassCurve τ₀) W (by rw [Heights.latticeWeierstrassCurve_j, hτ₀])
  exact ⟨_, _, _, uniformization_of_variableChange τ₀ W C hC⟩

end Uniformization
