/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.FieldTheory.RatFunc.Luroth
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# Subalgebras of `K[X]` are contained in `K[s]` for a polynomial `s` (via Lüroth)

Let `K` be algebraically closed and `R ⊆ K[X]` a `K`-subalgebra containing a non-constant
polynomial. Then there is a non-constant polynomial `s` in the fraction field of `R` with
`R ⊆ K[s]` (`RatFuncPoly.exists_poly_generator`).

By Lüroth, the subfield of `K(X)` generated by `R` is `K(g)`. After a Möbius change of `g`, the
numerator of `g` has larger degree than its denominator. If `A(g)/B(g)` is a polynomial `P`
(with `A`, `B` coprime), then `B` is constant: otherwise a root `β` of `B` is a value `g(x₁)` at
a point where `g` is finite, and `P(x₁) B(β) = A(β)` forces a common root. If moreover the
denominator of `g` vanished at some `x₀`, then `q^{deg A} P = q^{deg A} A(n/q)` evaluated at `x₀`
forces `deg A = 0`; so a non-constant `P` forces `g` to be a polynomial.
-/

open Polynomial IntermediateField

namespace Uniformization

namespace RatFuncPoly

variable {K : Type*} [Field K]

local notation "ι" => algebraMap K[X] (RatFunc K)

/-- `q^{deg A} A(n/q)`, as a polynomial. -/
noncomputable def homog (A n q : K[X]) : K[X] :=
  ∑ i ∈ Finset.range (A.natDegree + 1), C (A.coeff i) * n ^ i * q ^ (A.natDegree - i)

theorem algebraMap_homog (A n q : K[X]) (hq : q ≠ 0) :
    ι (homog A n q) = ι q ^ A.natDegree * aeval (ι n / ι q) A := by
  have hq' : ι q ≠ 0 := by
    rwa [ne_eq, map_eq_zero_iff _ (IsFractionRing.injective K[X] (RatFunc K))]
  rw [aeval_eq_sum_range, Finset.mul_sum, homog, map_sum]
  refine Finset.sum_congr rfl fun i hi ↦ ?_
  have hi' : i ≤ A.natDegree := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
  have hpow : ι q ^ A.natDegree = ι q ^ (A.natDegree - i) * ι q ^ i := by
    rw [← pow_add, Nat.sub_add_cancel hi']
  have hC : ι (C (A.coeff i)) = algebraMap K (RatFunc K) (A.coeff i) := by
    rw [IsScalarTower.algebraMap_apply K K[X] (RatFunc K)]; rfl
  rw [Algebra.smul_def, map_mul, map_mul, map_pow, map_pow, div_pow, hpow, hC]
  field_simp

theorem eval_homog_of_root {A n q : K[X]} {x : K} (hx : q.eval x = 0) :
    (homog A n q).eval x = A.leadingCoeff * n.eval x ^ A.natDegree := by
  rw [homog, eval_finsetSum, Finset.sum_range_succ, Finset.sum_eq_zero, leadingCoeff]
  · simp only [eval_mul, eval_C, eval_pow, Nat.sub_self, pow_zero, mul_one, zero_add]
  · intro i hi
    have : 0 < A.natDegree - i := Nat.sub_pos_of_lt (Finset.mem_range.mp hi)
    simp [hx, zero_pow this.ne']

theorem eval_homog_of_eq {A n q : K[X]} {x β : K} (hx : n.eval x = β * q.eval x) :
    (homog A n q).eval x = q.eval x ^ A.natDegree * A.eval β := by
  rw [homog, eval_finsetSum, eval_eq_sum_range (p := A) β, Finset.mul_sum]
  refine Finset.sum_congr rfl fun i hi ↦ ?_
  have hi' : i ≤ A.natDegree := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
  have hpow : q.eval x ^ A.natDegree = q.eval x ^ (A.natDegree - i) * q.eval x ^ i := by
    rw [← pow_add, Nat.sub_add_cancel hi']
  simp only [eval_mul, eval_C, eval_pow, hx, hpow]
  ring

theorem not_isCoprime_of_common_root {A B : K[X]} {β : K} (hA : A.eval β = 0)
    (hB : B.eval β = 0) : ¬ IsCoprime A B := by
  rintro ⟨u, v, h⟩
  have := congrArg (eval β) h
  simp [hA, hB] at this

/-- **The pole argument.** Let `g = n/q` with `n, q` coprime and `deg q < deg n`. A polynomial in
`K(g)` is a polynomial expression in `g`. -/
theorem exists_aeval_of_mem [IsAlgClosed K] {n q : K[X]} (hcop : IsCoprime n q) (hq : q ≠ 0)
    (hdeg : q.natDegree < n.natDegree) {P : K[X]} (hP : ι P ∈ K⟮ι n / ι q⟯) :
    ∃ A : K[X], ι P = aeval (ι n / ι q) A := by
  classical
  set g := ι n / ι q
  have hinj : Function.Injective ι := IsFractionRing.injective K[X] (RatFunc K)
  have hq' : ι q ≠ 0 := by rwa [ne_eq, map_eq_zero_iff _ hinj]
  obtain ⟨r, s, hrs⟩ := (mem_adjoin_simple_iff K _).mp hP
  by_cases hs0 : aeval g s = 0
  · exact ⟨0, by rw [hrs, hs0, div_zero, map_zero]⟩
  have hs : s ≠ 0 := by rintro rfl; simp at hs0
  obtain ⟨d, r₁, s₁, hcop₁, hr, hs'⟩ : ∃ d r₁ s₁ : K[X], IsCoprime r₁ s₁ ∧ r = d * r₁ ∧
      s = d * s₁ :=
    ⟨GCDMonoid.gcd r s, r / GCDMonoid.gcd r s, s / GCDMonoid.gcd r s,
      isCoprime_div_gcd_div_gcd hs,
      (EuclideanDomain.mul_div_cancel' (gcd_ne_zero_of_right hs) (gcd_dvd_left r s)).symm,
      (EuclideanDomain.mul_div_cancel' (gcd_ne_zero_of_right hs) (gcd_dvd_right r s)).symm⟩
  have hd0 : aeval g d ≠ 0 := by
    intro h; apply hs0; rw [hs', map_mul, h, zero_mul]
  have hs₁0 : aeval g s₁ ≠ 0 := by
    intro h; apply hs0; rw [hs', map_mul, h, mul_zero]
  have hP₁ : ι P * aeval g s₁ = aeval g r₁ := by
    rw [hrs, hr, hs', map_mul, map_mul, mul_div_mul_left _ _ hd0, div_mul_cancel₀ _ hs₁0]
  -- `s₁` is constant
  have hs₁deg : s₁.natDegree = 0 := by
    by_contra hne
    obtain ⟨β, hβ⟩ := IsAlgClosed.exists_root s₁ (by
      rw [degree_eq_natDegree (fun h ↦ hs₁0 (by rw [h, map_zero]))]; exact_mod_cast hne)
    -- a point `x` with `g(x) = β`
    have hdeg' : (n - C β * q).natDegree = n.natDegree := by
      rw [natDegree_sub_eq_left_of_natDegree_lt]
      exact (natDegree_C_mul_le β q).trans_lt hdeg
    obtain ⟨x, hx⟩ := IsAlgClosed.exists_root (n - C β * q) (by
      rw [degree_eq_natDegree (fun h ↦ by rw [h, natDegree_zero] at hdeg'; omega), hdeg']
      exact_mod_cast (Nat.zero_le _).trans_lt hdeg |>.ne')
    have hx' : n.eval x = β * q.eval x := by
      simpa [sub_eq_zero] using hx
    have hqx : q.eval x ≠ 0 := by
      intro h0
      exact not_isCoprime_of_common_root (β := x) (by rw [hx', h0, mul_zero]) h0 hcop
    have key : P * homog s₁ n q * q ^ r₁.natDegree = homog r₁ n q * q ^ s₁.natDegree := by
      apply hinj
      simp only [map_mul, map_pow, algebraMap_homog _ _ _ hq]
      rw [← hP₁]; ring
    have := congrArg (eval x) key
    simp only [eval_mul, eval_pow, eval_homog_of_eq hx', hβ.eq_zero, mul_zero, zero_mul] at this
    have hr₁β : r₁.eval β = 0 := by
      have h2 : q.eval x ^ r₁.natDegree * r₁.eval β * q.eval x ^ s₁.natDegree = 0 := by
        rw [← this]
      simpa [hqx] using h2
    exact not_isCoprime_of_common_root hr₁β hβ.eq_zero hcop₁
  obtain ⟨b, hb⟩ : ∃ b, s₁ = C b := ⟨s₁.coeff 0, eq_C_of_natDegree_eq_zero hs₁deg⟩
  have hb0 : b ≠ 0 := by rintro rfl; apply hs₁0; rw [hb, map_zero, map_zero]
  refine ⟨C b⁻¹ * r₁, ?_⟩
  rw [map_mul, aeval_C, ← hP₁, hb, aeval_C]
  rw [mul_comm, mul_assoc, ← map_mul, mul_inv_cancel₀ hb0, map_one, mul_one]

/-- If the denominator of `g = n/q` has a root, the polynomials in `K(g)` are constant. -/
theorem natDegree_eq_zero_of_mem [IsAlgClosed K] {n q : K[X]} (hcop : IsCoprime n q) (hq : q ≠ 0)
    (hdeg : q.natDegree < n.natDegree) {x₀ : K} (hx₀ : q.eval x₀ = 0) {P : K[X]}
    (hP : ι P ∈ K⟮ι n / ι q⟯) : P.natDegree = 0 := by
  have hinj : Function.Injective ι := IsFractionRing.injective K[X] (RatFunc K)
  obtain ⟨A, hA⟩ := exists_aeval_of_mem hcop hq hdeg hP
  have key : P * q ^ A.natDegree = homog A n q := by
    apply hinj
    rw [map_mul, map_pow, algebraMap_homog _ _ _ hq, hA, mul_comm]
  have hn : n.eval x₀ ≠ 0 := fun h ↦ not_isCoprime_of_common_root h hx₀ hcop
  have hAdeg : A.natDegree = 0 := by
    by_contra hne
    have := congrArg (eval x₀) key
    rw [eval_mul, eval_pow, hx₀, zero_pow hne, mul_zero, eval_homog_of_root hx₀] at this
    have hlc : A.leadingCoeff = 0 := by
      have := this.symm
      simpa [hn] using this
    rw [leadingCoeff_eq_zero] at hlc
    rw [hlc, natDegree_zero] at hne
    exact hne rfl
  rw [eq_C_of_natDegree_eq_zero hAdeg, aeval_C] at hA
  rw [hinj (hA.trans (by rw [IsScalarTower.algebraMap_apply K K[X] (RatFunc K)]; rfl) :
    ι P = ι (C (A.coeff 0))), natDegree_C]

/-- Polynomials in `K(s)`, `s` a non-constant polynomial, are polynomials in `s`. -/
theorem exists_comp_of_mem [IsAlgClosed K] {s : K[X]} (hs : 0 < s.natDegree) {P : K[X]}
    (hP : ι P ∈ K⟮ι s⟯) : ∃ A : K[X], P = A.comp s := by
  have hinj : Function.Injective ι := IsFractionRing.injective K[X] (RatFunc K)
  have h1 : ι s / ι 1 = ι s := by rw [map_one, div_one]
  obtain ⟨A, hA⟩ := exists_aeval_of_mem (n := s) (q := 1) isCoprime_one_right one_ne_zero
    (by rwa [natDegree_one]) (h1 ▸ hP)
  refine ⟨A, hinj ?_⟩
  rw [hA, h1, comp_eq_aeval, aeval_algebraMap_apply]

/-- **Subalgebras of `K[X]` lie in `K[s]`** (Lüroth). If a `K`-subalgebra `R ⊆ K[X]` contains a
non-constant polynomial, there is a non-constant polynomial `s`, a quotient of two elements of
`R`, with `R ⊆ K[s]`. -/
theorem exists_poly_generator [IsAlgClosed K] (R : Subalgebra K K[X])
    (hR : ∃ p ∈ R, 0 < p.natDegree) :
    ∃ s : K[X], 0 < s.natDegree ∧ (∃ r ∈ R, ∃ q ∈ R, q ≠ 0 ∧ s * q = r) ∧
      ∀ p ∈ R, ∃ A : K[X], p = A.comp s := by
  classical
  have hinj : Function.Injective ι := IsFractionRing.injective K[X] (RatFunc K)
  have hιC : ∀ c : K, ι (C c) = algebraMap K (RatFunc K) c := fun c ↦ by
    rw [IsScalarTower.algebraMap_apply K K[X] (RatFunc K)]; rfl
  obtain ⟨p₀, hp₀R, hp₀⟩ := hR
  set E : IntermediateField K (RatFunc K) := IntermediateField.adjoin K (ι '' (R : Set K[X]))
  have hmemE : ∀ p ∈ R, ι p ∈ E := fun p hp ↦ IntermediateField.subset_adjoin _ _ ⟨p, hp, rfl⟩
  have hdivE : ∀ y ∈ E, ∃ r ∈ R, ∃ q ∈ R, y = ι r / ι q := by
    intro y hy
    obtain ⟨r', hr', q', hq', rfl⟩ := IntermediateField.mem_adjoin_iff_div.mp hy
    have himg : ι '' (R : Set K[X]) = (IsScalarTower.toAlgHom K K[X] (RatFunc K)) '' R := rfl
    rw [himg, Algebra.adjoin_image, Algebra.adjoin_eq] at hr' hq'
    obtain ⟨r, hr, rfl⟩ := hr'
    obtain ⟨q, hq, rfl⟩ := hq'
    exact ⟨r, hr, q, hq, rfl⟩
  have hE : E ≠ ⊥ := by
    intro h
    have h1 := hmemE p₀ hp₀R
    rw [h, IntermediateField.mem_bot] at h1
    obtain ⟨c, hc⟩ := h1
    rw [← hιC] at hc
    rw [← hinj hc, natDegree_C] at hp₀
    exact lt_irrefl _ hp₀
  set g := RatFunc.Luroth.generator E
  have hEg : E = K⟮g⟯ := RatFunc.Luroth.eq_adjoin_generator
  have hgnd : g = ι g.num / ι g.denom := (RatFunc.num_div_denom g).symm
  -- a representation `g' = n / q` of a generator with `deg q < deg n`
  obtain ⟨n, q, hcop, hq, hdeg, hEnq⟩ : ∃ n q : K[X], IsCoprime n q ∧ q ≠ 0 ∧
      q.natDegree < n.natDegree ∧ E = K⟮ι n / ι q⟯ := by
    by_cases hlt : g.denom.natDegree < g.num.natDegree
    · exact ⟨g.num, g.denom, RatFunc.isCoprime_num_denom g, g.denom_ne_zero, hlt, hgnd ▸ hEg⟩
    · push Not at hlt
      set nn := g.num
      set qq := g.denom
      have hqq : qq ≠ 0 := g.denom_ne_zero
      have hqq' : ι qq ≠ 0 := by rwa [ne_eq, map_eq_zero_iff _ hinj]
      set c := nn.coeff qq.natDegree / qq.leadingCoeff
      set n₁ := nn - C c * qq
      have hg_sub : g - algebraMap K (RatFunc K) c = ι n₁ / ι qq := by
        rw [hgnd, ← hιC, map_sub, map_mul, sub_div, mul_div_assoc, div_self hqq', mul_one]
      have hn₁ : n₁ ≠ 0 := by
        intro h0
        apply hE
        rw [hEg]
        have hgc : g = algebraMap K (RatFunc K) c := by
          rw [← sub_eq_zero, hg_sub, h0, map_zero, zero_div]
        rw [hgc]
        exact IntermediateField.adjoin_simple_eq_bot_iff.mpr (IntermediateField.algebraMap_mem _ _)
      have hdeg₁ : n₁.natDegree < qq.natDegree := by
        rw [natDegree_lt_iff_degree_lt hn₁, degree_lt_iff_coeff_zero]
        intro m hm
        rcases hm.lt_or_eq with hm | rfl
        · simp only [n₁, coeff_sub, coeff_C_mul]
          rw [coeff_eq_zero_of_natDegree_lt (hlt.trans_lt hm),
            coeff_eq_zero_of_natDegree_lt hm, mul_zero, sub_zero]
        · have hlc : qq.coeff qq.natDegree = qq.leadingCoeff := rfl
          simp only [n₁, coeff_sub, coeff_C_mul, c, hlc]
          rw [div_mul_cancel₀ _ (leadingCoeff_ne_zero.mpr hqq), sub_self]
      have hcop₁ : IsCoprime qq n₁ := by
        have h := (RatFunc.isCoprime_num_denom g).symm.add_mul_left_right (-C c)
        have e : n₁ = g.num + g.denom * -C c := by
          change g.num - C c * g.denom = _; ring
        rwa [e]
      have hn₁' : ι n₁ ≠ 0 := by rwa [ne_eq, map_eq_zero_iff _ hinj]
      refine ⟨qq, n₁, hcop₁, hn₁, hdeg₁, ?_⟩
      have hy : ι qq / ι n₁ = (g - algebraMap K (RatFunc K) c)⁻¹ := by
        rw [hg_sub, inv_div]
      rw [hEg, hy]
      refine le_antisymm (IntermediateField.adjoin_simple_le_iff.mpr ?_)
        (IntermediateField.adjoin_simple_le_iff.mpr ?_)
      · have h2 := add_mem (inv_mem (IntermediateField.mem_adjoin_simple_self K
          (g - algebraMap K (RatFunc K) c)⁻¹)) (IntermediateField.algebraMap_mem _ c)
        rwa [inv_inv, sub_add_cancel] at h2
      · exact inv_mem (sub_mem (IntermediateField.mem_adjoin_simple_self K g)
          (IntermediateField.algebraMap_mem _ _))
  -- the denominator is constant
  have hqdeg : q.natDegree = 0 := by
    by_contra hne
    obtain ⟨x₀, hx₀⟩ := IsAlgClosed.exists_root q (by
      rw [degree_eq_natDegree hq]; exact_mod_cast hne)
    have := natDegree_eq_zero_of_mem hcop hq hdeg hx₀ (hEnq ▸ hmemE p₀ hp₀R)
    omega
  set q₀ := q.coeff 0
  have hqC : q = C q₀ := eq_C_of_natDegree_eq_zero hqdeg
  have hq₀ : q₀ ≠ 0 := fun h ↦ hq (by rw [hqC, h, C_0])
  set s := C q₀⁻¹ * n
  have hs : ι n / ι q = ι s := by
    rw [hqC, map_mul, hιC, hιC, map_inv₀, div_eq_inv_mul]
  have hsdeg : 0 < s.natDegree := by
    rw [natDegree_C_mul (inv_ne_zero hq₀)]; omega
  refine ⟨s, hsdeg, ?_, fun p hp ↦ exists_comp_of_mem hsdeg (hs ▸ hEnq ▸ hmemE p hp)⟩
  obtain ⟨r, hr, q', hq', hrq⟩ := hdivE (ι s)
    (hEnq ▸ hs ▸ IntermediateField.mem_adjoin_simple_self K _)
  have hq'0 : q' ≠ 0 := by
    rintro rfl
    rw [map_zero, div_zero, map_eq_zero_iff _ hinj] at hrq
    rw [hrq, natDegree_zero] at hsdeg
    exact lt_irrefl _ hsdeg
  refine ⟨r, hr, q', hq', hq'0, hinj ?_⟩
  rw [map_mul, hrq, div_mul_cancel₀]
  rwa [ne_eq, map_eq_zero_iff _ hinj]

end RatFuncPoly

end Uniformization
