/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Mathlib.Algebra.Category.Ring.Colimits
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Topology.Sheaves.Stalks

/-!
# The quotient of a presheaf of rings by the ideal generated by global sections

Let `F` be a presheaf of commutative rings on a topological space `X` and let `f : κ → F(⊤)` be a
family of global sections. Restricting the `f i` to an open `U` and taking the ideal they
generate defines a subpresheaf of ideals of `F`, and the quotient of `F` by it is again a
presheaf of commutative rings.

The point of this file is the computation of the stalks of that quotient: the projection
`F ⟶ F.quotientSpan f` is surjective on stalks, and the kernel of the induced map on stalks at
`y` is the ideal generated by the germs at `y` of the `f i`. Both statements are exactness of
filtered colimits in concrete form — every germ is the germ of a section, and two sections with
the same germ agree on a neighbourhood — and neither is available in Mathlib.

The quotient presheaf is a presheaf and nothing more: even when `F` is a sheaf, `F.quotientSpan f`
generally is not, since a section of the quotient given locally need not lift to a global section
of `F`. A user wanting a sheaf has to sheafify, which does not disturb the stalk computations
below.

There is no analytic content here, so this file is a candidate for upstreaming to Mathlib; it
lives in the `Oka/Topology/` mirror of the Mathlib directory tree for that reason.

## Main definitions

- `TopCat.Presheaf.spanIdeal`: the ideal of `F(U)` generated by the restrictions of the `f i`.
- `TopCat.Presheaf.quotientSpan`: the quotient presheaf `U ↦ F(U) ⧸ spanIdeal f U`.
- `TopCat.Presheaf.toQuotientSpan`: the projection `F ⟶ F.quotientSpan f`.
- `TopCat.Presheaf.quotientSpanDesc`: the universal property — a morphism out of `F` killing the
  `f i` factors through the quotient.
- `TopCat.Presheaf.stalkQuotientSpanEquiv`: the stalk of the quotient, as a quotient of the
  stalk; `TopCat.Presheaf.stalkQuotientSpanEquiv_mk` says it is the map induced by the
  projection.

## Main results

- `TopCat.Presheaf.surjective_toQuotientSpan_app`: the projection is objectwise surjective.
- `TopCat.Presheaf.surjective_stalkFunctor_map_toQuotientSpan`: it is surjective on stalks.
- `TopCat.Presheaf.ker_stalkFunctor_map_toQuotientSpan`: the kernel of the map on stalks at `y`
  is the ideal generated by the germs at `y` of the `f i`.
-/

open CategoryTheory Limits TopologicalSpace Opposite

universe v u

namespace TopCat.Presheaf

variable {X : TopCat.{u}} (F : X.Presheaf CommRingCat.{u}) {κ : Type v} (f : κ → F.obj (op ⊤))

section SpanIdeal

/-- The ideal of `F(U)` generated by the restrictions to `U` of the global sections `f i`. As `U`
varies this is a subpresheaf of ideals of `F`; `TopCat.Presheaf.spanIdeal_le_comap` is the
statement that restriction maps it into itself. -/
def spanIdeal (U : Opens X) : Ideal (F.obj (op U)) :=
  Ideal.span (Set.range fun i ↦ F.map (homOfLE (le_top : U ≤ ⊤)).op (f i))

/-- The restriction to `U` of a global section `f i` is a generator of `spanIdeal F f U`. -/
lemma res_mem_spanIdeal (U : Opens X) (i : κ) :
    F.map (homOfLE (le_top : U ≤ ⊤)).op (f i) ∈ F.spanIdeal f U :=
  Ideal.subset_span ⟨i, rfl⟩

/-- Restriction carries `spanIdeal F f` into itself: this is what makes the quotient presheaf a
presheaf. -/
lemma spanIdeal_le_comap {U V : (Opens X)ᵒᵖ} (i : U ⟶ V) :
    F.spanIdeal f U.unop ≤ (F.spanIdeal f V.unop).comap (F.map i).hom := by
  rw [spanIdeal, Ideal.span_le]
  rintro _ ⟨j, rfl⟩
  simp only [SetLike.mem_coe, Ideal.mem_comap]
  rw [← ConcreteCategory.comp_apply, ← F.map_comp]
  exact F.res_mem_spanIdeal f V.unop j

end SpanIdeal

section QuotientSpan

/-- The quotient of `F` by the subpresheaf of ideals generated by the global sections `f i`:
the presheaf of commutative rings `U ↦ F(U) ⧸ spanIdeal F f U`. -/
def quotientSpan : X.Presheaf CommRingCat.{u} where
  obj U := CommRingCat.of (F.obj U ⧸ F.spanIdeal f U.unop)
  map {_ _} i := CommRingCat.ofHom <| Ideal.Quotient.lift _
    ((Ideal.Quotient.mk _).comp (F.map i).hom) fun _ ha ↦
      Ideal.Quotient.eq_zero_iff_mem.2 (F.spanIdeal_le_comap f i ha)
  map_id _ := by ext x; simp
  map_comp _ _ := by ext x; simp

@[simp]
lemma quotientSpan_map_mk {U V : (Opens X)ᵒᵖ} (i : U ⟶ V) (s : F.obj U) :
    (F.quotientSpan f).map i (Ideal.Quotient.mk (F.spanIdeal f U.unop) s) =
      Ideal.Quotient.mk (F.spanIdeal f V.unop) (F.map i s) :=
  rfl

/-- The projection of `F` onto its quotient by the ideals generated by the `f i`. -/
def toQuotientSpan : F ⟶ F.quotientSpan f where
  app U := CommRingCat.ofHom (Ideal.Quotient.mk (F.spanIdeal f U.unop))
  naturality _ _ _ := by ext x; rfl

@[simp]
lemma toQuotientSpan_app_apply (U : (Opens X)ᵒᵖ) (s : F.obj U) :
    (F.toQuotientSpan f).app U s = Ideal.Quotient.mk (F.spanIdeal f U.unop) s :=
  rfl

/-- A morphism out of `F` that kills the global sections `f i` kills the whole subpresheaf of
ideals they generate. This is the hypothesis of `TopCat.Presheaf.quotientSpanDesc`, in the form
a caller can supply. -/
lemma spanIdeal_le_ker {G : X.Presheaf CommRingCat.{u}} (α : F ⟶ G)
    (h : ∀ i, α.app (op ⊤) (f i) = 0) (U : (Opens X)ᵒᵖ) :
    F.spanIdeal f U.unop ≤ RingHom.ker (α.app U).hom := by
  rw [spanIdeal, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  have hnat := ConcreteCategory.congr_hom (α.naturality (homOfLE (le_top (a := U.unop))).op) (f i)
  simp only [SetLike.mem_coe, RingHom.mem_ker]
  change (α.app U) (F.map (homOfLE (le_top (a := U.unop))).op (f i)) = 0
  rw [show (α.app U) (F.map (homOfLE (le_top (a := U.unop))).op (f i)) =
    G.map (homOfLE (le_top (a := U.unop))).op (α.app (op ⊤) (f i)) from hnat, h i, map_zero]

/-- **The universal property of the quotient presheaf**: a morphism out of `F` killing the ideals
generated by the `f i` factors, uniquely, through the quotient. -/
def quotientSpanDesc {G : X.Presheaf CommRingCat.{u}} (α : F ⟶ G)
    (hα : ∀ U : (Opens X)ᵒᵖ, F.spanIdeal f U.unop ≤ RingHom.ker (α.app U).hom) :
    F.quotientSpan f ⟶ G where
  app U := CommRingCat.ofHom (Ideal.Quotient.lift _ (α.app U).hom fun _ ha ↦ hα U ha)
  naturality _ _ k := by
    ext x
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective x
    exact ConcreteCategory.congr_hom (α.naturality k) x

@[simp]
lemma toQuotientSpan_comp_quotientSpanDesc {G : X.Presheaf CommRingCat.{u}} (α : F ⟶ G)
    (hα : ∀ U : (Opens X)ᵒᵖ, F.spanIdeal f U.unop ≤ RingHom.ker (α.app U).hom) :
    F.toQuotientSpan f ≫ F.quotientSpanDesc f α hα = α := by
  ext U x
  rfl

/-- The projection onto the quotient presheaf is surjective on every open set. -/
lemma surjective_toQuotientSpan_app (U : (Opens X)ᵒᵖ) :
    Function.Surjective ((F.toQuotientSpan f).app U).hom :=
  Ideal.Quotient.mk_surjective

/-- A section of `F` maps to zero in the quotient presheaf exactly when it lies in the ideal
generated by the restrictions of the `f i`. -/
lemma toQuotientSpan_app_eq_zero_iff {U : (Opens X)ᵒᵖ} (s : F.obj U) :
    (F.toQuotientSpan f).app U s = 0 ↔ s ∈ F.spanIdeal f U.unop :=
  Ideal.Quotient.eq_zero_iff_mem

end QuotientSpan

section Stalk

variable (y : X)

/-- Taking germs at `y` carries `spanIdeal F f U` into the ideal generated by the germs at `y`
of the `f i`. -/
lemma spanIdeal_le_comap_germ {U : Opens X} (hy : y ∈ U) :
    F.spanIdeal f U ≤
      (Ideal.span (Set.range fun i ↦ F.Γgerm y (f i))).comap (F.germ U y hy).hom := by
  rw [spanIdeal, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  simp only [SetLike.mem_coe, Ideal.mem_comap]
  rw [F.Γgerm_res_apply]
  exact Ideal.subset_span ⟨i, rfl⟩

/-- The map on stalks induced by the projection onto the quotient presheaf is surjective: every
germ of the quotient is the germ of a section, and every section of the quotient is locally the
class of a section of `F`. -/
theorem surjective_stalkFunctor_map_toQuotientSpan :
    Function.Surjective ((stalkFunctor CommRingCat.{u} y).map (F.toQuotientSpan f)).hom := by
  intro t
  obtain ⟨U, hy, s, rfl⟩ := (F.quotientSpan f).exists_germ_eq t
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective s
  exact ⟨F.germ U y hy s, stalkFunctor_map_germ_apply U y hy _ s⟩

/-- The kernel of the map on stalks induced by the projection onto the quotient presheaf is the
ideal generated by the germs of the `f i`.

This is the concrete form of exactness of filtered colimits: a germ dies in the quotient exactly
when the section representing it lies, on a possibly smaller neighbourhood, in the ideal
generated by the `f i`. -/
theorem ker_stalkFunctor_map_toQuotientSpan :
    RingHom.ker ((stalkFunctor CommRingCat.{u} y).map (F.toQuotientSpan f)).hom =
      Ideal.span (Set.range fun i ↦ F.Γgerm y (f i)) := by
  apply le_antisymm
  · intro t ht
    obtain ⟨U, hy, s, rfl⟩ := F.exists_germ_eq t
    rw [RingHom.mem_ker, stalkFunctor_map_germ_apply U y hy _ s] at ht
    have ht0 : (F.quotientSpan f).germ U y hy ((F.toQuotientSpan f).app (op U) s) =
        (F.quotientSpan f).germ U y hy 0 := by rw [map_zero]; exact ht
    obtain ⟨W, hyW, iU, iV, hW⟩ := (F.quotientSpan f).germ_eq y hy hy _ _ ht0
    rw [map_zero] at hW
    have hmem : F.map iU.op s ∈ F.spanIdeal f W := by
      rw [← F.toQuotientSpan_app_eq_zero_iff (U := op W)]
      have hnat : ((F.toQuotientSpan f).app (op W)) (F.map iU.op s) =
          (F.quotientSpan f).map iU.op ((F.toQuotientSpan f).app (op U) s) :=
        (ConcreteCategory.congr_hom ((F.toQuotientSpan f).naturality iU.op) s).symm
      rw [hnat, hW]
    have hspan := F.spanIdeal_le_comap_germ f y hyW hmem
    rwa [Ideal.mem_comap, F.germ_res_apply] at hspan
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨i, rfl⟩
    have h0 : ((F.toQuotientSpan f).app (op ⊤)) (f i) = 0 :=
      (F.toQuotientSpan_app_eq_zero_iff f (f i)).2 (by simpa using F.res_mem_spanIdeal f ⊤ i)
    refine RingHom.mem_ker.2 ?_
    change ((stalkFunctor CommRingCat.{u} y).map (F.toQuotientSpan f)).hom
      (F.Γgerm y (f i)) = 0
    rw [show F.Γgerm y (f i) = F.germ ⊤ y True.intro (f i) from rfl,
      stalkFunctor_map_germ_apply ⊤ y True.intro _ (f i), h0, map_zero]
    rfl

/-- The stalk of the quotient presheaf at `y` is the quotient of the stalk of `F` at `y` by the
ideal generated by the germs at `y` of the `f i`. -/
noncomputable def stalkQuotientSpanEquiv :
    (F.stalk y ⧸ Ideal.span (Set.range fun i ↦ F.Γgerm y (f i))) ≃+*
      (F.quotientSpan f).stalk y :=
  (Ideal.quotEquivOfEq (F.ker_stalkFunctor_map_toQuotientSpan f y).symm).trans
    (RingHom.quotientKerEquivOfSurjective (F.surjective_stalkFunctor_map_toQuotientSpan f y))

@[simp]
lemma stalkQuotientSpanEquiv_mk (t : F.stalk y) :
    F.stalkQuotientSpanEquiv f y (Ideal.Quotient.mk _ t) =
      (stalkFunctor CommRingCat.{u} y).map (F.toQuotientSpan f) t :=
  rfl

end Stalk

end TopCat.Presheaf
