/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.Analytification.PresentationStalk
import Oka.Analytification.FlatnessAtAPoint
import Oka.RingTheory.RingHom.FaithfullyFlat

/-!
# The stalk map of `X^an ⟶ X` is faithfully flat, for every presented affine `ℂ`-algebra

**The local input to GAGA, in the generality GAGA consumes it.**
`Oka/Analytification/FlatnessAtAPoint.lean` proves that the stalk map of the ambient comparison
morphism `ℂ^ι ⟶ 𝔸^ι_ℂ` is faithfully flat at every point. GAGA is about a scheme
`X = Spec (ℂ[x] ⧸ I)`, and what its arguments consume is the same statement for
`ComplexAnalytic.analytificationToSpec`:

```
ComplexAnalytic.faithfullyFlat_stalkMap_analytificationToSpec (y : X^an) :
  ((analytificationToSpec g).stalkMap y).hom.FaithfullyFlat
```

This is a deduction from the ambient case by base change along `ℂ[x]_q ↠ (ℂ[x] ⧸ I)_q`, not a
new analytic input: **nothing here goes near a power series.**

## The three inputs, and where each comes from

Write `z` for the point of `ℂ^n` underneath `y`. The square

```
𝒪_{Spec ℂ[x], z}  ⟶  𝒪_{ℂ^n, z}
       ↓                  ↓
𝒪_{Spec (ℂ[x]⧸I), φ y} ⟶  𝒪_{X^an, y}
```

has faithfully flat top row (the ambient case), and both verticals are surjective with the same
ideal — `I` and its image — as kernel. So the bottom row is faithfully flat by base change:

* the **source** vertical is `ComplexAnalytic.analytificationStalkQuotEquiv`
  (`Oka/Analytification/PresentationStalk.lean`): the stalk of `Spec (ℂ[x] ⧸ I)` under `y` is the
  stalk of `Spec ℂ[x]` under `y` modulo `I`, because localisation commutes with the quotient;
* the **target** vertical is `ComplexAnalytic.germQuotEquivStalk` below: the stalk of `𝒪_{X^an}`
  at `y` is the germ ring of `ℂ^n` at `z` modulo the ideal generated by the germs of the `gⱼ`.
  It is the zero locus construction's own stalk computation, transported across the stalk
  isomorphism of `(complexAffineSpace n).ofRestrict ⊤` — which is where
  `ComplexAnalytic.analytificationIncl` differs from `ComplexAnalytic.analytificationι`.
  **What is transported is the two inputs, not the conclusion**:
  `AlgebraicGeometry.LocallyRingedSpace.zeroLocusStalkQuotientEquiv` is that construction's own
  packaging of them and does not appear below, because
  `ComplexAnalytic.surjective_stalkMap_analytificationIncl` and
  `ComplexAnalytic.ker_stalkMap_analytificationIncl` transport across the isomorphism and the
  packaged equivalence does not;
* the **base change** is `RingHom.FaithfullyFlat.quotIdealMap`, the mirror-tree lemma.

## The compatibility, which is the only thing that could have been hard

A square of ring maps built from three separate identifications is worth nothing until someone
proves it commutes, and `ComplexAnalytic.stalkMap_analytificationToSpec_eq_comp` is that proof.
It is short for a structural reason: **the source of the stalk map is a localisation of
`ℂ[x] ⧸ I`**, so `IsLocalization.ringHom_ext` reduces the equality of two maps out of it to
their agreement on `ℂ[x] ⧸ I`, and `Ideal.Quotient.mk_surjective` reduces that to agreement on
`ℂ[x]`. There the two sides are
`ComplexAnalytic.toStalk_stalkMap_analytificationToSpec` on one and
`AlgebraicGeometry.LocallyRingedSpace.Γgerm_Γ_map` composed with
`ComplexAnalytic.mk_comp_quotientToGlobal` on the other — the latter proved in
`Oka/Analytification/Presentation.lean` for the statement about *points*, not for this.

## The `Ideal.span`-versus-`Ideal.map` seam, which is where the steps actually went

`AlgebraicGeometry.LocallyRingedSpace.ker_stalkMap_zeroLocusιHom` gives the kernel as
`Ideal.span (Set.range …)` of germs, while `RingHom.FaithfullyFlat.quotIdealMap` wants
`Ideal.map`. Turning one into the other is
`Ideal.map_map` and `Ideal.map_span`, as expected — but the germs in question are germs on
`complexAffineSpaceTop n`, the restriction of `ℂ^n` to `⊤`, and the flatness is about germs on
`ℂ^n`. Crossing that costs `Ideal.comap_map_of_bijective` along the stalk isomorphism of
`ofRestrict`, which is more than the two rewrites the seam was budgeted at.

## Main definitions

- `ComplexAnalytic.analytificationGermIdeal`: the ideal the presentation generates in the germ
  ring of `ℂ^n` at the point underneath `y`.
- `ComplexAnalytic.germQuotEquivStalk`: **the stalk of `𝒪_{X^an}` at `y` is the germ ring of
  `ℂ^n` at the point underneath `y`, modulo the presentation.**

## Main results

- `ComplexAnalytic.surjective_stalkMap_analytificationIncl` and
  `ComplexAnalytic.ker_stalkMap_analytificationIncl`: the map on stalks induced by the inclusion
  `X^an ↪ ℂ^n` is surjective with kernel the germs of the `gⱼ`.
- `ComplexAnalytic.stalkMap_analytificationToSpec_eq_comp`: the square commutes.
- `ComplexAnalytic.faithfullyFlat_stalkMap_analytificationToSpec` and
  `ComplexAnalytic.flat_stalkMap_analytificationToSpec`: **the conclusion.**

## What is not here

* **This is not GAGA.** It is the local input a GAGA argument consumes. Exactness of
  analytification on coherent sheaves needs, in addition, the analytification of a *sheaf* and a
  reason for the stalk of a pullback to be the base change of the stalk; neither is here.
* **Anything non-affine.** Nothing glues.
* **Anything analytic.** Every analytic fact used is upstream, in the ambient case; this file is
  localisation, quotients and base change.

## References

- [Hans Grauert and Reinhold Remmert, *Coherent analytic sheaves*][grauert-remmert1984], §A
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace

universe u

namespace ComplexAnalytic

noncomputable section

variable {n k : ℕ} (g : Fin k → MvPolynomial (ULift.{u} (Fin n)) ℂ)
  (y : AnalyticSpace.analytification.{u} g)

/-! ### The stalk map of the inclusion `X^an ↪ ℂ^n` -/

/-- The stalk isomorphism of `(complexAffineSpace n).ofRestrict ⊤` at the point underneath `y`.

`ComplexAnalytic.analytificationIncl` is `ComplexAnalytic.analytificationι` — the inclusion into
`ℂ^n` *presented as an open subspace of itself*, which is the shape the zero locus construction
works with — followed by that restriction. So every statement about the stalks of the former is
a statement about the stalks of the latter transported along this isomorphism. -/
abbrev restrictStalkHom :=
  (((complexAffineSpace.{u} n).ofRestrict
    (⊤ : Opens (complexAffineSpace.{u} n)).isOpenEmbedding).stalkMap
      ((complexAffineSpaceTop.{u} n).zeroLocusι (polySection g) y))

theorem bijective_restrictStalkHom : Function.Bijective (restrictStalkHom g y).hom :=
  haveI : IsIso (restrictStalkHom g y) := LocallyRingedSpace.ofRestrict_stalkMap_isIso _ _ _
  ConcreteCategory.bijective_of_isIso _

theorem stalkMap_analytificationIncl_eq :
    ((analytificationIncl g).stalkMap y).hom =
      ((analytificationι g).stalkMap y).hom.comp (restrictStalkHom g y).hom :=
  congrArg CommRingCat.Hom.hom (LocallyRingedSpace.stalkMap_comp _ _ y)

/-- **The map on stalks induced by the inclusion `X^an ↪ ℂ^n` is surjective**: the structure
sheaf of the analytification is a quotient of the structure sheaf of `ℂ^n`. -/
theorem surjective_stalkMap_analytificationIncl :
    Function.Surjective ((analytificationIncl g).stalkMap y).hom := by
  rw [stalkMap_analytificationIncl_eq]
  exact ((complexAffineSpaceTop.{u} n).surjective_stalkMap_zeroLocusιHom (polySection g) y).comp
    (bijective_restrictStalkHom g y).surjective

/-- **The ideal the presentation generates in the germ ring of `ℂ^n` at the point underneath
`y`.**

Spelled as the image of the image rather than as the image along
`ComplexAnalytic.germOfMvPolynomial`, because that is the shape
`RingHom.FaithfullyFlat.quotIdealMap` produces and the shape the quotient below has to have for
the flatness to apply on the nose. `ComplexAnalytic.analytificationGermIdeal_eq_span` says what
it is. -/
abbrev analytificationGermIdeal :
    Ideal ((complexSpace (ULift.{u} (Fin n))).presheaf.stalk (basePt g y)) :=
  Ideal.map (((complexSpaceToSpec (ULift.{u} (Fin n))).stalkMap (basePt g y)).hom)
    (Ideal.map (algebraMap (MvPolynomial (ULift.{u} (Fin n)) ℂ)
      (complexSpaceToSpecStalk (basePt g y))) (presentationIdeal g))

/-- **The ideal the presentation generates is generated by the germs of the `gⱼ`.** -/
theorem analytificationGermIdeal_eq_span :
    analytificationGermIdeal g y =
      Ideal.span (Set.range fun i ↦ germOfMvPolynomial (basePt g y) (g i)) := by
  rw [analytificationGermIdeal, Ideal.map_map, stalkMap_complexSpaceToSpec_comp_algebraMap,
    presentationIdeal, Ideal.map_span, ← Set.range_comp]
  rfl

/-- **The kernel of the map on stalks induced by `X^an ↪ ℂ^n` is generated by the germs of the
`gⱼ`** — a germ on `ℂ^n` dies on `X^an` exactly when it lies in the ideal the presentation
generates.

The zero locus construction proves this for `ComplexAnalytic.analytificationι`
(`AlgebraicGeometry.LocallyRingedSpace.ker_stalkMap_zeroLocusιHom`), whose ambient space is `ℂ^n`
presented as an open subspace of itself. Transporting it along
`ComplexAnalytic.restrictStalkHom` is `Ideal.comap_map_of_bijective`, and the germs match up by
`AlgebraicGeometry.LocallyRingedSpace.Γgerm_Γ_map` because
`ComplexAnalytic.polySection` *is* the pullback of a polynomial along the restriction. -/
theorem ker_stalkMap_analytificationIncl :
    RingHom.ker ((analytificationIncl g).stalkMap y).hom = analytificationGermIdeal g y := by
  have hg : ∀ i, (restrictStalkHom g y).hom (germOfMvPolynomial (basePt g y) (g i)) =
      (complexAffineSpaceTop.{u} n).presheaf.Γgerm
        ((complexAffineSpaceTop.{u} n).zeroLocusι (polySection g) y) (polySection g i) :=
    fun i ↦ (LocallyRingedSpace.Γgerm_Γ_map _ _ _).symm
  have hrange : (Set.range fun i ↦ (complexAffineSpaceTop.{u} n).presheaf.Γgerm
        ((complexAffineSpaceTop.{u} n).zeroLocusι (polySection g) y) (polySection g i)) =
      (restrictStalkHom g y).hom ''
        (Set.range fun i ↦ germOfMvPolynomial (basePt g y) (g i)) := by
    simp only [← Set.range_comp, Function.comp_def]
    exact congrArg Set.range (funext fun i ↦ (hg i).symm)
  have hker : RingHom.ker ((analytificationι g).stalkMap y).hom =
      Ideal.span (Set.range fun i ↦ (complexAffineSpaceTop.{u} n).presheaf.Γgerm
        ((complexAffineSpaceTop.{u} n).zeroLocusι (polySection g) y) (polySection g i)) :=
    (complexAffineSpaceTop.{u} n).ker_stalkMap_zeroLocusιHom (polySection g) y
  rw [stalkMap_analytificationIncl_eq]
  refine Eq.trans (RingHom.comap_ker _ _).symm ?_
  rw [hker, hrange, ← Ideal.map_span, analytificationGermIdeal_eq_span]
  exact Ideal.comap_map_of_bijective _ (bijective_restrictStalkHom g y)

/-! ### The two ends of the stalk map, and the square between them -/

/-- **The stalk of `𝒪_{X^an}` at `y` is the germ ring of `ℂ^n` at the point underneath `y`,
modulo the presentation.**

This is the identification `Oka/Analytification/PresentationStalk.lean` named as the outstanding
half of the flatness argument. It is the first isomorphism theorem applied to the two statements
above; nothing about it is a construction. -/
def germQuotEquivStalk :
    ((complexSpace (ULift.{u} (Fin n))).presheaf.stalk (basePt g y) ⧸
        analytificationGermIdeal g y) ≃+*
      (AnalyticSpace.analytification.{u} g).presheaf.stalk y :=
  (Ideal.quotEquivOfEq (ker_stalkMap_analytificationIncl g y).symm).trans
    (RingHom.quotientKerEquivOfSurjective (surjective_stalkMap_analytificationIncl g y))

/-- The isomorphism above is the map on stalks of the inclusion, on representatives.

Deliberately not `@[simp]`: its left-hand side is stated with `RingEquiv.toRingHom`, because that
is the spelling the composite in
`ComplexAnalytic.stalkMap_analytificationToSpec_eq_comp` produces, and `simp` would rewrite that
to the coercion. -/
theorem germQuotEquivStalk_mk
    (b : (complexSpace (ULift.{u} (Fin n))).presheaf.stalk (basePt g y)) :
    (germQuotEquivStalk g y).toRingHom (Ideal.Quotient.mk (analytificationGermIdeal g y) b) =
      ((analytificationIncl g).stalkMap y).hom b :=
  rfl

/-- **The two identifications agree on `ℂ[x]`**: the class of the germ of a polynomial is the
germ of the class.

This is the polynomial-level instance of the square below, and it is what makes
`ComplexAnalytic.germQuotEquivStalk` usable — without it the isomorphism identifies the stalk
with a quotient but says nothing about where any particular germ goes. -/
theorem germQuotEquivStalk_mk_germOfMvPolynomial (p : MvPolynomial (ULift.{u} (Fin n)) ℂ) :
    (germQuotEquivStalk g y).toRingHom
        (Ideal.Quotient.mk (analytificationGermIdeal g y)
          (germOfMvPolynomial (basePt g y) p)) =
      quotientToGerm g y (Ideal.Quotient.mk (presentationIdeal g) p) := by
  rw [germQuotEquivStalk_mk]
  refine Eq.trans (LocallyRingedSpace.Γgerm_Γ_map (analytificationIncl g)
    (okaGlobalOfMvPolynomial (ULift.{u} (Fin n)) p) y).symm ?_
  exact congrArg _ (congrFun (congrArg (fun f : CommRingCat.of _ ⟶ _ ↦ (f.hom : _ → _))
    (mk_comp_quotientToGlobal g).symm) p)

/-- The map on quotients induced by the ambient stalk map: the bottom row of the square in the
module docstring, before it is recognised as the stalk map of
`ComplexAnalytic.analytificationToSpec`. -/
abbrev analytificationStalkQuotMap :=
  Ideal.quotientMap (analytificationGermIdeal g y)
    (((complexSpaceToSpec (ULift.{u} (Fin n))).stalkMap (basePt g y)).hom) Ideal.le_comap_map

/-- **The stalk map of `X^an ⟶ Spec (ℂ[x] ⧸ I)` is the ambient stalk map modulo the
presentation**, read through the identifications of its two ends.

This is what makes the flatness a deduction rather than a coincidence of shapes: the three
isomorphisms of the previous section are not merely available, they fit together with the map
they are about. See the module docstring for why the proof is four rewrites — the source is a
localisation, so the two maps out of it need only be compared on `ℂ[x]`. -/
theorem stalkMap_analytificationToSpec_eq_comp :
    ((analytificationToSpec g).stalkMap y).hom =
      (germQuotEquivStalk g y).toRingHom.comp
        ((analytificationStalkQuotMap g y).comp
          (analytificationStalkQuotEquiv g y).toRingHom) := by
  refine IsLocalization.ringHom_ext ((analytificationToSpec g).base y).asIdeal.primeCompl
    (RingHom.ext fun a ↦ ?_)
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective a
  simp only [RingHom.comp_apply]
  rw [show (analytificationStalkQuotEquiv g y).toRingHom
      (algebraMap (PresentedAlgebra.{u} n k g) (analytificationToSpecStalk g y)
        (Ideal.Quotient.mk (presentationIdeal g) p)) =
      Ideal.Quotient.mk _ (algebraMap (MvPolynomial (ULift.{u} (Fin n)) ℂ)
        (complexSpaceToSpecStalk (basePt g y)) p) from AlgEquiv.commutes _ _]
  rw [algebraMap_analytificationToSpecStalk, toStalk_stalkMap_analytificationToSpec,
    Ideal.quotientMap_mk,
    show (((complexSpaceToSpec (ULift.{u} (Fin n))).stalkMap (basePt g y)).hom)
        (algebraMap (MvPolynomial (ULift.{u} (Fin n)) ℂ)
          (complexSpaceToSpecStalk (basePt g y)) p) =
      germOfMvPolynomial (basePt g y) p from
    congrFun (congrArg (fun f : _ →+* _ ↦ (f : _ → _))
      (stalkMap_complexSpaceToSpec_comp_algebraMap (basePt g y))) p]
  exact (germQuotEquivStalk_mk_germOfMvPolynomial g y p).symm

/-! ### The conclusion -/

/-- **The stalk map of the comparison morphism `X^an ⟶ Spec (ℂ[x] ⧸ I)` is faithfully flat, at
every point of `X^an` and for every presentation.**

This is the local input to GAGA in the generality GAGA consumes it, and — as at every earlier
stage of this argument — the faithfulness is free: `Module.FaithfullyFlat` is stable under
arbitrary base change, so quotienting the ambient statement by the presentation costs no
hypothesis on the ideal. **It is still the input to GAGA and not GAGA.** -/
theorem faithfullyFlat_stalkMap_analytificationToSpec :
    ((analytificationToSpec g).stalkMap y).hom.FaithfullyFlat := by
  rw [stalkMap_analytificationToSpec_eq_comp]
  exact RingHom.FaithfullyFlat.stableUnderComposition _ _
    (RingHom.FaithfullyFlat.stableUnderComposition _ _
      (RingHom.FaithfullyFlat.of_bijective
        (f := (analytificationStalkQuotEquiv g y).toRingHom)
        (analytificationStalkQuotEquiv g y).bijective)
      (RingHom.FaithfullyFlat.quotIdealMap
        (faithfullyFlat_stalkMap_complexSpaceToSpec (basePt g y)) _))
    (RingHom.FaithfullyFlat.of_bijective (f := (germQuotEquivStalk g y).toRingHom)
      (germQuotEquivStalk g y).bijective)

/-- **The stalk map of the comparison morphism `X^an ⟶ Spec (ℂ[x] ⧸ I)` is flat**, at every
point of `X^an`. -/
theorem flat_stalkMap_analytificationToSpec :
    ((analytificationToSpec g).stalkMap y).hom.Flat :=
  (faithfullyFlat_stalkMap_analytificationToSpec g y).flat

end

end ComplexAnalytic
