#!/usr/bin/env python3
"""Check that every `.lean` file under `Oka/` and `OkaTest/` has a non-empty module docstring.

Nothing else in this repository can see an empty one.  `lake build --wfail` sees only elaborated
terms and a `/-! -/` block elaborates fine; `lake lint` runs Mathlib's environment linters, which
check declarations and not files; `lake exe lint-style` checks whitespace, line endings, unicode
and module-name casing; `mk_all --check` checks imports.  `scripts/check_docstring_names.py`
checks the names *inside* docstrings against the environment, so on an empty docstring it finds
nothing to check and passes.  On 2026-08-23 seven files under `Oka/` had a module docstring
consisting of the two characters `/-!` followed by `-/`, holding 892 lines and 74 declarations
between them, and `bash .orchestra/validation.sh` exited 0 on all seven.

Usage:

    python3 scripts/check_module_docstrings.py       # check the tree
    python3 scripts/check_module_docstrings.py --self-test

Exits 0 when every file has a module docstring with a non-empty body, 1 when some do not.  It
reads text and nothing else: no build, no oleans, no `lake`.

## The rule, and deliberately only this rule

A file passes when its first `/-! … -/` block exists and its body is not whitespace.  That is
all.  In particular this does **not** require a `# Title` first line, does not look at what the
body says, and does not check that a mirror file states its destination.  A title convention
would be a second rule, would need thirteen further files looked at one by one, and would turn a
mechanical check into an argument about wording; the narrower rule is chosen on purpose and this
paragraph is here so that the narrowness does not read as an oversight.

## What is skipped, and why

The two library root modules `Oka.lean` and `OkaTest.lean` are generated by `lake exe mk_all` and
are lists of imports.  They have no docstring and should not have one — `mk_all` would drop it on
the next regeneration, and `.orchestra/validation.sh` runs `mk_all --check`, so a docstring added
to either would turn into a failure of a different check.  They are skipped by name.

Nothing else is skipped and there is no ignore file.  If a file legitimately has nothing to say,
the right answer is a sentence saying that, which is what the seven files this check was written
for now carry.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

# The two generated library root modules; see the module docstring.
SKIP = {"Oka.lean", "OkaTest.lean"}

DIRS = ("Oka", "OkaTest")

# The first module-docstring block.  Non-greedy, so it stops at the first `-/`; a module docstring
# containing a nested `/- -/` would end the match early, which can only make the body *shorter*
# and therefore cannot turn a non-empty docstring into an empty one.
MODULE_DOCSTRING = re.compile(r"/-!(.*?)-/", re.DOTALL)


def lean_files(root: Path) -> list[Path]:
    """Every `.lean` file under `Oka/` and `OkaTest/`, plus the two root modules, sorted."""
    files: list[Path] = []
    for d in DIRS:
        files += sorted((root / d).rglob("*.lean"))
    for name in sorted(SKIP):
        p = root / name
        if p.exists():
            files.append(p)
    return files


def verdict(text: str) -> str | None:
    """`None` if the file is fine, otherwise a one-line description of what is wrong."""
    m = MODULE_DOCSTRING.search(text)
    if m is None:
        return "no module docstring (`/-! … -/`) at all"
    if not m.group(1).strip():
        return "module docstring is empty"
    return None


def check(root: Path) -> int:
    bad: list[tuple[Path, str]] = []
    checked = 0
    for path in lean_files(root):
        if path.name in SKIP and path.parent == root:
            continue
        checked += 1
        why = verdict(path.read_text(encoding="utf-8"))
        if why is not None:
            bad.append((path.relative_to(root), why))
    for path, why in bad:
        print(f"{path}: {why}")
    print(f"checked {checked} files: {len(bad)} without a non-empty module docstring")
    if bad:
        print(
            "Every file under Oka/ and OkaTest/ needs a module docstring saying what it is for. "
            "See the mirror-tree section of README.md for what one on a mirror path has to claim."
        )
        return 1
    return 0


def self_test() -> int:
    """Plant each defect and confirm this script reports it.

    `.orchestra/validation.sh` records the same discipline for its own checks: a check that has
    only ever been seen to pass is not evidence of anything.  Both directions are exercised —
    a green tree passes, and each of the two defects fails — because a checker that always
    reports a failure would pass a negative test alone.
    """
    cases: list[tuple[str, str, bool]] = [
        ("a real docstring", "/-!\n# Something\n\nA sentence.\n-/\n", True),
        ("an empty docstring", "/-!\n-/\n", False),
        ("an empty one-line docstring", "/-! -/\n", False),
        ("a whitespace-only docstring", "/-!\n   \n\t\n-/\n", False),
        ("no docstring at all", "import Mathlib\n\ntheorem t : True := trivial\n", False),
        ("a declaration docstring only", "/-- Not a module docstring. -/\ndef f := 1\n", False),
    ]
    failures = 0
    for name, body, should_pass in cases:
        got = verdict(body) is None
        ok = got == should_pass
        print(f"  [{'ok' if ok else 'FAIL'}] {name}: {'passes' if got else 'fails'}")
        failures += not ok

    # And the same end to end, through `check` and its exit code, on a throwaway tree.
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "Oka").mkdir()
        (root / "OkaTest").mkdir()
        (root / "Oka" / "Good.lean").write_text("/-!\n# Good\n\nText.\n-/\n", encoding="utf-8")
        (root / "OkaTest" / "Good.lean").write_text("/-!\n# Good\n\nText.\n-/\n", encoding="utf-8")
        # The generated roots have no docstring and must not be reported.
        (root / "Oka.lean").write_text("import Oka.Good\n", encoding="utf-8")
        (root / "OkaTest.lean").write_text("import OkaTest.Good\n", encoding="utf-8")
        green = check(root)
        print(f"  [{'ok' if green == 0 else 'FAIL'}] a green tree exits 0 (got {green})")
        failures += green != 0

        (root / "Oka" / "Bad.lean").write_text("/-!\n-/\n", encoding="utf-8")
        red = check(root)
        print(f"  [{'ok' if red == 1 else 'FAIL'}] a planted empty docstring exits 1 (got {red})")
        failures += red != 1

    print("self-test failed" if failures else "self-test passed")
    return 1 if failures else 0


def main() -> int:
    if "--self-test" in sys.argv[1:]:
        return self_test()
    root = Path(
        subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    )
    return check(root)


if __name__ == "__main__":
    sys.exit(main())
