#!/usr/bin/env python3
"""Check that every `.lean` file under `Oka/` and `OkaTest/` has a non-empty module docstring.

Nothing else in this repository can see an empty one.  `lake build --wfail` sees only elaborated
terms and a `/-! -/` block elaborates fine; `lake lint` runs the environment linters, which
check declarations and not files; `lake exe lint-style` checks whitespace, line endings, unicode
and module-name casing; `mk_all --check` checks imports.  `scripts/check_docstring_names.py`
checks the names *inside* docstrings against the environment, so on an empty docstring it finds
nothing to check and passes.  On 2026-08-23 seven files under `Oka/` had a module docstring
consisting of the two characters `/-!` followed by `-/`, holding 892 lines and 74 declarations
between them, and `bash .orchestra/validation.sh` exited 0 on all seven.

Usage:

    python3 scripts/check_module_docstrings.py       # check the tree
    python3 scripts/check_module_docstrings.py --self-test

Exits 0 when every file has a module docstring with a non-empty body, 1 when some do not.  It
reads text and nothing else: no build, no oleans, no `lake`.

## The rule, and deliberately only this rule

A file passes when it has a **module** docstring whose body is not whitespace.  A `/-! … -/`
block counts as the module docstring when **both**

* nothing precedes it except comments, `module`, `prelude` and `import` lines — it stands where
  Mathlib puts a module docstring, before any content; and
* its first non-blank line is not a `##`-or-deeper markdown heading — it is not a section header.

**Both halves are needed and neither alone suffices**, which is worth stating because the obvious
implementation has only the first half or neither.  `/-! ### … -/` section headers are `/-!`
blocks too, and in this tree they are ordinary rather than exotic: **59** of the files this script
covers held one on 2026-08-23, about a third of them, and `OkaTest/FiniteMorphism.lean` has eleven
`/-!` blocks.  Two notes on that 59, both of which cost a wrong number on the way here.  A one-line
grep for `/-!` followed on the same line by `##` returns 58, because it cannot see
`Oka/LocalOkaRing.lean`, whose header is written across two lines — the count above is the one this
script's own predicate gives, which is the one the argument needs.  And there is deliberately no
denominator: the script prints it (`checked N files`) on every run, and a hardcoded copy of it went
stale in three places within a day of being written.  Taking merely "the first `/-! … -/`
block anywhere" accepts a section header found *after* declarations, which the first condition
rules out — but it also accepts one standing immediately after the imports, where the first
condition is satisfied and only the second catches it.  Under either half alone, a file in that
shape could lose its module docstring entirely and still pass, which is the defect this script
exists to make impossible.  `self_test` pins both.

In particular this does **not** require a `# Title` first line, does not look at what the
body says, and does not check that a mirror file states its destination.  **That decision is
deliberate and it is now worth a measured note**, because the original argument for it — that a
title convention would need thirteen further files looked at one by one — is no longer true:
every one of the 178 first blocks under `Oka/` and `OkaTest/` opens with a level-one `# ` heading,
so requiring one would today cost nothing.  It is still not required, because rejecting a heading
that is *too deep* is a claim about section headers, whereas requiring a heading at all is a
convention about titles, and only the first is needed to make the check sound.  The stronger rule
is one line away if a later maintainer wants it, and the number above is what they should decide
on.

## What is skipped, and why

The two library root modules `Oka.lean` and `OkaTest.lean` are generated by `lake exe mk_all` and
are lists of imports.  They have no docstring and should not have one — `mk_all` would drop it on
the next regeneration, and `.orchestra/validation.sh` runs `mk_all --check`, so a docstring added
to either would turn into a failure of a different check.  They are skipped by name.

Nothing else is skipped and there is no ignore file.  If a file legitimately has nothing to say,
the right answer is a sentence saying that, which is what the seven files this check was written
for now carry.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

# The two generated library root modules; see the module docstring.
SKIP = {"Oka.lean", "OkaTest.lean"}

DIRS = ("Oka", "OkaTest")

# The first `/-!` block.  Non-greedy, so it stops at the first `-/`; a module docstring
# containing a nested `/- -/` would end the match early, which can only make the body *shorter*
# and therefore cannot turn a non-empty docstring into an empty one.
DOC_BLOCK = re.compile(r"/-!(.*?)-/", re.DOTALL)

# What may stand before a module docstring: `module`, `prelude`, and imports.  Comments are
# removed before this is applied, so the copyright header does not need a case here.
PRELUDE = re.compile(r"^(?:module|prelude|(?:public\s+)?import\s+[\w.]+)$")

# A markdown heading of level two or deeper, as the first non-blank line of a `/-!` block: that is
# a section header, not a module docstring.  Measured on 2026-08-23 over `Oka/` and `OkaTest/`:
# of the 178 files' *first* `/-!` blocks, 178 open with a level-one `# ` heading and **none** opens
# with `##` or deeper; of the 254 *later* blocks, 252 open with `##` or deeper and the two that do
# not are continuation prose under a header in `OkaTest/Factorisation.lean`.  So the two shapes are
# perfectly separated by this line and the rule costs nothing.
SECTION_HEADER = re.compile(r"^#{2,}\s")


def strip_comments(text: str) -> str:
    """`text` with comment *contents* removed, newlines kept so line structure survives.

    Block comments nest, and `/-!` and `/--` open one like any other `/-`.  Line comments run to
    the end of the line.  This is only used on the text *before* a candidate docstring, to decide
    whether anything but imports stands there.
    """
    out: list[str] = []
    i = 0
    depth = 0
    n = len(text)
    while i < n:
        if depth == 0 and text.startswith("--", i) and not text.startswith("-/", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
            continue
        if text.startswith("/-", i):
            depth += 1
            i += 2
            continue
        if text.startswith("-/", i) and depth > 0:
            depth -= 1
            i += 2
            continue
        if depth == 0:
            out.append(text[i])
        elif text[i] == "\n":
            out.append("\n")
        i += 1
    return "".join(out)


def preceded_only_by_imports(head: str) -> str | None:
    """`None` if `head` is a legal prelude, otherwise the first line that is not."""
    for line in strip_comments(head).split("\n"):
        stripped = line.strip()
        if stripped and not PRELUDE.match(stripped):
            return stripped
    return None


def lean_files(root: Path) -> list[Path]:
    """Every `.lean` file under `Oka/` and `OkaTest/`, plus the two root modules, sorted."""
    files: list[Path] = []
    for d in DIRS:
        files += sorted((root / d).rglob("*.lean"))
    for name in sorted(SKIP):
        p = root / name
        if p.exists():
            files.append(p)
    return files


def verdict(text: str) -> str | None:
    """`None` if the file is fine, otherwise a one-line description of what is wrong."""
    m = DOC_BLOCK.search(text)
    if m is None:
        return "no module docstring (`/-! … -/`) at all"
    intruder = preceded_only_by_imports(text[: m.start()])
    if intruder is not None:
        return (
            "no module docstring: the first `/-! … -/` block is preceded by "
            f"`{intruder}`, so it comes after content and is not a module docstring"
        )
    body = m.group(1)
    if not body.strip():
        return "module docstring is empty"
    first_line = next(line.strip() for line in body.split("\n") if line.strip())
    if SECTION_HEADER.match(first_line):
        return (
            "no module docstring: the first `/-! … -/` block opens with "
            f"`{first_line}`, which is a section header and not a module docstring"
        )
    return None


def check(root: Path) -> int:
    bad: list[tuple[Path, str]] = []
    checked = 0
    for path in lean_files(root):
        if path.name in SKIP and path.parent == root:
            continue
        checked += 1
        why = verdict(path.read_text(encoding="utf-8"))
        if why is not None:
            bad.append((path.relative_to(root), why))
    for path, why in bad:
        print(f"{path}: {why}")
    print(f"checked {checked} files: {len(bad)} without a non-empty module docstring")
    if bad:
        print(
            "Every file under Oka/ and OkaTest/ needs a module docstring saying what it is for. "
            "See the mirror-tree section of README.md for what one on a mirror path has to claim."
        )
        return 1
    return 0


def self_test() -> int:
    """Plant each defect and confirm this script reports it.

    `.orchestra/validation.sh` records the same discipline for its own checks: a check that has
    only ever been seen to pass is not evidence of anything.  Both directions are exercised —
    a green tree passes, and each defect fails — because a checker that always reports a failure
    would pass a negative test alone.

    Three of the checks run this file as a *subprocess* rather than calling `check` directly.
    `main()` — resolving the repository root, and returning `check`'s exit code — is what
    `.orchestra/validation.sh` and `.github/workflows/lean_action_ci.yml` invoke and is the one
    part of this script that calling `check` cannot exercise; the comment beside those three
    records the mutation that survived every other check here until 2026-08-30.

    The `a section header and no module docstring` case is here because its absence is what let
    an earlier version of this script accept a file with no module docstring at all.  Five of the
    original six cases probed the *contents* of a `/-!` block and the sixth probed a file with no
    `/-!` anywhere; none probed a file whose only `/-!` is not a module docstring, which was the
    single shape that failed.
    """
    cases: list[tuple[str, str, bool]] = [
        ("a real docstring", "/-!\n# Something\n\nA sentence.\n-/\n", True),
        ("an empty docstring", "/-!\n-/\n", False),
        ("an empty one-line docstring", "/-! -/\n", False),
        ("a whitespace-only docstring", "/-!\n   \n\t\n-/\n", False),
        ("no docstring at all", "import Mathlib\n\ntheorem t : True := trivial\n", False),
        ("a declaration docstring only", "/-- Not a module docstring. -/\ndef f := 1\n", False),
        # The case whose absence let a file with no module docstring pass.  A `/-! ### … -/`
        # section header is a `/-!` block, so a check that takes the first one anywhere accepts
        # it.  This is an ordinary shape in this tree rather than a contrived one; the module
        # docstring has the count and says what it is and is not a count of.
        (
            "a section header and no module docstring",
            "import Mathlib\n\n/-! ### A section header -/\n\ntheorem t : True := trivial\n",
            False,
        ),
        # And the positive control for the same rule: a real module docstring followed by a
        # section header still passes, so the fix rejects the shape rather than the construct.
        (
            "a module docstring and a section header",
            "import Mathlib\n\n/-!\n# Real\n\nText.\n-/\n\n/-! ### A section -/\ndef f := 1\n",
            True,
        ),
        # A `module`/`prelude` prelude and a copyright header do not disqualify the block.
        (
            "a copyright header, `module`, and public imports",
            "/-\nCopyright.\n-/\nmodule\n\npublic import Mathlib.Tactic\n\n/-!\n# T\n\nText.\n-/\n",
            True,
        ),
    ]
    failures = 0
    for name, body, should_pass in cases:
        got = verdict(body) is None
        ok = got == should_pass
        print(f"  [{'ok' if ok else 'FAIL'}] {name}: {'passes' if got else 'fails'}")
        failures += not ok

    # And the same end to end, through `check` and its exit code, on a throwaway tree.
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "Oka").mkdir()
        (root / "OkaTest").mkdir()
        (root / "Oka" / "Good.lean").write_text("/-!\n# Good\n\nText.\n-/\n", encoding="utf-8")
        (root / "OkaTest" / "Good.lean").write_text("/-!\n# Good\n\nText.\n-/\n", encoding="utf-8")
        # The generated roots have no docstring and must not be reported.
        (root / "Oka.lean").write_text("import Oka.Good\n", encoding="utf-8")
        (root / "OkaTest.lean").write_text("import OkaTest.Good\n", encoding="utf-8")
        green = check(root)
        print(f"  [{'ok' if green == 0 else 'FAIL'}] a green tree exits 0 (got {green})")
        failures += green != 0

        (root / "Oka" / "Bad.lean").write_text("/-!\n-/\n", encoding="utf-8")
        red = check(root)
        print(f"  [{'ok' if red == 1 else 'FAIL'}] a planted empty docstring exits 1 (got {red})")
        failures += red != 1
        (root / "Oka" / "Bad.lean").unlink()

        # End to end for the section-header shape as well, because that is the one that used to
        # pass and a unit case on `verdict` alone would not have caught a `check` that filtered
        # it out on the way.
        (root / "Oka" / "Header.lean").write_text(
            "import Mathlib\n\n/-! ### A section header -/\n\ntheorem t : True := trivial\n",
            encoding="utf-8",
        )
        red = check(root)
        print(
            f"  [{'ok' if red == 1 else 'FAIL'}] a planted section-header-only file exits 1 "
            f"(got {red})"
        )
        failures += red != 1


    # The three above stop at `check`, which is not this script's entry point.  `main()` is: it
    # resolves the repository root with `git rev-parse --show-toplevel` and returns `check`'s exit
    # code, and until 2026-08-30 nothing here executed either step.  Substituting `return 0` for
    # `return check(root)` left all twelve lines above green, `.orchestra/validation.sh` at exit 0,
    # and the `checked N files` line simply absent from a run nobody reads when it passes.
    #
    # These three therefore run the file as a subprocess with no arguments, which is exactly how
    # `.orchestra/validation.sh` and `.github/workflows/lean_action_ci.yml` run it, and they assert
    # on the exit code *and* on a line of the output: an exit code alone cannot tell a check that
    # found nothing wrong from a check that looked at nothing.  `check_docstring_names.py` uses the
    # same `subprocess.run([sys.executable, __file__, ...])` idiom for its two CLI checks; this is
    # that idiom in this file's `[ok]`/`[FAIL]` style.
    #
    # The planted tree is a real `git init` because `git rev-parse --show-toplevel` is the thing
    # under test, and the last of the three runs from a subdirectory of it: the root has to come
    # from the repository *containing* the cwd and not from the cwd.  `check_docstring_names.py`
    # carries the same negative control -- `os.chdir` does not move the walk -- because that
    # script shipped with exactly this defect and its own self-test could not see it either.
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve()
        subprocess.run(["git", "init", "-q", str(root)], capture_output=True, check=True)
        (root / "Oka").mkdir()
        (root / "OkaTest").mkdir()
        (root / "Oka" / "Good.lean").write_text("/-!\n# Good\n\nText.\n-/\n", encoding="utf-8")
        (root / "OkaTest" / "Good.lean").write_text("/-!\n# G\n\nText.\n-/\n", encoding="utf-8")

        def cli(cwd: Path) -> subprocess.CompletedProcess[str]:
            """This script, run the way the two gates run it: no arguments, from `cwd`."""
            return subprocess.run(
                [sys.executable, str(Path(__file__).resolve())],
                cwd=cwd,
                capture_output=True,
                text=True,
            )

        got = cli(root)
        counted = "checked 2 files: 0 without a non-empty module docstring" in got.stdout
        ok = got.returncode == 0 and counted
        print(
            f"  [{'ok' if ok else 'FAIL'}] the CLI on a green tree exits 0 and says what it "
            f"checked (got {got.returncode}, count line {'present' if counted else 'absent'})"
        )
        failures += not ok

        (root / "Oka" / "Bad.lean").write_text("/-!\n-/\n", encoding="utf-8")
        got = cli(root)
        named = "Oka/Bad.lean: module docstring is empty" in got.stdout
        ok = got.returncode == 1 and named
        print(
            f"  [{'ok' if ok else 'FAIL'}] the CLI exits 1 on a planted defect and names it "
            f"(got {got.returncode}, defect line {'present' if named else 'absent'})"
        )
        failures += not ok

        nested = root / "Oka" / "Nested"
        nested.mkdir()
        got = cli(nested)
        named = "Oka/Bad.lean: module docstring is empty" in got.stdout
        ok = got.returncode == 1 and named
        print(
            f"  [{'ok' if ok else 'FAIL'}] the root is the repository and not the cwd: run from "
            f"Oka/Nested it still reports Oka/Bad.lean (got {got.returncode}, defect line "
            f"{'present' if named else 'absent'})"
        )
        failures += not ok

    print("self-test failed" if failures else "self-test passed")
    return 1 if failures else 0


def main() -> int:
    if "--self-test" in sys.argv[1:]:
        return self_test()
    root = Path(
        subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    )
    return check(root)


if __name__ == "__main__":
    sys.exit(main())
