/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka.Analytification.PresentationFlatness
import Oka.UFD
import OkaTest.AnalytificationStalk

/-!
# Non-vacuity of the flatness of the stalk map of `X^an ⟶ Spec (ℂ[x] ⧸ I)`

`Oka/Analytification/PresentationFlatness.lean` proves that stalk map faithfully flat, by
quotienting the ambient statement by the presentation. **If the ideal were zero the whole
argument would be the ambient case in disguise**, and a faithful-flatness statement that is
secretly about `ℂ^n ⟶ 𝔸^n` proves nothing new. This file rules that out at the node
`ℂ[x, y] ⧸ (x y)`, at the origin — the point where the node is not smooth.

## What is checked, and why it is the right thing

`OkaTest/AnalytificationStalk.lean` says explicitly what it could not test:

> the germs of `x` and `y` at the *origin* are both nonzero — so that the node's stalk there is
> not a domain. That is a statement about the target stalk `𝒪_{X^an, y}` and needs its
> identification with the germ ring modulo `I`, which is the outstanding half.

That identification is `ComplexAnalytic.germQuotEquivStalk`, and this file is that test:

* `ComplexAnalytic.not_noZeroDivisors_stalk_analytification_nodeG` — **the stalk of the node's
  structure sheaf at the origin has zero divisors.** The germs of `x` and `y` are both nonzero
  there and their product vanishes. On `ℂ²` the corresponding stalk is an integral domain, so
  this is a statement the ambient case cannot make, and it is about the *target* end of the
  stalk map rather than the source — the end that the earlier test file could not reach.
* `ComplexAnalytic.analytificationGermIdeal_nodeG_origin_ne_bot` — the ideal being quotiented by
  is not zero, which is the same degeneracy stated about the ideal rather than about the ring.

## Why the argument is short, and what it rests on

`ComplexAnalytic.injective_germOfMvPolynomial` — a nonzero polynomial has nonzero germ — is what
makes "the germ of `x` is nonzero" available at all, and it is itself a corollary of the ambient
faithful flatness. Given that, `x ∉ (x y)` in the germ ring is the usual argument in a domain:
if `x = x y c` then `x (1 - y c) = 0`, so `y` would be a unit, and `y` vanishes at the origin.
**Nothing here needs a power series or a convergence estimate**, which is the point: the
non-vacuity is as formal as the theorem it tests.
-/

open CategoryTheory Opposite AlgebraicGeometry TopologicalSpace

universe u

namespace ComplexAnalytic

noncomputable section

/-- The germ ring of `ℂ^ι` at any point is an integral domain: it is `LocalOkaRing ι`, which
`Oka/UFD.lean` proves is one.

Stated here rather than in `Oka/` because nothing under `Oka/` needs it — it is the input to the
non-vacuity argument below and to nothing else, and stating it upstream would put
`Oka/UFD.lean` into the import closure of the analytification files for that one use. -/
instance isDomain_stalk_complexSpace {ι : Type u} [Fintype ι] (z : ι → ℂ) :
    IsDomain ((complexSpace ι).presheaf.stalk z) :=
  Function.Injective.isDomain (okaStalkEquiv z).toRingHom (okaStalkEquiv z).injective

/-- **A coordinate has nonzero germ at the origin of the node.** This is
`ComplexAnalytic.injective_germOfMvPolynomial` — itself a corollary of the ambient faithful
flatness — at a coordinate function. -/
theorem germOfMvPolynomial_X_originNode_ne_zero (i : ULift.{u} (Fin 2)) :
    germOfMvPolynomial (basePt nodeG.{u} originNode.{u}) (MvPolynomial.X i) ≠ 0 := fun h ↦
  MvPolynomial.X_ne_zero i (injective_germOfMvPolynomial _ (h.trans (map_zero _).symm))

/-- A coordinate vanishes at the origin of the node — the hypothesis of the germ-unit
criterion. -/
theorem eval_basePt_originNode_X (i : ULift.{u} (Fin 2)) :
    MvPolynomial.eval (basePt nodeG.{u} originNode.{u})
      (MvPolynomial.X i : MvPolynomial (ULift.{u} (Fin 2)) ℂ) = 0 := by
  simp [basePt, originNode]

/-- The ideal the node's presentation generates in the germ ring at the origin is generated by
the germ of `x y`. -/
theorem analytificationGermIdeal_nodeG_origin :
    analytificationGermIdeal nodeG.{u} originNode.{u} =
      Ideal.span {germOfMvPolynomial (basePt nodeG.{u} originNode.{u}) nodePoly.{u}} := by
  rw [analytificationGermIdeal_eq_span]
  refine congrArg Ideal.span (Set.eq_singleton_iff_unique_mem.2 ⟨⟨0, rfl⟩, ?_⟩)
  rintro _ ⟨i, rfl⟩
  rfl

/-- **The ideal being quotiented by is not zero.** Without this the identification of
`𝒪_{X^an, y}` as a quotient would be compatible with the quotient being trivial, and the
flatness would be the ambient statement under another name. -/
theorem analytificationGermIdeal_nodeG_origin_ne_bot :
    analytificationGermIdeal nodeG.{u} originNode.{u} ≠ ⊥ := by
  intro h
  have hmem : germOfMvPolynomial (basePt nodeG.{u} originNode.{u}) nodePoly.{u} ∈
      analytificationGermIdeal nodeG.{u} originNode.{u} := by
    rw [analytificationGermIdeal_nodeG_origin]
    exact Ideal.mem_span_singleton_self _
  have hzero := Submodule.eq_bot_iff _ |>.1 h _ hmem
  rw [nodePoly, map_mul] at hzero
  exact mul_ne_zero (germOfMvPolynomial_X_originNode_ne_zero _)
    (germOfMvPolynomial_X_originNode_ne_zero _) hzero

/-- **A coordinate is not in the ideal generated by `x y`**, in the germ ring at the origin.

The argument is the one available in any domain: from `x = x y c` and `x ≠ 0` one gets
`y c = 1`, so `y` would be invertible, and a polynomial has invertible germ at the origin only
if it does not vanish there. -/
theorem germOfMvPolynomial_X_notMem_analytificationGermIdeal (i j : ULift.{u} (Fin 2))
    (hprod : nodePoly.{u} = MvPolynomial.X i * MvPolynomial.X j) :
    germOfMvPolynomial (basePt nodeG.{u} originNode.{u}) (MvPolynomial.X i) ∉
      analytificationGermIdeal nodeG.{u} originNode.{u} := by
  rw [analytificationGermIdeal_nodeG_origin]
  intro h
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.1 h
  rw [hprod, map_mul] at hc
  have key : germOfMvPolynomial (basePt nodeG.{u} originNode.{u}) (MvPolynomial.X i) *
      (1 - germOfMvPolynomial (basePt nodeG.{u} originNode.{u}) (MvPolynomial.X j) * c) = 0 := by
    rw [mul_sub, mul_one, ← mul_assoc, ← hc]; ring
  rcases mul_eq_zero.1 key with h1 | h2
  · exact germOfMvPolynomial_X_originNode_ne_zero i h1
  · exact (not_isUnit_germOfMvPolynomial_iff _ _).2 (eval_basePt_originNode_X j)
      (IsUnit.of_mul_eq_one c (by linear_combination -h2))

/-- **A coordinate has nonzero germ on the node at the origin.**

Through `ComplexAnalytic.germQuotEquivStalk` this is the previous statement: the germ of `x` on
`X^an` is the class of its germ on `ℂ²`, and the isomorphism is injective. -/
theorem quotientToGerm_nodeG_origin_X_ne_zero (i j : ULift.{u} (Fin 2))
    (hprod : nodePoly.{u} = MvPolynomial.X i * MvPolynomial.X j) :
    quotientToGerm nodeG.{u} originNode.{u}
        (Ideal.Quotient.mk (presentationIdeal nodeG.{u}) (MvPolynomial.X i)) ≠ 0 := by
  rw [← germQuotEquivStalk_mk_germOfMvPolynomial]
  intro h
  exact germOfMvPolynomial_X_notMem_analytificationGermIdeal i j hprod
    (Ideal.Quotient.eq_zero_iff_mem.1
      ((germQuotEquivStalk nodeG.{u} originNode.{u}).injective (h.trans (map_zero _).symm)))

/-- The germs of `x` and of `y` on the node multiply to zero: their product is the germ of
`x y`, which is zero in `ℂ[x, y] ⧸ (x y)`. -/
theorem quotientToGerm_nodeG_origin_mul_eq_zero :
    quotientToGerm nodeG.{u} originNode.{u}
        (Ideal.Quotient.mk (presentationIdeal nodeG.{u}) (MvPolynomial.X (ULift.up 0))) *
      quotientToGerm nodeG.{u} originNode.{u}
        (Ideal.Quotient.mk (presentationIdeal nodeG.{u}) (MvPolynomial.X (ULift.up 1))) = 0 := by
  rw [← map_mul, ← map_mul, ← nodePoly, mk_nodePoly_eq_zero_nodeG, map_zero]

/-- **The stalk of the node's structure sheaf at the origin has zero divisors.**

This is the statement `OkaTest/AnalytificationStalk.lean` named as the one it could not make.
It rules out the ideal being zero at the *target* end of the stalk map: on `ℂ²` the stalk at the
origin is an integral domain, so a development in which `I` had been accidentally trivial could
not prove this. -/
theorem not_noZeroDivisors_stalk_analytification_nodeG :
    ¬ NoZeroDivisors ((AnalyticSpace.analytification nodeG.{u}).presheaf.stalk
      originNode.{u}) := fun _ ↦ by
  rcases mul_eq_zero.1 quotientToGerm_nodeG_origin_mul_eq_zero.{u} with h | h
  · exact quotientToGerm_nodeG_origin_X_ne_zero (ULift.up 0) (ULift.up 1) rfl h
  · exact quotientToGerm_nodeG_origin_X_ne_zero (ULift.up 1) (ULift.up 0) (mul_comm _ _) h

/-- **The flatness, at an honest point of an honest presentation.** The general theorem
instantiated at the node's origin, so that it is on record that its hypotheses are satisfiable
somewhere other than at a trivial ideal. -/
theorem faithfullyFlat_stalkMap_analytificationToSpec_nodeG_origin :
    ((analytificationToSpec nodeG.{u}).stalkMap originNode.{u}).hom.FaithfullyFlat :=
  faithfullyFlat_stalkMap_analytificationToSpec nodeG.{u} originNode.{u}

end

end ComplexAnalytic
