/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka

/-!
# Non-vacuity of coherence of a quotient by a coherent subsheaf

`SheafOfModules.IsCoherent.cokernel` is stated over a small site with pullbacks and binary
products, and its analytic corollaries carry a `LocallyRingedSpace.IsCoherentStructureSheaf`
hypothesis. A statement with those hypotheses is worth nothing if they cannot be discharged, so
this file elaborates them at the sites this project actually uses: `ℂ^n`, an arbitrary complex
analytic space, and — concretely — the quotient of `𝒪_{ℂ²}` by the ideal generated by `z₀ z₁`,
whose support is the node.

Nothing here is a new theorem; the point is that each `example` is closed by a single
application, with every instance found.
-/

open CategoryTheory Limits Opposite TopologicalSpace AlgebraicGeometry ComplexAnalytic
open SheafOfModules

universe u

section ComplexSpace

variable (n : ℕ) {I : Type u} [Finite I]
  (f : I → (complexAffineSpace.{u} n).presheaf.obj (op ⊤))

/-- On `ℂ^n`, the quotient `𝒪 ⧸ (f₁, …, f_k)` is coherent. -/
example : (cokernel ((complexAffineSpace.{u} n).sectionsHom f)).IsCoherent :=
  (complexAffineSpace.{u} n).isCoherent_cokernel_sectionsHom
    (AnalyticSpace.complexAffineSpace.{u} n).isCoherentStructureSheaf f

end ComplexSpace

section AnalyticSpace

variable (X : AnalyticSpace.{u}) {I : Type u} [Finite I]
  (f : I → X.toLocallyRingedSpace.presheaf.obj (op ⊤))

/-- On an arbitrary complex analytic space the hypothesis is discharged by the main theorem. -/
example : (cokernel (X.toLocallyRingedSpace.sectionsHom f)).IsCoherent :=
  X.isCoherent_cokernel_sectionsHom f

end AnalyticSpace

section Node

/-- The one-element family `{z₀ z₁}` of global sections of `𝒪_{ℂ²}`, indexed by a type in the
universe `SheafOfModules.free` requires. -/
noncomputable def nodeFamily :
    PUnit.{u + 1} → (complexAffineSpace.{u} 2).presheaf.obj (op ⊤) :=
  fun _ ↦ OkaRing.ofMvPolynomial _ nodePoly.{u}

/-- **The quotient of `𝒪_{ℂ²}` by the ideal generated by `z₀ z₁` is coherent.**

This is the structure sheaf of the node, pushed forward to `ℂ²`; it is the first quotient of a
coherent sheaf by a coherent subsheaf in this development that is not itself a structure sheaf
of a smooth space. -/
example : (cokernel ((complexAffineSpace.{u} 2).sectionsHom nodeFamily.{u})).IsCoherent :=
  (complexAffineSpace.{u} 2).isCoherent_cokernel_sectionsHom
    (AnalyticSpace.complexAffineSpace.{u} 2).isCoherentStructureSheaf nodeFamily.{u}

end Node
