/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka

/-!
# Non-vacuity of coherence of a quotient by a coherent subsheaf

`SheafOfModules.IsCoherent.cokernel` is stated over a small site with pullbacks and binary
products, and its analytic corollaries carry a `LocallyRingedSpace.IsCoherentStructureSheaf`
hypothesis. A statement with those hypotheses is worth nothing if they cannot be discharged, so
this file elaborates them at the sites this project actually uses: `ℂ^n`, an arbitrary complex
analytic space, and — concretely — the quotient of `𝒪_{ℂ²}` by the ideal generated by `z₀ z₁`,
whose support is the node.

Nothing here is a new theorem; the point is that each `example` is closed by a single
application, with every instance found.

Elaborating the hypotheses is not enough on its own. `SheafOfModules.IsCoherent` holds of the
**zero** sheaf, so every `example` below would still be closed if `𝒪 ⧸ (f)` were `0`; that is
the same gap `OkaTest/CutOutQuotient.lean` closes for the ring-theoretic quotient. The last
section closes it here: `not_isZero_cokernel_sectionsHom_nodeFamily` shows that the quotient
of `𝒪_{ℂ²}` by the ideal generated by `z₀ z₁` is not the zero sheaf, because `z₀ z₁` vanishes
at the origin.
-/

open CategoryTheory Limits Opposite TopologicalSpace AlgebraicGeometry ComplexAnalytic
open SheafOfModules

universe u

section ComplexSpace

variable (n : ℕ) {I : Type u} [Finite I]
  (f : I → (complexAffineSpace.{u} n).presheaf.obj (op ⊤))

/-- On `ℂ^n`, the quotient `𝒪 ⧸ (f₁, …, f_k)` is coherent. -/
example : (cokernel ((complexAffineSpace.{u} n).sectionsHom f)).IsCoherent :=
  (complexAffineSpace.{u} n).isCoherent_cokernel_sectionsHom
    (AnalyticSpace.complexAffineSpace.{u} n).isCoherentStructureSheaf f

end ComplexSpace

section AnalyticSpace

variable (X : AnalyticSpace.{u}) {I : Type u} [Finite I]
  (f : I → X.toLocallyRingedSpace.presheaf.obj (op ⊤))

/-- On an arbitrary complex analytic space the hypothesis is discharged by the main theorem. -/
example : (cokernel (X.toLocallyRingedSpace.sectionsHom f)).IsCoherent :=
  X.isCoherent_cokernel_sectionsHom f

end AnalyticSpace

section Node

/-- The one-element family `{z₀ z₁}` of global sections of `𝒪_{ℂ²}`, indexed by a type in the
universe `SheafOfModules.free` requires. -/
noncomputable def nodeFamily :
    PUnit.{u + 1} → (complexAffineSpace.{u} 2).presheaf.obj (op ⊤) :=
  fun _ ↦ OkaRing.ofMvPolynomial _ nodePoly.{u}

/-- **The quotient of `𝒪_{ℂ²}` by the ideal generated by `z₀ z₁` is coherent.**

This is the structure sheaf of the node, pushed forward to `ℂ²`; it is the first quotient of a
coherent sheaf by a coherent subsheaf in this development that is not itself a structure sheaf
of a smooth space. -/
example : (cokernel ((complexAffineSpace.{u} 2).sectionsHom nodeFamily.{u})).IsCoherent :=
  (complexAffineSpace.{u} 2).isCoherent_cokernel_sectionsHom
    (AnalyticSpace.complexAffineSpace.{u} 2).isCoherentStructureSheaf nodeFamily.{u}

/-- **The quotient of `𝒪_{ℂ²}` by the ideal generated by `z₀ z₁` is not the zero sheaf.**

This is what makes the coherence statement above about something: coherence holds of the zero
sheaf, so the `example` preceding this one is, on its own, consistent with
`cokernel (sectionsHom nodeFamily)` being `0`.

The witness is the origin, where `z₀ z₁` vanishes: by
`germ_mem_maximalIdeal_iff` its germ there lies in the maximal ideal of
`𝒪_{ℂ², 0}`, which is the hypothesis of
`AlgebraicGeometry.LocallyRingedSpace.not_isZero_cokernel_sectionsHom_of_germ_mem`. -/
theorem not_isZero_cokernel_sectionsHom_nodeFamily :
    ¬ IsZero (cokernel ((complexAffineSpace.{u} 2).sectionsHom nodeFamily.{u})) :=
  (complexAffineSpace.{u} 2).not_isZero_cokernel_sectionsHom_of_germ_mem
    nodeFamily.{u} (0 : ULift.{u} (Fin 2) → ℂ) fun _ ↦
      (germ_mem_maximalIdeal_iff (U := ⊤) trivial _).2 <|
        (OkaRing.evalHom_ofMvPolynomial _ _ nodePoly.{u}).trans (by simp [nodePoly])

/-- The hypothesis of the theorem above is a real condition and not one every family satisfies:
at the point `(1, 1)`, which is off the node, the germ of `z₀ z₁` is a **unit**, so it does not
lie in the maximal ideal.

Without this the previous theorem would be open to the reading that its hypothesis is always
available, in which case it would be asserting that `𝒪 ⧸ (f)` is never zero. It is not:
`AlgebraicGeometry.LocallyRingedSpace.isZero_cokernel_sectionsHom_one` is the quotient by the
unit ideal, and it is zero. -/
example (i : PUnit.{u + 1}) :
    (complexAffineSpace.{u} 2).presheaf.germ ⊤ (fun _ ↦ (1 : ℂ)) trivial (nodeFamily.{u} i) ∉
      IsLocalRing.maximalIdeal ((complexAffineSpace.{u} 2).presheaf.stalk fun _ ↦ (1 : ℂ)) := by
  intro h
  have h0 : MvPolynomial.eval (fun _ ↦ (1 : ℂ)) nodePoly.{u} = 0 :=
    (OkaRing.evalHom_ofMvPolynomial _ _ nodePoly.{u}).symm.trans
      ((germ_mem_maximalIdeal_iff (U := ⊤) trivial _).1 h)
  simp [nodePoly] at h0

end Node
