/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka

/-!
# Non-vacuity of the completion of the germ ring

`Oka/Completion.lean` proves that `MvPowerSeries ι ℂ` is the `𝔪`-adic completion of the germ ring
`LocalOkaRing ι`, and that it is faithfully flat over it. Both statements would be true and empty
of a map nobody could compute with: an isomorphism of two `ℂ`-algebras says nothing about
convergent and formal power series unless it is *the* map induced by the inclusion, and faithful
flatness is a property of the module structure that never mentions a single power series.

So this file names two consequences on concrete elements.

* `ComplexAnalytic.symm_adicCompletionEquiv_of_coord` — the germ of the `i`-th coordinate
  function corresponds to the formal variable `X i`. This is `LocalOkaRing.toAdicCompletion_coe`
  at an element that is not `0` or `1`, and it is what says the isomorphism moves germs to the
  formal series they *are*.
* `ComplexAnalytic.exists_coord_mul_of_formal` — **a germ divisible by a coordinate in the formal
  power series is divisible by it in the germ ring**, with a convergent cofactor. This is the
  classical use of flatness: it turns a formal solution of an equation into a convergent one, and
  it is false for an arbitrary subring of `ℂ⟦X⟧`.

Neither is proved by hand: each is a general theorem of `Oka/Completion.lean` applied to an
argument, which is the point — a test that reproved its statement would be testing nothing.
-/

open IsLocalRing MvPowerSeries

universe u

namespace ComplexAnalytic

variable {ι : Type u} [Fintype ι]

/-- **The germ of a coordinate function is the formal variable**, under the identification of the
completion of the germ ring with the formal power series. -/
theorem symm_adicCompletionEquiv_of_coord (i : ι) :
    (LocalOkaRing.adicCompletionEquiv (ι := ι)).symm (AdicCompletion.of
        (maximalIdeal (LocalOkaRing ι)) (LocalOkaRing ι) (LocalOkaRing.coord i)) =
      MvPowerSeries.X i :=
  LocalOkaRing.symm_adicCompletionEquiv_of (LocalOkaRing.coord i)

/-- **A germ that is formally divisible by a coordinate is divisible by it in the germ ring**: if
a convergent power series is `Xᵢ` times a *formal* power series, then the cofactor is convergent
too.

This is `LocalOkaRing.coe_mem_map_iff` — faithful flatness of `ℂ⟦X⟧` over `ℂ{X}` — applied to the
ideal generated by one coordinate. Note what it is not: the naive argument "divide the
coefficients" proves this one particular case, but the statement holds for every finitely
generated ideal and is a theorem about flatness, not about coordinates. -/
theorem exists_coord_mul_of_formal {ι : Type u} [Finite ι] (i : ι) (P : LocalOkaRing ι)
    (h : ∃ F : MvPowerSeries ι ℂ, (P : MvPowerSeries ι ℂ) = MvPowerSeries.X i * F) :
    ∃ Q : LocalOkaRing ι, P = LocalOkaRing.coord i * Q := by
  have hmap : (Ideal.span {LocalOkaRing.coord i}).map
      (algebraMap (LocalOkaRing ι) (MvPowerSeries ι ℂ)) =
      Ideal.span {MvPowerSeries.X i} := by
    rw [Ideal.map_span]
    exact congrArg Ideal.span (by simp)
  refine Ideal.mem_span_singleton.mp
    ((LocalOkaRing.coe_mem_map_iff (Ideal.span {LocalOkaRing.coord i})).mp ?_)
  rw [hmap, Ideal.mem_span_singleton]
  exact h

end ComplexAnalytic
