/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka

/-!
# Non-vacuity of `epi ⟹ locally surjective` for sheaves of modules

`Oka/Algebra/Category/ModuleCat/Sheaf/LocallySurjective.lean` states its results over a variable
Grothendieck topology, behind `HasSheafify J AddCommGrpCat` and
`J.WEqualsLocallyBijective AddCommGrpCat`. A statement with those hypotheses is worthless if
they cannot be discharged at the site this project actually uses, so this file elaborates the
lemmas at `Opens.grothendieckTopology (TopCat.of (ι → ℂ))` and at the ring sheaf of an
arbitrary complex analytic space, against a genuine epimorphism rather than an identity: the
projection onto the quotient of `𝒪` by the ideal sheaf generated by finitely many global
sections. That is the map whose sections issue #577 has to lift on a cover.

Nothing here is a new theorem; the point is exactly that each `example` below is closed by a
single application, with every instance found.
-/

open CategoryTheory Limits Opposite TopologicalSpace AlgebraicGeometry ComplexAnalytic
open SheafOfModules

universe u

section ComplexSpace

variable (ι : Type u) [Fintype ι] {I : Type u} [Finite I]
  (f : I → (complexSpace ι).presheaf.obj (op ⊤))

/-- On `ℂ^ι`, the quotient map onto `𝒪 ⧸ (f₁, …, f_k)` is locally surjective on sections. -/
example : Sheaf.IsLocallySurjective
    ((toSheaf (complexSpace ι).ringSheaf).map (cokernel.π ((complexSpace ι).sectionsHom f))) :=
  isLocallySurjective_toSheaf_map_of_epi _

/-- The section-level form, at the same site: a section of `𝒪 ⧸ (f₁, …, f_k)` over an open set
of `ℂ^ι` is, on a covering sieve, the image of a section of `𝒪`. -/
example (Z : Opens (complexSpace ι).toTopCat)
    (b : (cokernel ((complexSpace ι).sectionsHom f)).val.obj (op Z)) :
    ∃ S : Sieve Z, S ∈ Opens.grothendieckTopology (complexSpace ι).toTopCat Z ∧
      ∀ ⦃W : Opens (complexSpace ι).toTopCat⦄ (g : W ⟶ Z), S g →
        ∃ a, (cokernel.π ((complexSpace ι).sectionsHom f)).val.app (op W) a =
          (cokernel ((complexSpace ι).sectionsHom f)).val.map g.op b :=
  exists_app_eq_of_epi _ Z b

/-- The finite-family form, at the same site: finitely many sections lift on **one** covering
sieve. This is the shape a lift of a map out of a finite free sheaf needs. -/
example {L : Type u} [Finite L] (Z : Opens (complexSpace ι).toTopCat)
    (b : L → (cokernel ((complexSpace ι).sectionsHom f)).val.obj (op Z)) :
    ∃ S : Sieve Z, S ∈ Opens.grothendieckTopology (complexSpace ι).toTopCat Z ∧
      ∀ ⦃W : Opens (complexSpace ι).toTopCat⦄ (g : W ⟶ Z), S g →
        ∀ l, ∃ a, (cokernel.π ((complexSpace ι).sectionsHom f)).val.app (op W) a =
          (cokernel ((complexSpace ι).sectionsHom f)).val.map g.op (b l) :=
  exists_forall_app_eq_of_epi _ Z b

/-- The form a lift of a map out of a finite free sheaf takes, at the same site: on a covering
sieve, everything `ψ` produces is in the image of the quotient map. This is the statement issue
#577 consumes. -/
example {L : Type u} [Finite L]
    (ψ : free (R := (complexSpace ι).ringSheaf) L ⟶ cokernel ((complexSpace ι).sectionsHom f))
    (Z : Opens (complexSpace ι).toTopCat) :
    ∃ S : Sieve Z, S ∈ Opens.grothendieckTopology (complexSpace ι).toTopCat Z ∧
      ∀ ⦃W : Opens (complexSpace ι).toTopCat⦄ (g : W ⟶ Z), S g →
        ∀ c : (free (R := (complexSpace ι).ringSheaf) L).val.obj (op W),
          ∃ a, (cokernel.π ((complexSpace ι).sectionsHom f)).val.app (op W) a =
            ψ.val.app (op W) c :=
  exists_free_app_eq_of_epi _ ψ Z

end ComplexSpace

section AnalyticSpace

variable (X : AnalyticSpace.{u}) {I : Type u} [Finite I]
  (f : I → X.toLocallyRingedSpace.presheaf.obj (op ⊤))

/-- The same on an arbitrary complex analytic space. -/
example : Sheaf.IsLocallySurjective
    ((toSheaf X.toLocallyRingedSpace.ringSheaf).map
      (cokernel.π (X.toLocallyRingedSpace.sectionsHom f))) :=
  isLocallySurjective_toSheaf_map_of_epi _

end AnalyticSpace
