/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka

/-!
# Non-vacuity of the flatness of the stalk map at a general point

`Oka/Analytification/FlatnessAtAPoint.lean` proves that the stalk map of `ℂ^ι ⟶ 𝔸^ι_ℂ` is
faithfully flat at **every** point. Two things could make that vacuous or a restatement of the
result at the origin, and this file rules out both.

* **The point matters.** At `z = 1` in one variable the coordinate `x` is *invertible* as a germ,
  and at the origin it is not: `LocalOkaRing.ofMvPolynomial` really does depend on its point, so
  `ComplexAnalytic.polyLocalToGermAt 1` is not `ComplexAnalytic.polyLocalToGerm` in disguise. The
  same in the source ring — `x` is a unit of `ComplexAnalytic.polyLocalAt 1` and a non-unit of
  `ComplexAnalytic.polyLocal (Fin 1)` — so the two localisations are not the same subring of the
  rational functions either.
* **Faithful flatness says something about elements.** It is a statement about tensoring with
  arbitrary modules, and would be equally true of a map to a ring nobody could compute in. Its
  two standard consequences are named here at a general point, including for the geometric stalk
  map itself.
-/

open AlgebraicGeometry

universe u

namespace ComplexAnalytic

variable {ι : Type u} [Fintype ι] (z : ι → ℂ)

/-! ### The point matters -/

/-- **The coordinate `x` is an invertible germ at `1` and not at the origin.** -/
theorem isUnit_ofMvPolynomial_one_X :
    IsUnit (LocalOkaRing.ofMvPolynomial (1 : Fin 1 → ℂ) (MvPolynomial.X 0)) := by
  rw [LocalOkaRing.isUnit_ofMvPolynomial_iff]
  simp

theorem not_isUnit_ofMvPolynomial_zero_X :
    ¬ IsUnit (LocalOkaRing.ofMvPolynomial (0 : Fin 1 → ℂ) (MvPolynomial.X 0)) := by
  rw [LocalOkaRing.isUnit_ofMvPolynomial_iff]
  simp

/-- **The coordinate `x` is a unit of the local ring of `𝔸¹` at `1`** — so that ring is not the
local ring at the origin. -/
theorem isUnit_algebraMap_polyLocalAt_one_X :
    IsUnit (algebraMap (MvPolynomial (Fin 1) ℂ) (polyLocalAt (1 : Fin 1 → ℂ))
      (MvPolynomial.X 0)) := by
  rw [IsLocalization.AtPrime.isUnit_to_map_iff (polyLocalAt (1 : Fin 1 → ℂ))
    (RingHom.ker (MvPolynomial.eval (1 : Fin 1 → ℂ)))]
  intro hcon
  simpa using RingHom.mem_ker.mp hcon

theorem not_isUnit_algebraMap_polyLocal_X :
    ¬ IsUnit (algebraMap (MvPolynomial (Fin 1) ℂ) (polyLocal (Fin 1)) (MvPolynomial.X 0)) := by
  rw [IsLocalization.AtPrime.isUnit_to_map_iff (polyLocal (Fin 1))
    (MvPolynomial.idealOfVars (Fin 1) ℂ)]
  intro hcon
  exact hcon (Ideal.subset_span ⟨0, rfl⟩)

/-! ### What the faithful flatness gives -/

/-- **A rational function regular at `z` is determined by its germ at `z`.** -/
theorem polyLocalToGermAt_injective : Function.Injective (polyLocalToGermAt z) := by
  letI : Algebra (polyLocalAt z) (LocalOkaRing ι) := (polyLocalToGermAt z).toRingHom.toAlgebra
  haveI : Module.FaithfullyFlat (polyLocalAt z) (LocalOkaRing ι) :=
    faithfullyFlat_polyLocalToGermAt z
  exact FaithfulSMul.algebraMap_injective (polyLocalAt z) (LocalOkaRing ι)

/-- **A rational function regular at `z` whose germ at `z` lies in an ideal of germs generated by
such functions lies in the ideal already.** -/
theorem mem_of_germ_mem_map_at (I : Ideal (polyLocalAt z)) {a : polyLocalAt z}
    (ha : polyLocalToGermAt z a ∈ I.map (polyLocalToGermAt z).toRingHom) : a ∈ I := by
  letI : Algebra (polyLocalAt z) (LocalOkaRing ι) := (polyLocalToGermAt z).toRingHom.toAlgebra
  haveI : Module.FaithfullyFlat (polyLocalAt z) (LocalOkaRing ι) :=
    faithfullyFlat_polyLocalToGermAt z
  rw [← Ideal.comap_map_eq_self_of_faithfullyFlat (B := LocalOkaRing ι) I]
  exact ha

/-- **The stalk map of `ℂ^ι ⟶ 𝔸^ι_ℂ` is injective at every point**: a section of `𝒪_{𝔸^ι}` near
the image of `z` is determined by the holomorphic germ it defines at `z`. -/
theorem stalkMap_complexSpaceToSpec_injective :
    Function.Injective ((complexSpaceToSpec ι).stalkMap z).hom :=
  (faithfullyFlat_stalkMap_complexSpaceToSpec z).injective

end ComplexAnalytic
