/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
import Oka

/-!
# Non-vacuity of the flatness of the germs over the local ring of affine space

`Oka/Analytification/Flatness.lean` proves that `ℂ{x}` is faithfully flat over `ℂ[x]_{(x)}`.
Faithful flatness is a statement about tensoring with arbitrary modules; nothing in it mentions a
single polynomial, and it would be equally true of a map to a ring nobody could compute in. This
file names two consequences on concrete elements.

* `ComplexAnalytic.polyLocalToGerm_injective` — **a rational function regular at the origin is
  determined by its germ.** Faithfully flat ring maps are injective, so the local ring of `𝔸^ι`
  at the origin really is a subring of the germ ring and the flatness is about an extension.
* `ComplexAnalytic.mem_of_germ_mem_map` — **a rational function lying in an ideal after passing
  to germs lies in it already.** This is the form the flatness is used in: it says a system of
  polynomial equations solvable by germs is solvable by rational functions regular at the origin,
  and it is the algebraic half of what makes analytification faithful.
-/

open MvPowerSeries IsLocalRing

universe u

namespace ComplexAnalytic

variable {ι : Type u} [Fintype ι]

/-- **A rational function regular at the origin is determined by its germ.** -/
theorem polyLocalToGerm_injective :
    Function.Injective (polyLocalToGerm (ι := ι)) := by
  letI : Algebra (polyLocal ι) (LocalOkaRing ι) := (polyLocalToGerm (ι := ι)).toRingHom.toAlgebra
  haveI : Module.FaithfullyFlat (polyLocal ι) (LocalOkaRing ι) := faithfullyFlat_polyLocalToGerm
  exact FaithfulSMul.algebraMap_injective (polyLocal ι) (LocalOkaRing ι)

/-- **A rational function whose germ lies in an ideal of germs generated by rational functions
lies in the ideal already.** -/
theorem mem_of_germ_mem_map (I : Ideal (polyLocal ι)) {a : polyLocal ι}
    (ha : polyLocalToGerm a ∈
      I.map (polyLocalToGerm (ι := ι)).toRingHom) : a ∈ I := by
  letI : Algebra (polyLocal ι) (LocalOkaRing ι) := (polyLocalToGerm (ι := ι)).toRingHom.toAlgebra
  haveI : Module.FaithfullyFlat (polyLocal ι) (LocalOkaRing ι) := faithfullyFlat_polyLocalToGerm
  rw [← Ideal.comap_map_eq_self_of_faithfullyFlat (B := LocalOkaRing ι) I]
  exact ha

end ComplexAnalytic
