/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
module

public import Mathlib.CategoryTheory.Limits.Constructions.Over.Products
public import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Basic
public import Oka.Algebra.Category.ModuleCat.Sheaf.Free

/-!
# A criterion for coherence

Checking that a sheaf of modules is coherent amounts to producing, locally, finitely many
generators for the sheaf of relations between finitely many sections. This file provides the
translation between such concrete data and the abstract definitions:

- `SheafOfModules.epi_kernelLift`: if every section of `P` killed by `φ : P ⟶ Q` is in the image
  of `ψ : free L ⟶ P`, then `ψ` induces an epimorphism onto `kernel φ`;
- `SheafOfModules.epi_kernelLift_of_locally`: the same conclusion under the weaker, sheaf
  theoretic hypothesis that such sections are only *locally* in the image of `ψ`;
- `SheafOfModules.isFiniteType_kernel_of_coversTop`: if, on a covering of the terminal object,
  the kernel of `φ` is generated by finitely many sections in this sense, then it is of
  finite type;
- `SheafOfModules.isCoherent_of_forall_kernel`: the resulting criterion for coherence.
-/

@[expose] public section

universe u v' u'

open CategoryTheory Limits

namespace SheafOfModules

section Epi

variable {C : Type u'} [Category.{v'} C] {J : GrothendieckTopology C} {R : Sheaf J RingCat.{u}}
  [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  {P Q : SheafOfModules.{u} R}

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}] in
lemma kernel_ι_val_app_injective (φ : P ⟶ Q) (Z : Cᵒᵖ) :
    Function.Injective ((kernel.ι φ).val.app Z) := by
  have : Mono ((evaluation R Z).map (kernel.ι φ)) :=
    Functor.map_mono (evaluation R Z) (kernel.ι φ)
  rwa [ModuleCat.mono_iff_injective] at this

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}] in
lemma val_app_apply_eq_zero_of_mem_kernel (φ : P ⟶ Q) (Z : Cᵒᵖ)
    (n : (kernel φ).val.obj Z) :
    φ.val.app Z ((kernel.ι φ).val.app Z n) = 0 := by
  have h : (kernel.ι φ ≫ φ).val.app Z n = (0 : kernel φ ⟶ Q).val.app Z n := by
    rw [kernel.condition]
  exact h

/-- If every section of `P` annihilated by `φ` is in the image of `ψ`, then the morphism
`free L ⟶ kernel φ` induced by `ψ` is an epimorphism. -/
lemma epi_kernelLift {L : Type u} (φ : P ⟶ Q) (ψ : free L ⟶ P) (hzero : ψ ≫ φ = 0)
    (hsurj : ∀ (Z : Cᵒᵖ) (b : P.val.obj Z), φ.val.app Z b = 0 →
      ∃ c, ψ.val.app Z c = b) :
    Epi (kernel.lift φ ψ hzero) := by
  refine (forget R).epi_of_epi_map (PresheafOfModules.epi_of_surjective (fun Z n ↦ ?_))
  obtain ⟨c, hc⟩ := hsurj Z _ (val_app_apply_eq_zero_of_mem_kernel φ Z n)
  refine ⟨c, kernel_ι_val_app_injective φ Z ?_⟩
  have h : (kernel.lift φ ψ hzero ≫ kernel.ι φ).val.app Z c = ψ.val.app Z c := by
    rw [kernel.lift_ι]
  exact h.trans hc

/-- The sections of `P` annihilated by `φ` are *locally* in the image of `ψ`: over every object
`Z` there is a covering sieve on which such a section becomes a section of the image of `ψ`.

This is the sheaf theoretic form of the hypothesis of `SheafOfModules.epi_kernelLift`, which
demands that the section be globally in the image. It is the form that arises in practice:
surjectivity of a map of sheaves is only ever available locally. -/
def LocallyGeneratesKernel {L : Type u} (φ : P ⟶ Q) (ψ : free L ⟶ P) : Prop :=
  ∀ (Z : C) (b : P.val.obj (Opposite.op Z)), φ.val.app (Opposite.op Z) b = 0 →
    ∃ S : Sieve Z, S ∈ J Z ∧ ∀ ⦃W : C⦄ (f : W ⟶ Z), S f →
      ∃ c, ψ.val.app (Opposite.op W) c = P.val.map f.op b

/-- A globally surjective family of relations is in particular locally surjective. -/
lemma locallyGeneratesKernel_of_forall {L : Type u} (φ : P ⟶ Q) (ψ : free L ⟶ P)
    (hsurj : ∀ (Z : Cᵒᵖ) (b : P.val.obj Z), φ.val.app Z b = 0 → ∃ c, ψ.val.app Z c = b) :
    LocallyGeneratesKernel φ ψ := by
  intro Z b hb
  refine ⟨⊤, J.top_mem Z, fun W f _ ↦ ?_⟩
  refine hsurj (Opposite.op W) _ ?_
  have h := PresheafOfModules.naturality_apply φ.val f.op b
  rw [hb, map_zero] at h
  exact h

/-- If every section of `P` annihilated by `φ` is *locally* in the image of `ψ`, then the
morphism `free L ⟶ kernel φ` induced by `ψ` is an epimorphism.

Unlike `SheafOfModules.epi_kernelLift`, this only requires local surjectivity: the induced map
onto `kernel φ` is a locally surjective morphism of sheaves, hence an epimorphism. -/
lemma epi_kernelLift_of_locally {L : Type u} (φ : P ⟶ Q) (ψ : free L ⟶ P) (hzero : ψ ≫ φ = 0)
    (hsurj : LocallyGeneratesKernel φ ψ) :
    Epi (kernel.lift φ ψ hzero) := by
  set g := kernel.lift φ ψ hzero with hgdef
  have hloc : Sheaf.IsLocallySurjective ((toSheaf R).map g) := by
    constructor
    intro Z n
    obtain ⟨S, hS, hcov⟩ := hsurj Z ((kernel.ι φ).val.app (Opposite.op Z) n)
      (val_app_apply_eq_zero_of_mem_kernel φ (Opposite.op Z) n)
    refine J.superset_covering ?_ hS
    intro W f hf
    obtain ⟨c, hc⟩ := hcov f hf
    have hlhs : (kernel.ι φ).val.app (Opposite.op W) (g.val.app (Opposite.op W) c) =
        ψ.val.app (Opposite.op W) c := by
      have h : (g ≫ kernel.ι φ).val.app (Opposite.op W) c = ψ.val.app (Opposite.op W) c := by
        rw [hgdef, kernel.lift_ι]
      exact h
    have hrhs : (kernel.ι φ).val.app (Opposite.op W) ((kernel φ).val.map f.op n) =
        P.val.map f.op ((kernel.ι φ).val.app (Opposite.op Z) n) :=
      PresheafOfModules.naturality_apply (kernel.ι φ).val f.op n
    have key : (kernel.ι φ).val.app (Opposite.op W) (g.val.app (Opposite.op W) c) =
        (kernel.ι φ).val.app (Opposite.op W) ((kernel φ).val.map f.op n) := by
      rw [hlhs, hrhs, hc]
    exact ⟨c, kernel_ι_val_app_injective φ (Opposite.op W) key⟩
  exact (toSheaf R).epi_of_epi_map inferInstance

end Epi

section Criterion

variable {C : Type u} [SmallCategory C] [HasPullbacks C] {J : GrothendieckTopology C}
  {R : Sheaf J RingCat.{u}}
  [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ (X : C), HasSheafify (J.over X) AddCommGrpCat.{u}]
  [∀ (X : C), (J.over X).WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ (X : C) (Y : Over X), HasSheafify ((J.over X).over Y) AddCommGrpCat.{u}]
  [∀ (X : C) (Y : Over X), ((J.over X).over Y).WEqualsLocallyBijective AddCommGrpCat.{u}]

/-- If, locally on a covering of the terminal object, the sections annihilated by `φ` are
generated by finitely many sections, then the kernel of `φ` is of finite type. -/
lemma isFiniteType_kernel_of_coversTop {P Q : SheafOfModules.{u} R} (φ : P ⟶ Q)
    {A : Type u} (Y : A → C) (hY : J.CoversTop Y)
    (h : ∀ a : A, ∃ (L : Type u) (_ : Finite L) (ψ : free L ⟶ P.over (Y a))
      (_ : ψ ≫ φ.over (Y a) = 0),
      ∀ (W : (Over (Y a))ᵒᵖ) (b : (P.over (Y a)).val.obj W),
        (φ.over (Y a)).val.app W b = 0 → ∃ c, ψ.val.app W c = b) :
    (kernel φ).IsFiniteType := by
  refine IsFiniteType.of_coversTop_of_forall _ Y hY (fun a ↦ ?_)
  haveI : HasBinaryProducts (Over (Y a)) :=
    Over.ConstructProducts.over_binaryProduct_of_pullback
  obtain ⟨L, _, ψ, hzero, hsurj⟩ := h a
  haveI : Epi (kernel.lift (φ.over (Y a)) ψ hzero) := epi_kernelLift _ ψ hzero hsurj
  haveI : IsFiniteType (kernel (φ.over (Y a))) :=
    IsFiniteType.of_generatingSections
      ((freeGeneratingSections L).ofEpi (kernel.lift (φ.over (Y a)) ψ hzero))
  exact IsFiniteType.of_iso (overKernelIso φ (Y a)).symm

/-- If, on a covering of the terminal object, the sections annihilated by `φ` are *locally*
generated by finitely many sections, then the kernel of `φ` is of finite type. -/
lemma isFiniteType_kernel_of_coversTop_of_locally {P Q : SheafOfModules.{u} R} (φ : P ⟶ Q)
    {A : Type u} (Y : A → C) (hY : J.CoversTop Y)
    (h : ∀ a : A, ∃ (L : Type u) (_ : Finite L) (ψ : free L ⟶ P.over (Y a))
      (_ : ψ ≫ φ.over (Y a) = 0), LocallyGeneratesKernel (φ.over (Y a)) ψ) :
    (kernel φ).IsFiniteType := by
  refine IsFiniteType.of_coversTop_of_forall _ Y hY (fun a ↦ ?_)
  haveI : HasBinaryProducts (Over (Y a)) :=
    Over.ConstructProducts.over_binaryProduct_of_pullback
  obtain ⟨L, _, ψ, hzero, hsurj⟩ := h a
  haveI : Epi (kernel.lift (φ.over (Y a)) ψ hzero) :=
    epi_kernelLift_of_locally _ ψ hzero hsurj
  haveI : IsFiniteType (kernel (φ.over (Y a))) :=
    IsFiniteType.of_generatingSections
      ((freeGeneratingSections L).ofEpi (kernel.lift (φ.over (Y a)) ψ hzero))
  exact IsFiniteType.of_iso (overKernelIso φ (Y a)).symm

variable [HasBinaryProducts C]

/-- A free sheaf of modules on a finite index type is of finite type: the tautological family
of sections generates it globally. -/
instance isFiniteType_free (I : Type u) [Finite I] : (free (R := R) I).IsFiniteType :=
  IsFiniteType.of_generatingSections (freeGeneratingSections I)

instance isFiniteType_unit : (unit R).IsFiniteType :=
  IsFiniteType.of_iso (M := free (R := R) PUnit.{u + 1}) freePUnitIso

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [HasBinaryProducts C] in
/-- A sheaf of modules of finite type all of whose sheaves of relations are, locally,
finitely generated in the concrete sense above, is coherent. -/
lemma isCoherent_of_forall_kernel {M : SheafOfModules.{u} R} [M.IsFiniteType]
    (h : ∀ (X : C) (I : Type u) (_ : Finite I) (φ : free I ⟶ M.over X),
      ∃ (A : Type u) (Y : A → Over X) (_ : (J.over X).CoversTop Y),
        ∀ a : A, ∃ (L : Type u) (_ : Finite L) (ψ : free L ⟶ (free I).over (Y a))
          (_ : ψ ≫ φ.over (Y a) = 0),
          ∀ (W : (Over (Y a))ᵒᵖ) (b : ((free I).over (Y a)).val.obj W),
            (φ.over (Y a)).val.app W b = 0 → ∃ c, ψ.val.app W c = b) :
    M.IsCoherent where
  isFiniteType := inferInstance
  hasFiniteTypeRelations X := by
    intro I _ φ
    obtain ⟨A, Y, hY, hgen⟩ := h X I ‹_› φ
    exact isFiniteType_kernel_of_coversTop φ Y hY hgen

omit [HasSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [HasBinaryProducts C] in
/-- A sheaf of modules of finite type all of whose sheaves of relations are, locally, generated
by finitely many sections in the sheaf theoretic sense, is coherent.

This is the form of `SheafOfModules.isCoherent_of_forall_kernel` that is usable in practice:
the relations only have to generate the kernel locally, not sectionwise. -/
lemma isCoherent_of_forall_kernel_of_locally {M : SheafOfModules.{u} R} [M.IsFiniteType]
    (h : ∀ (X : C) (I : Type u) (_ : Finite I) (φ : free I ⟶ M.over X),
      ∃ (A : Type u) (Y : A → Over X) (_ : (J.over X).CoversTop Y),
        ∀ a : A, ∃ (L : Type u) (_ : Finite L) (ψ : free L ⟶ (free I).over (Y a))
          (_ : ψ ≫ φ.over (Y a) = 0), LocallyGeneratesKernel (φ.over (Y a)) ψ) :
    M.IsCoherent where
  isFiniteType := inferInstance
  hasFiniteTypeRelations X := by
    intro I _ φ
    obtain ⟨A, Y, hY, hgen⟩ := h X I ‹_› φ
    exact isFiniteType_kernel_of_coversTop_of_locally φ Y hY hgen

end Criterion

end SheafOfModules
