/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
module

public import Mathlib.AlgebraicGeometry.Modules.Tilde
public import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Presentation
public import Oka.Algebra.Category.ModuleCat.Sheaf.Generators

/-!
# A module on an affine scheme and its global sections

Material for `Mathlib/AlgebraicGeometry/Modules/Tilde.lean`; see `README.md` on the mirror tree.

Mathlib proves `AlgebraicGeometry.isQuasicoherent_iff_isIso_fromTildeΓ`: an
`𝒪_{Spec R}`-module `M` is quasicoherent exactly when the counit
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ : (Γ M)^~ ⟶ M` is an isomorphism, and packages the
consequence as the equivalence `AlgebraicGeometry.tildeEquiv` between `ModuleCat R` and the
quasicoherent `𝒪_{Spec R}`-modules. This file records what that gives for the *coherent* ones,
which is the notion this repository's sheaf theory is stated in, and then two steps of the
affine-locality argument that a consumer of the dictionary needs.

`AlgebraicGeometry.Scheme.Modules.isoTildeΓ` is the first, and its content is entirely in
`SheafOfModules.IsCoherent.isQuasicoherent`; nothing about it is about `Spec`. It is stated
because the affine dictionary is quoted often enough — "a coherent sheaf on `Spec A` is a
module" — that the one-line derivation is worth having a name, and because the target
`M ≅ (Γ M)^~` is the form a consumer wants rather than `IsIso` of a counit.

## The two affine steps, and why they are here

The dictionary a consumer actually wants is "coherent sheaf on `Spec A` = finitely presented
`A`-module", and `M ≅ (Γ M)^~` is only half of it: it says nothing about `Γ M` as an `A`-module.
Getting the other half is the quasi-compactness argument on `Spec A`, and it has three steps.
The first and the third are here:

* `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections`: **a sheaf of
  finite type on `Spec R` is generated by finitely many sections over each of finitely many
  distinguished opens which span the unit ideal.** `SheafOfModules.IsFiniteType` gives generators
  over the members of *some* open covering; this replaces that covering by one of basic opens,
  using that they are a basis and that `Spec R` is quasi-compact, and moves the generators along
  with `SheafOfModules.GeneratingSections.restrict`.
* `AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`: **for a coherent
  `M`, restriction from `⊤` to `D(g)` exhibits `Γ(M, D(g))` as the localisation of `Γ M` away
  from `g`.** With the previous step this puts the hypotheses of
  `Module.Finite.of_localizationSpan_finite'` within reach: its spanning `Finset` is the first
  step's, and its `IsLocalizedModule.Away` is this.

## What is still missing, and it is one statement

> `Module.Finite Γ(Spec R, D(g)) Γ(M, D(g))` — that finitely many sections which generate `M`
> over `D(g)` **as a sheaf** generate its sections over `D(g)` **as a module**.

An epimorphism of sheaves is not surjective on sections in general; on an affine and for a
quasicoherent sheaf it is, and that is the mathematical content of the affine dictionary. Two
routes are known and neither is short: through `AlgebraicGeometry.tildeEquiv` being an
equivalence, hence reflecting epimorphisms, after reading `M` restricted to `D(g)` as a
`(Spec (Localization.Away g)).Modules`; or through stalks, using Mathlib's
`AlgebraicGeometry.tilde.toStalk` being a localisation at the prime together with
`Submodule.eq_top_of_localization_maximal`.

**Until that lands, nothing here produces a *global* presentation of `M` as a cokernel of finite
free sheaves, and nothing here shows `Γ M` finitely generated.** A consumer wanting the full
dictionary needs that step and will not find it in this repository.

## Main definitions

- `AlgebraicGeometry.Scheme.Modules.isoTildeΓ`
- `AlgebraicGeometry.Scheme.Modules.sectionsToBasicOpen`

## Main results

- `AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`
- `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections`
- `AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`, and its
  coherent corollary `…_of_isCoherent`
-/

@[expose] public section

universe u

open CategoryTheory Limits TopologicalSpace Opposite PrimeSpectrum

namespace AlgebraicGeometry.Scheme.Modules

variable {R : CommRingCat.{u}} (M : (Spec R).Modules)

/-- **A coherent `𝒪_{Spec R}`-module is `(Γ M)^~`.**

`SheafOfModules.IsCoherent.isQuasicoherent` and Mathlib's
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent`. Coherence is used only
through quasicoherence: `AlgebraicGeometry.tilde` cannot see the difference, and the finiteness
of `Γ M` that separates the two is not asserted — see the module docstring. -/
theorem isIso_fromTildeΓ_of_isCoherent [M.IsCoherent] : IsIso M.fromTildeΓ := by
  haveI := SheafOfModules.IsCoherent.isQuasicoherent M
  infer_instance

/-- **The comparison of a coherent `𝒪_{Spec R}`-module with the sheaf associated with its global
sections, as an isomorphism.** -/
noncomputable def isoTildeΓ [M.IsCoherent] :
    AlgebraicGeometry.tilde ((modulesSpecToSheaf.obj M).presheaf.obj (.op ⊤)) ≅ M :=
  haveI := isIso_fromTildeΓ_of_isCoherent M
  asIso M.fromTildeΓ

/-- **A sheaf of finite type on `Spec R` is generated by finitely many sections over each of
finitely many distinguished opens which span the unit ideal.**

`SheafOfModules.IsFiniteType` gives generators over the members of *some* open covering of
`Spec R`, and a covering is all it gives: no member need be distinguished and there need be no
finite subcovering among them. Both are repaired here, and this is the only place on this line
where quasi-compactness of `Spec R` is used.

The proof is the standard one and has no sheaf theory in it beyond the last line. Basic opens are
a basis (`PrimeSpectrum.isBasis_basic_opens`), so every point has a `D(g)` inside a member of the
given covering; those `D(g)` cover, so their `g` span the unit ideal
(`PrimeSpectrum.iSup_basicOpen_eq_top_iff`); and `1` lies in the span of a finite subset
(`Submodule.mem_span_finite_of_mem_span`), which is the finite subcovering. The generators are
carried from the member of the original covering to the `D(g)` inside it by
`SheafOfModules.GeneratingSections.restrict`.

**The `Finset` is the shape `Module.Finite.of_localizationSpan_finite'` consumes**, which is why
the statement is phrased with one rather than with a finite open covering. -/
theorem exists_finset_basicOpen_generatingSections [M.IsFiniteType] :
    ∃ s : Finset R, Ideal.span (s : Set R) = ⊤ ∧
      ∀ g ∈ s, ∃ σ : (M.over (PrimeSpectrum.basicOpen g)).GeneratingSections, σ.IsFiniteType := by
  obtain ⟨σ, hσ⟩ := SheafOfModules.IsFiniteType.exists_localGeneratorsData.{u, u} M
  have hcov : ⨆ i, σ.X i = ⊤ := (Opens.coversTop_iff (U := σ.X) _).1 σ.coversTop
  have htop : (⨆ g : {g : R // ∃ i, (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ σ.X i},
      (PrimeSpectrum.basicOpen g.1 : (Spec R).Opens)) = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hx : x ∈ ⨆ i, σ.X i := by rw [hcov]; trivial
    obtain ⟨i, hi⟩ := Opens.mem_iSup.1 hx
    obtain ⟨V, ⟨g, rfl⟩, hxV, hV⟩ :=
      Opens.isBasis_iff_nbhd.1 PrimeSpectrum.isBasis_basic_opens hi
    exact Opens.mem_iSup.2 ⟨⟨g, i, hV⟩, hxV⟩
  rw [PrimeSpectrum.iSup_basicOpen_eq_top_iff] at htop
  obtain ⟨s, hsub, hs1⟩ :=
    Submodule.mem_span_finite_of_mem_span ((Ideal.eq_top_iff_one _).1 htop)
  refine ⟨s, (Ideal.eq_top_iff_one _).2 hs1, fun g hg ↦ ?_⟩
  obtain ⟨⟨g', i, hi⟩, rfl⟩ := hsub hg
  haveI := hσ.isFiniteType i
  exact ⟨SheafOfModules.GeneratingSections.restrict.{u} (homOfLE hi) (σ.generators i),
    inferInstance⟩

/-- **Restriction of a section of `M` from the whole of `Spec R` to a distinguished open.**

Named because it is the map the localisation statement below is about, and because spelling it
out at a call site costs three lines. It is the presheaf of `R`-modules underlying `M`, applied
to `D(g) ≤ ⊤`; note that this is `AlgebraicGeometry.modulesSpecToSheaf`'s presheaf, valued in
`ModuleCat R`, and not `AlgebraicGeometry.Scheme.Modules.presheaf`, which is valued in abelian
groups and carries the `Γ(Spec R, U)`-module structure instead. The two have the same underlying
type, by `rfl`, and different `Module` instances; a statement about one is not found at the
other. -/
noncomputable abbrev sectionsToBasicOpen (g : R) :
    (modulesSpecToSheaf.obj M).presheaf.obj (op ⊤) ⟶
      (modulesSpecToSheaf.obj M).presheaf.obj (op (PrimeSpectrum.basicOpen g)) :=
  (modulesSpecToSheaf.obj M).presheaf.map
    (homOfLE (le_top : (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ ⊤)).op

/-- **For a coherent `M`, restriction to `D(g)` exhibits `Γ(M, D(g))` as the localisation of
`Γ M` away from `g`.**

For `M = N^~` this is Mathlib's instance on `AlgebraicGeometry.tilde.toOpen`, and
`AlgebraicGeometry.Scheme.Modules.toOpen_fromTildeΓ_app` says that `toOpen` followed by the
counit *is* the restriction map. Coherence enters only through
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`, which makes that counit an
isomorphism, and an isomorphism composed after a localisation map is again one
(`IsLocalizedModule.of_linearEquiv`).

**Stated for quasicoherent and not for coherent `M`.** Only quasicoherence is used, it is the
weaker hypothesis, and it is the one this repository can currently *instantiate* on a `Spec`:
`OkaTest/AffineSections.lean` exercises this at `𝒪_{Spec A} ⧸ (x)`, whereas no sheaf on a `Spec`
is proved coherent anywhere here. The coherent case is
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen_of_isCoherent`.

`AlgebraicGeometry.tilde.toOpen`'s localisation instance has to be supplied to
`IsLocalizedModule.of_linearEquiv` explicitly. Leaving it to be inferred fails: the goal is
stated in terms of `ModuleCat.Hom.hom` and search reduces it to the raw field
`ModuleCat.Hom.hom'`, at which the instance is not found. -/
theorem isLocalizedModule_away_sectionsToBasicOpen [M.IsQuasicoherent] (g : R) :
    IsLocalizedModule.Away g (sectionsToBasicOpen M g).hom := by
  haveI := isIso_fromTildeΓ_of_isQuasicoherent M
  haveI : IsIso ((modulesSpecToSheaf.map M.fromTildeΓ).hom.app (op (PrimeSpectrum.basicOpen g))) :=
    inferInstance
  rw [show sectionsToBasicOpen M g =
      tilde.toOpen ((modulesSpecToSheaf.obj M).presheaf.obj (op ⊤)) (PrimeSpectrum.basicOpen g) ≫
        (modulesSpecToSheaf.map M.fromTildeΓ).hom.app (op (PrimeSpectrum.basicOpen g)) from
    (toOpen_fromTildeΓ_app M (PrimeSpectrum.basicOpen g)).symm]
  exact IsLocalizedModule.of_linearEquiv (Submonoid.powers g)
    (tilde.toOpen ((modulesSpecToSheaf.obj M).presheaf.obj (op ⊤)) (PrimeSpectrum.basicOpen g)).hom
    (asIso ((modulesSpecToSheaf.map M.fromTildeΓ).hom.app
      (op (PrimeSpectrum.basicOpen g)))).toLinearEquiv

/-- **The coherent case of
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`.**

Coherence enters only through `SheafOfModules.IsCoherent.isQuasicoherent`. Stated separately, and
**not as an instance**, for the reason `SheafOfModules.IsCoherent.isFinitePresentation` gives:
`SheafOfModules.IsCoherent` is not a class instance search should be running from, and an
instance here would start such a search at every `IsLocalizedModule.Away` goal. -/
theorem isLocalizedModule_away_sectionsToBasicOpen_of_isCoherent [M.IsCoherent] (g : R) :
    IsLocalizedModule.Away g (sectionsToBasicOpen M g).hom :=
  haveI := SheafOfModules.IsCoherent.isQuasicoherent M
  isLocalizedModule_away_sectionsToBasicOpen M g

end AlgebraicGeometry.Scheme.Modules
