/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
module

public import Mathlib.AlgebraicGeometry.Modules.Tilde
public import Mathlib.RingTheory.Localization.Finiteness
public import Mathlib.RingTheory.LocalProperties.FinitePresentation
public import Mathlib.Algebra.Module.FinitePresentation
public import Oka.AlgebraicGeometry.Modules.Sheaf
public import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Presentation
public import Oka.Algebra.Category.ModuleCat.Sheaf.Generators

/-!
# A module on an affine scheme and its global sections

Material for `Mathlib/AlgebraicGeometry/Modules/Tilde.lean`; see `README.md` on the mirror tree.
That file does not currently import `Mathlib.RingTheory.Localization.Finiteness` or
`Mathlib.RingTheory.LocalProperties.FinitePresentation`, which the two change-of-site arguments
below need, so upstreaming it adds those imports — three files to its closure.

Mathlib proves `AlgebraicGeometry.isQuasicoherent_iff_isIso_fromTildeΓ`: an
`𝒪_{Spec R}`-module `M` is quasicoherent exactly when the counit
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ : (Γ M)^~ ⟶ M` is an isomorphism, and packages the
consequence as the equivalence `AlgebraicGeometry.tildeEquiv` between `ModuleCat R` and the
quasicoherent `𝒪_{Spec R}`-modules. This file records what that gives for the *coherent* ones,
which is the notion this repository's sheaf theory is stated in, and then two steps of the
affine-locality argument that a consumer of the dictionary needs.

`AlgebraicGeometry.Scheme.Modules.isoTildeΓ` is the first, and its content is entirely in
`SheafOfModules.IsCoherent.isQuasicoherent`; nothing about it is about `Spec`. It is stated
because the affine dictionary is quoted often enough — "a coherent sheaf on `Spec A` is a
module" — that the one-line derivation is worth having a name, and because the target
`M ≅ (Γ M)^~` is the form a consumer wants rather than `IsIso` of a counit.

## The two affine steps, and why they are here

The dictionary a consumer actually wants is "coherent sheaf on `Spec A` = finitely presented
`A`-module", and `M ≅ (Γ M)^~` is only half of it: it says nothing about `Γ M` as an `A`-module.
Getting the other half is the quasi-compactness argument on `Spec A`, and it has three steps.
All three are here, and so is their conclusion. The first and the third are the local ones:

* `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections`: **a sheaf of
  finite type on `Spec R` is generated by finitely many sections over each of finitely many
  distinguished opens which span the unit ideal.** `SheafOfModules.IsFiniteType` gives generators
  over the members of *some* open covering; this replaces that covering by one of basic opens,
  using that they are a basis and that `Spec R` is quasi-compact, and moves the generators along
  with `SheafOfModules.GeneratingSections.restrict`.
* `AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`: **for a coherent
  `M`, restriction from `⊤` to `D(g)` exhibits `Γ(M, D(g))` as the localisation of `Γ M` away
  from `g`.** With the previous step this puts the hypotheses of
  `Module.Finite.of_localizationSpan_finite'` within reach: its spanning `Finset` is the first
  step's, and its `IsLocalizedModule.Away` is this.

## The second step, and the change of site that finishes the argument

The mathematical content of the affine dictionary is that **an epimorphism of quasicoherent
sheaves on `Spec R` is surjective on global sections**, which is false for sheaves of modules in
general. That is `AlgebraicGeometry.Scheme.Modules.surjective_moduleSpecΓFunctor_map`:
`AlgebraicGeometry.tildeEquiv` is an *equivalence*, so it carries the epimorphism to a surjection
of `R`-modules. No cohomology and no stalks are needed — the vanishing that would otherwise be
required is already inside the statement that the counit is an isomorphism.

Its corollary `AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj` is the `⊤`
case: finitely many **global** sections generating `M` as a sheaf generate `Γ M` as a module. What
the argument consumes is the same statement over a distinguished open, where the generating family
supplied by `SheafOfModules.IsFiniteType` actually lives, and that is a **change of site**, since
`D(g)` is an affine *scheme* rather than a `Spec` on the nose.

It is done here, in three statements of increasing specificity:

* `AlgebraicGeometry.Scheme.Modules.module_finite_Γ_of_isAffine` — the statement at an arbitrary
  **affine scheme**, by `AlgebraicGeometry.Scheme.isoSpec`. This is more than the argument needs
  and is the shape at which the transport is actually short.
* `AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_isAffineOpen` — the statement at an
  affine **open** of an arbitrary scheme, which is the form that accepts generating sections of
  `M.over U` rather than of a module on a scheme.
* `AlgebraicGeometry.Scheme.Modules.module_finite_sections_basicOpen` — the `D(g)` case.

**Every transport in it is a change of the ring acting on a fixed carrier**, never a map of
carriers: `AlgebraicGeometry.Scheme.Modules.restrict_obj` is `rfl` and
`AlgebraicGeometry.Scheme.Modules.restrictAppIso` is `Iso.refl`, so what differs between
`Γ(M.restrict f, U)` and `Γ(M, f ''ᵁ U)` is only which ring acts, matched by
`AlgebraicGeometry.Scheme.Hom.appIso`. `Module.Finite.of_ringEquiv` is that situation and is
what does the work, through
`AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_restrict`.

**The two parts an earlier version of this docstring listed as unmeasured are in Mathlib**, and
saying which is the point of this paragraph: that `AlgebraicGeometry.Scheme.Modules.restrict`
preserves quasicoherence is the instance
`AlgebraicGeometry.Scheme.Modules.isQuasicoherent_restrictFunctor`, and the comparison between the
slice site `Over U` and the open subscheme's own site is the equivalence
`AlgebraicGeometry.Scheme.Modules.overEquiv`, with
`AlgebraicGeometry.Scheme.Modules.overFunctorEquiv` identifying `overFunctor ⋙ overEquiv.functor`
with `restrictFunctor U.ι`. Only the unit comparison and the generating-sections transport had to
be written, and they are in `Oka/AlgebraicGeometry/Modules/Sheaf.lean`.

## The conclusion

`AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj_of_isFiniteType`: **the
global sections of a quasicoherent sheaf of finite type on `Spec R` are a finite `R`-module.** The
three steps are assembled by `Module.Finite.of_localizationSpan_finite'`, with
`AlgebraicGeometry.Scheme.Modules.isScalarTower_sections` supplying the compatibility between the
`R`-action and the `Γ(Spec R, D(g))`-action on `Γ(M, D(g))` that it asks for.

Coherence is used nowhere on this line, so every statement is at
`SheafOfModules.IsQuasicoherent` plus `SheafOfModules.IsFiniteType`, which is why
`OkaTest/AffineSections.lean` can instantiate them. **This sentence used to give a second reason
— that coherence was not available at all, nothing in this repository proving a sheaf on a `Spec`
coherent — and that half is retired**: `AlgebraicGeometry.isCoherentStructureSheaf_spec`, in
`Oka/SchemeCoherent.lean`, proves `𝒪_{Spec A}` coherent for noetherian `A`. The hypotheses here
are unchanged, because they are the weaker ones and the ones the proofs use.

## Finite presentation, and a correction

An earlier version of this docstring said that `Module.FinitePresentation R (Γ M)` *"needs the same
argument run again on the relations"*. **Both halves of that were wrong**, and the second is the
one that matters:

* **It is not available at the same hypotheses.** `Module.FinitePresentation R (Γ M)` is **false**
  for `M` merely quasicoherent and of finite type. Take `R` non-noetherian and `I ⊆ R` an ideal
  that is not finitely generated; `M := (R ⧸ I)^~` is quasicoherent, is generated by the single
  global section `1`, and `Γ M = R ⧸ I` is cyclic — hence finite — and not finitely presented,
  precisely because `I` is not finitely generated. That is mathematics and is not formalised here;
  it is recorded, as `Oka/AnalyticSpace/Finite.lean` records `Spec k ⟶ Spec K`, because it is the
  reason the hypothesis below is what it is.
* **It is not the same argument.** `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ` takes a
  *global* `SheafOfModules.Presentation` that is finite on both sides, and the proof is not a
  re-run of the finite-type one: it never takes a kernel in the sheaf category and never uses
  right-exactness of `Γ`. Mathlib's `AlgebraicGeometry.isIso_fromTildeΓ_of_presentation` already
  builds a map `(K →₀ R) ⟶ (I →₀ R)` of `R`-modules out of the presentation, by
  `(tilde.functor R).preimage`, and exhibits `M` as the tilde of its cokernel; all that is added
  here is to keep that map instead of discarding it.

## The local statement, which is the one Mathlib's class asks for

`AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ_of_isFinitePresentation`: **the global
sections of a sheaf on `Spec R` of finite presentation are a finitely presented `R`-module**, at
Mathlib's `SheafOfModules.IsFinitePresentation` — the class asserting a finite presentation over
the members of *some* covering rather than a global one. It is the finite-
presentation analogue of
`AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj_of_isFiniteType`, and it is
assembled the same way, out of the same three pieces with `Module.Finite` replaced by
`Module.FinitePresentation` throughout:

* `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_presentation` refines the covering the
  class supplies to finitely many `D(g)` spanning the unit ideal, carrying the *presentations*
  along by `SheafOfModules.Presentation.restrict`;
* `AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_basicOpen` is the change of site,
  through `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ_of_isAffine` and
  `AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_of_isAffineOpen`;
* `Module.FinitePresentation.of_localizationSpan'` assembles them, at the same choice of localised
  ring — `Γ(Spec R, D(g))` — and the same `IsLocalizedModule` instance as the finite-type
  argument.

**It strictly generalises the global statement**, and not only informally:
`SheafOfModules.Presentation.isFinitePresentation` turns a finite global presentation into the
class, so `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ` is its specialisation. The
global one is kept because the local one is proved *through* it — the affine step of the change of
site is `finitePresentation_Γ` at a restricted presentation — and because it is the form a caller
holding a presentation wants.

**Two things this cost that the finite-type argument did not.** Neither was in Mathlib and both
are in the mirror tree: `SheafOfModules.Presentation.restrict`, the presentation-level analogue of
`SheafOfModules.GeneratingSections.restrict`; and `Module.FinitePresentation.of_ringEquiv`, the
sibling of `Module.Finite.of_ringEquiv` — whose proof is *not* the same, since
`Module.FinitePresentation` has no `of_restrictScalars` to reduce to. Both are recorded where they
would go upstream and both say so.

## And the converse, which closes the dictionary

`AlgebraicGeometry.Scheme.Modules.exists_isFinite_presentation` goes back: a **quasicoherent** `M`
on `Spec R` with `Module.FinitePresentation R (Γ M)` has a finite global
`SheafOfModules.Presentation`. So for quasicoherent sheaves on a `Spec` the two conditions on this
line — a finite global presentation, and finite presentation of the module of global sections —
are the same condition, and the coherent corollary
`AlgebraicGeometry.Scheme.Modules.exists_isFinite_presentation_of_isCoherent` is the whole affine
half of the dictionary in one statement.

**Quasicoherence is not removable and is not a technical hypothesis.** It is what makes
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ` an isomorphism, and without `M ≅ (Γ M)^~` a
presentation of `(Γ M)^~` says nothing about `M`.

The section docstring on `### Back up` says what the proof is; the short version is that
`Module.FinitePresentation` is *defined* by exactly the two sets
`AlgebraicGeometry.presentationTilde` asks for, so there is no construction to do.

## Main definitions

- `AlgebraicGeometry.Scheme.Modules.isoTildeΓ`
- `AlgebraicGeometry.Scheme.Modules.sectionsToBasicOpen`
- `AlgebraicGeometry.Scheme.Modules.freeΓIso`

## Main results

- `AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`
- `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections`
- `AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`, and its
  coherent corollary `…_of_isCoherent`
- `AlgebraicGeometry.Scheme.Modules.surjective_moduleSpecΓFunctor_map`, and its corollary
  `AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj`
- `AlgebraicGeometry.Scheme.Modules.module_finite_Γ_of_isAffine`,
  `AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_isAffineOpen` and
  `AlgebraicGeometry.Scheme.Modules.module_finite_sections_basicOpen`: the change of site
- `AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj_of_isFiniteType`: the
  affine-locality argument, assembled
- `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ`: **a sheaf on `Spec R` with a finite
  global presentation has finitely presented global sections**, and the correction that finite
  type is not enough for it
- `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_presentation`
- `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ_of_isAffine`,
  `AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_of_isAffineOpen` and
  `AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_basicOpen`: the change of site,
  again
- `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ_of_isFinitePresentation`: **the global
  sections of a sheaf of finite presentation on `Spec R` are a finitely presented `R`-module**
- `AlgebraicGeometry.Scheme.Modules.exists_isFinite_presentation`: **the converse**, for a
  quasicoherent sheaf, and with it
  `AlgebraicGeometry.Scheme.Modules.exists_isFinite_presentation_of_isCoherent`: **a coherent
  sheaf on `Spec R` has a finite global presentation**
-/

@[expose] public section

universe u

open CategoryTheory Limits TopologicalSpace Opposite PrimeSpectrum

namespace AlgebraicGeometry.Scheme.Modules

variable {R : CommRingCat.{u}} (M : (Spec R).Modules)

/-- **A coherent `𝒪_{Spec R}`-module is `(Γ M)^~`.**

`SheafOfModules.IsCoherent.isQuasicoherent` and Mathlib's
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent`. Coherence is used only
through quasicoherence: `AlgebraicGeometry.tilde` cannot see the difference, and the finiteness
of `Γ M` that separates the two is not asserted — see the module docstring. -/
theorem isIso_fromTildeΓ_of_isCoherent [M.IsCoherent] : IsIso M.fromTildeΓ := by
  haveI := SheafOfModules.IsCoherent.isQuasicoherent M
  infer_instance

/-- **The comparison of a coherent `𝒪_{Spec R}`-module with the sheaf associated with its global
sections, as an isomorphism.** -/
noncomputable def isoTildeΓ [M.IsCoherent] :
    AlgebraicGeometry.tilde ((modulesSpecToSheaf.obj M).presheaf.obj (.op ⊤)) ≅ M :=
  haveI := isIso_fromTildeΓ_of_isCoherent M
  asIso M.fromTildeΓ

/-- **A sheaf of finite type on `Spec R` is generated by finitely many sections over each of
finitely many distinguished opens which span the unit ideal.**

`SheafOfModules.IsFiniteType` gives generators over the members of *some* open covering of
`Spec R`, and a covering is all it gives: no member need be distinguished and there need be no
finite subcovering among them. Both are repaired here, and this is the only place on this line
where quasi-compactness of `Spec R` is used.

The proof is the standard one and has no sheaf theory in it beyond the last line. Basic opens are
a basis (`PrimeSpectrum.isBasis_basic_opens`), so every point has a `D(g)` inside a member of the
given covering; those `D(g)` cover, so their `g` span the unit ideal
(`PrimeSpectrum.iSup_basicOpen_eq_top_iff`); and `1` lies in the span of a finite subset
(`Submodule.mem_span_finite_of_mem_span`), which is the finite subcovering. The generators are
carried from the member of the original covering to the `D(g)` inside it by
`SheafOfModules.GeneratingSections.restrict`.

**The `Finset` is the shape `Module.Finite.of_localizationSpan_finite'` consumes**, which is why
the statement is phrased with one rather than with a finite open covering. -/
theorem exists_finset_basicOpen_generatingSections [M.IsFiniteType] :
    ∃ s : Finset R, Ideal.span (s : Set R) = ⊤ ∧
      ∀ g ∈ s, ∃ σ : (M.over (PrimeSpectrum.basicOpen g)).GeneratingSections, σ.IsFiniteType := by
  obtain ⟨σ, hσ⟩ := SheafOfModules.IsFiniteType.exists_localGeneratorsData.{u, u} M
  have hcov : ⨆ i, σ.X i = ⊤ := (Opens.coversTop_iff (U := σ.X) _).1 σ.coversTop
  have htop : (⨆ g : {g : R // ∃ i, (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ σ.X i},
      (PrimeSpectrum.basicOpen g.1 : (Spec R).Opens)) = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hx : x ∈ ⨆ i, σ.X i := by rw [hcov]; trivial
    obtain ⟨i, hi⟩ := Opens.mem_iSup.1 hx
    obtain ⟨V, ⟨g, rfl⟩, hxV, hV⟩ :=
      Opens.isBasis_iff_nbhd.1 PrimeSpectrum.isBasis_basic_opens hi
    exact Opens.mem_iSup.2 ⟨⟨g, i, hV⟩, hxV⟩
  rw [PrimeSpectrum.iSup_basicOpen_eq_top_iff] at htop
  obtain ⟨s, hsub, hs1⟩ :=
    Submodule.mem_span_finite_of_mem_span ((Ideal.eq_top_iff_one _).1 htop)
  refine ⟨s, (Ideal.eq_top_iff_one _).2 hs1, fun g hg ↦ ?_⟩
  obtain ⟨⟨g', i, hi⟩, rfl⟩ := hsub hg
  haveI := hσ.isFiniteType i
  exact ⟨SheafOfModules.GeneratingSections.restrict.{u} (homOfLE hi) (σ.generators i),
    inferInstance⟩

/-- **Restriction of a section of `M` from the whole of `Spec R` to a distinguished open.**

Named because it is the map the localisation statement below is about, and because spelling it
out at a call site costs three lines. It is the presheaf of `R`-modules underlying `M`, applied
to `D(g) ≤ ⊤`; note that this is `AlgebraicGeometry.modulesSpecToSheaf`'s presheaf, valued in
`ModuleCat R`, and not `AlgebraicGeometry.Scheme.Modules.presheaf`, which is valued in abelian
groups and carries the `Γ(Spec R, U)`-module structure instead. The two have the same underlying
type, by `rfl`, and different `Module` instances; a statement about one is not found at the
other. -/
noncomputable abbrev sectionsToBasicOpen (g : R) :
    (modulesSpecToSheaf.obj M).presheaf.obj (op ⊤) ⟶
      (modulesSpecToSheaf.obj M).presheaf.obj (op (PrimeSpectrum.basicOpen g)) :=
  (modulesSpecToSheaf.obj M).presheaf.map
    (homOfLE (le_top : (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ ⊤)).op

/-- **For a coherent `M`, restriction to `D(g)` exhibits `Γ(M, D(g))` as the localisation of
`Γ M` away from `g`.**

For `M = N^~` this is Mathlib's instance on `AlgebraicGeometry.tilde.toOpen`, and
`AlgebraicGeometry.Scheme.Modules.toOpen_fromTildeΓ_app` says that `toOpen` followed by the
counit *is* the restriction map. Coherence enters only through
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`, which makes that counit an
isomorphism, and an isomorphism composed after a localisation map is again one
(`IsLocalizedModule.of_linearEquiv`).

**Stated for quasicoherent and not for coherent `M`.** Only quasicoherence is used and it is the
weaker hypothesis; `OkaTest/AffineSections.lean` exercises this at `𝒪_{Spec A} ⧸ (x)`. The
coherent case is
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen_of_isCoherent`, and
the clause here that used to say it could not be instantiated — no sheaf on a `Spec` being proved
coherent anywhere in this repository — is retired by
`AlgebraicGeometry.isCoherentStructureSheaf_spec`; that same witness is now also proved coherent,
and the corollary is instantiated at it.

`AlgebraicGeometry.tilde.toOpen`'s localisation instance has to be supplied to
`IsLocalizedModule.of_linearEquiv` explicitly. Leaving it to be inferred fails: the goal is
stated in terms of `ModuleCat.Hom.hom` and search reduces it to the raw field
`ModuleCat.Hom.hom'`, at which the instance is not found. -/
theorem isLocalizedModule_away_sectionsToBasicOpen [M.IsQuasicoherent] (g : R) :
    IsLocalizedModule.Away g (sectionsToBasicOpen M g).hom := by
  haveI := isIso_fromTildeΓ_of_isQuasicoherent M
  haveI : IsIso ((modulesSpecToSheaf.map M.fromTildeΓ).hom.app (op (PrimeSpectrum.basicOpen g))) :=
    inferInstance
  rw [show sectionsToBasicOpen M g =
      tilde.toOpen ((modulesSpecToSheaf.obj M).presheaf.obj (op ⊤)) (PrimeSpectrum.basicOpen g) ≫
        (modulesSpecToSheaf.map M.fromTildeΓ).hom.app (op (PrimeSpectrum.basicOpen g)) from
    (toOpen_fromTildeΓ_app M (PrimeSpectrum.basicOpen g)).symm]
  exact IsLocalizedModule.of_linearEquiv (Submonoid.powers g)
    (tilde.toOpen ((modulesSpecToSheaf.obj M).presheaf.obj (op ⊤)) (PrimeSpectrum.basicOpen g)).hom
    (asIso ((modulesSpecToSheaf.map M.fromTildeΓ).hom.app
      (op (PrimeSpectrum.basicOpen g)))).toLinearEquiv

/-- **The coherent case of
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`.**

Coherence enters only through `SheafOfModules.IsCoherent.isQuasicoherent`. Stated separately, and
**not as an instance**, for the reason `SheafOfModules.IsCoherent.isFinitePresentation` gives:
`SheafOfModules.IsCoherent` is not a class instance search should be running from, and an
instance here would start such a search at every `IsLocalizedModule.Away` goal. -/
theorem isLocalizedModule_away_sectionsToBasicOpen_of_isCoherent [M.IsCoherent] (g : R) :
    IsLocalizedModule.Away g (sectionsToBasicOpen M g).hom :=
  haveI := SheafOfModules.IsCoherent.isQuasicoherent M
  isLocalizedModule_away_sectionsToBasicOpen M g


/-! ### Epimorphisms are surjective on global sections

An epimorphism of sheaves of modules is not surjective on sections in general. On `Spec R` and
between *quasicoherent* sheaves it is, and that is the mathematical content of the affine
dictionary: everything else in the argument is bookkeeping.
-/

/-- **An epimorphism of quasicoherent sheaves on `Spec R` is surjective on global sections.**

`AlgebraicGeometry.tildeEquiv` is an *equivalence* between `ModuleCat R` and the quasicoherent
`𝒪_{Spec R}`-modules, so it carries the epimorphism to an epimorphism of `R`-modules, which is a
surjection. **No cohomology and no stalks enter**: the vanishing that would otherwise be needed is
already inside the statement that the counit is an isomorphism.

`Epi f` is an explicit argument rather than an instance. At a call site the epimorphism usually
arrives as `SheafOfModules.GeneratingSections.epi`, and instance search does not find it there even
when it is in scope as a local instance — `σ.π` is an `abbrev` for
`SheafOfModules.freeHomEquiv.symm σ.s`, and the two are defeq at default transparency but search
runs at reducible transparency. Taking the hypothesis explicitly removes the question. -/
theorem surjective_moduleSpecΓFunctor_map {M N : (Spec R).Modules}
    [M.IsQuasicoherent] [N.IsQuasicoherent] (f : M ⟶ N) (hf : Epi f) :
    Function.Surjective (moduleSpecΓFunctor.map f).hom := by
  haveI := hf
  rw [← ModuleCat.epi_iff_surjective]
  let f' : (⟨M, ‹_›⟩ : (SheafOfModules.isQuasicoherent (Spec R).ringCatSheaf).FullSubcategory) ⟶
    ⟨N, ‹_›⟩ := ObjectProperty.homMk f
  haveI : Epi f' := (ObjectProperty.ι _).epi_of_epi_map (f := f') (by exact ‹Epi f›)
  exact (tildeEquiv (R := R)).inverse.map_epi f'

/-- **A free sheaf on `Spec R` is quasicoherent.**

Mathlib already has `IsIso (AlgebraicGeometry.Scheme.Modules.fromTildeΓ (SheafOfModules.free ι))`
as an instance, and this is `AlgebraicGeometry.isQuasicoherent_iff_isIso_fromTildeΓ` applied to it.

The instance has to be named through `inferInstanceAs`, **and at Mathlib's spelling rather than at
this statement's**: the goal here is about `SheafOfModules.free (R := (Spec R).ringCatSheaf) I`,
while the instance is stated at
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ (R := R) (SheafOfModules.free.{u} I)`. The two are
defeq and are different discrimination-tree keys, so `inferInstanceAs` at the goal's own spelling
fails — with the type fully written out and no metavariable anywhere — while at Mathlib's it
succeeds. Writing *a* type out is therefore not the fix; writing out the right one of the two
is. -/
theorem isQuasicoherent_free (I : Type u) :
    (SheafOfModules.free.{u} (R := (Spec R).ringCatSheaf) I).IsQuasicoherent :=
  (isQuasicoherent_iff_isIso_fromTildeΓ _).mpr
    (inferInstanceAs (IsIso (Scheme.Modules.fromTildeΓ (R := R) (SheafOfModules.free.{u} I))))

/-- **The global sections of the free sheaf on `Spec R` are the free module.**

`AlgebraicGeometry.tildeFinsupp` says `free I` is `(I →₀ R)^~`, and the unit of the adjunction is
an isomorphism, so its global sections are `I →₀ R`. -/
noncomputable def freeΓIso (I : Type u) :
    ModuleCat.of R (I →₀ R) ≅
      moduleSpecΓFunctor.obj (SheafOfModules.free.{u} (R := (Spec R).ringCatSheaf) I) :=
  (tilde.toTildeΓNatIso (R := R)).app (ModuleCat.of R (I →₀ R)) ≪≫
    moduleSpecΓFunctor.mapIso (tildeFinsupp I)

/-- **Finitely many global sections generating a quasicoherent sheaf on `Spec R` as a sheaf
generate its global sections as a module.**

This is the statement an epimorphism of sheaves does not give for free, and with it
`Module.Finite.of_localizationSpan_finite'` is within reach of `Module.Finite R (Γ M)`; see the
module docstring for what still stands between them.

Coherence is not needed, so the hypotheses are quasicoherence and a finite generating family,
which `OkaTest/AffineSections.lean` exhibits. It is also no longer unavailable — the clause here
that said so is retired by `AlgebraicGeometry.isCoherentStructureSheaf_spec` — but nothing on
this line wants it. -/
theorem module_finite_moduleSpecΓFunctor_obj {M : (Spec R).Modules} [M.IsQuasicoherent]
    (σ : M.GeneratingSections) [Finite σ.I] :
    Module.Finite R (moduleSpecΓFunctor.obj M) := by
  haveI := isQuasicoherent_free (R := R) σ.I
  have hπ : Function.Surjective (moduleSpecΓFunctor.map σ.π).hom :=
    surjective_moduleSpecΓFunctor_map σ.π σ.epi
  have hiso : Function.Surjective (freeΓIso (R := R) σ.I).hom.hom :=
    (ConcreteCategory.bijective_of_isIso (freeΓIso (R := R) σ.I).hom).2
  exact Module.Finite.of_surjective
    (((freeΓIso (R := R) σ.I).hom ≫ moduleSpecΓFunctor.map σ.π).hom)
    (by rw [ModuleCat.hom_comp]; exact hπ.comp hiso)


/-! ### The change of site, and the conclusion of the affine-locality argument

`AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj` above is about **global**
sections of a module on a `Spec`. The affine-locality argument needs it over a distinguished open,
where the generating family actually lives, and `D(g)` is an affine *scheme* rather than a `Spec`
on the nose. So the statement is first moved to an arbitrary affine scheme and then to an affine
open of an arbitrary scheme; the `D(g)` case is the specialisation, and `Module.Finite R (Γ M)`
follows from it by `Module.Finite.of_localizationSpan_finite'`.
-/

noncomputable section ChangeOfSite

set_option backward.isDefEq.respectTransparency false in
/-- **The global sections of a quasicoherent module on an affine scheme, generated by finitely
many global sections, are a finite module over the global sections of the scheme.**

`AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj` at
`AlgebraicGeometry.Scheme.isoSpec`. The transport is in three moves and each is a change of the
ring acting on a *fixed* carrier rather than a map of carriers, which is why
`Module.Finite.of_ringEquiv` is what does the work:

* `AlgebraicGeometry.Scheme.Modules.restrict` along the isomorphism `V.isoSpec.inv` puts the
  module on a `Spec`, keeping quasicoherence
  (`AlgebraicGeometry.Scheme.Modules.isQuasicoherent_restrictFunctor`) and the generating family
  (`SheafOfModules.GeneratingSections.map`, since `restrictFunctor` is a left adjoint);
* the `Γ(V, ⊤)`-action `AlgebraicGeometry.moduleSpecΓFunctor` produces and the
  `Γ(Spec Γ(V, ⊤), ⊤)`-action the sections carry differ by `AlgebraicGeometry.Scheme.ΓSpecIso`,
  and agree by `rfl`;
* `AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_restrict` crosses back over
  `V.isoSpec.inv`, landing at the open `V.isoSpec.inv ''ᵁ ⊤`, which is `⊤`.

The last step is a `▸` along an equality of opens, and so is the corresponding one in
`AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_isAffineOpen`. **Both are harmless
because `Module.Finite` is a `Prop`**: the transport moves a proof and no data, so no term
downstream can meet a stuck `Eq.mpr`. Neither open equality is `rfl` —
`AlgebraicGeometry.Scheme.Opens.ι_image_top` is `TopologicalSpace.Opens.isOpenEmbedding_obj_top`,
which is the `functor.obj ⊤`-versus-`U` seam, and Mathlib's own
`AlgebraicGeometry.Scheme.Opens.topIso` is an `eqToIso` along it.

`PreservesColimitsOfSize.{u, u}` for `restrictFunctor` is written out rather than left to search,
as Mathlib's own `AlgebraicGeometry.Scheme.Modules.presentationRestrict` does, and for the same
reason: the two `Module` instances on the sections of the restriction are also handed over, since
they exist at the `moduleSpecΓFunctor` spelling and instance search runs at reducible
transparency. -/
theorem module_finite_Γ_of_isAffine {V : Scheme.{u}} [IsAffine V] (N : V.Modules)
    [N.IsQuasicoherent] (σ : N.GeneratingSections) [Finite σ.I] :
    Module.Finite Γ(V, ⊤) Γ(N, ⊤) := by
  have : PreservesColimitsOfSize.{u, u} (restrictFunctor V.isoSpec.inv) := inferInstance
  haveI : Finite (σ.map (restrictFunctor V.isoSpec.inv)
      (restrictUnitIso V.isoSpec.inv).symm).I := inferInstanceAs (Finite σ.I)
  haveI hΓ : Module.Finite Γ(V, ⊤)
      (moduleSpecΓFunctor.obj (N.restrict V.isoSpec.inv) : Type u) :=
    module_finite_moduleSpecΓFunctor_obj
      (σ.map (restrictFunctor V.isoSpec.inv) (restrictUnitIso V.isoSpec.inv).symm)
  letI : Module Γ(V, ⊤) Γ(N.restrict V.isoSpec.inv, ⊤) :=
    inferInstanceAs (Module Γ(V, ⊤) (moduleSpecΓFunctor.obj (N.restrict V.isoSpec.inv) : Type u))
  haveI : Module.Finite Γ(V, ⊤) Γ(N.restrict V.isoSpec.inv, ⊤) := hΓ
  haveI : Module.Finite Γ(Spec Γ(V, ⊤), ⊤) Γ(N.restrict V.isoSpec.inv, ⊤) :=
    Module.Finite.of_ringEquiv (Scheme.ΓSpecIso Γ(V, ⊤)).symm.commRingCatIsoToRingEquiv
      fun _ _ ↦ rfl
  haveI h := module_finite_sections_of_restrict V.isoSpec.inv N ⊤
  have he : (V.isoSpec.inv ''ᵁ (⊤ : (Spec Γ(V, ⊤)).Opens) : V.Opens) = ⊤ := by simp
  exact he ▸ h

set_option backward.isDefEq.respectTransparency false in
/-- **The sections of a quasicoherent module over an affine open, generated there by finitely
many sections, are a finite module over the sections of the structure sheaf.**

This is the previous statement read on the open subscheme `U`, and it is the form the
affine-locality argument consumes, because `SheafOfModules.IsFiniteType` hands out generating
sections of `N.over U` rather than of `N.restrict U.ι`. The two are matched by
`AlgebraicGeometry.Scheme.Modules.generatingSectionsRestrict` and the conclusion is carried back
across `U.ι` by `AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_restrict`, at
`AlgebraicGeometry.Scheme.Opens.ι_image_top`.

`IsAffineOpen U` **is** `IsAffine U.toScheme`, but not at reducible transparency, which is why the
instance is named rather than inferred. -/
theorem module_finite_sections_of_isAffineOpen {X : Scheme.{u}} (N : X.Modules)
    [N.IsQuasicoherent] {U : X.Opens} (hU : IsAffineOpen U)
    (σ : (N.over U).GeneratingSections) [Finite σ.I] :
    Module.Finite Γ(X, U) Γ(N, U) := by
  haveI : IsAffine (U : Scheme.{u}) := hU
  haveI := module_finite_Γ_of_isAffine (N.restrict U.ι) (generatingSectionsRestrict N U σ)
  haveI h := module_finite_sections_of_restrict U.ι N ⊤
  exact U.ι_image_top ▸ h

/-- **`Γ(M, U)` is a module over `R` and over `Γ(Spec R, U)` compatibly.**

`AlgebraicGeometry.modulesSpecToSheaf` makes `R` act on `Γ(M, U)` by restricting scalars along
`R ⟶ Γ(Spec R, ⊤) ⟶ Γ(Spec R, U)`, which is `algebraMap R Γ(Spec R, U)` on the nose
(`AlgebraicGeometry.IsAffineOpen.algebraMap_Spec_obj`), so the tower is `Algebra.smul_def` and
`mul_smul`.

It is an instance because `Module.Finite.of_localizationSpan_finite'` asks for one at every member
of the spanning family. -/
instance isScalarTower_sections (N : (Spec R).Modules) (U : (Spec R).Opens) :
    IsScalarTower R Γ(Spec R, U) Γ(N, U) := by
  constructor
  intro a b x
  rw [Algebra.smul_def, mul_smul]
  rfl

/-- **`Γ(M, D(g))` is a finite `Γ(Spec R, D(g))`-module** when `M` is quasicoherent and finitely
many sections generate it over `D(g)`.

This is the change of site the affine dictionary was missing: it is
`AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj` at the affine open `D(g)`
rather than at `⊤`, and `AlgebraicGeometry.IsAffineOpen.Spec_basicOpen` is what says `D(g)` is
one. Nothing here is about `Localization.Away` as a ring: the ring that acts is
`Γ(Spec R, D(g))`, which Mathlib already knows *is* a localisation of `R` away from `g`, and that
instance is what the assembly below uses. -/
theorem module_finite_sections_basicOpen (N : (Spec R).Modules) [N.IsQuasicoherent] (g : R)
    (σ : (N.over (PrimeSpectrum.basicOpen g)).GeneratingSections) [Finite σ.I] :
    Module.Finite Γ(Spec R, PrimeSpectrum.basicOpen g) Γ(N, PrimeSpectrum.basicOpen g) :=
  module_finite_sections_of_isAffineOpen N (IsAffineOpen.Spec_basicOpen g) σ

set_option backward.isDefEq.respectTransparency false in
/-- **The global sections of a quasicoherent sheaf of finite type on `Spec R` are a finite
`R`-module.**

The three steps of the affine-locality argument, assembled by
`Module.Finite.of_localizationSpan_finite'`:
`AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections` supplies the
spanning `Finset` and the generators over each `D(g)`;
`AlgebraicGeometry.Scheme.Modules.module_finite_sections_basicOpen` makes `Γ(M, D(g))` a finite
`Γ(Spec R, D(g))`-module; and
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen` says the restriction
map exhibits it as the localisation of `Γ M` away from `g`.

**Coherence is not used**, and the hypotheses here are the two that
`OkaTest/AffineSections.lean` exhibits. This sentence used to read *"neither used nor available"*,
as the one on `AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj` above did;
**the "available" half is retired** by `AlgebraicGeometry.isCoherentStructureSheaf_spec`, and the
very sheaf `OkaTest/AffineSections.lean` exhibits is proved coherent there, by
`OkaTest.AffineSections.isCoherent_cokernel_specXHom`. The "used" half stands: nothing on this
line wants coherence, and these two hypotheses are the weaker ones.

The localisation instances and the two `Module` instances at the
`AlgebraicGeometry.modulesSpecToSheaf` spelling are handed over rather than searched for, for the
reason recorded on
`AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_restrict`. -/
theorem module_finite_moduleSpecΓFunctor_obj_of_isFiniteType (N : (Spec R).Modules)
    [N.IsQuasicoherent] [N.IsFiniteType] :
    Module.Finite R (moduleSpecΓFunctor.obj N : Type u) := by
  obtain ⟨s, hs, hσ⟩ := exists_finset_basicOpen_generatingSections N
  haveI : ∀ g : s, IsLocalizedModule.Away (g : R) (sectionsToBasicOpen N (g : R)).hom :=
    fun g ↦ isLocalizedModule_away_sectionsToBasicOpen N (g : R)
  letI : ∀ g : s, Module Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      ((modulesSpecToSheaf.obj N).presheaf.obj (op (PrimeSpectrum.basicOpen (g : R))) : Type u) :=
    fun g ↦ inferInstanceAs (Module Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      Γ(N, PrimeSpectrum.basicOpen (g : R)))
  haveI : ∀ g : s, IsScalarTower R Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      ((modulesSpecToSheaf.obj N).presheaf.obj (op (PrimeSpectrum.basicOpen (g : R))) : Type u) :=
    fun g ↦ inferInstanceAs (IsScalarTower R Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      Γ(N, PrimeSpectrum.basicOpen (g : R)))
  refine Module.Finite.of_localizationSpan_finite' s hs
    (Rₚ := fun g ↦ Γ(Spec R, PrimeSpectrum.basicOpen (g : R)))
    (fun g ↦ (sectionsToBasicOpen N (g : R)).hom) fun g ↦ ?_
  obtain ⟨σ, hσ'⟩ := hσ (g : R) g.2
  haveI := hσ'
  exact module_finite_sections_basicOpen N (g : R) σ

end ChangeOfSite

section FinitePresentation

/-- **The cokernel of a map out of a finite module into a finitely presented one is finitely
presented.**

`Module.finitePresentation_of_surjective` at the quotient projection, carried to the categorical
cokernel by `ModuleCat.cokernelIsoRangeQuotient`; the kernel of the projection is the range of
`g`, which is finitely generated because its source is.

**Its natural home upstream is `Mathlib/Algebra/Category/ModuleCat/Kernels.lean`, and it is not
stated there or in a mirror of it, deliberately.** That file does not import
`Mathlib/Algebra/Module/FinitePresentation.lean` and adding it costs **189 files**; the reverse
direction costs **137**. Both are far above the size this project has previously judged too
expensive for a mirror path, so the lemma sits with its only consumer instead, where the import it
needs costs **3**. Those are BFS counts over `^(public )?import` in `.lake/packages/mathlib` and
are meant to be re-run rather than believed. -/
theorem finitePresentation_cokernel {A B : ModuleCat.{u} R} (g : A ⟶ B)
    [Module.Finite R A] [Module.FinitePresentation R B] :
    Module.FinitePresentation R (cokernel g : ModuleCat.{u} R) := by
  have hfg : (LinearMap.range g.hom).FG := by
    rw [LinearMap.range_eq_map]
    exact (Module.Finite.iff_fg.mp inferInstance).map g.hom
  haveI : Module.FinitePresentation R (B ⧸ LinearMap.range g.hom) :=
    Module.finitePresentation_of_surjective (LinearMap.range g.hom).mkQ
      (Submodule.mkQ_surjective _) (by rw [Submodule.ker_mkQ]; exact hfg)
  exact Module.FinitePresentation.of_equiv (ModuleCat.cokernelIsoRangeQuotient g).symm.toLinearEquiv

set_option backward.isDefEq.respectTransparency false in
/-- **The map of `R`-modules underlying a global presentation of a sheaf on `Spec R`.**

A `SheafOfModules.Presentation` of `M` gives `free K ⟶ kernel P.generators.π ⟶ free I`; conjugating
by `AlgebraicGeometry.tildeFinsupp` reads that as a map between tildes of free modules, and
`tilde.functor R` is fully faithful, so it comes from a map `(K →₀ R) ⟶ (I →₀ R)` in `ModuleCat R`.

**This is Mathlib's own construction, three lines inside the proof of
`AlgebraicGeometry.isIso_fromTildeΓ_of_presentation`, which concludes `IsIso M.fromTildeΓ` and
discards the map.** Naming it is the whole of what this section adds over that theorem; the
mathematics is entirely there.

`set_option backward.isDefEq.respectTransparency false` is required and is not decoration. Without
it the term fails with `failed to synthesize HasZeroMorphisms (Spec (CommRingCat.of ↑R)).Modules`
— `tilde.functor R` lands at the `Spec (CommRingCat.of ↑R)` spelling, which is `rfl`-equal to
`Spec R` — and **supplying that instance does not help**: neither `haveI` nor `letI` of exactly
that type, obtained by `inferInstanceAs` from the `Spec R` spelling, removes the error. Why the
option works is not established here and no explanation should be read into this note; what
reproduces is the above, and the option is what `isIso_fromTildeΓ_of_presentation` itself
carries. -/
noncomputable def presentationRelMap (P : M.Presentation) :
    ModuleCat.of R (P.relations.I →₀ R) ⟶ ModuleCat.of R (P.generators.I →₀ R) :=
  (tilde.functor _).preimage <| (tildeFinsupp _).hom ≫ P.relations.π ≫ kernel.ι _ ≫
    (tildeFinsupp _).inv

set_option backward.isDefEq.respectTransparency false in
/-- **A sheaf with a global presentation is the tilde of the cokernel of
`AlgebraicGeometry.Scheme.Modules.presentationRelMap`.**

`tilde.functor R` preserves cokernels, `AlgebraicGeometry.tildeFinsupp` identifies the two ends,
and `SheafOfModules.Presentation.isColimit` says the presentation exhibits `M` as a cokernel.
Transcribed from the proof of `AlgebraicGeometry.isIso_fromTildeΓ_of_presentation`. -/
noncomputable def isoTildeCokernel (P : M.Presentation) :
    (tilde.functor R).obj (cokernel (presentationRelMap M P)) ≅ M :=
  PreservesCokernel.iso (tilde.functor R) (presentationRelMap M P) ≪≫
    (cokernel.mapIso _ _ (tildeFinsupp _) (tildeFinsupp _) (by
      simp only [presentationRelMap, (tilde.functor R).map_preimage]
      simp)) ≪≫
    IsColimit.coconePointUniqueUpToIso (colimit.isColimit _) P.isColimit

set_option backward.isDefEq.respectTransparency false in
/-- **The global sections of a sheaf on `Spec R` with a finite global presentation are a finitely
presented `R`-module.**

`M` is the tilde of `cokernel (presentationRelMap M P)`
(`AlgebraicGeometry.Scheme.Modules.isoTildeCokernel`), the counit `tilde.toTildeΓNatIso` identifies
the global sections of a tilde with the module it came from, and that cokernel is finitely
presented because both index types are finite
(`AlgebraicGeometry.Scheme.Modules.finitePresentation_cokernel`).

**A finite global presentation is strictly more than quasicoherent-of-finite-type, and the
strengthening is necessary rather than convenient**: see the module docstring for the
counterexample. It is *weaker* than `SheafOfModules.IsCoherent`, and
`OkaTest/AffineSections.lean` instantiates **both**, at one sheaf: `𝒪_{Spec A} ⧸ (x)` carries the
finite global presentation this theorem consumes and is also coherent, by
`OkaTest.AffineSections.isCoherent_cokernel_specXHom`. So the contrast is between the hypotheses
and not between what can be exhibited. **The clause here used to say that
`SheafOfModules.IsCoherent` was uninstantiated in this repository** — already loose, since
`OkaTest/CoherentFree.lean` instantiates it analytically, and false on a `Spec` since
`AlgebraicGeometry.isCoherentStructureSheaf_spec`; it is retired rather than renumbered, because
what it was for was the contrast and the contrast is what changed.

The `Module.FinitePresentation` instance is named at the `𝟭 (ModuleCat R)` spelling before the
final transport, because that is the spelling `tilde.toTildeΓNatIso.app` presents and search does
not see through the identity functor there. -/
theorem finitePresentation_Γ (P : M.Presentation) [P.IsFinite] :
    Module.FinitePresentation R (moduleSpecΓFunctor.obj M : Type u) := by
  haveI : Finite P.generators.I := SheafOfModules.GeneratingSections.IsFiniteType.finite
  haveI : Finite P.relations.I := SheafOfModules.GeneratingSections.IsFiniteType.finite
  haveI : Module.FinitePresentation R (cokernel (presentationRelMap M P) : ModuleCat.{u} R) :=
    finitePresentation_cokernel _
  haveI : Module.FinitePresentation R
      ((𝟭 (ModuleCat.{u} R)).obj (cokernel (presentationRelMap M P)) : Type u) :=
    inferInstanceAs
      (Module.FinitePresentation R (cokernel (presentationRelMap M P) : ModuleCat.{u} R))
  exact Module.FinitePresentation.of_equiv
    ((tilde.toTildeΓNatIso (R := R)).app (cokernel (presentationRelMap M P)) ≪≫
      moduleSpecΓFunctor.mapIso (isoTildeCokernel M P)).toLinearEquiv

/-! ### The local statement

Everything above about finite presentation is at a **global** `SheafOfModules.Presentation`.
Mathlib's class `SheafOfModules.IsFinitePresentation` asks only for one over the members of some
covering, and the passage from it to `Module.FinitePresentation R (Γ M)` is the quasi-compactness
argument again, with `Module.Finite` replaced by `Module.FinitePresentation` and generating
sections replaced by presentations at every step.
-/

/-- **Restricting a presentation along an open immersion preserves finiteness.**

`AlgebraicGeometry.Scheme.Modules.presentationRestrict` is `SheafOfModules.Presentation.map` along
`AlgebraicGeometry.Scheme.Modules.restrictFunctor`, which changes neither index type; the fields
are the source's, as for `SheafOfModules.Presentation.isFinite_restrict` and for the same reason —
`presentationRestrict` is an ordinary definition, so search does not see the `map` underneath
it. -/
instance isFinite_presentationRestrict {X Y : Scheme.{u}} (f : Y ⟶ X) [IsOpenImmersion f]
    {N : X.Modules} (P : N.Presentation) [P.IsFinite] : (presentationRestrict f P).IsFinite where
  isFiniteType_generators := ⟨inferInstanceAs (Finite P.generators.I)⟩
  isFiniteType_relations := ⟨inferInstanceAs (Finite P.relations.I)⟩

noncomputable section LocalFinitePresentation

/-- **The global sections of a module on an affine scheme with a finite global presentation are a
finitely presented module over the global sections of the scheme.**

`AlgebraicGeometry.Scheme.Modules.module_finite_Γ_of_isAffine` with `Module.Finite` replaced by
`Module.FinitePresentation`, generating sections by a presentation, and
`SheafOfModules.GeneratingSections.map` by
`AlgebraicGeometry.Scheme.Modules.presentationRestrict`; the three moves are the same and each is
again a change of the ring acting on a fixed carrier. Read that docstring for what they are.

The final `▸` is along an equality of opens and is harmless for the reason the finite-type
version's is: `Module.FinitePresentation` is a `Prop`, so the transport moves a proof and no data
and no term downstream can meet a stuck `Eq.mpr`. The same holds for the one in
`AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_of_isAffineOpen` below.

**It needs no `set_option`, and the finite-type version does.** `module_finite_Γ_of_isAffine` and
`module_finite_sections_of_isAffineOpen` both carry
`set_option backward.isDefEq.respectTransparency false`; deleting it from either of the two
statements here changes nothing, measured by deleting them. The assembly at the end of the file
does need it, as its finite-type counterpart does. No explanation is offered for the difference. -/
theorem finitePresentation_Γ_of_isAffine {V : Scheme.{u}} [IsAffine V] (N : V.Modules)
    (P : N.Presentation) [P.IsFinite] :
    Module.FinitePresentation Γ(V, ⊤) Γ(N, ⊤) := by
  have : PreservesColimitsOfSize.{u, u} (restrictFunctor V.isoSpec.inv) := inferInstance
  haveI hΓ : Module.FinitePresentation Γ(V, ⊤)
      (moduleSpecΓFunctor.obj (N.restrict V.isoSpec.inv) : Type u) :=
    finitePresentation_Γ _ (presentationRestrict V.isoSpec.inv P)
  letI : Module Γ(V, ⊤) Γ(N.restrict V.isoSpec.inv, ⊤) :=
    inferInstanceAs (Module Γ(V, ⊤) (moduleSpecΓFunctor.obj (N.restrict V.isoSpec.inv) : Type u))
  haveI : Module.FinitePresentation Γ(V, ⊤) Γ(N.restrict V.isoSpec.inv, ⊤) := hΓ
  haveI : Module.FinitePresentation Γ(Spec Γ(V, ⊤), ⊤) Γ(N.restrict V.isoSpec.inv, ⊤) :=
    Module.FinitePresentation.of_ringEquiv
      (Scheme.ΓSpecIso Γ(V, ⊤)).symm.commRingCatIsoToRingEquiv fun _ _ ↦ rfl
  haveI h := finitePresentation_sections_of_restrict V.isoSpec.inv N ⊤
  have he : (V.isoSpec.inv ''ᵁ (⊤ : (Spec Γ(V, ⊤)).Opens) : V.Opens) = ⊤ := by simp
  exact he ▸ h

/-- **The sections of a module over an affine open with a finite presentation there are a finitely
presented module over the sections of the structure sheaf.**

`AlgebraicGeometry.Scheme.Modules.module_finite_sections_of_isAffineOpen` with the same three
replacements, and the crossing from the slice site `Over U` to the open subscheme's own site is
`AlgebraicGeometry.Scheme.Modules.presentationOverRestrict` in place of
`AlgebraicGeometry.Scheme.Modules.generatingSectionsRestrict`. This is the form the argument
consumes, because `SheafOfModules.IsFinitePresentation` hands out presentations of `N.over U`. -/
theorem finitePresentation_sections_of_isAffineOpen {X : Scheme.{u}} (N : X.Modules)
    {U : X.Opens} (hU : IsAffineOpen U) (P : (N.over U).Presentation) [P.IsFinite] :
    Module.FinitePresentation Γ(X, U) Γ(N, U) := by
  haveI : IsAffine (U : Scheme.{u}) := hU
  haveI := finitePresentation_Γ_of_isAffine (N.restrict U.ι) (presentationOverRestrict N U P)
  haveI h := finitePresentation_sections_of_restrict U.ι N ⊤
  exact U.ι_image_top ▸ h

/-- **`Γ(M, D(g))` is a finitely presented `Γ(Spec R, D(g))`-module** when `M` has a finite
presentation over `D(g)`.

The specialisation of the previous statement at `AlgebraicGeometry.IsAffineOpen.Spec_basicOpen`,
exactly as `AlgebraicGeometry.Scheme.Modules.module_finite_sections_basicOpen` is of its
predecessor, and quasicoherence is not asked for here because a presentation gives it. -/
theorem finitePresentation_sections_basicOpen (N : (Spec R).Modules) (g : R)
    (P : (N.over (PrimeSpectrum.basicOpen g)).Presentation) [P.IsFinite] :
    Module.FinitePresentation Γ(Spec R, PrimeSpectrum.basicOpen g)
      Γ(N, PrimeSpectrum.basicOpen g) :=
  finitePresentation_sections_of_isAffineOpen N (IsAffineOpen.Spec_basicOpen g) P

/-- **A sheaf of finite presentation on `Spec R` has a finite presentation over each of finitely
many distinguished opens which span the unit ideal.**

`AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections` with presentations
in place of generating families. The proof is that one line for line — basic opens are a basis,
the resulting `D(g)` cover, so their `g` span the unit ideal, and `1` lies in the span of a finite
subset — and the only difference is the last line, where
`SheafOfModules.Presentation.restrict` carries a presentation from the member of the given
covering to the `D(g)` inside it, in place of
`SheafOfModules.GeneratingSections.restrict`.

**That last line is the whole of what had to be new**, and there was a reason to expect otherwise:
the generating-sections transport ends at `SheafOfModules.GeneratingSections.ofEpi`, and a
presentation does not transport along an epimorphism. See
`Oka/Algebra/Category/ModuleCat/Sheaf/Quasicoherent.lean` for why it does anyway. -/
theorem exists_finset_basicOpen_presentation [M.IsFinitePresentation] :
    ∃ s : Finset R, Ideal.span (s : Set R) = ⊤ ∧
      ∀ g ∈ s, ∃ P : (M.over (PrimeSpectrum.basicOpen g)).Presentation, P.IsFinite := by
  obtain ⟨q, hq⟩ := SheafOfModules.IsFinitePresentation.exists_quasicoherentData.{u, u} M
  have hcov : ⨆ i, q.X i = ⊤ := (Opens.coversTop_iff (U := q.X) _).1 q.coversTop
  have htop : (⨆ g : {g : R // ∃ i, (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ q.X i},
      (PrimeSpectrum.basicOpen g.1 : (Spec R).Opens)) = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hx : x ∈ ⨆ i, q.X i := by rw [hcov]; trivial
    obtain ⟨i, hi⟩ := Opens.mem_iSup.1 hx
    obtain ⟨V, ⟨g, rfl⟩, hxV, hV⟩ :=
      Opens.isBasis_iff_nbhd.1 PrimeSpectrum.isBasis_basic_opens hi
    exact Opens.mem_iSup.2 ⟨⟨g, i, hV⟩, hxV⟩
  rw [PrimeSpectrum.iSup_basicOpen_eq_top_iff] at htop
  obtain ⟨s, hsub, hs1⟩ :=
    Submodule.mem_span_finite_of_mem_span ((Ideal.eq_top_iff_one _).1 htop)
  refine ⟨s, (Ideal.eq_top_iff_one _).2 hs1, fun g hg ↦ ?_⟩
  obtain ⟨⟨g', i, hi⟩, rfl⟩ := hsub hg
  haveI := hq.isFinite_presentation i
  exact ⟨SheafOfModules.Presentation.restrict.{u} (homOfLE hi) (q.presentation i), inferInstance⟩

set_option backward.isDefEq.respectTransparency false in
/-- **The global sections of a sheaf of finite presentation on `Spec R` are a finitely presented
`R`-module.**

The three steps assembled by `Module.FinitePresentation.of_localizationSpan'`, at the same choice
of localised ring `Γ(Spec R, D(g))` that
`AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj_of_isFiniteType` makes and
with the same `AlgebraicGeometry.Scheme.Modules.isScalarTower_sections` and
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`: the assembly lemma
has the same shape as its `Module.Finite` counterpart and consumes them unchanged, which is the
one thing on this line that was measured in advance and came out as predicted.

`SheafOfModules.IsFinitePresentation` gives quasicoherence as an instance, so the localisation
statement applies without a separate hypothesis.

**This generalises `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ`**, through
`SheafOfModules.Presentation.isFinitePresentation`; that one is kept because this proof goes
through it, at a restricted presentation on an affine.

The `set_option` is needed and the two change-of-site statements above do not need theirs;
deleting it here leaves `failed to synthesize ∀ (g : ↑↑s), IsLocalizedModule (Submonoid.powers ↑g)
…`, the same instance hand-over its finite-type counterpart makes. -/
theorem finitePresentation_Γ_of_isFinitePresentation (N : (Spec R).Modules)
    [N.IsFinitePresentation] :
    Module.FinitePresentation R (moduleSpecΓFunctor.obj N : Type u) := by
  obtain ⟨s, hs, hP⟩ := exists_finset_basicOpen_presentation N
  haveI : ∀ g : (s : Set R), IsLocalizedModule.Away (g : R) (sectionsToBasicOpen N (g : R)).hom :=
    fun g ↦ isLocalizedModule_away_sectionsToBasicOpen N (g : R)
  letI : ∀ g : (s : Set R), Module Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      ((modulesSpecToSheaf.obj N).presheaf.obj (op (PrimeSpectrum.basicOpen (g : R))) : Type u) :=
    fun g ↦ inferInstanceAs (Module Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      Γ(N, PrimeSpectrum.basicOpen (g : R)))
  haveI : ∀ g : (s : Set R), IsScalarTower R Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      ((modulesSpecToSheaf.obj N).presheaf.obj (op (PrimeSpectrum.basicOpen (g : R))) : Type u) :=
    fun g ↦ inferInstanceAs (IsScalarTower R Γ(Spec R, PrimeSpectrum.basicOpen (g : R))
      Γ(N, PrimeSpectrum.basicOpen (g : R)))
  refine Module.FinitePresentation.of_localizationSpan' (s : Set R) hs
    (Rₚ := fun g ↦ Γ(Spec R, PrimeSpectrum.basicOpen (g : R)))
    (fun g ↦ (sectionsToBasicOpen N (g : R)).hom) fun g ↦ ?_
  obtain ⟨P, hP'⟩ := hP (g : R) (Finset.mem_coe.mp g.2)
  haveI := hP'
  exact finitePresentation_sections_basicOpen N (g : R) P

end LocalFinitePresentation

/-! ### Back up: a finitely presented `Γ M` gives a global presentation of `M`

Everything above goes from a presentation to a module. This goes back, and closes the affine
dictionary: a quasicoherent `M` on `Spec R` whose global sections are a finitely presented
`R`-module has a finite **global** `SheafOfModules.Presentation`.

**The whole of it is already in Mathlib and the only thing to notice is what
`Module.FinitePresentation` unfolds to.** `AlgebraicGeometry.presentationTilde` builds a
presentation of `M^~` from a spanning set `s ⊆ M` and a spanning set `t` of the kernel of
`Rˢ → M`; `Module.FinitePresentation R M` is, by definition, a **`Finset`** `s` spanning `M`
together with finite generation of that same kernel. So the two sets `presentationTilde` wants are
exactly the two the class hands out, and they are finite for free — no route through
`Module.FinitePresentation.exists_fin`, no cokernel of a map of finite free modules built by hand,
and no right-exactness argument for `tilde`.

Then `AlgebraicGeometry.Scheme.Modules.fromTildeΓ` is an isomorphism for a quasicoherent `M`
(Mathlib's `AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent`), and
`SheafOfModules.Presentation.ofIsIso` carries the presentation across.

**The conclusion is an existential and not a definition.** A `SheafOfModules.Presentation` is data
and the class `Module.FinitePresentation` is a `Prop`, so no canonical presentation can be
extracted; a caller `obtain`s one. That is also why there is no instance here.
-/

section GlobalPresentation

/-- **A finitely presented module has a finite presentation of its tilde.**

`AlgebraicGeometry.presentationTilde` at the spanning set and the relation set that
`Module.FinitePresentation` is *defined* by — see the section docstring — so the only work is
noting that a `Finset` coerced to a `Set` has a `Finite` coercion to a type.

The two fields are the given `Finite` instances, as everywhere else on this line:
`SheafOfModules.Presentation.IsFinite` is finiteness of the two index types and nothing else, and
`AlgebraicGeometry.presentationTilde`'s index types are `t` and `s` by construction. -/
instance _root_.AlgebraicGeometry.isFinite_presentationTilde {N : ModuleCat.{u} R} (s : Set N)
    [Finite s] (hs : Submodule.span R s = ⊤) (t : Set (s →₀ R)) [Finite t]
    (ht : Submodule.span R t = LinearMap.ker (Finsupp.linearCombination R ((↑) : s → N))) :
    (AlgebraicGeometry.presentationTilde.{u} N s hs t ht).IsFinite where
  isFiniteType_generators := ⟨inferInstanceAs (Finite s)⟩
  isFiniteType_relations := ⟨inferInstanceAs (Finite t)⟩

/-- **The tilde of a finitely presented module has a finite global presentation.**

`Module.FinitePresentation R N` unfolds to a `Finset s` with `Submodule.span R ↑s = ⊤` and
finite generation of `LinearMap.ker (Finsupp.linearCombination R ((↑) : ↥s → N))`, which is
literally the pair of hypotheses `AlgebraicGeometry.presentationTilde` asks for. Both sets are
`Finset`s, so `AlgebraicGeometry.isFinite_presentationTilde` applies.

An existential rather than a definition, because the class is a `Prop` and the presentation is
data; see the section docstring. -/
theorem exists_isFinite_presentation_tilde (N : ModuleCat.{u} R)
    [Module.FinitePresentation R N] :
    ∃ P : (AlgebraicGeometry.tilde N).Presentation, P.IsFinite := by
  obtain ⟨s, hs, hker⟩ := ‹Module.FinitePresentation R N›
  obtain ⟨t, ht⟩ := hker
  haveI : Finite (s : Set N) := s.finite_toSet.to_subtype
  haveI : Finite (t : Set ((s : Set N) →₀ R)) := t.finite_toSet.to_subtype
  exact ⟨AlgebraicGeometry.presentationTilde.{u} N (s : Set N) hs (t : Set _) ht, inferInstance⟩

set_option backward.isDefEq.respectTransparency false in
/-- **A quasicoherent sheaf on `Spec R` with finitely presented global sections has a finite
global presentation.**

The converse of `AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ`, and with it the affine
dictionary closes: for a quasicoherent `M` on a `Spec`, having a finite global
`SheafOfModules.Presentation` and having `Module.FinitePresentation R (Γ M)` are the same
condition.

The previous statement at `Γ M`, then `SheafOfModules.Presentation.ofIsIso` along
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ`, which quasicoherence makes an isomorphism. **The
`set_option` is needed** and is the `Spec R` versus `Spec (CommRingCat.of ↑R)` seam again:
without it `IsIso M.fromTildeΓ` is not synthesised even with
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent` supplied by hand. No
explanation is offered; it is measured, by deleting it. -/
theorem exists_isFinite_presentation (N : (Spec R).Modules) [N.IsQuasicoherent]
    [Module.FinitePresentation R (moduleSpecΓFunctor.obj N : Type u)] :
    ∃ P : N.Presentation, P.IsFinite := by
  obtain ⟨P, hP⟩ := exists_isFinite_presentation_tilde
    (moduleSpecΓFunctor.obj N : ModuleCat.{u} R)
  haveI := hP
  haveI := isIso_fromTildeΓ_of_isQuasicoherent N
  exact ⟨P.ofIsIso N.fromTildeΓ, inferInstance⟩

/-- **A coherent sheaf on `Spec R` has a finite global presentation.**

The whole affine half of the dictionary in one statement, and every step of it is on this line:
coherence gives quasicoherence and `SheafOfModules.IsFinitePresentation`
(`SheafOfModules.IsCoherent.isFinitePresentation`, a presentation over *some* covering);
`AlgebraicGeometry.Scheme.Modules.finitePresentation_Γ_of_isFinitePresentation` turns that into
`Module.FinitePresentation R (Γ M)`; and the previous statement turns *that* into a **global**
presentation. The passage from local to global happens at the level of modules, where
quasi-compactness of `Spec R` does it, and never at the level of sheaves.

**The clause here used to say this theorem had no witness**, because nothing in this repository
proved a sheaf on a `Spec` coherent. `AlgebraicGeometry.isCoherentStructureSheaf_spec` retired
that, and `OkaTest/CoherentPresentation.lean` instantiates this theorem at
`OkaTest/AffineSections.lean`'s witness, which
`OkaTest.AffineSections.isCoherent_cokernel_specXHom` proves coherent. The hypothesis one rung
down, `SheafOfModules.IsFinitePresentation`, is inhabited at the same sheaf. -/
theorem exists_isFinite_presentation_of_isCoherent (N : (Spec R).Modules) [N.IsCoherent] :
    ∃ P : N.Presentation, P.IsFinite := by
  haveI := SheafOfModules.IsCoherent.isQuasicoherent N
  haveI := SheafOfModules.IsCoherent.isFinitePresentation N
  haveI := finitePresentation_Γ_of_isFinitePresentation N
  exact exists_isFinite_presentation N

end GlobalPresentation

end FinitePresentation

end AlgebraicGeometry.Scheme.Modules
