/-
Copyright (c) 2026 Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuichiro Hoshi, Junnosuke Koizumi, Christian Merten
-/
module

public import Mathlib.AlgebraicGeometry.Modules.Tilde
public import Oka.Algebra.Category.ModuleCat.Sheaf.Coherent.Presentation
public import Oka.Algebra.Category.ModuleCat.Sheaf.Generators

/-!
# A module on an affine scheme and its global sections

Material for `Mathlib/AlgebraicGeometry/Modules/Tilde.lean`; see `README.md` on the mirror tree.

Mathlib proves `AlgebraicGeometry.isQuasicoherent_iff_isIso_fromTildeΓ`: an
`𝒪_{Spec R}`-module `M` is quasicoherent exactly when the counit
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ : (Γ M)^~ ⟶ M` is an isomorphism, and packages the
consequence as the equivalence `AlgebraicGeometry.tildeEquiv` between `ModuleCat R` and the
quasicoherent `𝒪_{Spec R}`-modules. This file records what that gives for the *coherent* ones,
which is the notion this repository's sheaf theory is stated in, and then two steps of the
affine-locality argument that a consumer of the dictionary needs.

`AlgebraicGeometry.Scheme.Modules.isoTildeΓ` is the first, and its content is entirely in
`SheafOfModules.IsCoherent.isQuasicoherent`; nothing about it is about `Spec`. It is stated
because the affine dictionary is quoted often enough — "a coherent sheaf on `Spec A` is a
module" — that the one-line derivation is worth having a name, and because the target
`M ≅ (Γ M)^~` is the form a consumer wants rather than `IsIso` of a counit.

## The two affine steps, and why they are here

The dictionary a consumer actually wants is "coherent sheaf on `Spec A` = finitely presented
`A`-module", and `M ≅ (Γ M)^~` is only half of it: it says nothing about `Γ M` as an `A`-module.
Getting the other half is the quasi-compactness argument on `Spec A`, and it has three steps.
The first and the third are here:

* `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections`: **a sheaf of
  finite type on `Spec R` is generated by finitely many sections over each of finitely many
  distinguished opens which span the unit ideal.** `SheafOfModules.IsFiniteType` gives generators
  over the members of *some* open covering; this replaces that covering by one of basic opens,
  using that they are a basis and that `Spec R` is quasi-compact, and moves the generators along
  with `SheafOfModules.GeneratingSections.restrict`.
* `AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`: **for a coherent
  `M`, restriction from `⊤` to `D(g)` exhibits `Γ(M, D(g))` as the localisation of `Γ M` away
  from `g`.** With the previous step this puts the hypotheses of
  `Module.Finite.of_localizationSpan_finite'` within reach: its spanning `Finset` is the first
  step's, and its `IsLocalizedModule.Away` is this.

## The second step, and what is left of it

The mathematical content of the affine dictionary is that **an epimorphism of quasicoherent
sheaves on `Spec R` is surjective on global sections**, which is false for sheaves of modules in
general. That is `AlgebraicGeometry.Scheme.Modules.surjective_moduleSpecΓFunctor_map`, and it is
here: `AlgebraicGeometry.tildeEquiv` is an *equivalence*, so it carries the epimorphism to a
surjection of `R`-modules. No cohomology and no stalks are needed — the vanishing that would
otherwise be required is already inside the statement that the counit is an isomorphism.

Its corollary `AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj` is the
`⊤` case of what the affine-locality argument wants: finitely many **global** sections generating
`M` as a sheaf generate `Γ M` as a module.

**What is left is a change of site.**

> `Module.Finite Γ(Spec R, D(g)) Γ(M, D(g))` — the same statement over a distinguished open.

`D(g)` is `Spec (Localization.Away g)`, so this *is* the theorem above, at a different affine, and
what has to be built is the translation. **How much work that is has not been established here**,
and the parts below are listed as measured or not rather than as easy or hard:

* `AlgebraicGeometry.basicOpenIsoSpecAway` gives the isomorphism of schemes, and
  `AlgebraicGeometry.Scheme.Modules.restrict` transports the module along it. The encouraging half
  is measured: `AlgebraicGeometry.Scheme.Modules.restrict_obj` is `rfl` and
  `AlgebraicGeometry.Scheme.Modules.restrictAppIso` is `Iso.refl`, so the *sections* need no
  transport at all.
* The unmeasured halves are that `restrict` preserves quasicoherence, and that a
  `SheafOfModules.GeneratingSections` of `M.over (D g)` — which lives over the slice site
  `Over (D g)` — becomes one of the restricted module over `Spec (Localization.Away g)`.
* And the module structures have to be reconciled: `Γ(M, D g)` carries a `Γ(Spec R, D g)`-action,
  the restriction carries a `Localization.Away g`-action, and
  `Module.Finite.of_localizationSpan_finite'` wants an `IsScalarTower` between them, which is a
  declared-instance decision this file has not taken.

**Until that lands, nothing here produces a *global* presentation of `M` as a cokernel of finite
free sheaves for a sheaf that is merely of finite type, and nothing here shows `Γ M` finitely
generated from local data.** A consumer wanting the full dictionary needs that step and will not
find it in this repository.

## Main definitions

- `AlgebraicGeometry.Scheme.Modules.isoTildeΓ`
- `AlgebraicGeometry.Scheme.Modules.sectionsToBasicOpen`
- `AlgebraicGeometry.Scheme.Modules.freeΓIso`

## Main results

- `AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`
- `AlgebraicGeometry.Scheme.Modules.exists_finset_basicOpen_generatingSections`
- `AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`, and its
  coherent corollary `…_of_isCoherent`
- `AlgebraicGeometry.Scheme.Modules.surjective_moduleSpecΓFunctor_map`, and its corollary
  `AlgebraicGeometry.Scheme.Modules.module_finite_moduleSpecΓFunctor_obj`
-/

@[expose] public section

universe u

open CategoryTheory Limits TopologicalSpace Opposite PrimeSpectrum

namespace AlgebraicGeometry.Scheme.Modules

variable {R : CommRingCat.{u}} (M : (Spec R).Modules)

/-- **A coherent `𝒪_{Spec R}`-module is `(Γ M)^~`.**

`SheafOfModules.IsCoherent.isQuasicoherent` and Mathlib's
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent`. Coherence is used only
through quasicoherence: `AlgebraicGeometry.tilde` cannot see the difference, and the finiteness
of `Γ M` that separates the two is not asserted — see the module docstring. -/
theorem isIso_fromTildeΓ_of_isCoherent [M.IsCoherent] : IsIso M.fromTildeΓ := by
  haveI := SheafOfModules.IsCoherent.isQuasicoherent M
  infer_instance

/-- **The comparison of a coherent `𝒪_{Spec R}`-module with the sheaf associated with its global
sections, as an isomorphism.** -/
noncomputable def isoTildeΓ [M.IsCoherent] :
    AlgebraicGeometry.tilde ((modulesSpecToSheaf.obj M).presheaf.obj (.op ⊤)) ≅ M :=
  haveI := isIso_fromTildeΓ_of_isCoherent M
  asIso M.fromTildeΓ

/-- **A sheaf of finite type on `Spec R` is generated by finitely many sections over each of
finitely many distinguished opens which span the unit ideal.**

`SheafOfModules.IsFiniteType` gives generators over the members of *some* open covering of
`Spec R`, and a covering is all it gives: no member need be distinguished and there need be no
finite subcovering among them. Both are repaired here, and this is the only place on this line
where quasi-compactness of `Spec R` is used.

The proof is the standard one and has no sheaf theory in it beyond the last line. Basic opens are
a basis (`PrimeSpectrum.isBasis_basic_opens`), so every point has a `D(g)` inside a member of the
given covering; those `D(g)` cover, so their `g` span the unit ideal
(`PrimeSpectrum.iSup_basicOpen_eq_top_iff`); and `1` lies in the span of a finite subset
(`Submodule.mem_span_finite_of_mem_span`), which is the finite subcovering. The generators are
carried from the member of the original covering to the `D(g)` inside it by
`SheafOfModules.GeneratingSections.restrict`.

**The `Finset` is the shape `Module.Finite.of_localizationSpan_finite'` consumes**, which is why
the statement is phrased with one rather than with a finite open covering. -/
theorem exists_finset_basicOpen_generatingSections [M.IsFiniteType] :
    ∃ s : Finset R, Ideal.span (s : Set R) = ⊤ ∧
      ∀ g ∈ s, ∃ σ : (M.over (PrimeSpectrum.basicOpen g)).GeneratingSections, σ.IsFiniteType := by
  obtain ⟨σ, hσ⟩ := SheafOfModules.IsFiniteType.exists_localGeneratorsData.{u, u} M
  have hcov : ⨆ i, σ.X i = ⊤ := (Opens.coversTop_iff (U := σ.X) _).1 σ.coversTop
  have htop : (⨆ g : {g : R // ∃ i, (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ σ.X i},
      (PrimeSpectrum.basicOpen g.1 : (Spec R).Opens)) = ⊤ := by
    rw [eq_top_iff]
    intro x _
    have hx : x ∈ ⨆ i, σ.X i := by rw [hcov]; trivial
    obtain ⟨i, hi⟩ := Opens.mem_iSup.1 hx
    obtain ⟨V, ⟨g, rfl⟩, hxV, hV⟩ :=
      Opens.isBasis_iff_nbhd.1 PrimeSpectrum.isBasis_basic_opens hi
    exact Opens.mem_iSup.2 ⟨⟨g, i, hV⟩, hxV⟩
  rw [PrimeSpectrum.iSup_basicOpen_eq_top_iff] at htop
  obtain ⟨s, hsub, hs1⟩ :=
    Submodule.mem_span_finite_of_mem_span ((Ideal.eq_top_iff_one _).1 htop)
  refine ⟨s, (Ideal.eq_top_iff_one _).2 hs1, fun g hg ↦ ?_⟩
  obtain ⟨⟨g', i, hi⟩, rfl⟩ := hsub hg
  haveI := hσ.isFiniteType i
  exact ⟨SheafOfModules.GeneratingSections.restrict.{u} (homOfLE hi) (σ.generators i),
    inferInstance⟩

/-- **Restriction of a section of `M` from the whole of `Spec R` to a distinguished open.**

Named because it is the map the localisation statement below is about, and because spelling it
out at a call site costs three lines. It is the presheaf of `R`-modules underlying `M`, applied
to `D(g) ≤ ⊤`; note that this is `AlgebraicGeometry.modulesSpecToSheaf`'s presheaf, valued in
`ModuleCat R`, and not `AlgebraicGeometry.Scheme.Modules.presheaf`, which is valued in abelian
groups and carries the `Γ(Spec R, U)`-module structure instead. The two have the same underlying
type, by `rfl`, and different `Module` instances; a statement about one is not found at the
other. -/
noncomputable abbrev sectionsToBasicOpen (g : R) :
    (modulesSpecToSheaf.obj M).presheaf.obj (op ⊤) ⟶
      (modulesSpecToSheaf.obj M).presheaf.obj (op (PrimeSpectrum.basicOpen g)) :=
  (modulesSpecToSheaf.obj M).presheaf.map
    (homOfLE (le_top : (PrimeSpectrum.basicOpen g : (Spec R).Opens) ≤ ⊤)).op

/-- **For a coherent `M`, restriction to `D(g)` exhibits `Γ(M, D(g))` as the localisation of
`Γ M` away from `g`.**

For `M = N^~` this is Mathlib's instance on `AlgebraicGeometry.tilde.toOpen`, and
`AlgebraicGeometry.Scheme.Modules.toOpen_fromTildeΓ_app` says that `toOpen` followed by the
counit *is* the restriction map. Coherence enters only through
`AlgebraicGeometry.Scheme.Modules.isIso_fromTildeΓ_of_isCoherent`, which makes that counit an
isomorphism, and an isomorphism composed after a localisation map is again one
(`IsLocalizedModule.of_linearEquiv`).

**Stated for quasicoherent and not for coherent `M`.** Only quasicoherence is used, it is the
weaker hypothesis, and it is the one this repository can currently *instantiate* on a `Spec`:
`OkaTest/AffineSections.lean` exercises this at `𝒪_{Spec A} ⧸ (x)`, whereas no sheaf on a `Spec`
is proved coherent anywhere here. The coherent case is
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen_of_isCoherent`.

`AlgebraicGeometry.tilde.toOpen`'s localisation instance has to be supplied to
`IsLocalizedModule.of_linearEquiv` explicitly. Leaving it to be inferred fails: the goal is
stated in terms of `ModuleCat.Hom.hom` and search reduces it to the raw field
`ModuleCat.Hom.hom'`, at which the instance is not found. -/
theorem isLocalizedModule_away_sectionsToBasicOpen [M.IsQuasicoherent] (g : R) :
    IsLocalizedModule.Away g (sectionsToBasicOpen M g).hom := by
  haveI := isIso_fromTildeΓ_of_isQuasicoherent M
  haveI : IsIso ((modulesSpecToSheaf.map M.fromTildeΓ).hom.app (op (PrimeSpectrum.basicOpen g))) :=
    inferInstance
  rw [show sectionsToBasicOpen M g =
      tilde.toOpen ((modulesSpecToSheaf.obj M).presheaf.obj (op ⊤)) (PrimeSpectrum.basicOpen g) ≫
        (modulesSpecToSheaf.map M.fromTildeΓ).hom.app (op (PrimeSpectrum.basicOpen g)) from
    (toOpen_fromTildeΓ_app M (PrimeSpectrum.basicOpen g)).symm]
  exact IsLocalizedModule.of_linearEquiv (Submonoid.powers g)
    (tilde.toOpen ((modulesSpecToSheaf.obj M).presheaf.obj (op ⊤)) (PrimeSpectrum.basicOpen g)).hom
    (asIso ((modulesSpecToSheaf.map M.fromTildeΓ).hom.app
      (op (PrimeSpectrum.basicOpen g)))).toLinearEquiv

/-- **The coherent case of
`AlgebraicGeometry.Scheme.Modules.isLocalizedModule_away_sectionsToBasicOpen`.**

Coherence enters only through `SheafOfModules.IsCoherent.isQuasicoherent`. Stated separately, and
**not as an instance**, for the reason `SheafOfModules.IsCoherent.isFinitePresentation` gives:
`SheafOfModules.IsCoherent` is not a class instance search should be running from, and an
instance here would start such a search at every `IsLocalizedModule.Away` goal. -/
theorem isLocalizedModule_away_sectionsToBasicOpen_of_isCoherent [M.IsCoherent] (g : R) :
    IsLocalizedModule.Away g (sectionsToBasicOpen M g).hom :=
  haveI := SheafOfModules.IsCoherent.isQuasicoherent M
  isLocalizedModule_away_sectionsToBasicOpen M g


/-! ### Epimorphisms are surjective on global sections

An epimorphism of sheaves of modules is not surjective on sections in general. On `Spec R` and
between *quasicoherent* sheaves it is, and that is the mathematical content of the affine
dictionary: everything else in the argument is bookkeeping.
-/

/-- **An epimorphism of quasicoherent sheaves on `Spec R` is surjective on global sections.**

`AlgebraicGeometry.tildeEquiv` is an *equivalence* between `ModuleCat R` and the quasicoherent
`𝒪_{Spec R}`-modules, so it carries the epimorphism to an epimorphism of `R`-modules, which is a
surjection. **No cohomology and no stalks enter**: the vanishing that would otherwise be needed is
already inside the statement that the counit is an isomorphism.

`Epi f` is an explicit argument rather than an instance. At a call site the epimorphism usually
arrives as `SheafOfModules.GeneratingSections.epi`, and instance search does not find it there even
when it is in scope as a local instance — `σ.π` is an `abbrev` for
`SheafOfModules.freeHomEquiv.symm σ.s`, and the two are defeq at default transparency but search
runs at reducible transparency. Taking the hypothesis explicitly removes the question. -/
theorem surjective_moduleSpecΓFunctor_map {M N : (Spec R).Modules}
    [M.IsQuasicoherent] [N.IsQuasicoherent] (f : M ⟶ N) (hf : Epi f) :
    Function.Surjective (moduleSpecΓFunctor.map f).hom := by
  haveI := hf
  rw [← ModuleCat.epi_iff_surjective]
  let f' : (⟨M, ‹_›⟩ : (SheafOfModules.isQuasicoherent (Spec R).ringCatSheaf).FullSubcategory) ⟶
    ⟨N, ‹_›⟩ := ObjectProperty.homMk f
  haveI : Epi f' := (ObjectProperty.ι _).epi_of_epi_map (f := f') (by exact ‹Epi f›)
  exact (tildeEquiv (R := R)).inverse.map_epi f'

/-- **A free sheaf on `Spec R` is quasicoherent.**

Mathlib already has `IsIso (AlgebraicGeometry.Scheme.Modules.fromTildeΓ (SheafOfModules.free ι))`
as an instance, and this is `AlgebraicGeometry.isQuasicoherent_iff_isIso_fromTildeΓ` applied to it.

The instance has to be named through `inferInstanceAs`, **and at Mathlib's spelling rather than at
this statement's**: the goal here is about `SheafOfModules.free (R := (Spec R).ringCatSheaf) I`,
while the instance is stated at
`AlgebraicGeometry.Scheme.Modules.fromTildeΓ (R := R) (SheafOfModules.free.{u} I)`. The two are
defeq and are different discrimination-tree keys, so `inferInstanceAs` at the goal's own spelling
fails — with the type fully written out and no metavariable anywhere — while at Mathlib's it
succeeds. Writing *a* type out is therefore not the fix; writing out the right one of the two
is. -/
theorem isQuasicoherent_free (I : Type u) :
    (SheafOfModules.free.{u} (R := (Spec R).ringCatSheaf) I).IsQuasicoherent :=
  (isQuasicoherent_iff_isIso_fromTildeΓ _).mpr
    (inferInstanceAs (IsIso (Scheme.Modules.fromTildeΓ (R := R) (SheafOfModules.free.{u} I))))

/-- **The global sections of the free sheaf on `Spec R` are the free module.**

`AlgebraicGeometry.tildeFinsupp` says `free I` is `(I →₀ R)^~`, and the unit of the adjunction is
an isomorphism, so its global sections are `I →₀ R`. -/
noncomputable def freeΓIso (I : Type u) :
    ModuleCat.of R (I →₀ R) ≅
      moduleSpecΓFunctor.obj (SheafOfModules.free.{u} (R := (Spec R).ringCatSheaf) I) :=
  (tilde.toTildeΓNatIso (R := R)).app (ModuleCat.of R (I →₀ R)) ≪≫
    moduleSpecΓFunctor.mapIso (tildeFinsupp I)

/-- **Finitely many global sections generating a quasicoherent sheaf on `Spec R` as a sheaf
generate its global sections as a module.**

This is the statement an epimorphism of sheaves does not give for free, and with it
`Module.Finite.of_localizationSpan_finite'` is within reach of `Module.Finite R (Γ M)`; see the
module docstring for what still stands between them.

Coherence is not needed and is not available: nothing in this repository proves a sheaf on a
`Spec` coherent, so the hypotheses are quasicoherence and a finite generating family, which
`OkaTest/AffineSections.lean` exhibits. -/
theorem module_finite_moduleSpecΓFunctor_obj {M : (Spec R).Modules} [M.IsQuasicoherent]
    (σ : M.GeneratingSections) [Finite σ.I] :
    Module.Finite R (moduleSpecΓFunctor.obj M) := by
  haveI := isQuasicoherent_free (R := R) σ.I
  have hπ : Function.Surjective (moduleSpecΓFunctor.map σ.π).hom :=
    surjective_moduleSpecΓFunctor_map σ.π σ.epi
  have hiso : Function.Surjective (freeΓIso (R := R) σ.I).hom.hom :=
    (ConcreteCategory.bijective_of_isIso (freeΓIso (R := R) σ.I).hom).2
  exact Module.Finite.of_surjective
    (((freeΓIso (R := R) σ.I).hom ≫ moduleSpecΓFunctor.map σ.π).hom)
    (by rw [ModuleCat.hom_comp]; exact hπ.comp hiso)

end AlgebraicGeometry.Scheme.Modules
